### ISSUE TITLE
Proposal - On faas-cli deploy --image <>, pull image if not found.

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas-cli#115]
I think this has been brought up before, but I believe that if you run `faas-cli deploy --image <>` and the image has not yet been pulled to your machine, it should pull this image first. Currently it doesn't even seem to display an error message on `faas-cli deploy`. Maybe a `faas-cli pull` command would also make sense.

If this sounds like a good addition, I would like to work on this.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
I'm pretty sure I do this every day and that it works on my clusters.. Can you give the instructions to reproduce the issue?

**Comment by ericstoekl** [comment]
Okay, so I tested it and as you say, it works. :+1:  It pulls the docker images properly, although it does not let the user know that it needs to pull the image.

However, if the image name specified does not exist on docker hub, it will not give any error message letting you know that it failed to pull the image. I believe there are some improvements that could be made here. Let me know your thoughts.

Thanks,
Erich

**Comment by johnmccabe** [comment]
@ericstoekl you'd need to make your image available from a local registry if you're not pushing it up to the hub, Swarm doesn't handle propagating images across a cluster.

**Comment by johnmccabe** [comment]
Derek add label: question

**Comment by ericstoekl** [comment]
@johnmccabe Thanks for the answer. However, I believe if the image is not found, instead of just deploying the non-existant image, which will forever be stuck at replica count of `0/1`, faas-cli should report some kind of error message saying "docker image not found". Similarly, if it does find an image but it is not yet pulled locally, it should say "pulling image from docker hub". Let me know your thoughts.

**Comment by alexellis** [comment]
Please fill out the whole template so people of varying levels of experience (or on little time) can repo the issue easily.

**Comment by alexellis** [comment]
Derek add label: revisit
