### ISSUE TITLE
Canonical repository URL does not match Go import

### ISSUE THREAD

**Issue by ilovezfs** [openfaas/faas-cli#116]
I noticed that the canonical repository url had changed, so was going to `%s/alexellis/openfaas/g` in the Homebrew formula, but it looks like the Go import paths are still using the old location. Ideally, these should probably match.

**Comment by alexellis** [comment]
Yes that's what we've seen happen with an org move. The imports will still work the same (GitHub does redirects) and then later this week or next we'll start to update the various projects with the new imports.

**Comment by johnmccabe** [comment]
@alexellis I'll push up a PR to perform the move

**Comment by johnmccabe** [comment]
Derek add label: skill/beginner

**Comment by alexellis** [comment]
Derek assign to: johnmccabe

**Comment by alexellis** [comment]
I'm not sure if he's upgraded yet

**Comment by johnmccabe** [comment]
You didn't merge that PR I think?

**Comment by alexellis** [comment]
Fixed in #117
