### ISSUE TITLE
Proposal - Include `ls` alias for faas-cli list

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas-cli#122]
It would be useful to be able to run 'faas-cli ls' rather than 'faas-cli list' in order to list running functions. This is just a matter of adding an `Aliases:` property to the `listCmd` object.

## Expected Behaviour

`faas-cli ls` provides the functionality of `faas-cli list`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by johnmccabe** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
Happy with this, but please full the full template out or delete the sections that don't apply. Merged in #118.
