### ISSUE TITLE
Print error message when --filter or --regex returns no matches

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas-cli#124]
This change is to provide an error message if --filter or --regex returns no matches. This was mentioned by @johnmccabe in the Slack to be a desired feature.

## Expected Behaviour

When you run a --filter or --regex statement that returns no functions from the YAML file, return an error message like: `"No functions found in YAML, check --filter/--regex"`

## Current Behaviour

No error message is returned, so each command that uses --filter or --regex ends up throwing an unrelated error. `deploy` throws: `"Please provide a --image to be deployed."`

## Possible Solution

Return error when no functions remain after filter or regex loop has finished.

## Steps to Reproduce (for bugs)

1. `cd` into `faas-cli` directory
2. Run `faas-cli deploy -f samples.yml --filter alsdfhklasd`
3. See unrelated error message
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by johnmccabe** [comment]
Derek add label: bug

**Comment by johnmccabe** [comment]
Can you get rid of the 'proposal -' in the issue title please.

**Comment by ericstoekl** [comment]
This is merged
