### ISSUE TITLE
When creating new functions - offer to append to existing YAML

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#128]
Here's the scenario:

I scaffold 5 functions, but end up with 5 YAML files.

```
faas-cli new --lang python --name func1
func1.yml created
faas-cli new --lang python --name func2
func2.yml created
faas-cli new --lang python --name func3
func3.yml created
```

Let's offer a new parameter `--yaml YAML_FILE` which means you can append new functions into an existing file:

```
faas-cli new --lang python --name func1
func1.yml created
faas-cli new --lang python --name func2 --append func1.yml
func1.yml appended
faas-cli new --lang python --name func3  --append func1.yml
func1.yml appended
```

**Comment by rgee0** [comment]
I think this is a great idea.  Making it easier for people to build and maintain a suite of functions.

So that others are clear, is the suggestion that the new parameter should be `--yaml` or `--append`?  The narrative and codeblock seem to suggest both.  I'd lean more towards `--append` as it would be more intuitive a command.

**Comment by ericstoekl** [comment]
I'm working on this ATM, appending the new function to the `Services` struct and then using  `yaml.Marshall()` to write out the modified YAML file. I gotta go to an all-day event today but I should have it done tomorrow morning (Sunday oct 1).

Also plan on adding some tests

**Comment by ericstoekl** [comment]
Alright, so I've got the basic functionality working in this branch. This one doesn't leverage the `Services` interface to append the data, it just writes string data to a file. I want to get maintainers' opinions on whether we should append by adding to a `*Services` object then writing that out with `yaml.Marshall()`, or if this way is sufficient.

https://github.com/ericstoekl/faas-cli/commit/eccf237c9dcb5190c3725e7ce3d654344a1028a4

Gif of the functionality:
https://imgur.com/a/Zggm3

**Comment by rgee0** [comment]
My preference would be to use `yaml.Marshall()` as I feel it keeps things cleaner.

**Comment by alexellis** [comment]
What resulting template do you get for Lang Dockerfile?

**Comment by ericstoekl** [comment]
@alexellis You get a folder containing an empty file named `Dockerfile`. I was thinking putting something very basic in, like `catservice` as a starting point, might be helpful for users.

**Comment by alexellis** [comment]
See also #132

**Comment by alexellis** [comment]
@ericstoekl did you PR for this yet?

**Comment by alexellis** [comment]
@rgee0 I'm not sure. Maybe we should actually go for `--yaml` because we'll need that anyway when we default all new functions to a `stack.yml` file instead of `NAME.yml`

**Comment by ericstoekl** [comment]
@alexellis  I don't have a PR yet, still working on the details. So far what I have is here:

https://github.com/ericstoekl/faas-cli/commit/89b255715745860813e665cb8eb5d13c3b43f690

Issues to fix:
1. Need to add tests for this functionality (manually tested and the happy path works)
2. Would be nice to be able to order the YAML data manually. For example, the file produced by this method looks like this:

```
functions:
  dt_2:
    lang: Dockerfile
    handler: ./dt_2
    image: dt_2
  nt_1:
    lang: node
    handler: ./nt_1
    image: nt_1
provider:
  name: faas
  gateway: http://localhost:8080
```

(alphabetical ordering seems to be the default by `yaml.Marshall()`)

**Comment by ericstoekl** [comment]
I'm only able to work on this a bit per day because of other stuff going on, but I'm about 90% of the way there. Just need a few more tests and it'll be ready to PR.

Progress so far: https://github.com/ericstoekl/faas-cli/commit/6c13121bfda95a1cf16bcd42aff3fa2fc0b0fb85

**Comment by ericstoekl** [comment]
Sent out a PR: #141

**Comment by alexellis** [comment]
Great, thank you 👍

**Comment by johnmccabe** [comment]
Derek assign: ericstoekl

**Comment by alexellis** [comment]
Derek close
