### ISSUE TITLE
Add colour to "faas-cli new" command

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#129]
This should mimic the project logo, but in ASCII colour. 

Alternatively add colour to the `figlet` OpenFaaS splash screen on `faas-cli version` command

**Comment by shorsher** [comment]
I'd like to help do this!  This would be my first OSS and I'm fairly novice with go but it doesn't seem too hard lol.  Any preferences on the colors?

**Comment by alexellis** [comment]
I was thinking we could use the ASCII art converter function to generate a sample based upon the logo we have for a favicon in the faas repo.

https://github.com/developius/faas-node-ascii

**Comment by shorsher** [comment]
I generated the faas logo with the ascii function but it turned out quite big.  I would add it here but probably not able to view it correctly.

**Comment by alexellis** [comment]
I think we may need to just go with a coloured figlet logo for now. Just did a release which you can check out via the sh script. We'll find something else for you to get stuck into and tag it #hacktoberfest

**Comment by alexellis** [comment]
If you like you can still share the image by dragging it into a comment

**Comment by shorsher** [comment]
I'll be happy to do the colored figlet logo.  Here's an attached screenshot from my terminal of the ascii favicon, quite large as you can see lol.
![screen shot 2017-09-29 at 3 23 44 pm](https://user-images.githubusercontent.com/10987380/31032517-4199e6ee-a52a-11e7-9086-510290fdb15e.png)

**Comment by alexellis** [comment]
Colour was added to `new` and `version` through ASCII codes.

**Comment by alexellis** [comment]
Thanks for helping to look into the ASCII art.
