### ISSUE TITLE
Proposal: Rename CLI

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#130]
Chatting on the Slack channel at JeffConf - should we rename?

I'll post three comments.. please vote or suggest another option.

**Comment by alexellis** [comment]
`faas-cli`

**Comment by alexellis** [comment]
`faas`

**Comment by alexellis** [comment]
`openfaas`

**Comment by developius** [comment]
`ofaas`?

**Comment by austinfrey** [comment]
i'm throwing in `ofs`

**Comment by johnmccabe** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
So if we pick one that's not `faas-cli` how easy is it to ensure both work even if `faas-cli` becomes an alias until everyone's used to the change?

**Comment by rgee0** [comment]
`ln` on linux & derivatives?
`mklink` on windows?

**Comment by ilovezfs** [comment]
A rename is supported.
https://github.com/Homebrew/homebrew-core/tree/master/Aliases
https://github.com/Homebrew/homebrew-core/blob/master/formula_renames.json

**Comment by ilovezfs** [comment]
@alexellis Are you also planning to rename the repository?

**Comment by alexellis** [comment]
No the alias I think will be faas we already have a core project repository called FaaS.

**Comment by alexellis** [comment]
Alias of `faas` added to `brew` and symlink, too. the `faas-cli` repo and binary will keep the same name. 

After updating this will be equivalent:

```
faas new --lang node test1
faas-cli new --lang node test1
```
