### ISSUE TITLE
Hacktoberfest: Alter verb invoke to take positional argument

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#134]
## Expected Behaviour

```
$ faas-cli invoke url-ping -f stack.yml
```

## Current Behaviour

```
$ faas-cli invoke --name url-ping -f stack.yml
```

## Possible Solution

Follow pattern in `new` and `remove` verbs.

## Context

Reducing CLI verbosity.

**Comment by amirkarimi** [comment]
Can I work on this issue?

**Comment by gardlt** [comment]
@alexellis can i pick up this work? per discussion on #133

**Comment by alexellis** [comment]
Hi Amir,

@gardlt asked to work on this via https://github.com/openfaas/faas-cli/issues/133 - but we can find you something else to get stuck into. Would you like to ping alex@openfaas.com and I'll introduce you to our Slack community and other new contributors?

We have more issues ready here too:

https://github.com/openfaas/faas/issues

https://github.com/openfaas/faas-netes/issues

https://github.com/openfaas/faas-cli/issues

**Comment by amirkarimi** [comment]
Of course, go ahead @alexellis :+1:

**Comment by alexellis** [comment]
Here's another example issue @amirkarimi - https://github.com/openfaas/faas/issues/198
