### ISSUE TITLE
Fail "build" if Docker CLI throws an error

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#138]
## Expected Behaviour

We need to "stop the world" if a `faas-cli build` throws an error. 

## Current Behaviour

Error is swallowed and hard to see.

## Possible Solution

At the least just `log.Fatal()` and emit non-zero exit code.

Better - print a message in red with the aec library we use for "version"/"new" commands.

## Steps to Reproduce (for bugs)

Use a Dockerfile with a bad instruction and do `faas-cli build`

**Comment by shorsher** [comment]
I’ll give this one a shot 🙌🏼🙌🏼

**Comment by alexellis** [comment]
Please provide output from testing in the PR (positive and negative) along with what happens if you have multiple functions or a single. GIFs are also very good for showing new behavior. Looking forward to seeing this.

**Comment by shorsher** [comment]
So it seems the only way to get the error status is in ExecCommand(), would you like to handle any errors there?  The push command also utilizes ExecCommand() so that might be the best option.

**Comment by alexellis** [comment]
I think you can check for Exit code on the command object

**Comment by alexellis** [comment]
Fixed in 139. With some notes on a v2 implementation.
