### ISSUE TITLE
How do I monitor resource utilization?

### ISSUE THREAD

**Issue by yesimdinesh** [openfaas/faas-cli#140]
Hi, is there a way to get the container id in which the deployed service/function is running?
I need this container id to use in docker stats command to get the resource utilization statistics of the service.

**Comment by alexellis** [comment]
As far as an OpenFaaS user is concerned you should not be getting deeply attached to the container instance. I'd suggest adding cadvisor or a Prometheus plugin to your deployment.

If we need to measure the memory usage of functions that is something we should do through the wider project.

**Comment by yesimdinesh** [comment]
Thanks Alex,
     I got the resource utilization of the non-containerized binary using "atop" command on a RaPi. But in future this binary shall be deployed in a docker container as a service/function on a resource constrained swarm node. Hence, while deploying this function(in a container), I will be specifying values for --reserve-cpu and --reserve-memory. 
My intention is to run this binary in a container as a function for some duration and get the resource stats of this container using "docker stats". Then, I will be selecting peak values from this stats as input to faas-cli deploy command.

Thanks
Dinesh

**Comment by yesimdinesh** [comment]
Anyway, I got the solution for this:

Get the task id for your service:
docker service ps facto
Get container id for this task:
docker inspect --format "{{.Status.ContainerStatus.ContainerID}}" <task id>
Run the docker stats command:
docker stats <container id>

Thanks
Dinesh
