### ISSUE TITLE
How do I use --reserve-cpu, --reserve-memory options in "faas-cli deploy" command ?

### ISSUE THREAD

**Issue by yesimdinesh** [openfaas/faas-cli#143]
Hi,

I want to supply minimum resource constraints needed for my application/service to run/deploy on a target swarm node. If this much quantity of resources is available on a swarm node then only the application/service should get deployed, else it should be in a state e.g. pending.

I would like to pass values for --reserve-cpu, --reserve-memory options in a "faas-cli deploy" command.

At the moment, I am able to create the service with these resource options by direct use of "docker service create" command.

I would like to use faas-cli deploy command to do the same. Please do let me know if its possible with faas-cli and how.

Thanks
Dinesh
## Expected Behaviour

faas-cli deploy --image=alexellis/faas-url-ping --name=url-ping --reserve-cpu=0.1 --reserve-memory=5mb
faas-cli deploy --image=alexellis/faas-url-ping --name=url-ping --constraint='node.hostname==swarm3'

## Current Behaviour

The current implementation of faas-cli does not support either the "--constraint" or "--reserve-cpu, --reserve-memory" options in .yml file or command line

## Possible Solution

1. Enhance faas-cli code to enable passing --reserve-cpu, --reserve-memory options along with their values to "faas-cli deploy" command.
2. Enhance faas-cli to accept constraints in "faas-cli deploy" command Or has capability to process it if mentioned in the service's .yml file. 
## Steps to Reproduce (for bugs)

1. Try to pass the said parameters to faas-cli command to deploy any experimental service. ( e.g. Hello World program (C/Go/Python as per your preference)
2.
3.
4.

## Context

I shall be using the resource constraint devices (e.g. Raspberry Pi) to deploy the services on those.
First I shall be profiling the service and find its peak resource requirements, e.g. cpu, ram. and pass on these values while deploying the service on RaPi like devices.
## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
17.05.0-ce
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux/arm (Rasperry Pi3, Jessie Linux) 
pi@swarm1:~/faas-cli $ uname -a
Linux swarm1 4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux
pi@swarm1:~/faas-cli $

* Link to your project or a code example to reproduce issue:
Not needed

**Comment by austinfrey** [comment]
Derek add label: question

**Comment by austinfrey** [comment]
@yesimdinesh i do not think those flags are currently supported. If you'd like to modify this issue or open up another as a proposal for changes that would allow that behavior, it can be discussed more in depth.

**Comment by yesimdinesh** [comment]
Hi Austin,

I propose to include these features (though not too immediate). People would use it in future.

Thanks
Dinesh

**Comment by austinfrey** [comment]
@yesimdinesh could you fill out the issue template above with more specific information? it would be helpful. Thanks!

**Comment by austinfrey** [comment]
ping @yesimdinesh

**Comment by austinfrey** [comment]
@yesimdinesh I'm going to close this issue, but there is some discussion about this in the main faas repo: https://github.com/openfaas/faas/issues/239 
feel free to re-open if you feel that it doesn't answer your question.

**Comment by austinfrey** [comment]
Derek close
