### ISSUE TITLE
Error deploying faas-cli

### ISSUE THREAD

**Issue by cmollis** [openfaas/faas-cli#144]
trying to deploy the sample.. I was able to successfully build:

Deploying: hello-python.
Error removing existing function: Delete http://localhost:8080/system/functions: dial tcp [::1]:8080: getsockopt: connection refused, gateway=http://localhost:8080, functionName=hello-python
Is FaaS deployed? Do you need to specify the -gateway flag?
Post http://localhost:8080/system/functions: dial tcp [::1]:8080: getsockopt: connection refused

## Expected Behaviour

It should deploy

## Current Behaviour

I see the above

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Version 17.09.0-ce-mac33 (19543)

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
no

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

* Link to your project or a code example to reproduce issue:

**Comment by cmollis** [comment]
I don't have anything running on :8080

**Comment by alexellis** [comment]
Please try changing your yaml from localhost to 127.0.0.1

**Comment by rgee0** [comment]
I'm a little concerned that you answered no to Swarm or K8S.  Where did you install openfaas @cmollis?  The cli needs to be pointed at the openfaas gateway in order to deploy.

**Comment by cmollis** [comment]
Yeah.. that's the problem.  Sorry new to this.. I didn't have the Swarm
running which is (probably) why it's not working.  Please close this
issue.  I will re-open once I get everything configured correctly.

**Comment by alexellis** [comment]
@cmollis which guide / link were you following? Maybe we need to make this clearer. Thanks @rgee0 for helping

**Comment by cmollis** [comment]
I was reading a few of the blog posts.. and just focused on the function
creation part using the CLI tool (which now I see was dumb).  Having never
deployed a swarm, I kind of *skipped* that part.

I ran one of the tutorials that used the docker playground and I saw what
 I was doing wrong.

Thanks for responding.. sorry for the bother.

**Comment by ericstoekl** [comment]
When I started working on this project I ran into the same issue. I suspect that folks with 0 Docker experience might run into this unless the blog posts all explicitly state that Step 1 is to run `docker swarm init`, with the `--advertise-addr` flag if necessary.

**Comment by cmollis** [comment]
right..  I focused on the 'python' tutorial, when I should have read the
node tutorial..   This spells it out pretty well, actually.

https://blog.alexellis.io/quickstart-openfaas-cli/

when I went back and created the swarm first and then deployed the faas
stack, everything went fine with my python sample func.

thanks again... it's all pretty cool, actually.

**Comment by gregbenner** [comment]
Got the same error following https://blog.alexellis.io/quickstart-openfaas-cli/

**Comment by alexellis** [comment]
@gregbenner which error did you run into?

**Comment by alexellis** [comment]
@gregbenner What was wrong? What needs changing?

**Comment by gregbenner** [comment]
It's missing a deploy local swarm step in the [docs]( https://blog.alexellis.io/quickstart-openfaas-cli/) I believe? 
When you do the curl command to TestDrive it runs it for you.  That's why nothing is running on port 8080 and it has nowhere to deploy a new faas too.

**Comment by gregbenner** [comment]
As per https://github.com/openfaas/faas/blob/master/TestDrive.md
Starting out it wasn't clear to do this I think. (from a noob view)
`# docker swarm init --advertise-addr eth0 && \
  git clone https://github.com/openfaas/faas && \
  cd faas && \
  git checkout master && \
  ./deploy_stack.sh && \
  docker service ls`

**Comment by rgee0** [comment]
Isn't it in the pre-requisites section?

**Comment by gregbenner** [comment]
100% it is, I just re-read now and saw it there. Sorry, that sorts out my issue. #dyslexia

**Comment by alexellis** [comment]
Thanks guys 👍 glad you are up and running now. Locking the thread.

**Comment by alexellis** [comment]
Derek lock
