### ISSUE TITLE
Golang Template Dockerfile tests Vendor Package

### ISSUE THREAD

**Issue by rgee0** [openfaas/faas-cli#146]
## Expected Behaviour
Tests run within the Dockerfile test user added content and ignore any vendor packages

## Current Behaviour
The Dockerfile has made provision for running go tests and as the base image uses 1.8.3 the current command is also testing any vendor packages that are present.

## Possible Solution
Choice:
1) Move base image to go 1.9
or
2) Keep current level of 1.8.3 and change the go test command to:
` go test $(go list ./... | grep -v /vendor/) -cover`

## Steps to Reproduce (for bugs)
Create a simple go function with vendored dependancies and add a unit test

## Context
Early testing of the new CLI capability whch enables native golang functions

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:12:06 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
+10 points for being the first person to fill out the whole issue template. If you would like to fix I'll merge. Thank you for the usual attention to detail @rgee0
