### ISSUE TITLE
faas-cli: not deploying to my pi swarm

### ISSUE THREAD

**Issue by craigham** [openfaas/faas-cli#148]
after I type in the deploy command the cli is hanging.  I am running it on my manager node, and I have updated the templates.

Is there a way for me to see logs for faas-cli so I maybe I can figure out what is not working for me ?  Or any suggestions on how I might debug the issue?

thanks
Craig

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
You need to fill out the whole template for us to offer support. Cheers Alex

**Comment by alexellis** [comment]
Also you may want to try changing the gateway from localhost to 127.0.0.1

**Comment by craigham** [comment]
it was the gateway.  thanks.

**Comment by alexellis** [comment]
If you'd like to chat more about RPi and OpenFaaS you're welcome to join us on Slack - email alex@openfaas.com

**Comment by craigham** [comment]
Thanks Alex.  Cool project you have going here.
