### ISSUE TITLE
faas-cli deploy  -f sample.yml failing to start

### ISSUE THREAD

**Issue by kenneyhe** [openfaas/faas-cli#156]
``` bash
faas-cli deploy  -f sample.yml
docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                                   PORTS
...
vkbv99hmnbzo        bing                replicated          0/1                 kenneyhe/bingreward                     
cat sample.yml 
provider:
  name: faas
  gateway: http://localhost:8080

functions:
  bing:
    lang: python
    # location of Dockerfile    handler: ./
    fprocess: /bin/entry.sh
    image: kenneyhe/bingreward
    environment:
#      LISTENER_ADDRESS: swarm-listener
#      MODE : swarm
      read_timeout : 60
      write_timeout : 60
    environment_file:
      - key.yml
```

## Expected Behavior

Should work just like just like below

```bash
faas-cli deploy --fprocess="/bin/entry.sh"     --env read_timeout=60 --env write_timeout=60     --image kenney/bingreward --name reward2

ID                  NAME                MODE                REPLICAS            IMAGE                                   PORTS
...       
o92gez2bvyos        reward2             replicated          1/1                 kenney/bingreward 
```

## Current Behaviour

I expect both to be same because "docker service inspect <name>" tells me they are the same.

## Possible Solution
Deploy state is not parsed to be true or use in stack yaml, I suspect

## Steps to Reproduce (for bugs)

1. 	copy https://github.com/kenneyhe/BingRewards.git (branch) mp_faas's compose yaml file 
2.    run from repo: faas-cli deploy  -f compose.yaml
3.    docker service ls 
4.    wait and see it never starts

## Context

I am trying to use secrets and hence yaml is better with this instead of passing env in parameter

I wish openfaas yaml can parse secrets like stack.yaml using /run/secrets/key.yml instead of using local file key.yml (which could be checked in and I like the flexibility of one manager node handling the key.yml)

## Your Environment

* brew installed faas-cli

  ___                   _____           ____  
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___| 
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \ 
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/ 
      |_|                                     

Commit: a4f03381443fd5c1e74ea7e17614df9b3b60abd1
Version: dev

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Version 17.09.0-ce-mac32 (19506)
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
MacOSX 10.11.4
* Link to your project or a code example to reproduce issue:
https://github.com/kenneyhe/BingRewards.git  's mp_faas

**Comment by johnmccabe** [comment]
What are you seeing in the service logs?

**Comment by kenneyhe** [comment]
@johnmccabe blank
``` bash
$ docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                                   PORTS
pz5fxmjkwntm        bing                replicated          0/1                 kenneyhe/bingreward                     
nkzpw987jb3x        func_alertmanager   replicated          1/1                 functions/alertmanager:latest           *:9093->9093/tcp
xksyq3ofzt0x        func_decodebase64   replicated          1/1                 functions/alpine:health                 
i4jw2yx953cc        func_echoit         replicated          1/1                 functions/alpine:health                 
vaqewefsjkql        func_gateway        replicated          1/1                 functions/gateway:0.6.3                 *:8080->8080/tcp
pp3bdfzlkcct        func_hubstats       replicated          1/1                 functions/hubstats:latest               
mdzomaogtuoc        func_markdown       replicated          1/1                 alexellis2/faas-markdownrender:latest   
qq5nxy3vttit        func_nodeinfo       replicated          1/1                 functions/nodeinfo:latest               
u75dlppjfxht        func_prometheus     replicated          1/1                 functions/prometheus:latest             *:9090->9090/tcp
te6c356nb6fv        func_webhookstash   replicated          1/1                 functions/webhookstash:latest           
mxl71iyfqe8w        func_wordcount      replicated          1/1                 functions/alpine:health                 
$ docker service logs bing
$ docker service logs bing
$ 
```

**Comment by johnmccabe** [comment]
Did you mean to use a different image name in your yaml and cli invocations?
```
# yaml
image: kenneyhe/bingreward
```
```
# cli
image: kenney/bingreward
```

**Comment by kenneyhe** [comment]
@johnmccabe Cool. That fixed it.  I have both docker hub accounts for company and private purposes.    thanks
