### ISSUE TITLE
Hacktoberfest: modify installation script to pull .exe on Windows / Git Bash

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#159]
## Expected Behaviour

Modify installation script to pull .exe on Windows / Git Bash

## Current Behaviour

`curl -sL cli.openfaas.com | sudo sh` should get you faas-cli.exe on Windows, but it gets the Linux binary.

## Possible Solution

* Add to README saying how to download from releases page
* Update shell script to see if we can work out "windows" from environment/uname.

@johnmccabe may know more

## Steps to Reproduce (for bugs)

1. Log onto Windows 10 for example.
2. Invoke curl script
3. End up with a Linux binary

## Context

Developer experience is poor.

**Comment by alexellis** [comment]
Derek add label: priority/high

**Comment by fntlnz** [comment]
Worth creating a chocolatey package contestually ? https://chocolatey.org/docs/create-packages

**Comment by wsteimel77** [comment]
It probably isn't perfect, but I've just added the following case to get it working for me for now
```
*_NT*)
suffix=".exe"
```

**Comment by alexellis** [comment]
What did you test on?

**Comment by alexellis** [comment]
Will you raise a PR for it too?

**Comment by wsteimel77** [comment]
Sure.  I am using Git Bash on Windows 10 (x64).  I also ran it on my Linux machine.

**Comment by wsteimel77** [comment]
There is also an OS environment variable which appears to always be Windows_NT if you prefer to go that route.

**Comment by wsteimel77** [comment]
And it is still saving it without the .exe extension, which works fine for git bash, but is going to cause problems if you wanted to use it elsewhere.

**Comment by wsteimel77** [comment]
#171 should ensure the .exe extension is retained when it is copied from temp to /usr/local/bin.  This allows it to be invoked outside of the Git Bash environment, for instance, on Powershell.

**Comment by pkeuter** [comment]
I've gone ahead and created a Chocolatey package, which is currently pending review: https://chocolatey.org/packages/faas-cli

Code is available here: https://github.com/pkeuter/au-packages/tree/master/faas-cli

**Comment by alexellis** [comment]
I think we'd need to control any official packages through the OpenFaaS GitHub organisation. You could transfer ownership, cancel the request or use another name such as faas-cli-community.

**Comment by pkeuter** [comment]
@alexellis Sure thing, I'd be happy to transfer ownership to openfaas, but I don't have authority to do so. What do you recommend?

**Comment by alexellis** [comment]
Thank you for putting this together. I have a couple of people I'd like to review this. We currently release to GitHub as a binary and to `brew`. Are you in our Slack community yet? Maybe we can sync-up there.

**Comment by pkeuter** [comment]
No I'm not, what do you need from me to join?

**Comment by johnmccabe** [comment]
@pkeuter did you get anywhere with the transfer?

**Comment by pkeuter** [comment]
@johnmccabe I did. It's currently have: https://github.com/openfaas-incubator/au-packages, but still connected to my AppVeyor account. It would be nice if we can use an openfaas account, and to initialize the build when a new version is released (I guess through Travis). I have had some contact with @alexellis about this but we haven't done anything concrete yet.

**Comment by alexellis** [comment]
Closing issue. We should still document in get.sh that a Windows binary can be downloaded.
