### ISSUE TITLE
python3 template proposal

### ISSUE THREAD

**Issue by psyhomb** [openfaas/faas-cli#163]
I have proposal for python3 template and this is how I think it should look like
https://github.com/psyhomb/serverless/tree/master/openfaas/templates/python3

example of two real functions based on it
https://github.com/psyhomb/serverless/tree/master/openfaas/imgmod
https://github.com/psyhomb/serverless/tree/master/openfaas/yaml2json

## Context

These are some of the changes I've made:
- Reduced number of layers in [Dockerfile](https://github.com/psyhomb/serverless/blob/master/openfaas/templates/python3/Dockerfile) (image) simply by using [.dockerignore](https://github.com/psyhomb/serverless/blob/master/openfaas/templates/python3/.dockerignore) file with reverse logic (include files), also this way only needed files will be sent to Docker build context
- IMHO `run.py` seems like more logical name, so I renamed `index.py` to `run.py`
- Added `get_qs()` function (query string parser) => [run.py](https://github.com/psyhomb/serverless/blob/master/openfaas/templates/python3/run.py)

**Comment by alexellis** [comment]
Great idea. Python 3 is important. 

Have you got the most recent CLI? I think we have this.. please double check.

**Comment by psyhomb** [comment]
Yes I have and I'm proposing improvements for existing template, cause it doesn't include query string parser function, existing `get_stdin()` function is overcomplicated and `Dockerfile` generates too many layers...

**Comment by alexellis** [comment]
Probably not going to merge this because it breaks with the convention of our signature. However you may want to propose a client library that we can use on pip to reconstitute http data from the environment

**Comment by alexellis** [comment]
Breaking convention means broken compatibility for existing users. I'm interested in your ideas around reducing image size

**Comment by alexellis** [comment]
Also work working with @jockdarock who is combining OpenFaaS with Flask.

**Comment by alexellis** [comment]
*worth

**Comment by alexellis** [comment]
We have a Python3 template, please check it out @psyhomb 

Closing issue.
