### ISSUE TITLE
curl / faas-cli etc hangs with IPv6 entry for localhost

### ISSUE THREAD

**Issue by Lewiscowles1986** [openfaas/faas-cli#164]
Running `faas-cli list` without valid `--gateway` seems to hang process indefinitely

## Expected Behaviour

Either: 

* an error message stating that --gateway parameter is not optional then exiting process with non-zero code
* attempting to get a list with a timeout of n-seconds (default to 30 seems sane)

## Current Behaviour

```
$ faas-cli list
^C

real    61m51.499s
user    0m0.030s
sys    0m0.010s
```

## Possible Solution

Please see expected behaviour

## Steps to Reproduce (for bugs)

1. Install Docker on Pi
2. Initiate swarm
3. Quick-Setup OpenFaaS `git clone https://github.com/alexellis/faas/ && cd faas &&./deploy_stack.armhf.sh`
4. `faas-cli list`

## Your Environment

* Docker version `docker version`:

```
docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:30:54 2017
 OS/Arch:      linux/arm

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:30:54 2017
 OS/Arch:      linux/arm
 Experimental: false

```

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Swarm

* Operating System and version (e.g. Linux, Windows, MacOS): Raspbian Stretch (Vanilla) + Docker + OpenFaaS (setup from tutorial)

* Link to your project or a code example to reproduce issue: N/A (tested in vanilla setup without custom code)

### Errata

* `faas-cli list --gateway http://0.0.0.0:8080 --verbose` works
* `faas-cli list --gateway http://127.0.0.1:8080 --verbose` works
* `faas-cli list --gateway http://localhost:8080 --verbose` hangs (indicating a possible network issue?)
* `curl 0.0.0.0:8080/system/functions` works
* `curl 127.0.0.1:8080/system/functions` works
* `curl localhost:8080/system/functions` hangs (indicating a possible network issue?)

**Comment by rgee0** [comment]
Seeing the same effect on rpi3 using v0.4.18b

Previous version would return:
```
pi@pi3:~ $ faas-cli list
give either -action= build or deploy
```

derek add label: bug

**Comment by rgee0** [comment]
derek add label: bug

**Comment by rgee0** [comment]
Derek add label: bug

**Comment by Lewiscowles1986** [comment]
I know limited go but I was thinking `net.Conn.SetReadDeadline(timeout)` might be an idea.

I noticed https://github.com/openfaas/faas-cli/blob/master/stack/stack.go#L90 seems to be the place making http calls

```
c := http.Client{
  Timeout: time.Second * 10,
}
```

I'd like to PR if possible

**Comment by Lewiscowles1986** [comment]
Btw @rgee0 I think the previous message was a bug too.

**Comment by rgee0** [comment]
stack.go fetches the yaml file.

Have you got an ipv6 address set in `/etc/hosts`?

**Comment by alexellis** [comment]
I don't believe this is a bug, but a configuration issue with Raspbian. 

Please try this:

Change your gateway to 127.0.0.1 or pass --gateway http://127.0.0.1

Or open up /etc/hosts and remove the IPv6 entry for localhost.

**Comment by alexellis** [comment]
Invalid gateway:

```
pi@swarm1:~ $ faas-cli list --gateway http://test:80080

Get http://test:80080/system/functions: dial tcp: address 80080: invalid port
2017/10/14 11:47:25 cannot connect to OpenFaaS on URL: http://test:80080
pi@swarm1:~ $ faas-cli version
  ___                   _____           ____  
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___| 
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \ 
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/ 
      |_|                                     

Commit: e804a60889e4d339762fb3643a315a173a963f26
Version: 0.4.18b
```

**Comment by rgee0** [comment]
IPv6 localhost in effect:
```
pi@pi3:~ $ netstat -an | grep 8080
tcp6       0      0 :::8080                 :::*                    LISTEN     
tcp6       0      0 ::1:53848               ::1:8080                FIN_WAIT2  
tcp6     112      0 ::1:8080                ::1:53442               CLOSE_WAIT 
tcp6     112      0 ::1:8080                ::1:52282               CLOSE_WAIT 
tcp6     112      0 ::1:8080                ::1:53848               CLOSE_WAIT 
```

IPv6 localhost commented out
```
pi@pi3:~ $ netstat -an | grep 8080
tcp        0      0 127.0.0.1:33380         127.0.0.1:8080          TIME_WAIT  
tcp6       0      0 :::8080                 :::*                    LISTEN     
tcp6       0      0 ::1:53848               ::1:8080                FIN_WAIT2  
tcp6     112      0 ::1:8080                ::1:53442               CLOSE_WAIT 
tcp6     112      0 ::1:8080                ::1:52282               CLOSE_WAIT 
tcp6     112      0 ::1:8080                ::1:53848               CLOSE_WAIT 
```

**Comment by rgee0** [comment]
Derek remove label: bug

**Comment by alexellis** [comment]
We should use a well-configured HTTP client - the default Golang client will hang forever. It needs changing in three files though rather than where we pull YAML. I'll look into this and get back.

**Comment by Lewiscowles1986** [comment]
I know it works for 127.0.0.1 it's in the tests I ran. It also works for 0.0.0.0 broadcast, but it should not hang for 60 minutes because it cannot resolve in any case (and could default internally to legacy compat ip for internal traffic no?)

**Comment by Lewiscowles1986** [comment]
Yeah confirmed it's a debian problem for raspbian and vanilla debian, so solving won't just be helpful to raspberry pi hobbyists

**Comment by alexellis** [comment]
Please look at the PR I raised.

We can't fix Docker's use of IPv4/IPv6. This will affect any system with the entries in /etc/hosts - but in your case it's a Raspbian issue.

**Comment by Lewiscowles1986** [comment]
It's not a raspbian issue, it's a Debian issue (which is a much wider audience of which a subset is Raspbian). I've tested this on x86_64 stretch too.

**Comment by udondan** [comment]
I was trying openFaaS on a new CentOS 7.3.1611 system and having the same issue. Removing the line `::1    localhost localhost6.localdomain6 localhost6` from `/etc/hosts` solved this.

**Comment by alexellis** [comment]
I believe it's because Docker doesn't support ipv6 with out of the box configuration - I.e. most people. Will ask at Dockercon if there is another fix for this other than using 127.0.0.1

**Comment by Lewiscowles1986** [comment]
So this affects CentOS, Debian, and Raspbian, localhost and any ipv6 address?

**Comment by alexellis** [comment]
I think I have said this before (maybe on Slack). It's any distro or OS with an ipv6 address for localhost. I think we've documented the behaviour of Docker on the main repo. I'll check once landed. It has nothing to do with Debian or Raspberry Pi specifically.

**Comment by alexellis** [comment]
@udondan alternatively use flag `--gateway http://127.0.0.1:8080` and with curl use the additional flag `-4`

**Comment by alexellis** [comment]
We now have generous timeouts for all functions between 60 and 120 seconds. Invoke is currently unlimited. Closing - please feel free to keep commenting.
