### ISSUE TITLE
Proposal: Set User-Agent: for all HTTP requests to identify FaaS-CLI

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#166]
Proposal: Set User-Agent: for all HTTP requests to identify FaaS-CLI

## Expected Behaviour

FaaS-CLI should identify itself through a standard HTTP header.

## Current Behaviour

`Go-http-client/2.0`

## Possible Solution

Add headers via Golang calls. See PR in motion #165

**Comment by Lewiscowles1986** [comment]
got it, thanks @alexellis should I base off of your PR or master?

**Comment by alexellis** [comment]
My PR I'd say - you will need the changes I believe.

**Comment by Lewiscowles1986** [comment]
I'm thinking that I can relocate version to it's own package (it's already injected on build for command version)

I'm not that great at go, but I think I'm nearly ready

**Comment by Lewiscowles1986** [comment]
okay I'm sure it's ready. I'll rebase against yours and merge once complete :+1:

**Comment by alexellis** [comment]
Completed.
