### ISSUE TITLE
Proposal: faas-cli should be able pass query string parameters

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#168]
## Expected Behaviour

```
faas-cli invoke flaskapp --query name=alex -q id=101 -q code=$CODE
```

## Current Behaviour

Can only do this via curl - or use the CLI with no query string.

## Possible Solution

Extend CLI code (this is written in Cobra) to add the parameters. See as an example "secrets" for the deploy command.

**Comment by nenadilic84** [comment]
@alexellis, why is this still open?

**Comment by alexellis** [comment]
Derek close
