### ISSUE TITLE
The CLI is setting fprocess to `node index.js` on deploy by default, ignoring the value set in images

### ISSUE THREAD

**Issue by johnmccabe** [openfaas/faas-cli#169]
## Expected Behaviour

If I set the `fprocess` envvar in a function image, I should be able to omit the `--fprocess` flag when deploying and have the value in the image used.

## Current Behaviour

Currently if I deploy using the CLI and omit the `--fprocess` flag then a default value is being set of `node index.js` in the deployed function.

See openfaas/faas#297 for an example.

## Possible Solution

I suggest we drop the default value for lang, which is where its falling over currently. We default to node, but I'm not sure this is particularly useful.

## Steps to Reproduce (for bugs)

1. `faas-cli deploy --image=functions/alpine:latest --name=func_alpine_test`
2. `faas-cli invoke func_alpine_test` - this will error out
3. Check the fprocess associated with that function in the UI - it'll be node.
4. `faas-cli deploy --image=functions/alpine:latest --name=func_alpine_test --fprocess="wc -l"`
5. `faas-cli invoke func_alpine_test` - this will succeed

## Context

The current behaviour is counter intuitive.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
`17.09.0-ce`
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS `10.12.6`
* Link to your project or a code example to reproduce issue:
https://github.com/openfaas/faas/tree/master/sample-functions/AlpineFunction

**Comment by johnmccabe** [comment]
Derek add label: bug

**Comment by johnmccabe** [comment]
Derek assign: johnmccabe

**Comment by alexellis** [comment]
Fix merged. Cheers John you ⭐️
