### ISSUE TITLE
Use strict parsing for --gateway flag

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas-cli#185]
I was trying to call `faas-cli list --gateway 10.244.0.6:8080`, which did not work. The error variable that you get when `http.NewRequest()` errors out is not assigned to a variable, and lost:

https://github.com/openfaas/faas-cli/blob/46b2db894024f8707d080510202a592930894d9e/proxy/list.go#L26

We assume the call succeeds, so we then call `client.Do()` with a `nil` request object.

## Expected Behaviour

The program should let me know what the expected format is for the `--gateway` param when I enter an incorrect one. It needs to be `http://10.244.0.6:8080` in this case.

## Current Behaviour

```
packet@kubehost1:~/faas/sample-functions$ fc ls --gateway 10.244.0.6:8080
2017/10/24 04:02:04 getReq is: <nil>, err is parse 10.244.0.6:8080/system/functions: first path segment in URL cannot contain colon
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x66750b]

goroutine 1 [running]:
net/http.(*Client).Do(0xc4200195c0, 0x0, 0xc4200398f0, 0x2, 0x2)
	/usr/local/go/src/net/http/client.go:491 +0x6b
github.com/openfaas/faas-cli/proxy.ListFunctions(0x7fff3c11873b, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openfaas/faas-cli/proxy/list.go:29 +0x2b0
github.com/openfaas/faas-cli/commands.runList(0x996c20, 0xc4200caa80, 0x0, 0x2)
	/go/src/github.com/openfaas/faas-cli/commands/list.go:59 +0xa0
github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra.(*Command).execute(0x996c20, 0xc4200caa20, 0x2, 0x2, 0x996c20, 0xc4200caa20)
	/go/src/github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra/command.go:654 +0x299
github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x9960e0, 0xc420096b40, 0xc420096c50, 0x0)
	/go/src/github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra/command.go:729 +0x339
github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra.(*Command).Execute(0x9960e0, 0x0, 0xffffffffffffffff)
	/go/src/github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra/command.go:688 +0x2b
github.com/openfaas/faas-cli/commands.Execute(0xc42000e600, 0x4, 0x4)
	/go/src/github.com/openfaas/faas-cli/commands/faas.go:47 +0x9b
main.main()
	/go/src/github.com/openfaas/faas-cli/app.go:19 +0x8c
```

## Possible Solution

Have an error handling at the `http.NewRequest()` in `proxy/list.go` and other commands.

## Steps to Reproduce (for bugs)

1. Call `faas-cli list --gateway <URL>` with a url that does not start with `http://`
2.
3.
4.

## Context

Trying to deploy faas on kubernetes on Packet.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
1.12.6
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
kubernetes
* Operating System and version (e.g. Linux, Windows, MacOS):
ubuntu 16.04
* Link to your project or a code example to reproduce issue:

**Comment by ericstoekl** [comment]
Derek assign: ericstoekl

**Comment by ericstoekl** [comment]
Derek add label: bug

**Comment by alexellis** [comment]
Yes we could add validation for this parameter for all the methods that need a gateway.

**Comment by alexellis** [comment]
Merged.
