### ISSUE TITLE
Proposal: Build and run tests on Windows with AppVeyor

### ISSUE THREAD

**Issue by stefanprodan** [openfaas/faas-cli#186]
## Expected Behaviour

We should build the CLI and run the unit tests on Windows to ensure everything works ok.

## Current Behaviour
No automated CI for Windows.

## Possible Solution
Reuse the AppVeyor setup from the watchdog project and add go test to it. 

Build script:
https://github.com/openfaas/faas/blob/master/watchdog/build.ps1

Docker file:
https://github.com/openfaas/faas/blob/master/sample-functions/BaseFunctions/golang/Dockerfile.win

**Comment by ericstoekl** [comment]
Derek add label: proposal

**Comment by ericstoekl** [comment]
Derek add label: skill/beginner

**Comment by ivanayov** [comment]
@stefanprodan is this still a valid proposal?
I can see the PR implementing it closed. Should we close the issue?

**Comment by stefanprodan** [comment]
Yes I'll close it. thanks for the ping
