### ISSUE TITLE
Deploy CentOS nodeJS image but got Internal Server Error Can't reach service 

### ISSUE THREAD

**Issue by rayhero** [openfaas/faas-cli#189]
Deploy CentOS nodeJS image but got Internal Server Error Can't reach service 

I try to run the sample nodejs-echo and it works on my k8s. Since I have some function
need to work on centOS, I need to install nodeJS on centOS kernel. I write a custom
Dockerfile and success build and deploy using faas-cli. But when I invoke the function 
I always get the error:
Server returned unexpected status code: 500 - Can't reach service: auto-hotspot

My kubectl log is show below:
``
kubectl logs deploy/auto-hotspot
öError from server (BadRequest): container "auto-hotspot" in pod "auto-hotspot-120556717-2hb8t" is waiting to start: trying and failing to pull image
``

and I try to using kubectl describe the deployment got below msg:
``
Name:			auto-hotspot
Namespace:		default
CreationTimestamp:	Thu, 26 Oct 2017 16:31:22 +0800
Labels:			faas_function=auto-hotspot
Annotations:		deployment.kubernetes.io/revision=1
Selector:		faas_function=auto-hotspot
Replicas:		1 desired ö 1 updated ö 1 total ö 0 available ö 1 unavailable
StrategyType:		RollingUpdate
MinReadySeconds:	0
RollingUpdateStrategy:	0 max unavailable, 1 max surge
Pod Template:
  Labels:	faas_function=auto-hotspot
  Containers:
   auto-hotspot:
    Image:	functions/base:node-latest-centos
    Port:	8080/TCP
    Liveness:	exec Äcat /tmp/.lockÅ delay=3s timeout=1s period=10s #success=1 #failure=3
    Environment:
      fprocess:	node handler.js
    Mounts:	<none>
  Volumes:	<none>
Conditions:
  Type		Status	Reason
  ----		------	------
  Available 	False	MinimumReplicasUnavailable
OldReplicaSets:	<none>
NewReplicaSet:	auto-hotspot-120556717 (1/1 replicas created)
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  11m		11m		1	deployment-controller			Normal		ScalingReplicaSet	Scaled up replica set auto-hotspot-120556717 to 1
``

## Expected Behaviour
work as same like  nodejs-echo, print the stdin to console

## Current Behaviour
always get the error:
Server returned unexpected status code: 500 - Can't reach service: auto-hotspot
I try to use docker run to check my image is work. And I can correct run it and the watchdog and 
node is correct be installed.

## Possible Solution
I try to use docker run to check my image is work. And I can correct run it and the watchdog and 
node is correct be installed.
Does the watch dog support centOS? I think the root cause is show on kubectl log:

My kubectl log is show below:
``
kubectl logs deploy/auto-hotspot
öError from server (BadRequest): container "auto-hotspot" in pod "auto-hotspot-120556717-2hb8t" is waiting to start: trying and failing to pull image
``

But I have no idea where I can change. If I open the async mode will works?

## Steps to Reproduce (for bugs)

1.  create a sample follow node base function sample:
 https://github.com/openfaas/faas/tree/master/sample-functions/BaseFunctions/node

2. change Dockerfile as below:
`
FROM centos

USER root

WORKDIR /root/

ADD https://github.com/openfaas/faas/releases/download/0.5.1-alpha/fwatchdog /usr/bin
RUN chmod +x /usr/bin/fwatchdog
RUN curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
RUN yum -y install nodejs
RUN yum install unzip -y

COPY package.json .
RUN npm i
COPY handler.js .
ENV fprocess="node handler.js"

HEALTHCHECK --interval=1s CMD [ -e /tmp/.lock ] || exit 1

CMD ["fwatchdog"]
`

3. build and deploy by faas-cli
4. check kubectl describe result

## Context
At beginning I try the nodejs-echo sample on my k8s. It works well. Then I try the node base function sample:
 https://github.com/openfaas/faas/tree/master/sample-functions/BaseFunctions/node

it's also works. Finally I change the Dockerfile to install nodeJS on centOS. I can success deploy but
can not reach the service 

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
 Kubernetes
* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS 10.12.5(latest)
* Link to your project or a code example to reproduce issue:
you can try echo -n "lalalala" ö faas-cli invoke --gateway http://35.192.105.196:8080 auto-hotspot

**Comment by rayhero** [comment]
I solve the problem...The root cause is my k8s is build on GCP. So I need to push my image to GCR. That's why I get the "trying and failing to pull image" error

**Comment by austinfrey** [comment]
Derek add label: question

**Comment by austinfrey** [comment]
@rayhero did you need anything else? or is this closable?

**Comment by alexellis** [comment]
@austinfrey please feel free to close resolved issues.

@rayhero feel free to keep commenting.
