### ISSUE TITLE
Should have - templates for other platforms like armv7/armv8

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#19]
Maybe the FaaS CLI should look at the `uname` on a local machine to decide whether to use the armv7 or armv8 templates.

i.e.

templates/armv6/node
templates/armv8/python

The main part of a template that needs to change is the line that picks up the watchdog binary and the base Docker image.

**Comment by rgee0** [comment]
Since the Dockerfile is the only part of templates that requires a change how about adding additional suffixed Dockerfiles within the existing structure?  We could then switch using `-f` in the build and limit duplication in the templates directories.

**Comment by alexellis** [comment]
Would that always be the case?

**Comment by rgee0** [comment]
Is the question "would there be any occasion when a language implementation would be different depending on hardware platform"?

**Comment by alexellis** [comment]
What is the latest thinking? new field in the YML file `architecture: armhf`? Or a new language - `language: node-armhf`?

**Comment by alexellis** [comment]
Supported and released. Closing issue.
