### ISSUE TITLE
Dependency resolution within template Dockerfiles

### ISSUE THREAD

**Issue by Lewiscowles1986** [openfaas/faas-cli#191]
TGI demo highlighted that Makefile or similar should be used to resolve deps

## Expected Behaviour

`faas-cli build -t func.yml` should build and fetch deps. Provided templates should provide that.

## Current Behaviour

When following the go hash tutorial presenter had an issue resolving dependencies.

## Possible Solution

The build is already multi-stage. Makefile in templates could assist in resolving deps. (IDK)

## Steps to Reproduce ~~(for bugs)~~

1. faas-cli new --name golang_test --lang go
2. follow golang hash tutorial

## Context

To be honest it's a nice to have, but would make getting started easier and lower ragequits / frustration.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ): recommended

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? faas-netes

* Operating System and version (e.g. Linux, Windows, MacOS): MacOS

* Link to your project or a code example to reproduce issue: Following golang serverless hash

**Comment by alexellis** [comment]
Going to close this for now. Happy to re-group next week on slack and review comments etc.
