### ISSUE TITLE
Proposal: Set default gateway value for executable

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas-cli#196]
It would be nice to be able to set the default gateway value, when you are working with `faas-cli` on a platform that requires it.

For example, when deployed on a raspberry pi with docker swarm, you will need to use `--gateway http://127.0.0.1:8080`. With kubernetes, you will need to use the IP of your gateway pod for the `--gateway` value.

## Expected Behaviour

Ability to set default gateway, then use `faas-cli` commands without the `--gateway` flag.

## Current Behaviour

Need to use `--gateway` flag for every command on pi and k8.

## Possible Solution

Leverage the Basic Auth Support WIP PR here ( #182 ) to add this functionality.

## Steps to Reproduce (for bugs)

1. Deploy on raspberry pi
2. Install `faas-cli`
3. You will need to use `--gateway http://127.0.0.1:8080` flag
4.

## Context

Talked about this in the slack channel https://openfaas.slack.com/archives/C4XCQR8TY/p1509377973000370

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker version 17.10.0-ce, build f4ffd25
Raspberry pi
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
jessie 2017-07-05
* Link to your project or a code example to reproduce issue:

**Comment by ericstoekl** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
Agreed, but bear in mind we already have at least 3 places we can override the gateway and this applies for every command. I recently wrote a unit test and function that deals with the ordering. Alternatively you can use a YAML file and specify the gateway there.

Do we have an alias for --gateway yet? Maybe we can add that first... `faas-cli list --gw $GW`

**Comment by developius** [comment]
@alexellis an alias would be good, I'd vote for `-g` unless that conflicts with something else

**Comment by ericstoekl** [comment]
@johnmccabe Do you know if it's possible to add an alias to a flag in cobra? The only other way I'm thinking of to add `--gw` as a shorthand for `--gateway` is to add `"gw"` as another flag, for example:

```
listCmd.Flags().StringVar(&gateway, "gw", defaultGateway, "Gateway URI")
```

**Comment by johnmccabe** [comment]
@ericstoekl adding a second longopt is not a good idea, aliases are for verbs only.

I would go with @developius' suggestion of adding the `-g` short flag.

**Comment by rgee0** [comment]
Can we try to keep issues on topic, please?  If another idea comes to the fore during discussions then a new issue should be raised to cover it.

As a point of accuracy - which I mention as some people will review issues as a sort of 1st line support mechanism - it is only necessary to specify `--gateway http://127.0.0.1:8080` on RPi when running with a IPv6 localhost entry in your hosts file.  As long as you have only an IPv4 entry then the default `http://localhost:8080` will resolve adequately.

On the original topic, env vars could be an option with the cli checking for an env var and reverting to the current default if one doesn't exist.  I've utilised a similar approach on a branch with Derek.

**Comment by alexellis** [comment]
Let's revisit later. We have good ways of doing this for now.

**Comment by Chrislevi** [comment]
Is there any ENV variable for the gateway url to override the default 8080? @alexellis
