### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by ilovezfs** [openfaas/faas-cli#204]
Is 0.4.3b considered newer than 0.4.20?

**Comment by rgee0** [comment]
0.4.3b is shown as the latest release.

0.4.20 was released 8 days ago

**Comment by ilovezfs** [comment]
Is there an explanation of this version scheme somewhere? If it continues like this we'll have to keep bumping the `version_scheme` in Homebrew over and over because it's not actually monotonically increasing.

**Comment by ilovezfs** [comment]
Specifically:
```
Josephs-MacBook-Pro:~ joe$ brew irb
V==> Interactive Homebrew Shell
Example commands available with: brew irb --examples
irb(main):001:0> Version.new("0.4.3b") > Version.new("0.4.20")
=> false
irb(main):002:0> 
```

**Comment by alexellis** [comment]
We'll fix this, sorry for any inconvenience.

**Comment by ilovezfs** [comment]
@alexellis no worries.

**Comment by alexellis** [comment]
Look out for 0.4.39 just released now.

**Comment by ilovezfs** [comment]
Perfect. I'll close https://github.com/Homebrew/homebrew-core/pull/20258.

**Comment by ilovezfs** [comment]
Voilà: https://github.com/Homebrew/homebrew-core/pull/20274
