### ISSUE TITLE
Weird permission issue with node.js when requiring packages.

### ISSUE THREAD

**Issue by kenfdev** [openfaas/faas-cli#215]
When you `npm install --save` a package and `faas-cli build` it on a `OSX` machine, `faas-cli deploy` ing it to a `ubuntu` machine causes a permission error when `require` ing the package.

## Expected Behaviour

We should be able to `faas-cli build` on any machine and `faas-cli deploy` it to any machine.

## Current Behaviour

`faas-cli build` ing on `OSX` and `faas-cli deploy` ing it on `OSX` which has Docker for Mac works as expected. But deploying the same image to an `ubuntu` machine creates an error

## Possible Solution

https://github.com/openfaas/faas-cli/blob/master/template/node/Dockerfile#L32

I think this line is copying the `node_modules` the local machine already has. We should be ignoring the `node_modules` the local machine already has and install a clean version while `faas-cli build` ing.
One way to fix this is probably to add a `.dockerignore` file to the `template/node` . With the content like the following:

```
function/node_modules
npm-debug.log
```

## Steps to Reproduce (for bugs)

1. `faas-cli new faas-test-permission --lang node`
2. `npm install --save request`
3. Add a `require` statement
```
"use strict"

var request = require('request');

module.exports = (context, callback) => {
    callback(undefined, {status: "done"});
}
```

4. `faas-cli build -f faas-test-permission.yml` on an `OSX` machine
5. `faas-cli push -f faas-test-permission.yml` on an `OSX` machine
6. `faas-cli deploy -f faas-test-permission.yml` to an `ubuntu` machine with  gateway running

Invoking the function will produce an error like the following:

```
exit status 1
module.js:471
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/app/function/handler.js:3:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

## Context

Developing on Mac and deploying to Ubuntu isn't working as expected.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Developing on MacOS and deploying to Ubuntu.

* Link to your project or a code example to reproduce issue:
https://github.com/kenfdev/faas-test-permission

**Comment by kenfdev** [comment]
Derek add label: bug

**Comment by alexellis** [comment]
Try creating a . dockerignore file in there for `node_modules`

**Comment by nicholasjackson** [comment]
This pull request should fix if you could test @kenfdev

https://github.com/openfaas/faas-cli/pull/216

**Comment by kenfdev** [comment]
Thanks @nicholasjackson , I've commented on the PR. Thank you!

**Comment by alexellis** [comment]
Thanks @nicholasjackson and @kenfdev - FYI templates now exist in openfaas/templates.

**Comment by shubhamseth29** [comment]
@alexellis I am facing a similar issue , I am using a library aspose.cells in my handler.js file , added it in package.json , but on deploying function and invoking it , I get error cannot find module 'aspose.cells'.
npm install is running , then what can be the issue ?

**Comment by welteki** [comment]
Hi, @shubhamseth29

Could you please open an issue in: https://github.com/openfaas/templates.

Make sure to fill out the issue template and include an example or link to a repo. Also specify which NodeJS template you are using.

This will give us the information we need to help you further.

Han
