### ISSUE TITLE
`faas-cli deploy` needs to wait until function has been deleted before running deploy

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas-cli#217]
On kubernetes with multi-node cluster on AWS EC2, I get this error when using `faas-cli deploy` on an already deployed function:

```
Deploying: url-ping.
Removing old function.
Unexpected status: 500, message: object is being deleted: deployments.extensions "url-ping" already exists
500 Internal Server Error
Deploying: nodejs-echo.
Removing old function.
Unexpected status: 500, message: object is being deleted: deployments.extensions "nodejs-echo" already exists
500 Internal Server Error
Deploying: shrink-image.
No existing function to remove
Deployed.
URL: http://10.244.0.19:8080/function/shrink-image
```

The function will eventually terminate, but it will not re-deploy. Will have to run `faas-cli deploy` again.

## Expected Behaviour

The cli tool waits until the function has been deleted before deploying in `faas-cli deploy` in kubernetes.

## Possible Solution

Poll a kubernetes endpoint

## Steps to Reproduce (for bugs)

1. Deploy 3 node cluster on kubernetes
2. `faas-cli deploy` a stack of functions
3. Rerun `faas-cli deploy` on the same stack. 
4.It will delete, then be unable to deploy

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
ubuntu@ip-172-31-46-242:~/faas-cli$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit
```

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes faas-netes latest

* Operating System and version (e.g. Linux, Windows, MacOS):
ubuntu 1604 on EC2

* Link to your project or a code example to reproduce issue:

**Comment by ericstoekl** [comment]
derek add label bug

**Comment by ericstoekl** [comment]
derek add label: bug

**Comment by ericstoekl** [comment]
Derek add label: bug

**Comment by alexellis** [comment]
I don't think we can wait as this is an async operation. I'd rather resolve this by checking if the function exists then doing a rolling update. Would you like to work on this?

**Comment by alexellis** [comment]
Derek close

**Comment by alexellis** [comment]
We've resolved this via the rolling update. Thanks for raising Eric
