### ISSUE TITLE
Feature: OpenFaaS store integration

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#237]
The `faas` CLI should allow users to browse and deploy functions from the [OpenFaaS Function Store](https://github.com/openfaas/store)

Three new commands:

* `faas store list`
Fetches/parses JSON and lists all items

* `faas store inspect`
Gives specific info on one item

* `faas store deploy`
Same as faas-cli deploy except pre-loaded with arguments from JSON file. Must take all valid overrides such as `--gateway` and `--env`

## Example usage:

```
$ faas store list

Function                 Description
figlet                       Create ASCII logos

$ faas store inspect figlet

Function                 Description                                                     Image                         Function Process
figlet                       Create ASCII logos                                         alexellis/asciilogos     node handler.js


$ faas store deploy figlet
```

## Out of scope

* `faas store search`
* `faas store list --filter`

**Comment by amirkarimi** [comment]
If it doesn't have a very high priority, I would like to work on this. I suppose it can get the data directly from the store repo?

**Comment by alexellis** [comment]
Yes we download and parse the JSON file over the GitRaw CDN.

**Comment by alexellis** [comment]
Thank you @amirkarimi - just to update Amir has started working on this change. Look out for a PR - maybe @BurtonR + @ericstoekl can collaborate / help out with stuff.
