### ISSUE TITLE
Unused method - buildLabelMap() in commands/deploy.go

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas-cli#238]
While looking over the `commands/deploy.go` I came across this function, which is unused:

https://github.com/openfaas/faas-cli/blob/741412dff6a964584fb97438466adde1b22b83b6/commands/deploy.go#L209

I would like to remove but first we should make sure that Labels are getting parsed correctly, and the behavior described in the `buildLabelMap()` method is actually being applied to the label map by `mergeMap()`.

## Expected Behaviour

`buildLabelMap()` is used to create the label map

## Current Behaviour

`mergeMap()` is used to create the label map

## Possible Solution

Review this code in detail to find out if it's doing what we want. If so, it's safe to remove `buildLabelMap()`

## Steps to Reproduce (for bugs)

1. Code issue, no repro steps.
2.
3.
4.

## Context

Ran into this while reviewing the `commands/deploy.go` file.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker version 17.11.0-ce-rc2, build d7062e5

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 16.04

* Link to your project or a code example to reproduce issue:

**Comment by ericstoekl** [comment]
Derek assign: ericstoekl

**Comment by alexellis** [comment]
@ericstoekl are you sure the label is un-used? If so then I approve it - go ahead and remove it in a PR.

**Comment by alexellis** [comment]
@ericstoekl or @dungeonmaster18 please go ahead and fix.

**Comment by dungeonmaster18** [comment]
It seems that it's not been used. Creating PR
