### ISSUE TITLE
Proposal: Should retrieval of the official templates auto patch Dockerfiles on ARM?

### ISSUE THREAD

**Issue by rgee0** [openfaas/faas-cli#239]
## Expected Behaviour
`faas-cli new` results in templates being pulled from the official repo if the required language template doesn't already exist.  Should this facility also assess the host architecture and if found to be `arm` move the `armhf` Dockerfiles into the default language directories? 

## Current Behaviour
`faas-cli build` drops out at the Dockerfile stage giving rise to a poorer UX.

## Possible Solution
Auto patch on ARM.
Multi arch base images
Friendly error message reminding user to check that the Dockerfile is appropriate to host arch

## Steps to Reproduce (for bugs)
Run the following in a clean directory on ARM
1. `faas-cli new --lang python fred`
2. `faas-cli build -f fred.yml`
3. Observe as the build fails

## Context
Minor niggle upon forgetting and consequently having to run the build twice.  Concerned that fresh users might be put off when the build fails.

## Your Environment
* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:30:54 2017
 OS/Arch:      linux/arm

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:30:54 2017
 OS/Arch:      linux/arm
 Experimental: false
```
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
```
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
I think we should tell people to use the template python-armhf. I think they are full templates now rather than patched as before we couldn't support multiples that weren't hard-coded.

**Comment by alexellis** [comment]
Thoughts @rgee0 ?

**Comment by rgee0** [comment]
They are full templates.  I still think there is scope for a more consistent UX across architectures.  It would mean amending the approach suggested earlier so that the default language template **directory** is renamed and the appropriate hardware specific directories become the new defaults.

From a users' perspective they should be able to run `--lang python` regardless of what their hardware is.  Similarly, bloggers and technical authors should be able to specify one command for all available architectures.

**Comment by alexellis** [comment]
They are now full templates but under different names for the relevant architecture. Closing the issue.
