### ISSUE TITLE
Nodejs templates use `let` where `const` would be more appropriate

### ISSUE THREAD

**Issue by diddledan** [openfaas/faas-cli#240]
The nodejs templates use `let` where `const` might be more appropriate, as the values stored within the names are unchanging.

## Expected Behaviour

Uses `const` keywords for constant values in nodejs templates.

## Current Behaviour

Currently the nodejs templates use the `let` keywords for values that do not change.

## Possible Solution
Change `let` keywords to `const` in nodejs templates.

## Steps to Reproduce (for bugs)

1. no reproduction steps. This is not really a bug, more a code-style issue.

## Context
This doesn't affect adversely. The change is merely code-style.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Not relevant, but 17.11.0-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Not relevant, but Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Not relevant, but Windows and Linux

* Link to your project or a code example to reproduce issue:
The proposed fix is included in my `patch-1` branch at https://github.com/diddledan/faas-cli/tree/patch-1

**Comment by developius** [comment]
Looks good and shouldn't cause any issues 👍 worth opening a PR I reckon.

/cc @austinfrey

**Comment by alexellis** [comment]
Hey @diddledan go for it and raise a PR (but do it via the `git` CLI so you can sign off). I have no strong feelings about this change - like you say it's purely stylistic.
