### ISSUE TITLE
Golang template Dockerfile's gofmt find command doesn't ignore vendor directories

### ISSUE THREAD

**Issue by ChrisCGH** [openfaas/faas-cli#244]
## Current Behaviour
The Dockerfile for the golang template attempts to ignore the vendor directories in the find command used when running gofmt -l, by specifying '-not -path "./vendor/*"', but when running faas-cli build the vendor directories are still checked, causing the build to fail when some vendor code is not formatted according to gofmt's rules.
## Possible Solution
The find cmd should specify '-path ./vendor -prune' instead.

## Your Environment
* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker-ce 17.11.0

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Fedora 26

**Comment by ChrisCGH** [comment]
Actually, suggested solution isn't quite right, I'll update when I've wrestled find into submission

**Comment by ChrisCGH** [comment]
find . -path ./vendor -prune -o -type f -name '*.go' -print 
should work

**Comment by ChrisCGH** [comment]
More investigation showed it was probably my fault: the path to be ignored should have been ./function/vendor and that could be because of the changes I've made to the Dockerfile, so I'll close this issue

**Comment by alexellis** [comment]
Hey Chris glad you resolved this and thank you for using OpenFaaS
