### ISSUE TITLE
Point default templates at new location in faas-cli code

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#248]
The templates can now graduate to their own repo openfaas/templates.

Pros:
* This means a smaller download

Cons:
* Minor code change and dual-maintenance while we move people over to the new version that knows to pul from the new location.

https://github.com/openfaas/templates

Help is wanted - this is a beginner-level item.

Alex

**Comment by viveksyngh** [comment]
@alexellis I would like to work on this one.

**Comment by austinfrey** [comment]
@viveksyngh i believe there is already a PR out for it #252. Feel free to test it out and provide feedback. What are your interests? Maybe I could point you to some other issues?

**Comment by viveksyngh** [comment]
@austinfrey My interests are Golang, Docker and I am open to something new as well. Please point to some other issues on which I work.

**Comment by austinfrey** [comment]
@viveksyngh I've tagged you in some open issues that could use some attention. let me know if any suit you

**Comment by itscaro** [comment]
close #248 via #252

**Comment by itscaro** [comment]
@alexellis why don't we delete the templates in this repo?

**Comment by alexellis** [comment]
It's a breaking change - so there will be some people with the old CLI prior to the change here. As soon as we delete them they'll get a crash without a very good explanation.
