### ISSUE TITLE
Add CPU limit to deployment options

### ISSUE THREAD

**Issue by nicholasjackson** [openfaas/faas-cli#250]
Currently only Memory is passed as a deployment option, this should be extended to allow passing of CPU limits.

## Expected Behaviour
When a limit for cpu is defined in a stack yaml file this should be passed to the gateway

## Current Behaviour
Only memory is passed

## Possible Solution
Add additional parameter from yaml

**Comment by austinfrey** [comment]
Derek add label: proposal
