### ISSUE TITLE
issue with function file permissions 

### ISSUE THREAD

**Issue by ganesshkumar** [openfaas/faas-cli#253]
I am creating a template and provide some default scripts(with execute permission for the user) that belong to the function
```
|--template
  |-- my-template-name
     |--function
        |-- default-script
```

I pulled the template from github, examined the template folders. It has the execute permission as it had been set. 

Later, I create a function out of my template and in the new generated function folder, the script has only read and write permission for the user. It does not have the execute permission. 

## Expected Behaviour
The newly created function should have the permission of the files as in the template.

## Current Behaviour
The generated function files have only read and write permission.

## Possible Solution
I have narrowed down the code to [new_function.go](https://github.com/openfaas/faas-cli/blob/master/commands/new_function.go#L104) and [build.go](https://github.com/openfaas/faas-cli/blob/master/builder/build.go#L89). I am not sure how go handles the permission during file creation.

## Steps to Reproduce (for bugs)
```
$ faas-cli template pull https://github.com/ganesshkumar/openfaas-template-java
$ faas-cli new --lang java-gradle gradle-function
```
Since, I am creating a gradle based function, there is a `gradlew` executable in the function folder, that will build the jar.

**Difference between the permissions in function file and template file**
```
$  ll java-function/gradlew
-rw-r-----  1 ganessh  staff   5.2K Dec 10 14:59 java-function/gradlew

$  ll template/java-gradle/function/gradlew
-rwxr-xr-x  1 ganessh  staff   5.2K Dec 10 14:30 template/java-gradle/function/gradlew
```

It leads to failure of the project build using docker
```
$  functions faas-cli build -f java-function.yml

[0] > Building: java-function.
Clearing temporary build folder: ./build/java-function/
Preparing ./java-function/ ./build/java-function/function
Building: java-function with java-gradle template. Please wait..
Sending build context to Docker daemon  33.28kB
Step 1/21 : FROM anapsix/alpine-java:8_jdk as builder
 ---> 46796749789c
Step 2/21 : USER root
 ---> Using cache
 ---> 6b354a844d9d
Step 3/21 : RUN mkdir -p /root/src/
 ---> Using cache
 ---> 151625409012
Step 4/21 : ADD function /root/src/
 ---> Using cache
 ---> fee9b46f6986
Step 5/21 : WORKDIR /root/src/
 ---> Using cache
 ---> 51b126cb2a6a
Step 6/21 : RUN ./gradlew
 ---> Running in 988f3123c86c
/bin/sh: ./gradlew: Permission denied
The command '/bin/sh -c ./gradlew' returned a non-zero code: 126
2017/12/10 14:54:35 ERROR - Could not execute command: [docker build -t java-function .]
```

## Your Environment

* Docker version 17.09.0-ce
* Docker Swarm
* Operating System: macOS Sierra (10.12.6)

**Comment by ganesshkumar** [comment]
Just noticed that, in the [`cp`](https://github.com/openfaas/faas-cli/blob/master/builder/build.go#L143) function in `builder.go` has explicit mask 066 set.

```
writeErr := ioutil.WriteFile(destination, memoryBuffer, 0660)
```

This functions is also being used to move the function files to `./build` directory when executing `faas-cli build`. So the permission on files created inside the function is also lost. 

Any specific reason behind the explicit 0660 mask?

**Comment by alexellis** [comment]
Hey @ganesshkumar thank you for this fix. We've merged the code and it will be part of the next release.
