### ISSUE TITLE
Support npm installation from git repositories (including private) for --lang=node

### ISSUE THREAD

**Issue by ryanfields** [openfaas/faas-cli#255]
## Expected Behaviour

Packages containing dependencies from Github, Bitbucket, etc should be installed in image. 

## Current Behaviour

Image is missing git and openssh-client packages, preventing npm from installing from git repositories.  Further, because there is no mechanism for configuring SSH or providing private keys, private repositories cannot be accessed.

## Possible Solution

1. Option to ensure that git and openssh-client packages are installed on image.
1. Mechanism for making key files available to builder
1. Add keys and set GIT_SSH_COMMAND env used by npm
```
# Configure SSH
COPY keys/deploy_rsa ./deploy_rsa
RUN chmod 600 ./deploy_rsa
ENV GIT_SSH_COMMAND='ssh -i /home/app/deploy_rsa -o "StrictHostKeyChecking=No"'
```

If I edit the Dockerfile in template/node to include the extra ```apk add``` commands and a slightly modified version of the _Configure SSH_ section above, I can get my npm install to succeed.  I'm also running a step later in the file to remove the deploy key when I no longer need it.  It's a bit sloppy that I have to put my key into the function folder in order to get it into the image.  Also, when files are copied to the build directory, their permissions are not respected, hence the ```chmod``` line above.

This issue also raises another, which is that some npm packages have build steps that rely on the presence of native packages.  The only way to ensure those builds succeed is to customize template/node/Dockerfile to install required packages.  At the very least, ```build-base``` is a commonly needed alpine package.

Since I'm editing the contents of template/node/Dockerfile, this feels unsustainable as a means of solving this problem long-term.  I'm not sure if there's any kind of best-practice approach for modifying the contents of template, especially since it's in .gitignore.  If I'm going to be using a customized Dockerfile, I definitely need it to exist in the repo of my function suite.  It would be my preference to not have to customize Dockerfile by hand at all.  At the very least, it'd be ideal if extra apk packages could be specified in the YAML stack file.  As for the other customizations to the Dockerfile, maybe some way to identify certain sections of the Dockerfile and include user-defined partial content into those sections?  (CONFIGURE_APP_DIR, CONFIGURE_FUNCTION_DIR, BEFORE_NPM_INSTALL, AFTER_NPM_INSTALL, etc)

## Context

Some of my functions need to rely on npm packages contained in a private Bitbucket repository.  It is not an option for me to publish these packages to the public npm repository.

**Comment by itscaro** [comment]
@ryanfields For a custom Dockerfile, you can create your own template based on the minimalist one provided. You can find the documentation in `guide/TEMPLATE.md`

**Comment by ryanfields** [comment]
There are a number of challenges that the templates solution alone doesn't address.  Some of those challenges them stem from the fact that I group functions into suites, but I don't need all of the same build steps for every function.

I don't need the same set of native packages for every function, for example, but unless there's a way to associate different templates with different functions, all of my functions will be packaged up with _all_ of the dependencies for _all_ functions.

This becomes even more of an issue when arbitrary files are added (such as key files).  I only get one template per suite of functions, and the Docker build context is set to the function folder.  This results in me having to copy the full collection of arbitrary files into every single function directory that I'm going to build against the custom template.  Otherwise, the custom template will fail when it reaches some part that applies to some functions but not others.

Even in the simplest case where I just want a single key added to most builds, I have to have a separate copy of that key in each function folder.  If the key ever changes, that's a lot of work (or an extra script I have to maintain) to replace the key across all builds.

Unless I stop grouping my functions into suites, I seem to need two additional features from faas-cli even if I'm using custom templates:
1. I need to be able to point to different templates for different builds.
2. I need to be able to specify a different build context for Docker.

Those two features would work okay as a compromise.  I'd still wind up with a whole lot of duplication between Dockerfiles, so I'd still need to come up with some kind of solution for building Dockerfiles from a template before I then use them to build functions.

**Comment by ryanfields** [comment]
It looks like modifications to build.go could resolve the majority of the challenges I'm facing.  If build.go's createBuildTemplate or related functions could check the YAML stack file for a list of arbitrary files to import into the temporary build directory, then I could make use of those files via a custom template.  I have the information I need to use custom templates.  I'm just lacking the ability to get common files into the build dir, and the ability to signal to my custom shell scripts that certain build steps should or shouldn't be run.  The build-args fix suggested in #262 would solve that latter challenge, but I'm still in need of the ability to copy files to the build directory prior the `docker build` call in build.go

I think I proposed this elsewhere, but I envision the YAML file to include something like:

```
docker:
  build-args:
    with-ssh: 1
    with-git: 1
    
build:
  extra-files:
    - from: ./common/my_repo_key_rsa
      to: keys/repo_rsa
    - from: ./common/setup.sh
      to: scripts/common-setup.sh
```

build.go would take care of copying those files, and then my Dockerfile coming from my custom template would contain something like:

```
ENV INSTALL_SSH=$with-ssh
ENV INSTALL_GIT=$with-git

COPY scripts/common-setup.sh ./common-setup.sh
RUN ./common-setup.sh

COPY keys/repo_rsa .ssh/repo_rsa
RUN chmod 600 .ssh/repo_rsa
ENV GIT_SSH_COMMAND='ssh -i /home/app/.ssh/repo_rsa -o "StrictHostKeyChecking=No"'
```

common-setup.sh would look at that first group of ENV vars to decide whether or not a given function image needs extra setup like `apk install openclient-ssh` and such.  The latter stuff deals with allowing my npm installs to pull from private repos.

**Comment by alexellis** [comment]
What is the concept of this?

```
build:
  extra-files:
    - from: ./common/my_repo_key_rsa
      to: keys/repo_rsa
```

What does it mean "extra files" and "from" and "to" where?

**Comment by ryanfields** [comment]
An example function suite would be set up like this:

```
my_function1/
my_function2/
common/
  my_repo_key_rsa
functions.yml
template/
```

`faas-cli build` will create a `build/` directory, and within it a `my_function1/` directory (and then later a `my_function2/` directory.)  When `build/my_function1/` is created, the Dockerfile and other template files are copied from the appropriate `template/` subfolder, as are the contents of `./my_function1`.  During this step, the above yaml section would instruct `faas-cli` to also copy `./common/my_repo_key_rsa` into `build/my_function1/keys/repo_rsa`.

This would allow me to have a pool of common files that I can insert into the build directories prior to the Docker build.  Those common files would then be part of the Docker build context and could be used by my custom `./template/node/Dockerfile`.

Without this functionality, I would have to include a duplicate copy of `my_repo_key_rsa` in every single function directory in the suite.  The same would go for any common configuration files.  And yes, I could use symlinks to mitigate the "what happens when a common file needs to be replaced/changed" but that still ends up requiring devs to remember to set up symlinks after checking out the repo.  Having the common files declared in the yaml allows that to be very explicitly committed to the repo and self-documented within the suitem and makes the suite immediately ready to be built by a developer or CI without any extra steps after a `git clone`.

**Comment by alexellis** [comment]
How would you solve this specific problem with a static Dockerfile? Can you write one that does above?

**Comment by ryanfields** [comment]
The following is what I've been experimenting with most recently:

```
FROM node:8.9.1-alpine

RUN addgroup -S app && adduser -S -g app app

# Alternatively use ADD https:// (which will not be cached by Docker builder)
RUN apk --no-cache add curl \
    && echo "Pulling watchdog binary from Github." \
    && curl -sSL https://github.com/openfaas/faas/releases/download/0.6.9/fwatchdog > /usr/bin/fwatchdog \
    && chmod +x /usr/bin/fwatchdog \
    && apk del curl --no-cache \
    && apk --no-cache add git \
    && apk --no-cache add openssh-client

WORKDIR /root/

# Turn down the verbosity to default level.
ENV NPM_CONFIG_LOGLEVEL warn

RUN mkdir -p /home/app

# Wrapper/boot-strapper
WORKDIR /home/app
COPY package.json ./

# This ordering means the npm installation is cached for the outer function handler.
RUN npm i

# Copy outer function handler
COPY index.js ./

# Configure SSH
COPY keys/deploy_rsa ./deploy_rsa
RUN chmod 600 ./deploy_rsa
ENV GIT_SSH_COMMAND='ssh -i /home/app/deploy_rsa -o "StrictHostKeyChecking=No"'

# COPY function node packages and install, adding this as a separate
# entry allows caching of npm install
WORKDIR /home/app/function
COPY function/*.json ./
RUN npm i || :

# COPY function files and folders
COPY function/ ./

# Remove deploy key
RUN rm ../deploy_rsa && rm ./deploy_rsa

# Set correct permissions to use non root user
WORKDIR /home/app/

# chmod for tmp is for a buildkit issue (@alexellis)
RUN chown app:app -R /home/app \
    && chmod 777 /tmp

USER app

ENV cgi_headers="true"
ENV fprocess="node index.js"

HEALTHCHECK --interval=1s CMD [ -e /tmp/.lock ] || exit 1

CMD ["fwatchdog"]
```

I'm already able to use this template in our setup, following the instructions that were presented earlier in this issue thread at (https://github.com/openfaas/faas-cli/blob/master/guide/TEMPLATE.md).  The only line that can't work is:

```
COPY keys/deploy_rsa ./deploy_rsa
```

This is because there's currently no way for me to add arbitrary files to the build before Docker is called.

**Comment by ryanfields** [comment]
I'm closing this issue.  If support for Docker build args gets added to faas-cli (#262), I can resolve the rest of my issues through custom templates.
