### ISSUE TITLE
Backlog: prefer rolling update over delete/create

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#256]
## Description

For `faas deploy` we should prefer rolling updates over our current delete/create pattern.

You can get similar behaviour by doing `--update=true --replace=false`.

## Expected Behaviour

CLI should try to update service rather than delete/create. We did this initially to get to "update-like" behaviour faster but it causes issues with K8s which is slow to delete definitions.

When deploying functions let's first try an update, if we get a 404 we'll then send in a create instead.

Help wanted for this one, looking for the community to lead the changes including testing.

**Comment by ericstoekl** [comment]
derek assign: ericstoekl

**Comment by ericstoekl** [comment]
Derek assign: ericstoekl
