### ISSUE TITLE
[re-factoring] Gather errors into one place & use errors.New() to define errors

### ISSUE THREAD

**Issue by itscaro** [openfaas/faas-cli#259]
## Context
Currently errors are generated with `fmt.Errorf` which is not re-usable to compare errors in unit-test, there are many copy-paste of the error strings.

Instead of creating errors with `fmt.Errorf`, we can pre-defined errors with `errors.New()` and we can re-use the errors everywhere in the package.

This applies to errors whose string is not formatted with `printf` since the string is constant.

**Comment by ivanayov** [comment]
This proposal seems not approved, so I'm closing the issue.
Please feel free to comment, if you have any additional input or think this should be revisited. Thanks

**Comment by ivanayov** [comment]
Derek close
