### ISSUE TITLE
Error on faas-cli on windows

### ISSUE THREAD

**Issue by vodasan** [openfaas/faas-cli#263]
I'm trying openFaas. I use docker swarm.

When i use faas-cli (faas-cli list or other commands) I have this message ?

> give either -action= build or deploy

## Steps to Reproduce (for bugs)

1. docker swarm init --advertise-addr eth1
2. deploy_stack.sh
3. faas-cli list

**Comment by alexellis** [comment]
Did you find out what was going wrong?
