### ISSUE TITLE
`faas-cli deploy` stalls at 'Deploying: <image_name>'

### ISSUE THREAD

**Issue by mysmartbus** [openfaas/faas-cli#264]
Installed Docker, faas, and faas-cli following the instructions at https://blog.alexellis.io/your-serverless-raspberry-pi-cluster/ then went to step 3 of https://blog.alexellis.io/first-faas-python-function/ to create hello-python demo image. `faas-cli new` and `faas-cli build` work as expected.

My problem occurs when I try to deploy the hello-python demo image with `faas-cli deploy`. The command never displays anything other than `Deploying: hello-python`.

Docker hello-world works (`docker run hello-world`) as expected.
The OpenFaas Portal can be accessed from any computer on the network.

## Expected Behaviour
```
faas-cli deploy -f ./hello-python.yml
Deploying: hello-python.  
No existing service to remove  
Deployed.  
200 OK  
URL: http://localhost:8080/function/hello-python
```

## Current Behaviour
Unable to deploy new functions using `faas-cli deploy`.

## Possible Solution
None identified yet.

Any possibility of having `faas-cli` do some logging when deploying a function?

## Steps to Reproduce (for bugs)
I can reproduce by running `faas-cli deploy -f ./hello-python.yml`

## Context
faas-cli is useless to me if I can't create, edit, delete, or deploy new functions via bash scripts.

## Your Environment

My docker swarm consists of 1 Raspberry Pi 2 and 4 Raspberry Pi 3's. The Pi 2 is a manager (availability=drained), 2 of the Pi 3's are managers and the other Pi 3's are workers.

All of the Pi's are running Raspbian Jessie 8.0.

```
$ docker version
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:53:02 2017
 OS/Arch:      linux/arm

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:45:14 2017
 OS/Arch:      linux/arm
 Experimental: false
```

```
$ faas-cli version
Commit: d1d38e9b2d5600a3485442b75641bf73b566313b
Version: 0.5.1
```

## Edit (Add Stack Trace)
Added: 2017-12-21 17:47
Running a stack trace on `strace faas-cli deploy -f ./hello-python.yml` pauses at an `epoll_wait` after checking for `/home/pi/.openfaas/config.yml`
```
...snip...
futex(0x108480ac, FUTEX_WAKE, 1)        = 1
stat64("stack.yml", 0x10868804)         = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "./hello-python.yml", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fstat64(3, {st_mode=S_IFREG|0600, st_size=162, ...}) = 0
read(3, "provider:\n  name: faas\n  gateway"..., 674) = 162
read(3, "", 512)                        = 0
close(3)                                = 0
write(1, "Deploying: hello-python.\n", 25Deploying: hello-python.
) = 25
stat64("./template/python/template.yml", {st_mode=S_IFREG|0644, st_size=43, ...}) = 0
openat(AT_FDCWD, "./template/python/template.yml", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
fstat64(3, {st_mode=S_IFREG|0644, st_size=43, ...}) = 0
read(3, "language: python\nfprocess: pytho"..., 555) = 43
read(3, "", 512)                        = 0
close(3)                                = 0
stat64("/home/pi/.openfaas/config.yml", 0x10868b64) = -1 ENOENT (No such file or directory)
futex(0x108480ac, FUTEX_WAKE, 1)        = 1
futex(0x4cc6b4, FUTEX_WAIT, 0, NULL)    = 0
epoll_wait(4, {}, 128, 0)               = 0
epoll_wait(4, 
```

**Comment by mysmartbus** [comment]
To get the function to deploy, I had to edit `hello-python.yml` and change the gateway from `http://localhost:8080` to `http://127.0.0.1:8080`.

Using `--gateway http://127.0.0.1:8080` instead of change the gateway in `hello-python.yml` also allowed the function to deploy.

**Comment by alexellis** [comment]
Hi @mysmartbus glad this worked out for you. This is documented on the site and is an artefact of the way some Linux distros map an IPv6 alias to `localhost`. If we can help more please get back in touch and thank you for using OpenFaaS!
