### ISSUE TITLE
[Proposal] Pull templates from private Git repos using CLI

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-cli#266]
The `faas-cli template pull` command should support pulling template definitions from both public and private git repositories.  It would also be good to support hosts beyond Github.  The cli should support pulling via ssh or via https with username and password.

Supporting private repos and other git servers improve the support for users with high security constraints, e.g. large enterprises that host on-prem.  

## Expected Behaviour
If I run 
```sh
faas-cli template pull https://github.com/LucasRoesler/privatefunctions0.git
faas-cli template pull git@github.com:LucasRoesler/privatefunctions1.git
faas-cli template pull git@gitlab.com:LucasRoesler/privatefunctions2.git
faas-cli template pull https://lucasroesler.com/bitbucket/privatefunctions3.git
```
I expect that a `template` folder in the project is populated with the functions from each of the repositories.  If there is a name conflict, I expect the command to report the issue, it should ask me to skip or overwrite. If I pass the `--overwrite` flag, it should assume overwrite for any name conflicts.

## Current Behaviour
```sh
$ faas-cli template pull git@github.com:LucasRoesler/privatefunctions1.git
The repository URL must be in the format https://github.com/<owner>/<repository>
```

## Possible Solution
Mimic the solution in `go get` by using `exec.Command` to run the git command and utilize the users git configuration including credentials.  See https://github.com/golang/go/blob/master/src/cmd/go/internal/get/vcs.go

**Comment by alexellis** [comment]
@LucasRoesler - this is a sensible request and I know it will help your business use-case. I'd be concerned about reinventing the wheel here or having to vendor too many packages - so I like the idea of using a fork/exec out to `git` - that way we get access to any credential cache/helper for `git` too.

We'd need to bring the folder down into a temporary location and then find the templates folder and bring it back to the local context.

Would you be able to put together a sequence diagram to attach to the issue?

## Other notes:

This will also mean we'd remove the code responsible for handling .zip files as this is the only purpose for the code.

Suggested reviewers: @ericstoekl @itscaro

**Comment by LucasRoesler** [comment]
For a sequence diagram, were you thinking something like this
![faas-cli-template-pull-flow](https://user-images.githubusercontent.com/891889/34352828-173a266c-ea25-11e7-9142-c9e01655e522.png)

**Comment by alexellis** [comment]
I was thinking about a UML sequence diagram, but this works well to convey the flow.

**Comment by alexellis** [comment]
@LucasRoesler is this diagram still valid? Can we add it into the docs here?

**Comment by LucasRoesler** [comment]
No, i will need to update it

**Comment by LucasRoesler** [comment]
![faas-cli-template-pull-flow 1](https://user-images.githubusercontent.com/891889/35037398-ac6ce176-fb77-11e7-8b78-92197093b437.png)

I changed it to reflect the fact that there is no interactive "should I overwrite" behavior, it is only handled by cli flags.

**Comment by dungeonmaster18** [comment]
Ping @alexellis close this #274
