### ISSUE TITLE
faas-cli remove doesn't allow overriding gateway specified in file

### ISSUE THREAD

**Issue by dvdmuckle** [openfaas/faas-cli#267]
## Expected Behaviour
Using `faas-cli remove` should behave the same way as `faas-cli deploy` such that `--gateway` will override any gateway entry in the `-f` file.

## Current Behaviour
Currently using `faas-cli -f somefile.yaml --gateway http://somegateway.local:8080` will ignore the `--gateway` and instead try to use the gateway specified in the file provided.

## Possible Solution
I'l look through the code and submit a PR request if I find the error, though it's worth mentioning the order of the flags doesn't seem to matter, the behavior is the same.

## Steps to Reproduce (for bugs)
See above.

## Context
Instead of using `-f` to specify functions to remove, I specify them by name. It's not that big of a deal, however `remove` should ideally mirror the function of `deploy`, except performing the opposite action.

## Your Environment
* Docker version `docker version` (e.g. Docker 17.0.05 ): 17.0.05-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Kubernetes, version 1.9.0

* Operating System and version (e.g. Linux, Windows, MacOS): HypriotOS v7 (Modified Raspbian Jessie)

**Comment by alexellis** [comment]
Hi thank you for raising this issue. Please see #268 from Stefan. Also would you like to join our Slack community? We'd like to have you join us there 👍 If so email alex@openfaas.com

**Comment by dvdmuckle** [comment]
Wow, that was a lot of activity overnight! Expect an email from me about the Slack community!

**Comment by alexellis** [comment]
No probs, glad to have you in the community 👍 please raise issues / generate discussion again.
