### ISSUE TITLE
Proposal: Support multiple template versions - i.e. Python 2 + 3 separately

### ISSUE THREAD

**Issue by rawkode** [openfaas/faas-cli#27]
I have started to work on providing a PHP template and I'd like to ensure support for PHP 5 and 7 (This proposal is also relevant for Python 2/3)

I'd like to propose that we add an additional parameter, either `version` or `language_version`

I considered having a template for each and avoiding additional changes, but as very little would be different across the templates, I think it's better to provide the additional parameter.

As the template library grows, the `version` parameter would also allow keen developers to benchmark / test / dabble with newer, but potentially breaking, versions of their run-time.

**Comment by alexellis** [comment]
Thanks for the suggestion. There should be a template available for new issues now.

> I considered having a template for each and avoiding additional changes, but as very little would be different across the templates, I think it's better to provide the additional parameter.

How would this work in either scenario? I think whether you have a different "language" field entry or use a pair of fields (language, version) - it will still need a second template. The template is the Dockerfile and entrypoint/loader class/module.

**Comment by johnmccabe** [comment]
Derek add label: enhancement

**Comment by alexellis** [comment]
Python 3 supported merged @rawkode

**Comment by alexellis** [comment]
This has been released.
