### ISSUE TITLE
Make "Dockerfile" a language template

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#271]
Make "Dockerfile" a language template

## Expected/Current Behaviour

The "Dockerfile" language template is currently kept partially in code. We should find a way to make it into an OpenFaaS template so that it can be versioned in the same way as the other templates.

I started the work in #221 but I need to focus on other areas right now.

I'd like help with this. 

Alex

**Comment by alexellis** [comment]
@itscaro @johnmccabe @nicholasjackson do any of you guys want to start off the New Year with a little OpenFaaS PR? :smile_cat:

**Comment by itscaro** [comment]
@alexellis I take this PR if no one took it already

**Comment by itscaro** [comment]
Derek assign: itscaro

**Comment by itscaro** [comment]
Derek assign: me

**Comment by dungeonmaster18** [comment]
Ping @alexellis close this
