### ISSUE TITLE
Question: Help needed deploying python-armhf template

### ISSUE THREAD

**Issue by bdparrish** [openfaas/faas-cli#273]
## Expected Behaviour

Expected behavior is that function deploys correctly to arm64 architecture and can invoke appropriately on OpenFaaS dashboard.

## Current Behaviour

Successfully built, pushed, and deployed a python-armhf function from `faas-cli` templates.

The pod status ends with "CrashLoopBackOff".

## Possible Solution

My best guess is that I am running a Raspberry Pi 3 running Raspbian Stretch and the Docker image does not support this.

## Steps to Reproduce (for bugs)

1. `faas-cli new --lang python-armhf hello-python`
2. `faas-cli build -f ./hello-python.yml`
3. `faas-cli push -f ./hello-python.yml` (<-- updated image name to be `bdparrish/hello-python` and published to hub.docker.com)
4. `faas-cli deploy -f ./hello-python.yml`

<img width="1160" alt="screen shot 2018-01-01 at 10 31 55 am" src="https://user-images.githubusercontent.com/720788/34468822-0b88edee-eedf-11e7-90b8-4b58908bcb1f.png">

<img width="1176" alt="screen shot 2018-01-01 at 10 32 33 am" src="https://user-images.githubusercontent.com/720788/34468824-1d0003d2-eedf-11e7-9eb7-322186725235.png">

## Context

I am trying to run the basic python-armvh template.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
  * Client:
    * Version: 17.12.0-ce
    * API version: 1.35
    * Go version: go1.9.2
    * Git commit: c97c6d6
    * OS/Arch: linux/arm

  * Server:
    * Engine:
      * Version: 17.12.0-ce
      * API version: 1.35 (minimum version 1.12)
      * Go version: go1.9.2
      * OS/Arch: linux/arm

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
K8s

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux - Raspbian Stretch (2017-11-29)

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Do you mean `arm64 architecture`? Raspberry Pi with Jessie Stretch is armv7. Can you run `uname -a`?

**Comment by alexellis** [comment]
Hey @bdparrish I tried this on my cluster with my own function and with yours and both worked without restarting the container. Please can you confirm the architecture of the machine where you're doing the build, the machines in the cluster and anything else you feel may be relevant?

@stefanprodan also agreed to give this a second look using ARMv7 hosts on Scaleway.

**Comment by stefanprodan** [comment]
The `bdparrish/hello-python` works fine on ARMv7, tested on Scaleway Kubernetes v1.9

<img width="328" alt="screen shot 2018-01-03 at 13 03 48" src="https://user-images.githubusercontent.com/3797675/34518125-a12db700-f086-11e7-910a-0825ec2d77a9.png">

**Comment by alexellis** [comment]
Pinging @bdparrish ... this issue is now a month old. I'm going to close it due to inactivity. If you are still interested we've given some commands on how to help us diagnose your issue. Feel free to keep commenting.

**Comment by bdparrish** [comment]
Alex,

Apologies, I have not been able to doing anything related to my project since I put his ticket in.  I’ll verify when able.
