### ISSUE TITLE
Add F# Template

### ISSUE THREAD

**Issue by jeremyabbott** [openfaas/faas-cli#276]
Give the FaaS CLI the ability to create an F# function using `faas-cli new <name> --lang fsharp`

## Expected Behaviour
When a user calls `faas-cli new callme --lang fsharp`:
1. A new F# function handler should be created within a directory named callme.
1. The callme directory should have an `.fsproj` file named `Function` and an `.fs` file named `Handler.fs`.

## Current Behaviour
Currently uses must supply an existing docker image for an F# function if they want to use open-faas.

## Possible Solution
I'm making a PR for this based on the existing C# template.

**Comment by alexellis** [comment]
@jeremyabbott thanks for your interest in OpenFaaS. 

As per [the contributing guide](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) you should wait for approval for the proposal before working on it.

Fortunately for your FSharp template we can accommodate this via the "template pull" mechanism. You'll need to:

* create your own Git repo
* use the structure defined in the templates.md file in this repo
* raise a PR to the README.md file in this repo to list your F# template

Users will first run `faas template pull https://github.com/jeremyabbott/fsharp-template` before then issuing a `faas new fsharp` command.

I'd suggest closing your PR and following the steps above, you'll also see a sample from @itscaro for PHP.

**Comment by jeremyabbott** [comment]
@alexellis thanks Alex! I'll do that.

**Comment by ericstoekl** [comment]
Derek close
