### ISSUE TITLE
Check for invalid URL in faas-cli login

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas-cli#279]
When using `faas-cli login` without the `http(s)://` portion of the URL, an unhandled exception occurs:

```
$ faas-cli login -u admin -p <pw> -g <endpoint-ip>:31112

WARNING! Using --password is insecure, consider using: cat ~/faas_pass.txt | faas-cli login -u user --password-stdin

Calling the OpenFaaS server to validate the credentials...

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x6d0cb2]
```

## Expected Behaviour

The error needs to be handled, in the same way that it is in the fix for the `deploy` and `delete` commands: 

https://github.com/openfaas/faas-cli/commit/fa9e08d4c545399c6d81f3827682f34c116d7af1#diff-32a00314934dd566c4dbf7a14c10ce85R77

## Current Behaviour

Segmentation fault occurs if invalid URL is supplied

## Possible Solution

Check the `err` variable that is returned by `NewRequest()`, currently `_` is used instead of `err`:

https://github.com/openfaas/faas-cli/blob/cadf7dea543d149b1932f9636dc24805de8643a9/commands/login.go#L110

## Steps to Reproduce (for bugs)

1. Run `faas-cli login -u <user> -p <pw> -g <ip>:<port>` without `http(s)://` in front of `<ip>
2.
3.
4.

## Context

Ran into this while trying to log in to GKE cluster

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
GKE (Kubernetes 1.7.11-gke.1)

* Operating System and version (e.g. Linux, Windows, MacOS):
coreos

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
@stefanprodan would you like to tackle this?

**Comment by stefanprodan** [comment]
Yes I'm on it
