### ISSUE TITLE
faas-cli remove will remove functions from stack.yml even if specific function is given

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas-cli#280]
If you run `faas-cli rm <function name>` while working in a directory that has a `stack.yml` file present, `faas-cli` will attempt to remove the functions from stack.yml even though a function was specified.

## Expected Behaviour

The specified function was removed

## Current Behaviour

The functions from `stack.yml` will be attempted to be removed.

## Possible Solution

Check for named function in CLI params before checking stack.yml

## Steps to Reproduce (for bugs)

1. Create `stack.yml` file in your directory with a function or two
2. Run `faas-cli rm <name a different function not in stack.yml>`
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker version 17.12.0-ce-rc1, build ee2f943

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 1604

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Good point @ericstoekl 

Please can you also look into the other commands and see how they act?

I tried build and `--filter=screenshotter` does filter correctly in your example of [fc-test](https://github.com/ericstoekl/fc-test)

**Comment by ericstoekl** [comment]
`faas-cli invoke` is fine, it will prefer the named function over the `stack.yml`

However, `faas-cli deploy` prefers the `stack.yml`:

```
$ faas-cli deploy --image=alexellis/faas-url-ping --name=url-ping
Deploying: screenshotter.
Function screenshotter already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://localhost:8080/function/screenshotter

Deploying: mma-stats.
Function mma-stats already exists, attempting rolling-update.
```

**Comment by alexellis** [comment]
@ericstoekl is anyone working on this?

**Comment by ericstoekl** [comment]
Not that I know of, I could take it though.

**Comment by ericstoekl** [comment]
Derek assign: me

**Comment by ericstoekl** [comment]
Derek add label: testing

**Comment by james-r-smith** [comment]
+1 on this bug. I was running through the Docker Swarm tutorial. I used `faas deploy` for the sample functions, then I deployed an additional function, let's call it `foo`. When trying to remove `foo` while in the `/faas` directory using the command `faas remove foo`, it removed the sample functions instead and left `foo`.
