### ISSUE TITLE
python3 and python-armhf function template build process needs improvement 

### ISSUE THREAD

**Issue by viveksyngh** [openfaas/faas-cli#284]
```faas-cli build ...``` for ```python3``` and ```python-armhf``` functions installs the requirements every time we run  ```faas-cli build ...```  command even if requirements are not changed. 

## Expected Behaviour

If requirements.txt in not updated then ```faas-cli build ...``` should not install the requirements.  

## Current Behaviour

if we change anything in the handler or update anything in function folder other than requirements.txt ```faas-cli build ...``` installs the requirements.

## Possible Solution

Changing the  ```Dockerfile``` for these templates will fix this.

## Steps to Reproduce (for bugs)

1. Create a new function with python3 template ```faas-cli new test1 --lang=python3```
2. Add some requirements in requirements.txt
3. Build the function ```faas-cli bulild -f test1.yml ```
4. Make some changes in ```handlers.py```
5. Build function once again ```faas-cli build -f test1.yml```

## Context

This can help in reducing the build time for functions which has dependencies that takes time in installation.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Thanks for attending to this @viveksyngh - I already fixed this up for the regular "python" template so it's good to have this level for all Python templates.

**Comment by alexellis** [comment]
Derek close
