### ISSUE TITLE
Colored texts in PowerShell native console

### ISSUE THREAD

**Issue by itscaro** [openfaas/faas-cli#289]
## Current Behaviour
In PowerShell native console, ANSI escape are used and the PowerShell does not understand. The printed logs are not much readable.

With WSL (Windows Subsystem for Linux), we can still use the CLI correctly, but it's preferable that we can use it with the same UX in the PowerShell native console.

PowerShell native
![PowerShell native](https://user-images.githubusercontent.com/266018/35217016-fe25c7d0-ff69-11e7-8d5d-a68d9b8265b2.png)

PowerShell in WSL - ubuntu
![PowerShell in WSL - ubuntu](https://user-images.githubusercontent.com/266018/35217031-09e07584-ff6a-11e7-9687-a69be15350c4.png)

## Possible Solution
Use docker/pkg/term

**Comment by itscaro** [comment]
Derek add label:enhancement
Derek add label:proposal

**Comment by itscaro** [comment]
Derek add label: proposal

**Comment by itscaro** [comment]
Derek remove label: enhancement Derek add label: proposal

**Comment by itscaro** [comment]
Derek remove label: enhancement proposal

**Comment by alexellis** [comment]
@johnmccabe I thought this worked in PowerShell? Looks a bit odd in the first screenshot

**Comment by johnmccabe** [comment]
Top is what you see in cmd.exe, it's not got the same level of support for escape code formatting as powershell.

You'd need to detect whether you were invoked withing a powershell or cmd session.

Not convinced cmd.exe is something to be encouraged?

**Comment by itscaro** [comment]
@johnmccabe it's not `cmd.exe`, it's the native powershell console `%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe`

I have PowerShellCore 6 too which is launched from its own exe `%HOMEPATH%\AppData\Local\Microsoft\powershell\pwsh.exe`

**Comment by johnmccabe** [comment]
Looks like the logo printed as part of the help output doesn't use the escape codes. I'd been looking at that. @itscaro is correct regarding powershell 5.1/6.0

**Comment by johnmccabe** [comment]
@alexellis this *had* been working tho.... #150

**Comment by itscaro** [comment]
using ansi.Printf() is a quick fix.

ansi.Printf() instead of fmt.Printf()

![image](https://user-images.githubusercontent.com/266018/35241120-c0c9d678-ffb5-11e7-8452-531e74af7639.png)

**Comment by itscaro** [comment]
I've remarked that log.Fatal() prints coloured texts correctly :-|
I don't see how :-?
