### ISSUE TITLE
Provide a command to self-update to latest version

### ISSUE THREAD

**Issue by itscaro** [openfaas/faas-cli#297]
It would be useful to have a sub-command like `version update --beta` to perform a self-update

## Expected Behaviour
`version update` updates to latest stable version - version without suffix `-beta`

`version update --beta` updates to latest version including version suffixed with `-beta`

Progress bar would be nice but not required

![image](https://user-images.githubusercontent.com/266018/35350715-134aa960-013f-11e8-8159-4cf2f7ed17fc.png)

![image](https://user-images.githubusercontent.com/266018/35350944-ba9558dc-013f-11e8-98b9-d723e5a737eb.png)

![image](https://user-images.githubusercontent.com/266018/35350850-737b87aa-013f-11e8-8241-c36039c71cd0.png)

Attempt to address this issue: https://github.com/openfaas/faas-cli/compare/master...itscaro:version-update-cmd

**Comment by alexellis** [comment]
Thanks for the idea Minh. Since we have a mixture of package manages including `brew` - this may sound like a good idea on paper but could cause problems. Let's keep it in the issue tracker for reference but I don't think we should work on this right now.

**Comment by dungeonmaster18** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
Derek add label: revisit

**Comment by alexellis** [comment]
I think having people update their CLIs would be useful but can we do it in another way like nagging them? What do you think @johnmccabe ? You are a packaging/config guy

**Comment by itscaro** [comment]
this feature would be great on linux, since users can run directly ./faas-cli version update (like other tools, helm, minishift, minikube), instead of getting to a documentation to file the `curl command` with the link :)

**Comment by alexellis** [comment]
How about we just add a help message instead?

```
$ faas-cli upgrade

For Linux type in :

 curl .....

For Mac and Homebrew:

  brew upgrade faas-cli

```

**Comment by dungeonmaster18** [comment]
I like @alexellis idea because any way we have brew formula.

**Comment by ericstoekl** [comment]
I agree that I like @alexellis suggestion of just outputting a help message. We all want to use a package manager eventually anyway.

**Comment by rgee0** [comment]
The API rate limit could be a factor here unless we shift the version lookup 'somewhere else'

**Comment by alexellis** [comment]
I'll close and mark for #revisit
