### ISSUE TITLE
[Fixed] Warnings are output when building csharp template

### ISSUE THREAD

**Issue by BurtonR** [openfaas/faas-cli#305]
## Expected Behaviour

No errors are present during build of C# function from template

## Current Behaviour

An error occurs during the `faas build` when using the `csharp` template

```
Program.cs(25,13): warning CS0436: The type 'FunctionHandler' in '/root/src/function/FunctionHandler.cs' conflicts with the imported type 'FunctionHandler' in 'Function, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in '/root/src/function/FunctionHandler.cs'. [/root/src/root.csproj]
```

## Possible Solution

Remove the extra `FunctionHandler.csproj` file

## Steps to Reproduce (for bugs)

1. `faas new tester --lang csharp`
2. `faas build -f tester.yml`
3. Observe the error text in the build output

## Context

Errors indicate things aren't working properly. If a new user saw this, or a sysadmin, they would think something is wrong with their code, but it is actually being caused by the template

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
17.12.0-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Both, but for this test in particular: Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 17.10

* Link to your project or a code example to reproduce issue:
Just the csharp template code

**Comment by alexellis** [comment]
Thank you for logging this Burton

**Comment by alexellis** [comment]
Fixed in openfaas/templates - @BurtonR please feel free to pull in those changes via a new PR.

**Comment by BurtonR** [comment]
@alexellis Created the new PR to update the cli to match the templates repo #311
