### ISSUE TITLE
Question on when templates folder is required

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas-cli#307]
## Expected Behaviour

When deploying, the `template/` directory should not be required.

## Current Behaviour

Currently, if you do not have the `template/` folder and you try to deploy a function that uses a non-`Dockerfile` language (e.g. `python`, `node`, etc), the `template.yml` file will still be looked up:

```
$ faas-cli deploy -f zsavi.yml 
Deploying: zmagick.
Stat ./template/python/template.yml: no such file or directory
```

## Possible Solution

I think we don't need to check at all if the language is a valid template when we are deploying.

## Steps to Reproduce (for bugs)

1. Create a function with a language template, build the image
2. Delete the `template/` folder
3. Attempt to deploy
4.

## Context

Issue raised through slack conversation

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
17.12.0-ce-rc1
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
ubuntu 1604
* Link to your project or a code example to reproduce issue:
```
$ cat zsavi.yml 
provider:
  name: faas
  gateway: http://localhost:8080
  network: "func_functions" 

functions:
  zmagick:
    lang: Dockerfile
    handler: ./zmagick/function
    image: beco1/zmagick:latest
    fprocess: "python subp.py"
    limits:
      memory: 20m
    requests:
      memory: 20m
```

**Comment by viveksyngh** [comment]
@alexellis  @ericstoekl  I would like to work on this one if nobody is working.

**Comment by alexellis** [comment]
Please hold off on changing this.

From Slack:

> The templates need to be available when doing a new, build or deploy:

* New - for a list of templates
* Build - to make use of the template's files and to know if the template is valid - this includes the Dockerfile type which also uses a template.
* Deploy - at deployment time we pull the fprocess value out of the templates to set the correct function entry-point for the language.

**Comment by ericstoekl** [comment]
Good call Alex. I also figured that if the image is already built + deployed, then the deploy operation should not need templates. However you make the good point that the `fprocess` still needs to be set, and that comes from the `template.yml` file.

In that case, maybe we could change this task to require that templates are *pulled* if the `template.yml` file is not found. Just giving the error message "Unable to stat template.yml" is not very instructive for how users can fix this issue. I think we should automatically run `template pull` when `deploy` is called but the template/ folder is not present, or prompt the user to run `template pull`.

**Comment by ericstoekl** [comment]
Derek add label: PR
