### ISSUE TITLE
Refactoring: store commands should be in their own .go files

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#310]
## Expected Behaviour

store commands should be in separate files like we have for `template pull`

## Current Behaviour

They're intermingled in the same file.

## Possible Solution

Please split out so we retain the coding style.

I'd suggest that @itscaro may want to work on this?

<img width="549" alt="screen shot 2018-01-31 at 21 19 54" src="https://user-images.githubusercontent.com/6358735/35648119-8bbddf38-06cc-11e8-901e-ce7c5f61674d.png">

**Comment by itscaro** [comment]
@alexellis I'll take it

**Comment by alexellis** [comment]
Thank you @itscaro - this should be easy to merge quickly as it's just moving things around.
