### ISSUE TITLE
Cannot deploy "YouTube Video Downloader" via CLI

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#312]
## Expected Behaviour

```
$ faas-cli store deploy "YouTube Video Downloader"
```

This should deploy the function just like it does with ones like figlet.

## Current Behaviour

```
$ faas-cli store deploy "YouTube Video Downloader"
Error parsing envvars: label format is not correct, needs key=value
```

## Possible Solution

I imagine there is a bug in the parsing logic for environmental variables cc @amirkarimi @itscaro @viveksyngh if any of you chaps fancy taking this on please do.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

N/a

**Comment by amirkarimi** [comment]
I'll take care of this

**Comment by amirkarimi** [comment]
Ah didn't see @itscaro PR

**Comment by alexellis** [comment]
Please review and test the PR @amirkarimi
