### ISSUE TITLE
Push image - Error message incomplete

### ISSUE THREAD

**Issue by fpommerening** [openfaas/faas-cli#323]
If you use the push-command and an error occur the message is incomplete.

## Expected Behaviour
The push-command should show the same error message like the docker cli.

> docker push fpommerening/openfaas-dotnet:alexa
The push refers to repository [docker.io/fpommerening/openfaas-dotnet]
9cc81488ac50: Layer already exists
....
e27a10675c56: Layer already exists
errors:
denied: requested access to the resource is denied
unauthorized: authentication required

## Current Behaviour
The hint how to fix the error ("unauthorized: authentication required") is missing.

> c:\OpenFaaS\faas-cli.exe push -f Alexa.yml
[0] > Pushing Alexa.
The push refers to repository [docker.io/fpommerening/openfaas-dotnet]
9cc81488ac50: Preparing
...
e27a10675c56: Waiting
denied: requested access to the resource is denied
2018/02/11 19:15:33 ERROR - Could not execute command: [docker push fpommerening/openfaas-dotnet:alexa]

## Steps to Reproduce (for bugs)
1) use a clean docker system or logout with the command "docker logout"
2) use the command:  faas-cli.exe push -f yourFunc.yml

## Context
The reason for my error was that I forget to use docker login. 
After authentication, the command was executed correctly.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker 17.12.0-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Windows 10

**Comment by itscaro** [comment]
Docker prints out only `denied: requested access to the resource is denied`, we just passthroughs Docker logs.

**Comment by itscaro** [comment]
Derek add label: question

**Comment by viveksyngh** [comment]
Also, there is already a thread for implementing this in docker. Hope this will help.

https://github.com/moby/moby/issues/15466

**Comment by ericstoekl** [comment]
Derek close: As explained by @viveksyngh and @itscaro, we pass the error message thru.
