### ISSUE TITLE
400 Error faas-cli deploy

### ISSUE THREAD

**Issue by CentricStraaten** [openfaas/faas-cli#327]
When i try to deploy my function with 

` faas-cli deploy --image=bengkel/cencept_demo --name=cencept_demo --handler=/function/ --gateway=http://cen-openfaas.westeurope.cloudapp.azure.com:8080 --lang=csharp`

I receive an error

`Unexpected status: 400, message: (cencept_demo) must be a valid DNS entry for service name`

What am i doing wrong?

**Comment by alexellis** [comment]
Hi @CentricStraaten,

If you'd like us to provide support and help then you need to fill out the whole issue template (it's not a nice-to-have) it gives us key information.

The error is telling you what is wrong. The name `cencept_demo` is not a valid DNS entry. You should use `cencept-demo` instead.

> Valid DNS entries consist of [a-z][0-9] and [-] (hyphen) but not underscore.

Btw I'd suggest you use a YAML file to define and deploy your function. How did you end up with all these CLI arguments?

**Comment by alexellis** [comment]
Derek close: resolved. Feel free to keep commenting.
