### ISSUE TITLE
faas-cli push should not work without a user or registry prefix [help wanted]

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#329]
Some new users are trying to run `faas-cli push` without reading or understanding the instructions on adding their own user account as a prefix to the image name.

## Expected Behaviour

```
$ faas push --image function1
or
$ faas push -f ./file.yml

Unable to push image "function1" without a username prefix such as user1/function.
If you need a Docker Hub account you can sign up here: https://hub.docker.com
```

## Current Behaviour

```
Pushing to docker.io/library/function1:latest

Access denied...
```

## Possible Solution

Pre-validate any CLI or YAML file and prevent going any further unless all of the images defined have a valid prefix. Also take note of the `skip_build` flag which means an image will not be built.

Test scenarios:

* no prefix i.e. `function1:latest` (fail)
* prefix given i.e. `alexellis2/function1` (pass)
* private server given but no user prefix i.e. `127.0.0.1:5000/function1` (pass)
* private server given and a prefix i.e. `127.0.0.1:5000/myfunctions/function1` (pass)

Test all of above with CLI arguments and a YAML file.

## Steps to Reproduce (for bugs)

1. `faas new --lang go test1`
2. `faas push -f test1.yml`

**Comment by BurtonR** [comment]
I'll work on this

**Comment by alexellis** [comment]
Having reviewed the PR #330 I want to make an update to the message where several functions fail to pass the validation:

```
$ faas-cli push
We were unable to push one or more of your functions to the Docker Hub.
- movie-lister
- ec2-autoscaler
- faas-cli

You must provide a username or registry prefix to the Function's image such as user1/function1.
If you need a Docker Hub account, you can sign up here: https://hub.docker.com
```

Please see the note on `skip_build` too.

**Comment by Collinshbk** [comment]
I just had the same problem.  “You must provide a username or registry prefix to the Function’s image such as user1/function1”

**Comment by alexellis** [comment]
I've commented here: https://github.com/openfaas/faas-cli/pull/330#issuecomment-1464876050
