### ISSUE TITLE
Docker Swarm issue - Address in use (upstream issue)

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#33]
When re-deploying a function (aka Docker Swarm Service) we can get an error "Address in use - unable to allocate container" or similar.

I've raised the issue upstream but it's been open 30 days already. I don't believe the issue occurs when using Kubernetes as a back-end. 

https://github.com/moby/moby/issues/34163

The Docker swarm work-around appears to be to deploy again after a few seconds or to use `docker service rm` via the Docker CLI first.

I think this might also be fixed with a restart policy of > 1.

https://github.com/alexellis/faas/blob/master/gateway/handlers/functionshandler.go#L189

**Comment by rorpage** [comment]
The same is happening for me as well. My workaround is to simply re-issue the deploy command:
`faas-cli -action deploy -f ./stack.yml` and then my function starts.

**Comment by alexellis** [comment]
I'll update the Python blog post with a few notes on troubleshooting & logs. https://blog.alexellis.io/first-faas-python-function/

**Comment by alexellis** [comment]
The following work-around fixes the observed behaviour - https://github.com/alexellis/faas/pull/128

Ideally this will be fixed upstream too.

**Comment by alexellis** [comment]
Closing since we have a work-around built-in.
