### ISSUE TITLE
Feature: implement --header -H flag for faas-cli invoke

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#333]
Feature: implement `--header` with `-H` short-flag for `faas-cli invoke`

We have this for the querystring value via `--query`, but need to defer to `curl` right now for setting custom headers. This change would be used in an upcoming [OpenFaaS workshop](https://github.com/alexellis/openfaas-workshop).

I'm happy to help / mentor someone in making this change.

## Expected Behaviour

`faas-cli invoke --header X-Ping-Url=http://request.bin/etc`

`faas-cli invoke --header X-Config-2=on --header X-Config-2=off`

`faas-cli invoke -H X-Ping-Url=http://request.bin/etc`

The header must validate as a key/value pair - `key=value`, or give an error.

## Current Behaviour

Need to use `curl` for this.

## Possible Solution

Add the flag to the invoke code in Cobra. I suggest we copy the style / approach used for `--query`.

**Comment by rgee0** [comment]
Note the typo in expected behaviour.

`faas-cli invoke --H X-Ping-Url=http://request.bin/etc`
should read
`faas-cli invoke -H X-Ping-Url=http://request.bin/etc`

Single dash for the short flag as standard

**Comment by viveksyngh** [comment]
I would like to work on this.

**Comment by alexellis** [comment]
Edited .. @rgee0 thanks for pointing that out. Vivek if you have time I'm fine with that.

**Comment by viveksyngh** [comment]
@alexellis Yes, I have time. I might need some help.

**Comment by alexellis** [comment]
Sure, let's collaborate on here + Slack. Have a read over the code and review how `--query` is implemented. @itscaro and @ericstoekl have done lots here too so feel free to reach out to us all.
