### ISSUE TITLE
Help wanted: --async flag for invoking functions

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#337]
## Expected Behaviour

`echo test | faas invoke --async func_echoit`

With short-flag

`echo test | faas invoke -a func_echoit`

The difference in the underlying code is that instead of calling `/function`/ on the gateway, this code should call `/async-function`. That's it.

## Current Behaviour

We use `curl` instead so that we can specify a different route.

## Code references

Command in Cobra format:

https://github.com/openfaas/faas-cli/blob/master/commands/invoke.go#L22

Proxy code that calls remote gateway:

https://github.com/openfaas/faas-cli/blob/master/proxy/invoke.go#L37

**Comment by johnmccabe** [comment]
Derek assign: johnmccabe

**Comment by johnmccabe** [comment]
I'll grab this one and do it over lunch

**Comment by alexellis** [comment]
SGTM 🥇

**Comment by alexellis** [comment]
Derek close: released
