### ISSUE TITLE
Proposal : add --method or -m flag for faas-cli `invoke`

### ISSUE THREAD

**Issue by viveksyngh** [openfaas/faas-cli#342]
With HTTP mode functions can support HTTP methods like `GET`, `POST`. To pass which method to use by `invoke` command add `--method`  or `-m` flag. By default, if no flag is passed it should invoke the function with `POST` method.

## Expected Behaviour

`faas-cli invoke --method GET `
`faas-cli invoke -m POST`

## Current Behaviour

No option to pass the method

## Possible Solution

Add --method flag to invoke command

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by viveksyngh** [comment]
Derek add label: skill/beginner

**Comment by alexellis** [comment]
This would also need a short flag ‘-m’?

**Comment by viveksyngh** [comment]
Yes, I have added that.

**Comment by rgee0** [comment]
Derek close: merged in #349
