### ISSUE TITLE
Consider use of environmental variable for gateway override

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#345]
## Description

Consider use of environmental variable for gateway URL override.

On Kubernetes everyone has to provide an override all the time - whether `-g` 127.0.0.1:31112` or `-g `minikube ip`` or similar.

## Pros

* Could allow an override of the default address of `localhost:8080`
* Less typing when the gateway is not localhost:8080 and user doesn't want to update a YAML file

## Cons/Concerns

* hard to maintain a flag that has three sources - YAML, argument and ENV
* code change could cause regression for existing users so would need extensive testing
* work-arounds already exist - changing the YAML file or passing `-g`/`--gateway`
* affects several commands: `deploy` / `list` / `invoke` etc etc

**Comment by alexellis** [comment]
As I recall I think @nicholasjackson also wanted this

**Comment by johnmccabe** [comment]
You should look at [spf13/viper](https://github.com/spf13/viper) for this.

**Comment by milsonian** [comment]
👍 https://github.com/spf13/cobra#bind-flags-with-config

**Comment by alexellis** [comment]
@milsonian it would be great to get some context with your link and a short explanation of how it can be used to help with this problem.

> In this example the persistent flag author is bound with viper. Note, that the variable author will not be set to the value from config, when the --author flag is not provided by user.

I took a look at the link and this sentence doesn't mention config/args and env vars. It's worth noting that we have our own configuration file / format already for storing basic auth and for the YAML stack files.

**Comment by milsonian** [comment]
I was just stashing the link for later.  I'm not super familiar with viper but after some poking at it, that's correct this doesn't provide for any envvar on its own.  It could imply switching to/adding viper for some of this stuff which would obviously be a bigger refactor (though perhaps would make this easier to manage longer term)..I'm going to ping some folks who know viper better for their thoughts.

**Comment by johnmccabe** [comment]
FYI this is a 5 line change to introduce, can raise a PR for it later if you wish @alexellis

**Comment by alexellis** [comment]
I'm not sure whether viper is going to be the right thing to do:

* resulting binary size
* additional value offered isn't obvious

John the change will have to cover all the verbs and be thoroughly tested.

Before raising the PR we need to discuss expectations about the preferential order of flag/env/yaml (config).

Does it make sense to make use of the config file and have a context like Kubernetes' CLI (`kubectl`)? We already store an entry for login details.

**Comment by johnmccabe** [comment]
roughly 1.6MB overhead with all the additional functionality you get, agree if `os.Getenv` is all thats wanted here better to roll your own.
