### ISSUE TITLE
Change `defaultNetwork` so that `func_functions` is no longer used when a value isn't provided

### ISSUE THREAD

**Issue by rgee0** [openfaas/faas-cli#352]
## Expected Behaviour
With the changes in https://github.com/openfaas/faas-swarm/commit/e36f90b36f5b81498ea7dc018b3cf0b48127f7a1 a default network is no longer required.  Instead the network to be used will default to the swarm network labelled with `openfaas` during deployment.

## Current Behaviour
if a value for the network isn't provided then the CLI defaults to sending `func_functions` which can be undesirable.

## Possible Solution
The shortest path would be to set `defaultNetwork` to ""

## Steps to Reproduce (for bugs)
Not a bug

## Context
This is a mop up following backend changes

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
Client:
 Version:	18.01.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	03596f5
 Built:	Wed Jan 10 20:16:34 2018
 OS/Arch:	linux/arm
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.01.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	03596f5
  Built:	Wed Jan 10 20:12:44 2018
  OS/Arch:	linux/arm
  Experimental:	false
```
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
Raspbian
* Link to your project or a code example to reproduce issue:
N/A

**Comment by alexellis** [comment]
@rgee0 are you going to raise a PR for this or should someone else work on it?

**Comment by rgee0** [comment]
I’m doing it. Started with the store but at the time I couldn’t get the latest cli from GitHub to test.

**Comment by alexellis** [comment]
Please raise a PR here too when ready. https://github.com/openfaas/store/issues/27

GH release should be available for downloads - I think AWS S3 was having a hiccup.

**Comment by iyovcheva** [comment]
Derek add label: proposal
