### ISSUE TITLE
Runtime Error in Function - Fatal error: epollwait failed

### ISSUE THREAD

**Issue by tarunmangukiya** [openfaas/faas-cli#356]
## Context

I am doing image resizing with Node Sharp. Functions are failing with an error: `runtime: epollwait on fd 4 failed with 14`. Containers gets restarted.

Googled some references and feels like it's Go Language issue. Can anyone help to debug and resolve the same?

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Version 17.12.0-ce-win47 (15139)
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
Windows

**Comment by iyovcheva** [comment]
Hi @tarunmangukiya , can you please share steps to reproduce?

**Comment by iyovcheva** [comment]
Derek add label: support

**Comment by alexellis** [comment]
@tarunmangukiya You need to provide more context if you want us to help support your usage of OpenFaaS. I don't know what "Node Sharp" is?

Please share a GitHub repo with us which we can use to build/test your application.

**Comment by alexellis** [comment]
Derek close

**Comment by alexellis** [comment]
Closing this issue as inactive, we've also had no instructions on reproducing the error and couldn't reproduce it locally. Feel free to keep commenting.
