### ISSUE TITLE
faas-cli remove command doesn't honor OPENFAAS_URL

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas-cli#366]
There seems to be some inconsistencies with the `faas-cli remove` command. It tries to access `127.0.0.1:8080` even though I have the `OPENFAAS_URL` set.

## Expected Behaviour

The function is removed.

## Current Behaviour

```
ubuntu@ip-172-31-0-118:~/faas-cli/sample$ echo $OPENFAAS_URL
http://localhost:31112
ubuntu@ip-172-31-0-118:~/faas-cli/sample$ faas-cli remove n1
Deleting: n1.
Error removing existing function: Delete http://127.0.0.1:8080/system/functions: dial tcp 127.0.0.1:8080: getsockopt: connection refused, gateway=http://127.0.0.1:8080, functionName=n1
```

If I run the command `faas-cli remove n1 -g http://localhost:31112` (my correct url endpoint), the remove command works. However, if I run the command with the same url without the `http://` part, it will fail with this error message:

```
$ faas-cli rm n1 -g localhost:31112
Deleting: n1.
Error removing existing function: Delete localhost:31112/system/functions: unsupported protocol scheme "localhost", gateway=localhost:31112, functionName=n1
```

## Possible Solution

Look at the `faas-cli remove` code, find out where it is getting its gateway URL from, and make sure the URL is correct according to the `OPENFAAS_URL` env variable.

## Steps to Reproduce (for bugs)

1. `curl -sSL cli.openfaas.com | sudo sh`
2. Deploy a function, set `OPENFAAS_URL` to your gateway endpoint
3. `faas-cli rm <function name>`
4.

## Your Environment
* `faas-cli` version:
```
Commit: ae7390005a2fe13873f2cb6fcfa2d830dad4a40b
Version: 0.6.5
```

* Docker version `docker version` (e.g. Docker 17.0.05 ):
1.13.1

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes 1.10

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 1604

* Link to your project or a code example to reproduce issue:

**Comment by ericstoekl** [comment]
Derek add label: skill/beginner

**Comment by rgee0** [comment]
@ericstoekl can you provide the output of 'faas-cli version', please?

@alexellis can we get the issue template on this repo updated to request the output of 'faas-cli version', please?

**Comment by alexellis** [comment]
@rgee0 yes please raise a PR.

**Comment by viveksyngh** [comment]
@alexellis I will have look at this one.

**Comment by ericstoekl** [comment]
Updated with faas-cli version.

**Comment by ericstoekl** [comment]
Derek assign: viveksyngh
