### ISSUE TITLE
build error while image name is uppercase

### ISSUE THREAD

**Issue by s8sg** [openfaas/faas-cli#374]
`faas-cli build` command failed when image name has a uppercase tag as
For example: 
`faas-cli build `
the internal `docker build -t <image_name> .` fails

## Expected Behaviour
```bash
$ faas-cli new myFunc --lang go
$ faas-cli build --yaml myFunc.yml
```
A image should be created have a image name as of my function name if not specified

## Current Behaviour
The `faas-cli build` command fails with below error: 
```bash
invalid argument "myFunc" for "-t, --tag" flag: invalid reference format: repository name must be lowercase
See 'docker build --help'.
2018/04/10 13:08:17 ERROR - Could not execute command: [docker build -t myFunc .]
```

## Possible Solution
This bug is introduced as docker build doesn't allow repository name to have uppercase
```bash
invalid argument "myFunc" for "-t, --tag" flag: invalid reference format: repository name must be lowercase
```
The bug can be omitted by always converting image name to lowercase before using any docker command locally or requesting to the gateway, even if they are in uppercase in `stack.yml` or in `--build` flag.

Otherwise lower case image name can be enforced by checking if `image` values and return error in case it is `Uppercase`

## Steps to Reproduce (for bugs)
```bash
// STEP 1
$ faas-cli new myFunc --lang go
// STEP 2
$ faas-cli build --yaml myFunc.yml
```

## Context
This issue currently forces the user to use lower case Image Name 
and when generated a new function provide the Image Name seperately

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ):
```bash
Commit: ae7390005a2fe13873f2cb6fcfa2d830dad4a40b
Version: 0.6.5
```

* Docker version ( Full output from: `docker version` ):
```bash
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:10:09 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:08:36 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
FaaS-swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

* Link to your project or a code example to reproduce issue:

**Comment by ericstoekl** [comment]
I believe that the current error message is sufficient. `repository name must be lowercase` should describe the issue clearly to most users.

Maybe we could bubble up the error and make it nicer than `Could not execute command: [docker build -t myFunc .]`. I don't think running `toLower()` on the image name should be done here.

**Comment by s8sg** [comment]
Agreed. Although for a new function we can't mandate user to provide **lower case func name**, as we generated by the platform we can change the image name to lowercase.  i.e. for a new function named `myAwsomeFunc` the image name would be `myawsomefunc`. The current PR includes only this change

**Comment by BurtonR** [comment]
I'd have to argue against doing a "magic update" to the users' input. Having the function name match the image name is expected. 

As an example: If someone is using a script that looks at the deployed functions, then parsing the images available, they wouldn't find "MyAwesomeFunc" due to the case differences. (probably a bad example, but it's the first thing that came to mind :) )

I'd vote for a warning message instead that would let the user know the acceptable characters for function names, i.e. can't start with a number, only lower-case, no special characters, etc... That way it's not surprising that the image doesn't match the function.

**Comment by alexellis** [comment]
So the concern is valid but it sounds like we don’t want to edit the string to prevent side effects. I wonder if we should  prevalidate the value passed to the new command rather than do a conversion?
