### ISSUE TITLE
Quick-install script can cause hitting of rate limiter from GitHub

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas-cli#377]
During the workshop people starting hitting an issue where the `cli.openfaas.com` quick-install script was failing. The exact issue is that the file that was downloaded contained only the text `Not Found` -- the cause of this was that the first command of the script which runs:

`version=$(curl -s https://api.github.com/repos/openfaas/faas-cli/releases/latest | grep 'tag_name' | cut -d\" -f4)`

was failing to get the version number (an empty `$version` variable was the result). The reason from this was found by calling that URL directly, which resulted in this error message:

```
"message": "API rate limit exceeded for x.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
```

We need to set up an alternate service that hosts these binaries (like an S3 bucket).

## Expected Behaviour

The faas-cli installs.

## Current Behaviour

The installed "binary" only contains the text "Not Found".

## Possible Solution

Increase or remove the rate limit, or provide an alternative location to download from.

## Steps to Reproduce (for bugs)

1. Try to run the quick-install script when lots of others on the same IP are also running the install script.
2.
3.
4.

## Context

Found while running the DevNet workshop

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by rgee0** [comment]
Since the API call is only looking for the latest release, rather than the moving the binaries would an alternative approach be to trigger a webhook on release and store the release value 'somewhere else'?  The value can then be read from 'somewhere else' and the binaries still retrieved from GH.

**Comment by ericstoekl** [comment]
@rgee0 That would be great especially if we have a standard storage bucket that contains the current version.

**Comment by alexellis** [comment]
Caching sounds like a useful solution for rate limited scenarios. What are the thoughts on the PR that aims to improve the error experience?

**Comment by rgee0** [comment]
@ericstoekl has addressed my comment on the PR.

**Comment by alexellis** [comment]
This will be closed when updated on the server

**Comment by alexellis** [comment]
@ericstoekl this has been deployed on the server cli.openfaas.com now

Can you try to repo the error and see that you get the expected instructions?

**Comment by ericstoekl** [comment]
This works but the only trick is that you NEED to execute the script with `bash` -- `sh` will cause it to download a corrupted version of `faas-cli` when the rate limit is exceeded.

```
$ curl -sSL cli.openfaas.com | sh
sh: 2: [[: not found

You already have the faas-cli!
Overwriting in 1 seconds.. Press Control+C to cancel.

x86_64
Downloading package https://github.com/openfaas/faas-cli/releases/download//faas-cli as /home/s/github/go/src/github.com/openfaas/faas-cli/faas-cli
```

**Comment by rgee0** [comment]
I'm not sure how it would do that.  If the rate limit is exceeded then it wont get a version and therefore shouldn't download anything.

Looks icky on the double square brackets - the rest of the script uses single.

**Comment by ericstoekl** [comment]
New PR has been submitted to address this issue. Thanks for your input @alexellis and @rgee0

**Comment by alexellis** [comment]
That’s a breaking change. Was this work tested?
