### ISSUE TITLE
Revise error message for faas-cli deploy

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas-cli#379]
To deploy a new stack from a YAML file, use the command:

```
faas-cli deploy -f <stack.yml>
```

If the user makes a mistake and instead issues:

```
faas-cli deploy <stack.yml>
```

The error message that is thrown can be confusing:

```
Please provide a --image to be deployed
```

## Expected Behaviour

An error message such as:

```
Unable to deploy function. If using a YAML file for deployment, use:

faas-cli deploy -f <file.yml>

Otherwise, you need to specify:

faas-cli deploy --name <name> --image <image>
```

## Current Behaviour

Prints `Please provide a --image to be deployed`

## Possible Solution

Add extra checks in code and provide a better error message.

## Steps to Reproduce (for bugs)

1. `faas-cli deploy stack.yml`
2.
3.
4.

## Context

Someone at the workshop ran into this error message and got confused.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.6.5
* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
Mac
* Link to your project or a code example to reproduce issue:

**Comment by rgee0** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
We can probably make this more concise and still resolve the problem:

```
To deploy a function give --yaml/-f or a --image flag.
```

**Comment by alexellis** [comment]
Closing - fix merged.
