### ISSUE TITLE
"Unexpected status: 500, Unauthorized"  error on faas-cli deploy/list

### ISSUE THREAD

**Issue by dineshsriram** [openfaas/faas-cli#382]
I'm trying to deploy my first (lang: Dockerfile) function on an in-house k8s cluster.

I was able to build and push the Docker image to my internal registry using the `faas-cli` fine. However when I try to list/deploy, I get an Unauthorized 500 status code error which I'm not sure why.

## Expected Behaviour
faas-cli deployment to succeed.

## Current Behaviour
```
$ faas-cli deploy -f ./helloworld.yml
Deploying: hello-world.
Unexpected status: 500, message: Unauthorized
```
```
$ faas-cli list -g <ip>:31112
Server returned unexpected status code: 500 - Error pulling metrics from provider/backend. Status code: 500
```

## Possible Solution
More detailed error message with stack trace could help. 

## Steps to Reproduce (for bugs)
```
$ faas-cli build -f ./helloworld.yml
$ faas-cli push -f ./helloworld.yml
$ faas-cli list -g <ip>:31112
```

## Context
Following instructions [here](https://blog.alexellis.io/quickstart-openfaas-cli/), I downloaded the `faas-cli` and tried to deploy a simple hello world application onto k8s. The deployment, however, seems to fail with status code 500. 

This application has no business logic and basically just writes "Ok" to stdout.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.6.5

* Docker version ( Full output from: `docker version` ): 18.03.0-ce

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)? FaaS-netes

* Operating System and version (e.g. Linux, Windows, MacOS): MacOS 10.13.3

* Link to your project or a code example to reproduce issue:

**Comment by BurtonR** [comment]
Hi @dineshsriram! Sorry to hear you're having some troubles.

That blog post is a little outdated already (it's a fast moving project!) We have RBAC enabled by default on `faas-netes`. That could be the source of your troubles. Are you able to view the UI?

What versions of the OpenFaaS services are you running? Gateway, faas-netes?

Have you had a look at the [Kubernetes guide](http://docs.openfaas.com/deployment/kubernetes/), or the [Troubleshooting guide](http://docs.openfaas.com/deployment/troubleshooting/) yet?

**Comment by dineshsriram** [comment]
Thanks for the response @BurtonR. I ended up re-deploying `faas-netes` artifacts onto the k8s cluster again and that seemed to have fixed the problem. Most likely my missed/erred on an instalation step.

**Comment by BurtonR** [comment]
Glad you got it sorted!
