### ISSUE TITLE
Create a Docker image openfaas/faas-cli for use in CI and jobs

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#384]
We should release a tagged Docker image after every GitHub release / tag.

Please see the pattern for the API gateway in the faas repo or faas-netes repo.

Help wanted - you should change the .travis.yml file in this repository.

**Comment by alexellis** [comment]
https://github.com/openfaas/faas/blob/master/.travis.yml

**Comment by iyovcheva** [comment]
Derek assign: iyovcheva

**Comment by iyovcheva** [comment]
@alexellis May be you mean a `faas-cli` only as an image name - https://github.com/openfaas/faas-cli/blob/86370e8042b20d22bb55ffe92e9c001af35a0a1d/build.sh#L3 ?
I think there is not existing `openfaas` docker namespace.

**Comment by alexellis** [comment]
> I think there is not existing openfaas docker namespace.

I have some images on there already.

The primary change here is to push the image to make it available for other people to pull in and use in their automation of functions.

Also just check that the final image stage is a minimal image and not a full Golang SDK which would be a huge Docker image.

**Comment by alexellis** [comment]
Ping @iyovcheva

**Comment by iyovcheva** [comment]
Derek close
