### ISSUE TITLE
Regression in 0.6.6 - panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#386]
## Expected Behaviour

Deployment as per usual

## Current Behaviour

I'm trying to deploy an image to my local machine but got this error:

```
mini:sample-functions alex$ faas deploy -f dockerhub-stats.yml
Deploying: dockerhub-stats.
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/openfaas/faas-cli/commands.getRegistryAuth(0xc4200ec680, 0xc420013010, 0xf, 0x1, 0x1)
        /go/src/github.com/openfaas/faas-cli/commands/deploy.go:438 +0x1df
github.com/openfaas/faas-cli/commands.runDeployCommand(0xc4200ec640, 0x0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x162ada0, ...)
        /go/src/github.com/openfaas/faas-cli/commands/deploy.go:168 +0x45c
github.com/openfaas/faas-cli/commands.runDeploy(0x1605a20, 0xc4200ec640, 0x0, 0x2, 0x0, 0x0)
        /go/src/github.com/openfaas/faas-cli/commands/deploy.go:110 +0xcd
github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra.(*Command).execute(0x1605a20, 0xc4200ec600, 0x2, 0x2, 0x1605a20, 0xc4200ec600)
        /go/src/github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra/command.go:698 +0x47a
github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x16053c0, 0xc42007bc70, 0x0, 0x0)
        /go/src/github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra.(*Command).Execute(0x16053c0, 0x0, 0x0)
        /go/src/github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/openfaas/faas-cli/commands.Execute(0xc42000e780, 0x4, 0x4)
        /go/src/github.com/openfaas/faas-cli/commands/faas.go:71 +0xb6
main.main()
        /go/src/github.com/openfaas/faas-cli/app.go:19 +0x7d
```

## Possible Solution

@BurtonR @nenadilic84 to investigate how this issue could have occurred on Docker for Mac since it is the primary platform for our users.

## Steps to Reproduce (for bugs)

1. Create function with Go template
2. Build
3. Deploy

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

0.6.6

* Docker version ( Full output from: `docker version` ):

```
Client:
 Version:       18.04.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    3d479c0
 Built: Tue Apr 10 18:13:16 2018
 OS/Arch:       darwin/amd64
 Experimental:  true
 Orchestrator:  swarm
```

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):

MacOS Sierra

**Comment by BurtonR** [comment]
@alexellis  You're right. After checking out commit `86a6c25b21240a222d647884db0f4cd65ab5258c` which is what `0.6.6` was tagged, I created a new `go` function and got a panic when trying to deploy. 
This was an oversight in the work that was done for the authentication. We didn't verify that it would still work with a basic local function.
I did checkout commit `4e72ea6ef77a3375904a8b84e257efc1663607bc` and verified that the same function that had a panic before is now successfully deployed and invokable. :+1:
