### ISSUE TITLE
0.6.6 spams two messages about HTTPS when deploying

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#387]
## Expected Behaviour

A single warning about HTTPS not being used on a remote gateway - or actually nothing for loopback addresses of `127.0.0.1` and `localhost` cc @stefanprodan 

## Current Behaviour

Since the change via @BurtonR @nenadilic84 to make registry auth strings get passed on every deployment.

```
go build && ./faas-cli deploy -f ~/go/src/github.com/open
faas/faas/sample-functions/dockerhub-stats.yml
Deploying: dockerhub-stats.
WARNING! Communication is not secure, please consider using HTTPS. Letsencryp
t.org offers free SSL/TLS certificates.
WARNING! Communication is not secure, please consider using HTTPS. Letsencryp
t.org offers free SSL/TLS certificates.

Deployed. 200 OK.URL: http://127.0.0.1:8080/function/dockerhub-stats
```

## Possible Solution

We need to only print the message once - not twice. It could be since it was a rolling deployment?

Registry Auth behavior is giving a bit more of an obtrusive experience. If the majority of users will be on Kubernetes then should we even send the registry auth string on every deployment?

## Steps to Reproduce (for bugs)

See #386 

## Your Environment

Provided in #386

**Comment by alexellis** [comment]
I think the feature that populates private registry configs for Swarm should be made an opt-in configuration via environmental variable.

**Comment by stefanprodan** [comment]
I think on Kubernetes we should not send the registry auth at all as it exposes this sensitive information with no benefit for the user. On Kubernetes you have to use the secrets field inside the stack file to specify the registry auth.

**Comment by alexellis** [comment]
Introduce an environmental variable to opt-in to this feature if wanted?

`OPENFAAS_SEND_REGISTRY_CREDS=1` or similar?

**Comment by alexellis** [comment]
cc @BurtonR

**Comment by BurtonR** [comment]
Trying to repro this locally (from the master branch) I get the double warning only the first time I deploy a function...
```
$ ./faas-cli deploy -f warning.yml
Deploying: warning.
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Deployed. 200 OK.
URL: http://127.0.0.1:8080/function/warning


$ ./faas-cli deploy -f warning.yml
Deploying: warning.
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
Function warning already exists, attempting rolling-update.

Deployed. 200 OK.
URL: http://127.0.0.1:8080/function/warning
```

The first warning, and the one that is present in the subsequent requests, is the warning that was recently added inside the `proxy/deploy.go` file. The second warning, only present on the first call is coming from the `commands/login.go` when it attempts a login to the faas gateway.

Adding the environment variable to eliminate the login unless explicitly opted in will remove that duplicated warning, but the one from the `proxy/deploy.go` will remain. With the exception of the loopback addresses of course.

**Comment by alexellis** [comment]
I think we should suppress the message for loopback addresses and make the flag opt-in - i.e. not on by default. I'll also document this in the README.md file but would like you to write a documentation page under the CLI section explaining how to work with private registries on Swarm or Kubernetes - it should cover this new flag.
