### ISSUE TITLE
When deploying an image directly, I get Invalid Registry Auth on 0.6.7

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas-cli#391]
## Expected Behaviour

An image that I am able to deploy with a Stack YAML file should be able to be deployed directly using syntax like `faas deploy --image tf2 --name tf2`

## Current Behaviour

```
$ faas-cli deploy --image tf2 --name tf2
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Unexpected status: 400, message: Invalid registry auth

```

## Steps to Reproduce (for bugs)

1. Build latest version of faas-cli (925937c12)
2. deploy an image from the command line like `faas deploy --image tf2 --name tf2`
3. It will fail with registry auth error
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
latest
* Docker version ( Full output from: `docker version` ):
18.03.0-ce-rc4
* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 1604
* Link to your project or a code example to reproduce issue:

**Comment by BurtonR** [comment]
I'm willing to bet it's related to this bug issued against `faas-swarm`
https://github.com/openfaas/faas-swarm/issues/19

At the moment, faas-swarm expects the image to be in the `<username>`/`<imagename>` format _only_ 
Once that issue is corrected, we'll need to release a new faas-swarm that will accept all variations of the image field

**Comment by alexellis** [comment]
The flag I introduced in 0.6.8 should resolve this. It will suppress sending the registry auth statement. Please update and try again.

**Comment by alexellis** [comment]
Please re-test with master.

**Comment by ericstoekl** [comment]
Tested, issue is resolved. Thanks :100:

**Comment by alexellis** [comment]
Derek lock
