### ISSUE TITLE
Build returns "docker build" requires exactly 1 argument with particular build-arg values

### ISSUE THREAD

**Issue by ryanfields** [openfaas/faas-cli#392]
When passing a build-arg value that contains newlines, the docker build step fails with `ERROR - Could not execute command`

A practical example is to pass to the CLI the expansion of an environment variable containing a private key.

```
> export DEPLOY_KEY=$(cat ~/.ssh/private_key_rsa)
> faas-cli build my-function --build-arg DEPLOY_KEY="$DEPLOY_KEY"
```

This will fail, and even worse, will echo the private key to the screen.

## Expected Behaviour

CLI should gracefully handle quoted multiline strings as input to build-arg without causing the `docker build` to error out due to encountering more arguments than expected.

## Current Behaviour

CLI invokes `docker build` in such a way as to treat newlines as argument separators even when the value passed to build-arg quoted.

## Possible Solution

This might just be a case of not adequately escaping the flags before adding them to the command to be executed, but I'm not familiar with the intricacies of Go's mechanism for calling shell commands to say for certain.  I do know that running the raw docker command from my own shell behaves as expected.  A working image can be built by running:

```
cd ./build/my-function && docker build --build-arg DEPLOY_KEY="$DEPLOY_KEY" -t user/repo:tag .
```

I'm also not certain how to guard against echoing the contents of the env var to screen (or to a log in CI) if the exec from go fails due to the contents of the env var or for any other reason.

## Steps to Reproduce (for bugs)

1. `export MY_MULTILINE_ARG=$(cat any_file_with_newlines)`
2. `faas-cli build my-function --build-arg TEST_ARG="$MY_MULTILINE_ARG"`
3. The docker command will fail because it interprets anything after a newline as a new argument despite the presence of quotes before and after the passed argument's contents.

## Context

I'm trying to build functions that rely on packages from a private repo, and doing so requires the presence of a private key in the docker context.  A quick and repeatable way to accomplish this is to place the key into an environment variable to be passed as a build arg.  My custom build template takes care of all of that just fine, but it can't be called through `faas-cli build` due to this bug.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

Commit: ae7390005a2fe13873f2cb6fcfa2d830dad4a40b
Version: 0.6.5
```

* Docker version ( Full output from: `docker version` ):
```
Client:
 Version:      17.09.0-ce
 API version:  1.23
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.12.1-ce
 API version:  1.35 (minimum version 1.12)
 Go version:   go1.9.4
 Git commit:   7390fc6
 Built:        Tue Feb 27 22:20:43 2018
 OS/Arch:      linux/amd64
 Experimental: false
```

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
macOS 10.12.6

**Comment by ericstoekl** [comment]
Derek add label: bug

**Comment by ericstoekl** [comment]
How about create a Secret in Kubernetes to store this info?

I can repro this issue however, and people may need to have multi-line build args outside of this context. @ryanfields would you like to have a go at fixing this?

**Comment by ryanfields** [comment]
@ericstoekl This is needed for the Docker build step and therefore exists completely outside of Kubernetes.  A Kubernetes secret would be of no help here.

As for fixing this, I have not had the opportunity to learn go and am probably weeks or months away from understanding go well enough to be making system calls with it.

**Comment by rgee0** [comment]
I'm not sure this is to do with newlines, but rather the spaces in `--build-arg` value.  Theres a split on space to create a slice which is fed into `exec.command`.  The upshot of that is that the `--build-arg` value appears as multiple args.

As part of the debug I stripped the newlines out and it still failed in the same way.  Taking the spaces out of the value sees it build.

@ryanfields In order to help validate, I'd appreciate it if you could try:

```
$ export DEPLOY_KEY2=${DEPLOY_KEY// /}
$ faas-cli build my-function --build-arg DEPLOY_KEY="$DEPLOY_KEY2"
```

We can then move on to having a look at how we accommodate this.

As an addendum, there was also a clue in that if you copy the command that is dumped when it errors and run it in the `./build/fn` directory then it will build. So it is something about how golang running the command.

**Comment by rgee0** [comment]
Derek set title: Build returns "docker build" requires exactly 1 argument with particular build-arg values

**Comment by ryanfields** [comment]
@rgee0 I tried this and it does get manage to start the docker build.  Build still fails, but now it's just because the key format has become invalid.

**Comment by alexellis** [comment]
@rgee0 does your PR fix this?

**Comment by rgee0** [comment]
@alexellis PR #399 aims to be less sensitive to spaces which seems to be the issue here.  

Its still WIP as it needs refining & testing, although it is now passing CI. 

I've pinged @ryanfields to see if he can build locally and confirm it solves his issue.

**Comment by rgee0** [comment]
Derek assign: me
