### ISSUE TITLE
Re-deploy fails when using generic secrets in stack.yml

### ISSUE THREAD

**Issue by ryanfields** [openfaas/faas-cli#393]
I'm using secrets, provided via stack.yml, in faas-netes.

faas-cli deploy works as expected when deploying a function that isn't currently deployed.  However, subsequent attempts to deploy the same function result in: 

```
Unexpected status: 500, message: Deployment.apps "my-function" is invalid: [spec.template.spec.volumes[1].name: Duplicate value: "my-function-projected-secrets", spec.template.spec.containers[0].volumeMounts[1].mountPath: Invalid value: "/run/secrets": must be unique]
```

## Expected Behaviour

I should be able to re-deploy a function that relies on secrets without having to completely remove the function from openfaas first.

## Current Behaviour

The only way to re-deploy a function that relies on secrets via stack.yml is to completely take that function offline by removing it from openfaas before doing another deploy.

## Steps to Reproduce (for bugs)

1.  Create a generic secret in kubernetes
2.  Reference that secret in stack.yml
3.  Deploy the function
4.  Deploy the function again, deploy will fail

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

Commit: ae7390005a2fe13873f2cb6fcfa2d830dad4a40b
Version: 0.6.5
```
* Docker version ( Full output from: `docker version` ):
```
Client:
 Version:      17.09.0-ce
 API version:  1.23
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.12.1-ce
 API version:  1.35 (minimum version 1.12)
 Go version:   go1.9.4
 Git commit:   7390fc6
 Built:        Tue Feb 27 22:20:43 2018
 OS/Arch:      linux/amd64
 Experimental: false
```

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
macOS 10.12.6

**Comment by alexellis** [comment]
Ryan thanks for logging the issue (I haven't seen this yet), but it looks like something we should fix ASAP in the faas-netes code.

Please can someone take a look from: @LucasRoesler @ericstoekl @stefanprodan - if either of you have 5 mins we should aim to get this straighten-out fast.

**Comment by LucasRoesler** [comment]
Agreed, this is an issue in the faas-netes project, we need to update this block to modify or create the projected secrets volume instead of just appending it to the list of volumes https://github.com/openfaas/faas-netes/blob/master/handlers/secrets.go#L75

**Comment by LucasRoesler** [comment]
I have a potential fix, but I am trying to write a test case for it and that is just being tedious to get setup correctly

**Comment by LucasRoesler** [comment]
Hi @ryanfields the newest release of faas-netes (tag 0.5.1) has been released and includes the fix for this issue. If you update faas-netes, deployment with the client should behave as expected.

**Comment by alexellis** [comment]
Resolved.

**Comment by alexellis** [comment]
Derek lock
