### ISSUE TITLE
support GET request in python function

### ISSUE THREAD

**Issue by kenyeung128** [openfaas/faas-cli#400]
Hi,

in all the samples, it looks like the input can only be POST request with string or json? what about GET request with parameters in url?

Thanks.

**Comment by alexellis** [comment]
> it looks like the input can only be POST request with string or json

That is not correct. Any binary data is also acceptable.

GET is also support by the OpenFaaS templates.

Try creating a new function with `faas-cli new` and then deploying that.

**Comment by alexellis** [comment]
Feel free to re-reopen the issue if you are building with the official templates and finding they won't accept a GET.
