### ISSUE TITLE
Unexpected 0 exit code with unreachable gateway URL (connection refused)

### ISSUE THREAD

**Issue by rosskevin** [openfaas/faas-cli#401]
When using `faas-cli` in a CI environment, it is critical that exit codes are properly used to avoid continuing on in a build pipeline when a command has failed.

Specifically, this should return a non-zero exit code

```sh
❯❯❯ docker swarm leave --force
Node left the swarm.
~/p/a/dummy ❯❯❯ faas-cli deploy
Deploying: renderNotification.

Is FaaS deployed? Do you need to specify the --gateway flag?
Put http://127.0.0.1:8080/system/functions: dial tcp 127.0.0.1:8080: getsockopt: connection refused

~/p/a/dummy ❯❯❯ echo $?
0
```

## Expected Behaviour

The deploy command should exit with [1 or higher](http://bencane.com/2014/09/02/understanding-exit-codes-and-how-to-use-them-in-bash-scripts/) in the case it did not succeed for any of the functions in the stack.

## Current Behaviour

Exits with `0` regardless of success or failure.

## Steps to Reproduce (for bugs)

1. Don't deploy open faas
2. Try to deploy your own function
3. execute `echo $?` to see the last exit code

## Context

CI scripting

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
Commit: ae7390005a2fe13873f2cb6fcfa2d830dad4a40b
Version: 0.6.5

* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):
OSX and Linux

* Link to your project or a code example to reproduce issue:

**Comment by kenfdev** [comment]
Derek add label: enhancement

**Comment by alexellis** [comment]
All commands were altered to bubble up errors. If this isn't doing then it will be an exception to the rule and should be fixed.

**Comment by alexellis** [comment]
I'd suggest starting with the specific scenario given:

`Put http://127.0.0.1:8080/system/functions: dial tcp 127.0.0.1:8080: getsockopt: connection refused`

**Comment by alexellis** [comment]
Remember this needs testing with positive, negative and edge cases.

So with a YAML file with a single function - with no functions and with more than one function.

And then again without a YAML file

Do the same testing and fix-up for the `faas-cli store deploy` command.

@rosskevin do you want to work on the fix? How important is this to you?

**Comment by kenfdev** [comment]
If we bubble the errors [here](https://github.com/openfaas/faas-cli/blob/master/commands/deploy.go#L214), when we have multiple functions it's going to end early while before bubbling the errors, it used to try to deploy all the functions.

e.g. current behavior (all failing silently)
```
faas-cli git:(master) ✗ ./faas-cli-darwin deploy
Deploying: ruby-echo.
Deploying: url-ping.
Deploying: stronghash.
Deploying: nodejs-echo.
Deploying: shrink-image.

faas-cli git:(master) ✗ echo $?
0
```

e.g. bubble the errors
```
faas-cli git:(master) ✗ ./faas-cli-darwin deploy
Deploying: url-ping.
Unexpected status: 404, message: default backend - 404

faas-cli git:(master) ✗ echo $?
1
```

Does anyone know if trying to deploy all the functions despite an error intended? If not, I think it makes sense to fail earlier.

**Comment by rgee0** [comment]
In proxy.deploy the http status is returned but it is then only used internally within proxy.deployFunction to trigger a further deploy with update set to false.  Nothing is returned from here to indicate an error has occurred and the status is lost - only the deployOutput is printed.

My opinion on the deployment of a stack file would be that it may depend on the nature of the failure.  If the gateway is 404 then why try all the functions against the same gateway?  If it failed for a different reason - something which affects only a subset - then we are heading into the realms of non-deterministic deployments (see #402) which @kenfdev's example inadvertently highlights.

**Comment by alexellis** [comment]
Derek close: merged. @rosskevin please give this a test now by building from master.

**Comment by alexellis** [comment]
Derek set milestone: 0.6.16
