### ISSUE TITLE
Latest version? 0.6.5? 0.6.7? 0.6.8?

### ISSUE THREAD

**Issue by ilovezfs** [openfaas/faas-cli#406]
0.6.7 had been marked as the latest version. Then it went back to being marked as prerelease. Now there's also an 0.6.8 prerelease and yet 0.6.5 is still marked as latest release.

Should we rollback to 0.6.5 in Homebrew? Wait for 0.6.8 to be marked latest? Something else?

**Comment by alexellis** [comment]
Please roll back - there was a bad PR submitted so I had to update the OpenFaaS curl script to point to an earlier version by making the later ones as prerelease.

**Comment by alexellis** [comment]
I'm drafting 0.6.9 which I hope corrects the issues we had.

**Comment by johnmccabe** [comment]
hi @ilovezfs are there instructions on how to raise a rollback?

**Comment by alexellis** [comment]
Let's do it.

**Comment by ilovezfs** [comment]
0.6.9 shipped in Homebrew!

**Comment by alexellis** [comment]
Thank you @ilovezfs 👍
