### ISSUE TITLE
Question: `Unexpected status: 502, message:` when attempting to deploy

### ISSUE THREAD

**Issue by cnashRR** [openfaas/faas-cli#408]
I was working through your "Morning coffee with the OpenFaaS CLI" when I got down to the deploy section, which just states to call the line `faas-cli deploy -f callme.yml`

When I do this, however, I get the status listed above: 
`Unexpected status: 502, message: ` 

I have no Idea what is going wrong. I also tried to change the gateway under the provider section from `127.0.0.1` to `localhost` and nothing changed after re-building. 

I have also made sure to re-check that I have deployed openfaas, and that swarm is working too. 

FaaS-CLI Version 0.6.5
Docker Version 18.05.0-ce, API version 1.37
Using Docker Swarm
Linux Ubuntu 64-bit

from the tutorial here:  https://blog.alexellis.io/quickstart-openfaas-cli/

EDIT: thought I might pre-emptively add what my callme.yml file looks like: 

    provider:
        name: faas
        gateway: http://localhost:8080

    functions:
        callme:
            lang: node
            handler: ./callme
            image: cjnash/callme

Also, when I try to run the command `faas-cli list`, I get the following error: 
`Server returned unexpected status code: 500 - Error pulling metrics from provider/backend. Status code: 502` Are these two errors related somehow?

**Comment by viveksyngh** [comment]
can you see anything is `gateway` and `faas-swarm` logs ?

You can use these command to check the logs. 
`docker service logs -f func_gateway` 
`docker service logs -f func_faas-swarm`

**Comment by alexellis** [comment]
You need to work through the troubleshooting guide which is linked for you in the issue template (which you deleted) 

Please also try the suggestions from Vivek including docker service ps

**Comment by cnashRR** [comment]
After booting up my VM again and trying to replicate the problem, the deploy worked flawlessly. I am pretty sure that it was a problem with my gateway, as now when I connect to the localhost I can see the "Search for function" toolbar with a lot of the functions that I imported during a different tutorial pop up, which was not present before, and the command `docker service logs -f func_gateway` correctly displays the forwarded functions. 

The part that confused me the other day is that I could still deploy the faas swarm, initialize the docker swarm, and build and push my functions to the docker hub, but I was getting that deploy error. I will try to reproduce it and I will start another ticket if I do, but please close this issue. I apologize for the inconvenience and thanks Vivek and Alex for your input. 

Also, I am unsure about where this troubleshooting guide is within the issue template. When I hit "new issue" there are no links present.

**Comment by alexellis** [comment]
@cnashRR please see https://docs.openfaas.com for all guides/docs and thanks for using OpenFaaS.

**Comment by alexellis** [comment]
Derek lock
