### ISSUE TITLE
[0.6.8] deploying from docker repository results in server error with 500 status code 

### ISSUE THREAD

**Issue by hamish-rose** [openfaas/faas-cli#411]
## Expected Behaviour

`faas-cli deploy --image=viveksyngh/openfaas-ocr --name=openfaas-ocr --gateway=http://<GATEWAYIP>`

202/200 status, function is deployed

## Current Behaviour

Deployment fails
`
Unexpected status: 500, message: Deployment.apps "openfaas-ocr" is invalid: spec.template.spec.containers[0].image: Required value`

## Steps to Reproduce (for bugs)
1. Download 0.6.8 windows faas-cli.exe release 
2. Deploy function from repository e.g. 
`faas-cli deploy --image=viveksyngh/openfaas-ocr --name=openfaas-ocr --gateway=http://<GATEWAYIP>`

## Your Environment
minikube version: v0.26.1
Windows 10

* FaaS-CLI version ( Full output from: `faas-cli version` ):
Commit: 925937c120dbb03ac0ec8ef8a2a37cbae764de65
Version: 0.6.8

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
FaaS-netes

* Operating System and version (e.g. Linux, Windows, MacOS):
Windows 10

**Comment by alexellis** [comment]
Hi @hamish-rose, why are you using 0.6.8 when it's marked as pre-release?

The error you found is interesting though - it looks like your image value is not being honored. Have you tried running this command in a new folder?

Alex

**Comment by alexellis** [comment]
I've been able to deploy via 0.6.5 and master (which will be 0.6.9)

```
faas-cli deploy --image=viveksyngh/openfaas-ocr --name=openfaas-ocr --gateway http://$IP:31112
```

I do wonder if you have an unwanted stack.yml or similar in your current directory?

**Comment by BurtonR** [comment]
Derek close

**Comment by alexellis** [comment]
Great to hear it @hamish-rose - if you'd like to join Slack check out https://docs.openfaas.com for the community page.
