### ISSUE TITLE
Allow for --image to be defined for faas-cli push as it is for build and deploy.

### ISSUE THREAD

**Issue by IainColledge** [openfaas/faas-cli#417]
When using faas-cli in a CICD pipeline it is advantageous to override the developer defined image in the associated config.yml file.

For example a workflow may have a developer locally developing with a local image of hello-python but when the last git commit is pushed to the remote repository and subsequent CICD build, push and deploy activities take place they may use a remote docker repository.

Like faas-cli build and faas-cli deploy the use of --image IMAGE_NAME should be supported in order to decouple developer workflow and configuration from CICD pipeline steps and configuration.

## Expected Behaviour

Given an example config yml file hello-python.yml:

```
provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  hello-python:
    lang: python
    handler: ./hello-python
    image: hello-python
```

Executing:

`faas-cli build -f hello-python.yml --image REGISTRY_PREFIX/hello-python`

followed by:

`faas-cli push -f hello-python.yml --image REGISTRY_PREFIX/hello-python`

Should result in the image REGISTRY_PREFIX/hello-python being pushed to the registry defined by REGISTRY_PREFIX.

## Current Behaviour

faas-cli push fails with `Unknown flag: --image`

## Possible Solution

Change the code for faas-cli push to allow for --image flag usage.

## Context

Allowing developers to develop and test functions as they see fit without having to be coupled to the CICD build and deploy process.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

Commit: 6532f3c66967b3a872208a29b1b60a873b7d2490
Version: 0.6.9

* Docker version ( Full output from: `docker version` ):

Client:
 Version:      17.03.1-ce-rc1
 API version:  1.26 (downgraded from 1.27)
 Go version:   go1.7.5
 Git commit:   3476dbf
 Built:        Fri Mar 17 00:27:41 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

Kubernetes (Azure aks)

* Operating System and version (e.g. Linux, Windows, MacOS):

`uname -a 
Linux teamcityba-1 4.13.0-1016-azure #19-Ubuntu SMP Thu May 3 17:29:51 UTC 2018 x86_64 GNU/Linux`

* Link to your project or a code example to reproduce issue:

Just override any faas-cli push with an --image flag.

**Comment by iyovcheva** [comment]
@IainColledge you can still add the docker registry prefix to the image name in the yaml file and do not push until the latest updates.
Can you please give an example for an use-case when this will not work?

**Comment by IainColledge** [comment]
Thanks for the reply. Absolutely that is a workaround however what it does is introduce tight coupling between the developer and eventual deployment config.

The developer either has to change the config.yml file every time just before push or has to sync two config.yml files which seems to go against the ethos of functions making deploys simple and minimal effort.

This is also not congruent with the behaviour of build and deploy where the image can be overridden on the command line allowing separation of concerns.

For example ideally one could do in automation:

```
faas-cli build -f hello-python.yml --image REGISTRY_PREFIX/hello-python
faas-cli push -f hello-python.yml --image REGISTRY_PREFIX/hello-python
faas-cli deploy -f hello-python.yml --image REGISTRY_PREFIX/hello-python
```
at the moment it is:

```
faas-cli build -f hello-python.yml --image REGISTRY_PREFIX/hello-python
faas-cli push -f hello-python.yml 
faas-cli deploy -f hello-python.yml --image REGISTRY_PREFIX/hello-python
```

In reality the push and deploy are automated steps that would be separated to allow for say security container scanning products to give it the once over before it enters the dev -> qa -> prod auto testing pipeline.

**Comment by alexellis** [comment]
Let's see what the current options are and whether we can come up with any ideas in this thread 

The --image override assumes there is only one file in the stack.yml file. This is not a correct assumption.

Can we go back to the original problem and understand the requirements before discussing one solution or another?

In OpenFaaS Cloud the image name gets a suffix of :TAG-SHA. I would expect that something similar would be useful here?

**Comment by rgee0** [comment]
Has there been a misunderstanding around how `--image` functions?  If `-f filename.yml` is provided for build then the `--image` flag isn't used. Try:
```
$ faas-cli new callme --lang node && \
    faas-cli build -f callme.yml --image=rgee0/burt && \
      docker images
```
You will likely see:
```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
callme              latest              36c0ffd34f5d        6 minutes ago       72.2MB
node                8.9.1-alpine        8bcb66e2abe9        6 months ago        67.7MB
```

This is the piece of code that handles the parsing of flags / yaml:

https://github.com/openfaas/faas-cli/blob/56c251a3f82532ad73bb809577105a23bc96793b/commands/build.go#L136-L150

If the yaml file has size then do something with the contents otherwise validate the flags and use those.  Ultimately this is what Alex is alluding to above and the two have to be mutually exclusive as there could be a 1..* scenario if `--image` is provided when the yaml file contains > 1 functions.

**Comment by IainColledge** [comment]
Thanks for your replies everyone and I had assumed that the --image flag overrode the yaml file definition for the first function.

The use case for me is that I want to plug this into a CICD pipeline and separate developer configuration from deployment in a way that still gives the developer all of the advantages of the fast and easy function development pattern. It may mean that there is a constraint for me of having one function per yaml file which is something I'm fine with if it allows me to use an automated CICD pipeline.

So for an example workflow:

1) Developer develops locally with say an auto generated YAML file such as:

```
provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  hello-python:
    lang: python
    handler: ./hello-python
    image: hello-python
```

2) The developer is happy with their code and this is pushed to a Git Repo.
3) Teamcity pulls from the repo and builds, then pushes the image into a remote private docker repository.
4) Teamcity then takes steps such as security scanning the container using a tool such as twistlock.
5) Teamcity then pulls the docker image from the repo and deploys to dev.
6) Teamcity then automates the API smoke testing.
7) Teamcity then deploys to QA for regressions testing.
8) Teamcity then deploys to Prod etc.

(Teamcity can be any tool BTW, I just happen to use Teamcity + Ansible)

This pattern allows me to use containers in an environment in a healthcare provider company where it's advantageous to automate security scanning and also show separation of concerns to auditors, no one person has the ability to write code and deploy it to production. That would mean that only the CICD pipeline can push to the Docker repository used in the pipeline for example.

For other languages there is a hierarchy such as:

1. command line flag overides
2. environment variable, which overrides
3. config file

For example: https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

This allows the same container image to flow through the CICD pipeline environments without having to be built every time.

Another way of doing this is that say used by Logstash of using an environment variable if present and using a default if not: https://www.elastic.co/guide/en/logstash/current/environment-variables.html

I understand the above may mean a constraint of a one to one mapping of function to function config file but for my use case that is an acceptable trade off to separate developer config from CICD pipeline config.

Hopefully I've explained my use case and constraints well and look forward to your replies.

**Comment by iyovcheva** [comment]
@IainColledge AFAIU your use-case is that you need to automate the process of pull function code/build/push/deploy for automated testing, you can configure the Docker namespace in the testing tool, but the developer should not know or does not need to know the namespace.

If you're using a script for triggering tests, you can do the same with
```
docker tag <function_name>:<version> <docker_namespace>/< function_name >:<version>
docker push <docker_namespace>/< function_name >:<version>
faas deploy --image <docker_namespace>/< function_name >:<version> -name < function_name >
```

Automating that within faas-cli can be reasonable if this is a common use-case and the shared approach is not preferred. Then this should better be something like
```
faas-cli push -f func.yml --prefix docker_namespace
```
which can prefix the image or replace the already existing prefix.

If you're using a `stack.yml` with more than one function, this can prefix all images or would require a more complicated approach of selecting only the required. 

Is my understanding of what you need in the right direction?

@alexellis @rgee0 WDYT about adding this as a feature?

**Comment by iyovcheva** [comment]
@IainColledge Yes, it finally runs `docker push`  - [push.go](https://github.com/openfaas/faas-cli/blob/master/commands/push.go#L72).
The benefit of `faas-cli push` is that it allows you to push the whole stack of functions and makes use of the function's yaml configuration.

**Comment by IainColledge** [comment]
@iyovcheva So my trade off is I would have to export the functions one by one using multiple docker push's, if that's correct then am perfectly happy with that.

Overriding the prefix in future as an option would be fantastic but this at least lets me get going with building the CICD machinery.

Thanks very much, you're a star!!!

**Comment by iyovcheva** [comment]
@IainColledge I'm happy this helps.
If this works for you, then I will close the issue.

If the community agrees on adding the `--prefix` flag, then we'll add a `help wanted` label and you (or someone else) are welcome to contribute.

**Comment by iyovcheva** [comment]
Derek close

**Comment by alexellis** [comment]
I don't think we should close this issue. 

If we're going to do that then let's open a new one so we can resolve the problem of running the CLI in a CI/CD environment.

**Comment by IainColledge** [comment]
I'm not a Go dev, but put me down for testing it out in a CICD environment as illustrated above.

**Comment by alexellis** [comment]
Can you give us the clear requirements?

You want the same image tag as the yaml but with a different repository? Because each environment has its own registry?

**Comment by IainColledge** [comment]
For me in this case it is having a different registry for devs and the pipeline, if as it seems I can tag with a version then I can have multiple versions living in the same image repository.

Devs can use whatever they want including local, and the pipeline just changes and/or adds a prefix to one or more defined functions in the config file.

However a prefix command line arg covers all cases.

**Comment by iyovcheva** [comment]
Derek reopen

**Comment by alexellis** [comment]
Let's review at next contributor call. @IainColledge please can you also join Slack? https://docs.openfaas.com/community

**Comment by IainColledge** [comment]
Yup, will do, thanks for the invite.

**Comment by alexellis** [comment]
@IainColledge just checking in with you - did you make it into Slack?

We added a feature `--tag` which might be useful for you, please take a look over at and let us know if we can close this issue - https://docs.openfaas.com/cli/tags/

**Comment by Rasarts** [comment]
In some-project.yaml I have:
```yaml
provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  some-project-name:
    lang: go
    handler: ./some-project-name
    image: some-project-name
```

When I try use faas-cli like this:
```bash
faas-cli build -f ./some-project-name.yml  --image=some-name/some-project-name
```
after that I use docker command:
``` bash
$ docker push some-name/some-project-name
```
than I get error in my pipeline :
```bash
The push refers to repository [docker.io/some-name/some-project-name]
An image does not exist locally with the tag: some-name/some-project-name
```
But I am expect what I can build docker image with other tag then some-project-name in some-project.yaml

**Comment by alexellis** [comment]
Hi @Rasarts I'm going to close this issue since it's an old thread and you have a different question.

Basically you need to fill in all the details in the .yaml file

This is an invalid Docker image name if you want to push it:

```yaml
    image: function-name
```

Best use `faas-cli new --lang golang --prefix=some-user`

Which will generate:

```yaml
    image: some-user/function-name
```

Alex

**Comment by alexellis** [comment]
Derek lock: original issue resolved

**Comment by alexellis** [comment]
Derek close
