### ISSUE TITLE
Trouble using "Deployment guide for Docker Swarm"

### ISSUE THREAD

**Issue by marclar** [openfaas/faas-cli#421]
I'm following https://docs.openfaas.com/deployment/docker-swarm/ but I get errors when running `faas deploy`.

So far I've done:

- `docker swarm init`

- `docker swarm join --token ***`

there, I get: 

> "Error response from daemon: This node is already part of a swarm. Use "docker swarm leave" to leave this swarm and join another one."

considering manager nodes are worker nodes, I figured I could skip past this step.

- `./deploy_stack.sh`

```
Deploying stack
Creating network func_functions
Creating config func_alertmanager_config
Creating config func_prometheus_config
Creating config func_prometheus_rules
Creating service func_gateway
Creating service func_faas-swarm
Creating service func_nats
Creating service func_queue-worker
Creating service func_prometheus
Creating service func_alertmanager
```

- `docker service ls`

| ID | NAME | MODE | REPLICAS | IMAGE | PORTS |
| --- | --- | --- | --- | --- | --- |
| s97s24qsrync | func_alertmanager | replicated | 0/1 | prom/alertmanager:v0.15.0-rc.0 | - |
| l5jliwb4m8ha | func_faas-swarm | replicated | 0/1 | functions/faas-swarm:0.3.3 | - |
| vtnzao08vrfh | func_gateway | replicated | 0/1 | functions/gateway:0.8.3 | *:8080->8080/tcp |
| zouodmgy53vb | func_nats | replicated | 0/1 | nats-streaming:0.6.0 | - |
| k6kudmr06rjk | func_prometheus | replicated | 0/1 | prom/prometheus:v2.2.0 | *:9090->9090/tcp |
| h6i56e4idf3f | func_queue-worker | replicated | 0/1 | functions/queue-worker:0.4.6 | - |
---

- `faas deploy` (Note: I changed `localhost` to `127.0.0.1` in `stack.yml`)

```
Deploying: wordcount.

Is FaaS deployed? Do you need to specify the --gateway flag?
Put http://127.0.0.1:8080/system/functions: dial tcp 127.0.0.1:8080: connect: connection refused

Deploying: base64.

Is FaaS deployed? Do you need to specify the --gateway flag?
Put http://127.0.0.1:8080/system/functions: dial tcp 127.0.0.1:8080: connect: connection refused

Deploying: markdown.

Is FaaS deployed? Do you need to specify the --gateway flag?
Put http://127.0.0.1:8080/system/functions: dial tcp 127.0.0.1:8080: connect: connection refused

...
```
What am I doing wrong?

- `docker version` 18.03.1-ce
- `faas-cli version` 0.6.10
- MacOS 10.13.3 High Sierra

**Comment by rgee0** [comment]
Deploy failing is likely linked to what we see in the output of `docker service ls`.  In order to deploy the OpenFaaS containers need to be showing at least 1 replica.

Did you leave sufficient time for the stack images to be pulled down? 
Did you try removing the stack and redeploying?

```
$ docker stack rm func

$ ./deploy_stack.sh
```

Could you try restarting docker?

**Comment by alexellis** [comment]
Hi there please let us know how you get on. I can Richard is working with you on this.

The join command is meant to be run on another computer not on your master node. When you have a single node like your Mac then the join isn't needed.

If the services stay at 0/1 you may need to restart docker.

**Comment by rgee0** [comment]
@marclar how did you progress on this?  For info, the documentation has also been updated in order to make the required order of events during deployment via swarm clearer.

**Comment by marclar** [comment]
Hey - sorry for the delay; gonna try this out now

**Comment by marclar** [comment]
Everything works now - I'm guessing restarting Docker did it?

Anyway, thanks for the help :)

**Comment by rgee0** [comment]
Highly likely, it’s my initial action whenever docker images don’t fire up.
Great to read you’re up and running. Do let us know if you need help as you continue to use OpenFaaS.

I’ll close this as resolved.

**Comment by rgee0** [comment]
Derek close: resolved

**Comment by marclar** [comment]
Oh - one more thing - I just noticed that the link to "install the OpenFaaS CLI" is broken here (section 2.2): https://docs.openfaas.com/deployment/docker-swarm/

**Comment by rgee0** [comment]
Thanks. I’ll take a look

**Comment by alexellis** [comment]
Yes it's broken let's fix in a new PR. No issue needed

**Comment by rgee0** [comment]
ref: https://github.com/openfaas/docs/pull/40
