### ISSUE TITLE
No files created in the function directory when created with Python-armhf language.

### ISSUE THREAD

**Issue by Gallouche** [openfaas/faas-cli#423]
The `faas new` function provided by the CLI doesn't seems to work with the Python-armhf.
## Expected Behaviour

When you run `faas new test --lang Python-armhf` in the same directory as the `template` directory, it should produce something like : 
├── test
│   ├── handler.js
│   └── package.json
├── test.yml
└── template

## Current Behaviour
There is nothing in the `test` directory, it's look like this : 
├── test
├── test.yml
└── template

## Steps to Reproduce (for bugs)
1. run `faas new test --lang Python-armhf`

## Your Environment
Running Docker Swarm and OpenFaas on a two nod Raspberry PI 3B+

* FaaS-CLI version ( Full output from: `faas-cli version` ):

Commit: 3995a8197f1df1ecdf524844477cffa04e4690ea
Version: 0.6.11

* Docker version ( Full output from: `docker version` ):

Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:24:36 2018
 OS/Arch:      linux/arm
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f150324
  Built:        Wed May  9 22:20:37 2018
  OS/Arch:      linux/arm
  Experimental: false

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
 Currently using Docker Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
 Linux Raspbian Stretch Lite

**Comment by alexellis** [comment]
Hi, thanks for using OpenFaaS. 

It's case-sensitive, so you should enter it the same as it is listed. python-armhf or python3-armhf

Alez

**Comment by Gallouche** [comment]
Oh ! Sorry so ! Thanks a lot ! :+1:
