### ISSUE TITLE
Enhancement: version command should give the server version

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#427]
Enhancement: the faas-cli version command should give the server version info via `/system/info` URL which already exists in the gateway.

Current data from `/system/info`

```json
{"provider":"faas-swarm","version":{"sha":"b8cc399b5eadfb59956b8341a44ea3ba4acf1e7f","release":"0.3.5"},"orchestration":"swarm"}
```

Data format will change slightly via PR mentioned below to also give gateway version. **Please read carefully**

Current version:

```
$ faas-cli version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

Commit: 999a6669148c30adeb64400609953cf59db2fb64
Version: 0.6.10
```

Expected result when version endpoint available:

```
$ faas-cli version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI commit: 999a6669148c30adeb64400609953cf59db2fb64
CLI version: 0.6.11

Server:
- Gateway: OpenFaaS Gateway  0.x.x
- Orchestration: Swarm
```

Expected result when version endpoint not available (earlier versions):

```
$ faas-cli version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI commit: 999a6669148c30adeb64400609953cf59db2fb64
CLI version: 0.6.11

Server: unable to fetch version information 
```

**Comment by alexellis** [comment]
We have a /system/info endpoint which can be used to start the work, the PR by Ed will extend/alter the payload response from the gateway. 

https://github.com/openfaas/faas/pull/737

**Comment by alexellis** [comment]
Calling @openfaas/cli - would be great to get a volunteer for this one, should be an easy one.

**Comment by ivanayov** [comment]
For setting `Orchestration` I'm thinking of:
1. If `! -z $OPENFAAS_URL` check `$OPENFAAS_URL/system/info` for `faas-netes` or `faas-swarm`
2. Check `http://127.0.0.1:8080/system/info`

If both swarm and netes are available, print both.
Print versions.

```
Server:
- Gateway: OpenFaaS Gateway  0.x.x
- Orchestration: Swarm, version 0.y.y
```

Not sure how we can find out easily if OpenFaaS is running on Kubernetes and `OPENFAAS_URL` is not set.

What about `faas-cli version --endpoint <gateway>` ?
How do we determine the orchestration - only on the same machine where faas-cli is installed or we'd like to allow this check for a remote instance? 

As the CLI is just a client and it's separated this is not quite clear.

**Comment by rgee0** [comment]
If OPENFAAS_URL isnt set we tend to use the defaultgw value.  The orchestrator is available from the /system/info endpoint, isn't it?

I think the server output should also output the gateway address that has been interrogated.

**Comment by alexellis** [comment]
@rgee0 you're right it exists.

@ivanayov the endpoint already exists with basic information and will gain additional data in the PR referenced. The task is to parse the JSON and format it as plaintext for the user.

What do you think?

Alex

**Comment by alexellis** [comment]
PR is merged - Ed volunteered to pick up the change.

**Comment by ewilde** [comment]
@alexellis yes i think now that the PR is merged, I can go ahead with the spec as you outlined at the top of this issue

**Comment by rgee0** [comment]
@ewilde please include the gateway address as well as the ouput alex has specified. I think it will help offset questions where people are ‘defaulting’ rather than ‘remoting’ and so seeing results they may not be expecting.

**Comment by ewilde** [comment]
@alexellis @rgee0 

Made a start with the version command change:

```
		  ___                   _____           ____
		 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
		| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
		| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
		 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
		      |_|
		
		Commit: 56c251a3f82532ad73bb809577105a23bc96793b
		Version: dev
		- Gateway 
			uri: http://127.0.0.1:60832 
			version: 0.3.3 
			sha: c890cba302d059de8edbef3f3de7fe15444b1ecf 
			commit: Bump faas-swarm to latest
		- Provider 
			name: faas-swarm 
			orchestration: swarm 
			version: 0.3.3 
			sha: c890cba302d059de8edbef3f3de7fe15444b1ecf
```

Thoughts?
