### ISSUE TITLE
PyMySQL will not build with python3 template

### ISSUE THREAD

**Issue by jjainschigg** [openfaas/faas-cli#429]
I've been using the PyMySQL python3 connector without issues for several months, building functions atop Kubernetes. Today I deployed a fresh Kubernetes cluster and OpenFaaS, without issues, used OpenFaaS to build and deploy several small Python3 functions, without issues. I then tried to build a known-good Python3 function with PyMySQL as the connector, and received a build error around the cryptography package.

## Expected Behaviour

Normally this function builds and runs fine with PyMySQL in requirements.txt.

## Current Behaviour

Functions that call PyMySQL do not compile, apparently failing during compilation of the cryptography system.

k8suser@k8smaster:~/functions$ faas-cli build -f randshow.yml
[0] > Building randshow.
Clearing temporary build folder: ./build/randshow/
Preparing ./randshow/ ./build/randshow/function
Building: johnjainschigg/randshow:v1.0.0 with python3 template. Please wait..
Sending build context to Docker daemon 9.216 kB
Step 1/20 : FROM python:3-alpine
 ---> f5cdcff7bf21
Step 2/20 : RUN apk --no-cache add curl     && echo "Pulling watchdog binary from Github."     && curl -sSL https://github.com/openfaas/faas/releases/download/0.8.0/fwatchdog > /usr/bin/fwatchdog     && chmod +x /usr/bin/fwatchdog     && apk del curl --no-cache
 ---> Using cache
 ---> cced53efe253
Step 3/20 : RUN addgroup -S app && adduser -S -g app app
 ---> Using cache
 ---> e8c0b00de0c7
Step 4/20 : WORKDIR /home/app/
 ---> Using cache
 ---> 6eb3ded325a8
Step 5/20 : COPY index.py .
 ---> Using cache
 ---> 56d5e993ada3
Step 6/20 : COPY requirements.txt .
 ---> Using cache
 ---> d02b283427b2
Step 7/20 : RUN chown -R app /home/app
 ---> Using cache
 ---> bcfe237e8a4c
Step 8/20 : USER app
 ---> Using cache
 ---> 7f4cebc869fe
Step 9/20 : ENV PATH $PATH:/home/app/.local/bin
 ---> Using cache
 ---> 03b446966c64
Step 10/20 : RUN pip install --user app  -r requirements.txt
 ---> Using cache
 ---> 0a26391cdce9
Step 11/20 : RUN mkdir -p function
 ---> Using cache
 ---> 4ac916100bbc
Step 12/20 : RUN touch ./function/__init__.py
 ---> Using cache
 ---> fd449f230654
Step 13/20 : WORKDIR /home/app/function/
 ---> Using cache
 ---> 3eb4fdc05ece
Step 14/20 : COPY function/requirements.txt .
 ---> Using cache
 ---> 66bb6976a0a3
Step 15/20 : RUN pip install --user app -r requirements.txt
 ---> Running in 9f64cf4cef8b
Requirement already satisfied: app in /home/app/.local/lib/python3.7/site-packages (0.0.1)
Collecting requests (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl (91kB)
Collecting PyMySQL (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/a7/7d/682c4a7da195a678047c8f1c51bb7682aaedee1dca7547883c3993ca9282/PyMySQL-0.9.2-py2.py3-none-any.whl (47kB)
Collecting chardet<3.1.0,>=3.0.2 (from requests->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting idna<2.8,>=2.5 (from requests->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
Collecting urllib3<1.24,>=1.21.1 (from requests->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl (133kB)
Collecting certifi>=2017.4.17 (from requests->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl (150kB)
Collecting cryptography (from PyMySQL->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/ec/b2/faa78c1ab928d2b2c634c8b41ff1181f0abdd9adf9193211bd606ffa57e2/cryptography-2.2.2.tar.gz (443kB)
Collecting asn1crypto>=0.21.0 (from cryptography->PyMySQL->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
Collecting six>=1.4.1 (from cryptography->PyMySQL->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting cffi>=1.7 (from cryptography->PyMySQL->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/e7/a7/4cd50e57cc6f436f1cc3a7e8fa700ff9b8b4d471620629074913e3735fb2/cffi-1.11.5.tar.gz (438kB)
    Complete output from command python setup.py egg_info:
    
        No working compiler found, or bogus compiler options passed to
        the compiler from Python's standard "distutils" module.  See
        the error messages above.  Likely, the problem is not related
        to CFFI but generic to the setup.py of any Python package that
        tries to compile C code.  (Hints: on OS/X 10.8, for errors about
        -mno-fused-madd see http://stackoverflow.com/questions/22313407/
        Otherwise, see https://wiki.python.org/moin/CompLangPython or
        the IRC channel #python on irc.freenode.net.)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ywqp3eot/cffi/
The command '/bin/sh -c pip install --user app -r requirements.txt' returned a non-zero code: 1
2018/07/05 19:04:56 ERROR - Could not execute command: [docker build -t johnjainschigg/randshow:v1.0.0 .]

## Steps to Reproduce (for bugs)
Create a Python3 function with the below handler.py and requirements.txt. Build with faas-cli build -f function-name.yml

Handler:
import pymysql # module PyMySQL
import base64
import os

def handle(req):
    # get db connection stuff
    if "thehost" not in os.environ or "theuser" not in os.environ or "thepassword" not in os.environ or "thedb" not in os.environ:
      print("Missing environment stuff")
      return req
    else:
      thehost = os.environ["thehost"]
      theuser = os.environ["theuser"]
      thepassword = os.environ["thepassword"]
      thedb = os.environ["thedb"]
    # grab an image from the db at random
    connection = pymysql.connect(host=thehost,user=theuser,password=thepassword,db=thedb,charset='utf8mb4',cursorclass=pymysql.cursors.DictCursor)
    cursor = connection.cursor()
    sql = "SELECT img_data FROM images ORDER BY RAND() LIMIT 1"
    cursor.execute(sql)
    result = cursor.fetchone()
    if cursor.rowcount == 0:
        print("No results.")
        return req
    img_data = result["img_data"]
    cursor.close()
    connection.close()
    # convert base64 raw to UTF8 and insert as image payload
    im_utf8 = img_data.decode(encoding="UTF-8")
    print("<html><head><title></title></head><body>")
    print("<img src=\"data:image/jpeg;base64,%s\">" % im_utf8)
    print("</body></html>")
    return req

requirements.txt:
requests
PyMySQL

## Context

I'm creating little demo functions that stress a Percona MySQL 5.7 database. I'm not married to PyMySQL -- I just need a straightforward MySQL connector for Python that works reliably with OpenFaaS. I'd prefer not to use an ORM or similar device.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
Commit: d33cb5cdc128b75fc7a9856c30fc0eded39fec1e
Version: 0.6.12
* Docker version ( Full output from: `docker version` ):
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
No
* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 16.04
* Link to your project or a code example to reproduce issue:

**Comment by ericstoekl** [comment]
Hi @jjainschigg , thank you for your question and welcome to the community.

I was able to build the function with the `requirements.txt` file you described by running the following command:

```
fc build -f mysqlfunc.yml --build-arg ADDITIONAL_PACKAGE='gcc libffi-dev musl-dev openssl-dev'
```

This makes use of the new `build_option` feature from [Release 0.6.11](https://github.com/openfaas/faas-cli/releases/tag/0.6.11)

Please let us know if you have any other questions.

**Comment by ericstoekl** [comment]
Derek close

**Comment by jjainschigg** [comment]
Worked for me in vivo, too. Thanks a lot, Eric! Alex and others recommended this, but I was befuddled at how to use it.

**Comment by alexellis** [comment]
Hi folks,

First of all thanks to Eric @ericstoekl for helping.

I just want to make sure we get to the best solution for you. I would not recommend passing `ADDITIONAL_PACKAGES` - consider this a private API.

@ivanayov and @rgee0 have been working on a solution for the problem when a pip module needs a native compilation toolchain as in the example above. The mechanism we've added is for consumption is to pass `build_options` which can also be added in the YAML file (ADDITIONAL_PACKAGES cannot and is considered an internal API right now)

I was hoping that Ivana's example that I shared with you would resolve this issue. I am wondering if you could try it and get back? It makes use of `build_options` and the example was put together to show how to solve this problem using the new feature/mechanism.

This is Ivana's example, check out the "stack.yml" - https://github.com/ivanayov/mysql-function-openfaas

I'm pretty sure that the new `dev` option in the Python3 template includes the packages mentioned by Eric `gcc libffi-dev musl-dev openssl-dev`

Some more documentation on the new build option feature:
https://docs.openfaas.com/cli/build/

**Comment by jjainschigg** [comment]
Thanks, Alex -- this is very helpful.

Confirmed that I can compile functions that use PyMySQL (my original issue) using the build_options -- specifically, by adding options:

- dev
- mysql
