### ISSUE TITLE
Feature: Generate unique image tag on build

### ISSUE THREAD

**Issue by stefanprodan** [openfaas/faas-cli#432]
Faas-cli `build` should produce unique image tags as in `gitbranch-gitsha` besides the `latest` one. 
Faas-cli `push` should push the unique tag along with `latest`.

## Expected Behaviour

The faas-cli CI pipeline should:
- detect Git
- get the current branch name and commit SHA
- tag the function image with `gitbranch-gitsha`
- build, push and deploy the  `function:gitbranch-gitsha` image

## Current Behaviour
Only the `latest` tag is applied and pushed to image registry.

## Possible Solution

Detect Git and compose the image tag based on branch and commit.

## Context

Using `latest` for production systems is problematic, there is no way to trace what version of a function you are running. 

Having unique image tags for each build enables:
- easy rollbacks 
- automatic update with tools like Weave Flux
- canary and A/B testing with Istio

**Comment by stefanprodan** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
We do something like this with OpenFaaS cloud, this is what we have done in OpenFaaS cloud:

Example from OpenFaaS Cloud via the functions for @kenfdev: 

```json
[{"name":"kenfdev-contributors-page","image":"ofcommunity/kenfdev-faas-contributors-page-contributors-page:0.9.1-4456fab11f107a35ee60c4cd3cb6e1e1281cdf95","invocationCount":15,"replicas":1,"labels":{"Git-Cloud":"1","Git-DeployTime":"1530886357","Git-Owner":"kenfdev","Git-Repo":"faas-contributors-page","Git-SHA":"4456fab11f107a35ee60c4cd3cb6e1e1281cdf95","app":"kenfdev-contributors-page","faas_function":"kenfdev-contributors-page","uid":"923909804"}},{"name":"kenfdev-github-stats","image":"ofcommunity/kenfdev-faas-github-stats-github-stats:0.9.0-6cdb02ccb3b07ab92101ff1414bbcaa2dc9acc89","invocationCount":44,"replicas":1,"labels":{"Git-Cloud":"1","Git-DeployTime":"1530885810","Git-Owner":"kenfdev","Git-Repo":"faas-github-stats","Git-SHA":"6cdb02ccb3b07ab92101ff1414bbcaa2dc9acc89","app":"kenfdev-github-stats","faas_function":"kenfdev-github-stats","uid":"793864064"}},{"name":"kenfdev-github-stats-page","image":"ofcommunity/kenfdev-faas-github-stats-github-stats-page:0.9.0-6cdb02ccb3b07ab92101ff1414bbcaa2dc9acc89","invocationCount":39,"replicas":1,"labels":{"Git-Cloud":"1","Git-DeployTime":"1530885808","Git-Owner":"kenfdev","Git-Repo":"faas-github-stats","Git-SHA":"6cdb02ccb3b07ab92101ff1414bbcaa2dc9acc89","app":"kenfdev-github-stats-page","faas_function":"kenfdev-github-stats-page","uid":"746438620"}}]
```

**Comment by alexellis** [comment]
I think the tag should be the SHA only (similar to [Skaffold](https://github.com/GoogleContainerTools/skaffold))

**Comment by ivanayov** [comment]
Working on this

**Comment by ivanayov** [comment]
I think that we don't need the branch as the SHA is unique and it's enough to identify the version.

If one really needs the branch name, can easily find it with ` git branch --contains <sha>`.
For a version as shorter as possible is always better IMO.

**Comment by alexellis** [comment]
## Task acceptance

This task is only complete when it works for the following:

- build
- push
- deploy

Without all of the above there is no point in merging a PR.

We also have a tricky case where someone may build/push then add another commit. They will then type in "deploy" expecting it to deploy the previous SHA but it won't. It will deploy the current SHA that will not exist. 

Alex

**Comment by ivanayov** [comment]
@alexellis For the use case you've mentioned - only `faas build` is taking into account the latest SHA. 

`faas push` works as required (pushing both versions) without any code changes as all the tagged images of the same function have the same image id.

If there is a new commit, there won't be an image associated with it, so deploy takes the latest built.

May be I don't understand well the use case and your concern. Does it differ from what I described?

**Comment by alexellis** [comment]
The use-case is that build/push and deploy all use the SHA. cc @stefanprodan 

Alex

**Comment by alexellis** [comment]
This is the developer workflow and use-case as I understand it from Stefan who has only just got back from vacation, so may not have time to reply straight away.

* Make change to code 1
* Commit to git
* faas-cli build --tag  (hello-world:0.2-bbe56fab)
* faas-cli push --tag  (hello-world:0.2-bbe56fab)
* faas-cli deploy --tag  (hello-world:0.2-bbe56fab)

Test function

* Make change to code 2
* Commit to git
* faas-cli build --tag  (hello-world:0.2-ee536fab)
* faas-cli push --tag  (hello-world:0.2-ee536fab)
* faas-cli deploy --tag  (hello-world:0.2-ee536fab)

Test function

* Make change to code 3
* Commit to git
* faas-cli build --tag (hello-world:0.2-4456fab)
* faas-cli push --tag  (hello-world:0.2-4456fab)
* faas-cli deploy --tag  (hello-world:0.2-4456fab)

Test function

Etc..

Optionally the user can also change the tag in the YAML from 0.2 to something else, this `--tag` feature automates that.

Alex

**Comment by stefanprodan** [comment]
Yes that's the workflow I had in mind. A more advanced use case will also require the git branch name, so you can do multi-env promotion with a CD tool.

**Comment by stefanprodan** [comment]
@ivanayov I hope the above example is ok. The `--tag` without a value will add only the `-sha` while `--tag=branch` will result in `branch-sha`

**Comment by ivanayov** [comment]
@stefanprodan Do we really need the branch? I mean that the SHA is unique and can determine the branch it belongs to.

**Comment by alexellis** [comment]
This is the feature being asked for and it's easy to do. Stefan suggests default of the SHA and with s flag you get his variant with branch-SHA.

**Comment by ivanayov** [comment]
@stefanprodan I'm going to address the `--tag=branch` in a separate PR. 

Does a new flag `--tag-branch` look fine to you?

**Comment by ivanayov** [comment]
For test purposes this is going to the `tagging` branch first by suggestion from @alexellis. See [#456](https://github.com/openfaas/faas-cli/pull/456)

**Comment by alexellis** [comment]
I've had to spend around half a day working on the code in #465, but it is now working as expected for adding the SHA and the default mode of using the tag from the YAML file (this was never meant to use a git tag).

I'll raise a separate issue for @stefanprodan to work on to add the branch-formatting mode.
