### ISSUE TITLE
Feature: Language-specific welcome messages for "faas-cli new"

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#437]
When generating a template with a given language we should be able to supply a message to give the user hints on how to use it.

* With Go for instance we could mention installing and using `dep` for vendoring 

* For Java (coming very soon) we would explain the Gradle version installed and optionally link to a docs page on it containing examples.

* For Node we'd state that `npm i --save` can be used to add packages like `request` or `cheerio`

I'd see this as another field in template.yml - to follow a unix convention it could be "moto" or something else like "welcome"

A flag in the CLI could suppress this screen `--quiet` or `--no-info`

Alex

```
Folder: example-1 created.
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|


Function created in folder: example-1
Stack file written: example-1.yml

Notes:
  You have created a new function which uses Golang 1.9.7.
  To include third-party dependencies, use a vendoring tool like dep:
  dep documentation: https://github.com/golang/dep#installation
```

**Comment by alexellis** [comment]
I'd like someone to volunteer to start work on this feature as soon as possible so it can go out with the Java template, or shortly there-after.

Alex

cc @viveksyngh @dungeonmaster18 @ericstoekl @rgee0 @burtonr

**Comment by viveksyngh** [comment]
I can work on this one.

**Comment by alexellis** [comment]
Derek assign: viveksyngh

**Comment by alexellis** [comment]
Thank you. How long do you think it will take?

**Comment by viveksyngh** [comment]
I will try to have CLI changes ready by tomorrow morning IST. We will have to also add the welcome message for each template.

**Comment by viveksyngh** [comment]
@alexellis The welcome message format will be a single string separated by newlines in `template.yml` ?

**Comment by rgee0** [comment]
It might be easier for formatting to use a block in `template.yml` where multiline content is desired

**Comment by alexellis** [comment]
A block of text, multi-line within the YAML file. @viveksyngh
