### ISSUE TITLE
Upgrade to license-check 0.2.2 as per faas repo

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#441]
## Expected Behaviour

`OpenFaaS Author(s)` should now be recognized as a valid license header, but is not.

## Possible Solution

Update to latest version of license-check - https://github.com/alexellis/license-check/releases

Check openfaas/faas openfaas/faas-netes for usage guidelines (in the Dockerfile)

This is blocking PR #439 

Skill level: easy - copy/paste from openfaas/faas project and test locally with "docker build" on PR #439.

**Comment by burtonr** [comment]
I'm on it!
