### ISSUE TITLE
Return real exit code

### ISSUE THREAD

**Issue by rimiti** [openfaas/faas-cli#443]
Hello,

In first, thank you everybody for this amazing project.

### Issue:  

When I try to deploy a function and there is an error, the exit is always returning a 0 exit code: 

**Command**

```bash
$ faas-cli deploy -f ./deploy-production.yml
Deploying: graphql.

Unexpected status: 400, message: secrets "gitlab-registry" not found
```

**Exit status**
```bash
$ echo $?
0
```

It could be useful to return 1 when deploy hasn't be succeeded. :)

Have a nice coding day.
Regards,

**Comment by alexellis** [comment]
I agree that this would be useful. I thought we had addressed the issue (it should be shown in past issues)

**Comment by mrtind** [comment]
I can work on this one!

**Comment by alexellis** [comment]
Thanks @mrtind - what's your ETA for this change?

**Comment by alexellis** [comment]
Derek add label: duplicate

**Comment by mrtind** [comment]
Probably two days. I am not sure yet how faas-cli works and i need some time to check that out and in which places I should return 1.I looked into the code and saw that we return err but no os.Exit(1) in most of the places in commands/deploy.go

**Comment by alexellis** [comment]
If you return an error in the command it should be sufficient as long as it bubbles up. There's some discussion on the linked issue.

**Comment by alexellis** [comment]
@rgee0 bump

**Comment by mrtind** [comment]
@alexellis I was wondering on which status codes you want to exit 1 ? I made it to return 1 for codes 4XX and 5XX as stated by @kenfdev in the other issue?

**Comment by alexellis** [comment]
Non 2xx I would say. @rgee0?

Alex

**Comment by rgee0** [comment]
Review request acknowledged. Short on time / tech today.

If we’re being strict then >= 400 usually makes sense. However, I can’t think of a situation where we would expect, and handle, a 3xx in the CLI.

**Comment by alexellis** [comment]
Derek close: merged. @rimiti please give this a test now by building from master.

**Comment by alexellis** [comment]
Derek set milestone: 0.6.16
