### ISSUE TITLE
Self-signed cert: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by maiermic** [openfaas/faas-cli#444]
I'm running a OpenFaas gateway at https://faas.mysite.com and a Docker registry at https://docker-registry.mysite.com. I can build my function, push it, login to the registry and the gateway:

```bash
faas-cli build -f OpenFaas.yml
docker login docker-registry.mysite.com
faas-cli push -f OpenFaas.yml
faas-cli login --username user --password password
```

**OpenFaas.yml**

```yml
provider:
  name: faas
  gateway: https://faas.mysite.com

functions:
  function_name:
    lang: node
    handler: ./src
    image: docker-registry.mysite.com/function_name:1.0.0
    environment:
      ENV_REQUIRED_BY_FUNCTION: "has to be passed"
```

However, if I try to deploy I get a certificate error:

```bash
$ faas-cli deploy -f OpenFaas.yml
Deploying: function_name.

Is FaaS deployed? Do you need to specify the --gateway flag?
Put https://faas.mysite.com/system/functions: x509: certificate signed by unknown authority
```

I got a similar error for the Docker registry before I added the certificate `~/.docker/certs.d/docker-registry.mysite.com/ca.crt` (I'm running faas-cli on MacOS; on Linux `/etc/docker/certs.d/docker-registry.mysite.com/ca.crt`). Do I have to add the certificate somewhere elese for faas-cli? Why do I get a certificate error on deploy but not on login?

## Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
Commit: 999a6669148c30adeb64400609953cf59db2fb64
Version: 0.6.10
```
* Docker version ( Full output from: `docker version` ):
  * machine from which I'd like to deploy (MacOS)
  ```
  Client:
   Version:      18.03.1-ce
   API version:  1.37
   Go version:   go1.9.5
   Git commit:   9ee9f40
   Built:        Thu Apr 26 07:13:02 2018
   OS/Arch:      darwin/amd64
   Experimental: false
   Orchestrator: swarm

  Server:
   Engine:
    Version:      18.03.1-ce
    API version:  1.37 (minimum version 1.12)
    Go version:   go1.9.5
    Git commit:   9ee9f40
    Built:        Thu Apr 26 07:22:38 2018
    OS/Arch:      linux/amd64
    Experimental: true
  ```

  * machine of the gatewayy (Linux, Docker Swarm)

  ```
  Client:
   Version:      18.03.1-ce
   API version:  1.37
   Go version:   go1.9.5
   Git commit:   9ee9f40
   Built:        Thu Apr 26 07:17:20 2018
   OS/Arch:      linux/amd64
   Experimental: false
   Orchestrator: swarm

  Server:
   Engine:
    Version:      18.03.1-ce
    API version:  1.37 (minimum version 1.12)
    Go version:   go1.9.5
    Git commit:   9ee9f40
    Built:        Thu Apr 26 07:15:30 2018
    OS/Arch:      linux/amd64
    Experimental: false
  ```

**Comment by alexellis** [comment]
Hi,

It looks like you have a self-signed certificate in use where your certificate authority is not trusted by the server or the client.

Alex

**Comment by maiermic** [comment]
Hi Alex,
it is not a self-signed certificate. It is a wildcard certificate `*.mysite.com` that is used for `faas.mysite.com` and `docker-registry.mysite.com`.

Michael

**Comment by maiermic** [comment]
Which CA database is faas-cli using?

**Comment by alexellis** [comment]
It should use the one in your local system.

Can you link to the actual site so we can verify the cert?

Alex

**Comment by maiermic** [comment]
Sorry that it took that long. The actual site is https://faas.virality.de/

By the way, `curl` is working. I did a request using OpenFaaS Portal and used "copy as cURL" in Chrome Dev Tools to get the command.

The x509 error appears also on `invoke` (not only on `deploy`).

**Comment by alexellis** [comment]
I have a suspicion that your HTTPS certificate is not set up correctly.

When I try to access a non-existing sub-domain it gives a bad HTTP certificate error, try this for example:

https://test.virality.de/

```
curl https://test.virality.de/ -v
*   Trying 85.214.237.187...
* TCP_NODELAY set
* Connected to test.virality.de (85.214.237.187) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: self signed certificate
* stopped the pause stream!
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
```

**Comment by alexellis** [comment]
There's an error in the logs showing the issue:

> * SSL certificate problem: self signed certificate

I've just merged a feature into faas-cli which you should not use (fix the underlying issue instead), but will remove the error. It's called `--no-tls-verify`. To use the changes in master, do a git clone and run ./build.sh in the faas-cli repo.

Alex

**Comment by maiermic** [comment]
Not all domains are handled by the same server. `test.virality.de` is resolved as IP `85.214.237.187` and `faas.virality.de` is resolved as `188.172.243.59` by the DNS server. It shouldn't matter that the server of `85.214.237.187` is using a self signed certificate, should it?

**Comment by alexellis** [comment]
There appears to be something wrong with the certificate configuration or redirection. I can't reproduce the issue with a single HTTPS cert or wildcard card from LetsEncrypt with Nginx. 

Have you tried looking at issues in the Traefik repos? Not sure how to help you more at this point. Maybe someone else has a suggestion?

Alex

**Comment by maiermic** [comment]
I found the cause of the error: A misconfiguration of traefik. I didn't use a CA bundle. Error messages have led me quite astray.

@alexellis Thanks for your help.
