### ISSUE TITLE
Add a new command to display a function information 

### ISSUE THREAD

**Issue by viveksyngh** [openfaas/faas-cli#446]
Add a new command in CLI which will show information related to a function (same as what we display in Gateway UI for a function)

## Expected Behaviour

Have a new command with the name `describe`/`get`/`inspect` which can be invoked as

```
faas-cli  describe  <function_name> -g <gateway>

```

which will display function information like `Status`, `Replicas`, `Invocations`, `Image`, `URL`

## Current Behaviour

NA

## Possible Solution

Invoke gateway service to get details of a function and display it. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by burtonr** [comment]
How would the output look?

Would it be a table, similar to the `faas-cli list` command?

Or, should we go with a `json` object return? 
This may be more expected if using the `describe` command (as is the result with Swarm and K8s using that same command).

**Comment by burtonr** [comment]
Derek add label: proposal

**Comment by viveksyngh** [comment]
I think with table structure we will have the challenge in putting everything into one line in the terminal as `URL` length can be varied. 

We can display in `json` structure like `describe` or `inspect`.  

cc @alexellis

**Comment by rgee0** [comment]
What the user knows:
the gateway address in order to deploy, which can bee obtained from `—version`
the function name, which can also be found in the existing list command.

The url of a function is http://$OPENFAAS_URL/function/<function-name>. With a variation for async.

What is the problem we are trying to address here? Ultimately understanding that will drive the solution.

**Comment by alexellis** [comment]
I think this would act like the store and print in ASCII. Take a look at the store subcommand, there's something available like "info".

A table doesn't make sense because an argument would be necessary so we're only showing one item. Not sure what the idea about JSON was, but this is already available via the API.

**Comment by alexellis** [comment]
I think Vivek's original intent was to get a URL for a specific function and some other data that we hold. Kind of like an info/inspect/get function in Docker or kubectl. Is that about right?

**Comment by viveksyngh** [comment]
@alexellis Yes, Idea was to display the function URL and other information related to a function in CLI as we are displaying Gateway UI.  

When I was getting familiar with OpenFaaS, many times I forgot what is the URL to use to invoke the function using curl or any other client. I think having this information available in CLI for a particular function will help a new OpenFaaS user.

**Comment by alexellis** [comment]
@burtonr there's data you're showing which is not available on a deployed function. We can only show what's available within the API.

> When I was getting familiar with OpenFaaS, many times I forgot what is the URL to use to invoke the function using curl or any other client.

@viveksyngh do you know about the `faas-cli invoke` command?

Alex

**Comment by alexellis** [comment]
I think it'd be fine if someone wanted to work on this. Do we have any volunteers?

Alex

**Comment by viveksyngh** [comment]
I will work on this.

**Comment by viveksyngh** [comment]
Derek assign: me

**Comment by viveksyngh** [comment]
I will be working on it this weekend.
