### ISSUE TITLE
Registry auth with `-send-registry-auth` fails for nested images in custom registry (Gitlab)

### ISSUE THREAD

**Issue by johnmccabe** [openfaas/faas-cli#452]
## Expected Behaviour

It should be possible to use a private registry by setting the `-send-registry-auth` flag to extract an auth header from the docker credentials manager.

## Current Behaviour

This currently fails on Gitlab when using an image thats nested under the parent repo.

For example this works:

    registry.gitlab.com/johnmccabe/myfunctions

But this fails to find any credentials:

    registry.gitlab.com/johnmccabe/myfunctions/coolfn

Using `docker pull/push` etc all work as expected with the private registries.

## Possible Solution

Fix the getRegistryAuth domain extraction function in `commands/deploy.go`.

## Steps to Reproduce (for bugs)

1. Create a private repo in Gitlab, for example: `johnmccabe/test-registry`
2. Push an image nested under that repo, for example: `registry.gitlab.com/johnmccabe/test-registry/gitlabfn`
3. Ensure the image pushed above is deleted locally
4. Docker login to the gitlab repo
5. Attempt to deploy, you should see the function fail to pull the image (`docker service ls`).

## Context

Number of users have been encountering issues with custom registries.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 
```
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  6c28891cf648621ef120c802d9160cae7506b977
 version: 0.6.14

Gateway
 uri:     http://127.0.0.1:8080

Provider
 name:          faas-swarm
 orchestration: swarm
 version:       0.3.5
 sha:           b8cc399b5eadfb59956b8341a44ea3ba4acf1e7f
```

* Docker version ( Full output from: `docker version` ):
```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:12:05 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:20:16 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
OSX

* Link to your project or a code example to reproduce issue:
n/a, you need your own private creds

**Comment by johnmccabe** [comment]
@tarunmangukiya this *should* fix the issue for you on Gitlab, can you run this build of the cli on your Windows env and let us know please.

**Comment by johnmccabe** [comment]
@alexellis ^ do you have a K8s setup with a private registry to hand that you could sanity check this on.

**Comment by tarunmangukiya** [comment]
Thanks for opening an issue!

**Comment by alexellis** [comment]
Derek close: resolved & released
