### ISSUE TITLE
Question: Using multiple environments

### ISSUE THREAD

**Issue by tarunmangukiya** [openfaas/faas-cli#455]
Generally, we're deploying our functions to multiple environments, i.e. testing, staging, production, etc.
We use, different key, secrets i.e. AWS_KEY, AWS_SECRET, AWS_BUCKETS, and many more in our functions. It makes redundant to change them every time before I use `faas-deploy`.

## Current Behaviour
Every-time before I deploy to production/staging, I need to
- Change  `environment_file`
- Manually pass  `gateway` every time via `faas-cli`.

## Possible Solutions

1. Feature to override `stack.yml` with `stack.prod.yml` like we do with `docker-compose.yml`
2. Facility to use environment variables in `stack.yml`
3. Adding a facility to add common `environment_file` in `stack.yml` as I have around 20+ functions, and have added the same `env.yml` to each of them.

## Context

This will save time to pass them manually each time. Plus, in case of high number of functions, providing common environment file will be beneficial.

**Comment by alexellis** [comment]
Hi Tarun, if you have private data such as keys there is a feature for this called "secrets".

Providing each gateway URL is a separate environment, you can create your secrets in each environment and then just change the gateway URL without editing any YAML files.

i.e.

In staging and prod:

* Create secret `aws-s3-key` (use the respective values)
* Create function and add `- aws-s3-key` to `secrets`
* Deploy function to either environment specifying `--gateway https://staging.com` or `--gateway https:///prod.com`

Environmental variables really aren't suitable for this purpose.

There is the ability to use `environment_file` per function too, and it can be shared between functions for non-private data.

Hope this helps.

@stefanprodan may also have some thoughts on this.

**Comment by alexellis** [comment]
Derek close: suggestion given on GitHub & Slack
