### ISSUE TITLE
Feature: offer --tag option which includes branch name

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#463]
## Expected Behaviour

@stefanprodan has asked for extension to the new `--tag` flag which includes branch name as part of the Docker tag.

Given this stack.yml, branch: staging and SHA ef5b6

```
image: image-name:0.2
```

Produce this image name: `image-name:0.2-ef5b6-staging`

## Current Behaviour

Tag used from file, or if `--tag=sha` is given the short-SHA is appended to the tag.

Given this stack.yml and no options you get what you put in the file:

```
image: image-name:0.2
```

Given the same stack.yml and SHA ef5b6

It will produce this image name: `image-name:0.2-ef5b6`

## Possible Solution

Code needs to be extended in build/push/deploy commands to factor in the new mode, just do a code search for `schema.SHAFormat` to find all the places that need updating.

## Context

This should make it easier to enable people to use the Weave Cloud product to do continuous deployment.

**Comment by alexellis** [comment]
@stefanprodan if you'd like to add this feature it should be very easy now given the pre-work and tests done this morning.

**Comment by stefanprodan** [comment]
Yes but the branch name should be a prefix not suffix, instead of `image-name:0.2-ef5b6-staging` should be `image-name:0.2-staging-ef5b6`

**Comment by alexellis** [comment]
(I'm curious, why is that?)

**Comment by stefanprodan** [comment]
So you can define deployment policies like:
*  `glob:0.2-staging-*`  --> staging namespace
* `glob:0.2-master-*`  --> prod namespace

The CD flow I'm referring to is documented [here](https://github.com/stefanprodan/gitops-helm)

**Comment by alexellis** [comment]
What about a policy of: `glob:0.2-*-staging`?

**Comment by stefanprodan** [comment]
ThiswWill break if instead of the sha you'll be using sem ver since sem ver can have `-`

**Comment by alexellis** [comment]
Derek close: released
