### ISSUE TITLE
Feature: tell in store list what platform the image is built for

### ISSUE THREAD

**Issue by jukefr** [openfaas/faas-cli#467]
When a user runs
`faas-cli store list`

He gets back the available images.

I ran this command on my raspberry pi and tried 4/5 different images, but apparently they are not built for armhf architecture. 

Maybe there could be a way to differentiate between built platforms for store images ?

Now I can completely understand if the armhf support is simply a little side-project or a demo type feature, if you mainly target non armhf users than this won't be much of a problem.

**Comment by alexellis** [comment]
We have that for the UI, for the CLI I don't think we had a good way to determine the architecture. You can specify the URL for the arm JSON file. https://raw.githubusercontent.com/openfaas/store/master/store-armhf.json

**Comment by jukefr** [comment]
Since you do have a separation for architecture in your data (via urls) maybe you could simply run 
```
$ arch
x86_64
```
and maybe use that ?

**Comment by ivanayov** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
Hi, I could see how this could be confusing but creating a portable solution is not easy.

For `store deploy` on ARM you will have to pass the armhf raw-git URL right now.

Alex

**Comment by martindekov** [comment]
I think we already added platforms for `template store` why shouldn't we do the same with `store`? 

I see we have couple of `store-armhf.json` etc... containing different images with functions on the architectures

We can add `--platform` flag to `faas-cli template store list --platform armhf` and get the `store-armhf.json` etc.

Now we can do this if we find the link and manually paste `faas-cli template store list --url https://raw.githubusercontent.com/openfaas/store/master/store-armhf.json` which, to be honest I find inconvenient.

I would like to work on this once we set for solution, if the issue is not obsolete.

**Comment by alexellis** [comment]
> Now we can do this if we find the link and manually paste faas-cli template store list --url https://raw.githubusercontent.com/openfaas/store/master/store-armhf.json which, to be honest I find inconvenient.

It is inconvenient as a user experience.

For the UI code we bake-in the architecture at build-time for the function store. We could do the same via a compile-time variable for the faas-cli?

I would like to see 3-4 clearly-written ideas for this from the community. cc @rgee0 @burtonr 

Alex

**Comment by rgee0** [comment]
The CLI is a client which may run on a different architecture to the gateway/ui/functions. How would baking in a compile time variable help in this regard?

My view has always been one file for store.json and supported architectures becomes an attribute of the listed functions. The user could then filter on the target hardware through either a user supplied value or a gateway API derived equivalent.

Maybe multi arch images have a part to play here too.

**Comment by rgee0** [comment]
Ref: https://github.com/openfaas/faas/issues/429

**Comment by LucasRoesler** [comment]
I like the idea of adding `architectures` as an attribute in the `store.json`

**Comment by ivanayov** [comment]
I like the option with the `—platform` flag. This + `architectures` as an attribute would work well.

**Comment by burtonr** [comment]
I'll put another vote in for the `architectures` attribute and a `--platform` flag. That solution makes the most sense in my mind. 

We could then combine both `store*.json` files into one

**Comment by martindekov** [comment]
I saw in the code and currently the way we would implement the `--platform` flag would be to point to the different `store*.json` files and in the future if we combine the stores into one, we can change the implementation.

Or merge the `store*.json` files into one before implementing `--platform` so we don't do that twice if we are sure merging the files into one is a good idea in general.

**Comment by alexellis** [comment]
Derek close: duplicate https://github.com/openfaas/faas/issues/1099

**Comment by alexellis** [comment]
We'll track this via the main faas repo now. Thanks for all the comments.
