### ISSUE TITLE
Command store deploy still returns 0 when deploy failed

### ISSUE THREAD

**Issue by mrtind** [openfaas/faas-cli#473]
I referenced the return status 0 in this PR https://github.com/openfaas/faas-cli/pull/445. But that PR only fixed deploy command and didn't include store deploy.

## Expected Behaviour

Couple of cases pointed by @rgee0 

```
$ ../faas-cli store deploy Figlet

Is FaaS deployed? Do you need to specify the --gateway flag?
Put http://192.168.0.8/system/functions: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

Should return 1

```
../faas-cli-darwin store deploy Figlet

unauthorized access, run "faas-cli login" to setup authentication for this server
```

Should return 1

## Current Behaviour

Examples above return 0.

## Possible Solution

Bubble up the error like in deploy command.

## Steps to Reproduce (for bugs)

1.Deploy openfaas
2.```$ docker service scale func_gateway=0```
3.```$ faas-cli store deploy figlet```
4.```$ echo $?```

## Context

With time more functions will be added to the store and store deploy feature will be used more often
and some people may need proper return code for whatever reason. In the last PR couple
of issues were open for failed deploy with improper return code.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.6.15
* Docker version ( Full output from: `docker version` ):
18.03.1-ce
* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
FaaS-swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 16.04
* Link to your project or a code example to reproduce issue:
Steps to reproduce ^

**Comment by rgee0** [comment]
Derek close: fixed in #476

**Comment by rgee0** [comment]
@mrtind just for info, when referencing issues in PRs please try to use one of the keywords that Github looks for as that will enable Github to close the issue on merge.

Further info here: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by alexellis** [comment]
Can you so put "closes #number"?

**Comment by alexellis** [comment]
Derek set milestone: 0.6.16

**Comment by mrtind** [comment]
Yeah ok
