### ISSUE TITLE
`faas-cli build` fails for function with same directory for stack and handler file

### ISSUE THREAD

**Issue by viveksyngh** [openfaas/faas-cli#478]
`faas-cli build` fails for function when we have `stack.yml` and `handler` are in the same directory.
if we update the handler path to `.` in `stack.yml`

## Expected Behaviour

The build should pass successfully.

## Current Behaviour

It fails with below error.

```
[0] > Building kph-demo.
Clearing temporary build folder: ./build/kph-demo/
Preparing ./ ./build/kph-demo/function
Building: viveksyngh/kph-demo with python template. Please wait..
error checking context: 'lstat /Users/viveks/Repos/openfaas/functions/kph-demo/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/function/build/kph-demo/Dockerfile: file name too long'.
2018/07/26 18:07:28 ERROR - Could not execute command: [docker build -t viveksyngh/kph-demo .]
```

## Steps to Reproduce (for bugs)

1. create a new function using `faas-cli new`
2. Move function .yml file to function folder
3. Edit handler in .yml file to `.`
4. `faas-cli build -f <file_name.yml`

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 

```
CLI:
 commit:  6c28891cf648621ef120c802d9160cae7506b977
 version: 0.6.14

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.8.7
 sha:     9512f09d2b4b8d28dcc947e1838bc08968e3c8ca
 commit:  Refactor scaling to use existing code


Provider
 name:          openfaas-operator
 orchestration: kubernetes
 version:       0.8.0
 sha:           d0c4d843516accd1cce821d6c2e41d8acee9023a
```
* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by rgee0** [comment]
I believe the cause to be losing the recursion flag from the copyFiles method. As `build` is also written to the current directory the recursion traverses this.

**Comment by viveksyngh** [comment]
Yeah, We should exclude `build` and `template` directory when we are copying files to `build` folder. let me know what do you think?

**Comment by rgee0** [comment]
My thinking at the moment is that we should discover what needs to be copied - traverse the filesystem from the provided handler point - prior to commencing any copying activity.

I also think that how we can exclude `build` and `template` directories also needs some careful consideration.

**Comment by viveksyngh** [comment]
Derek add label: bug

**Comment by LucasRoesler** [comment]
I agree with @rgee0, to keep the current behavior and to supper the handler being in the same folder as the stack, we would need to traverse and index at least the current directory, if not the whole folder, and then copy the contents.  Perhaps [using Glob](https://golang.org/pkg/path/filepath/#Glob) would help?  Either way the fix will probably need to completely replace the current copy methods. A proper implementation probably needs to add an "exclude" list as well.

Alternatively, and a bit contrarian, do we even want to allow this behavior? Should the stack live next to the handler code? Should we require that the handler code live in a subfolder? At the minimum, our template system strongly encourages subfolders, when you use `faas-cli new` the content is put in a folder.  This allows for clear separation of concerns and allows the project to grow and add more functions without colliding.  We could keep the current copy logic but add a pre-validation step to test that we aren't trying to copy the root folder.

**Comment by LucasRoesler** [comment]
What if we move the openfaas `build` folder to the os level temp folder using https://golang.org/pkg/io/ioutil/#TempDir ? 

Instead of changing `CopyFiles` we change `createBuildTemplate` and `dockerBuildFolder`.  Doing this means we aren't potentially modifying the directory that we are iterating over.  

I prefer this solution because it doesn't introduce any additional assumptions about what should be allowed or how the folder is structured, we don't need to skip or ignore any special files/folders.

**Comment by LucasRoesler** [comment]
This is a classic issue in iteration, you should _not_ mutate the thing you are iterating over, in this case the filesystem.  

Adding an ignore for certain folders/files might just cause a new bug. Can we really assume that we should ignore the `build` folder? It is not unreasonable that someone would create a folder called `build` to contain content specifically for their Docker build process.   Similarly for `template`, there could be some static content in that folder that they want to embed into the function. 

 I would prefer not to add rules for how you structure your project, if we don't have to.

**Comment by ivanayov** [comment]
We could move to `.build` and `.template`. This way we can distinguish the contents that belong to the framework from the user's function code.

**Comment by ivanayov** [comment]
Derek remove label: bug

**Comment by ivanayov** [comment]
Derek add label: review

**Comment by LucasRoesler** [comment]
We could do that to make the distinction clearer.  

I still think that modifying the project structure with temporary build objects is messy.  Ideally, we should only write content into the project when we expect the user to save that content, e.g. only if they should subsequently commit that content.  I can see an argument for committing the `template` folder, but not so much for the `build` folder.   Currently the biggest pro for keeping the `build` folder in the project is that it makes it easier to debug that build if it fails. But this could also be achieved by telling the user where the temp build dir is when a failure happens. 


If we are going to implement a filter, I would still recommend doing it in the `createBuildTemplate` and the `dockerBuildFolder`, replacing `CopyFiles(handler, functionPath)` with something like 

```go
infos, readErr := ioutil.ReadDir(handler)
if readErr != nil {
    fmt.Printf("Error reading the handler %s - %s.\n", handler, readErr.Err())
}

for _, info := range infos {
    switch info.Name() {
    case ".build":
        fmt.Println("Skipping \".build\" folder")
        continue
    default:
        CopyFiles(info.Name(), functionPath)
    }
}
```

this avoids needing to pass a allow/skip list into the `CopyFiles` and only skips in the project root.  Deciding when to use the and when to stop using the allow/skip list inside of `CopyFiles` is messy.  The switch syntax also makes it easy to extend the list and behavior.

**Comment by viveksyngh** [comment]
I think this is a nice approach to avoid copying the `build` directory from the root folder. I have updated the PR to use this approach.
