### ISSUE TITLE
Should faas-cli new honour $OPENFAAS_URL?

### ISSUE THREAD

**Issue by rgee0** [openfaas/faas-cli#482]
Not sure if this is actually by design as $OPENFAAS_URL it would be honoured during deploy.

## Expected Behaviour
If $OPENFAAS_URL is set then should the provider gateway value in the function's yaml file represent this value rather than favouring the default gateway?

## Current Behaviour
```
provider:
  name: faas
  gateway: http://127.0.0.1:8080
```

## Possible Solution

Update `new` so it follows a pattern similar to that of other verbs

## Steps to Reproduce (for bugs)
1. `export OPENFAAS_URL=http://127.0.0.1:31112`
2. `faas-cli new --lang=go function-name`
3.  `cat function-name.yml`
4.  Find:
```
provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  function-name:
    lang: go
    handler: ./function-name
    image: function-name
```

## Context
Noticed someone on social media commenting about updating their yaml files for k8s.  Before suggesting $OPENFAAS_URL checked it worked as expected.

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
$ faas version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  6c28891cf648621ef120c802d9160cae7506b977
 version: 0.6.14
```
* Docker version ( Full output from: `docker version` ):
```
$ docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:26 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```
* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

* Link to your project or a code example to reproduce issue:
N/A - steps above

**Comment by alexellis** [comment]
Yes, this is a miss and should be factored in.

@martindekov please can you work on this?

Alex

**Comment by martindekov** [comment]
Yeah I'm on it.
