### ISSUE TITLE
Add `--annotation` flag to deploy

### ISSUE THREAD

**Issue by ivanayov** [openfaas/faas-cli#498]
At the moment annotations are supported only via YAML.

This doesn't allow applying them to functions deployed from store, f.e.
```
faas store deploy figlet --annotation topic="faas-request"
```

Documentation update is also required. It should follow up [docs#54](https://github.com/openfaas/docs/issues/54)

For reference [faas-swarm#28](https://github.com/openfaas/faas-swarm/pull/28)

**Comment by alexellis** [comment]
This could be useful for deploying from the store. @martindekov would you be able to work on this? Assign it to yourself with Derek if you want to pick it up.

**Comment by martindekov** [comment]
Derek assign: me
