### ISSUE TITLE
Feature: Template pull override

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#502]
## Expected Behaviour

Provide an override for where to pull templates from i.e. `OPENFAAS_TEMPLATES_URL`, if not set we'd use https://github.com/openfaas/templates, but it could be set to https://internal-gitlab.com/alexellis/suse-golden-images for instance.

## Current Behaviour

You can pass this as a parameter, but allowing an override would mean a user could customize this as a one-time thing in their bash profile.

## Possible Solution

See how OPENFAAS_URL is used and copy the approach

**Comment by martindekov** [comment]
@s8sg If you are not currently working on this can I take the issue?

**Comment by martindekov** [comment]
Of course @s8sg !

**Comment by rgee0** [comment]
Derek close: Fixed in #515
