### ISSUE TITLE
Invoke failed with header containing several = symbols

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#509]
## Expected Behaviour

This should work:

```
$ echo | faas-cli invoke figlet --header "X-Hub-Signature"="sha1=shashashaebaf43"
The --header or -H flag must take the form of key=value
```

## Current Behaviour

Invoke failed to parse the line properly

## Possible Solution

Investigate and fix.

## Steps to Reproduce (for bugs)

1. Run command given above
2.
3.
4.

## Context

It's preventing me from triggering openfaas-cloud events via the CLI with an additional header I need to use. 

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

0.7.0

**Comment by LucasRoesler** [comment]
I am away from my computer, but should 

`"X-Hub-Signature"="sha1=shashashaebaf43"`

be

`X-Hub-Signature="sha1=shashashaebaf43"`

**Comment by alexellis** [comment]
Both give the same result. 

```
echo | faas-cli invoke figlet --header X-Hub-Signature="sha1=shashashaebaf43"
The --header or -H flag must take the form of key=value
```

**Comment by rgee0** [comment]
https://github.com/openfaas/faas-cli/blob/dbb4c78462f807b2eed6cda202bfb6eecb632e95/proxy/invoke.go#L129-L132

**Comment by warunsl** [comment]
Is the parser expected to handle `=` in the keys as well?

**Comment by viveksyngh** [comment]
Derek assign: me

**Comment by alexellis** [comment]
@warunsl looks like Vivek is taking it. Please can you join Slack and I'll help to find something else for you to pick up. Don't worry, there's plenty! https://docs.openfaas.com/community
