### ISSUE TITLE
Test mixed-case usernames

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#511]
We need to test mixed-case usernames end-to-end including:

* of-router (using wildcard DNS)

No instructions exist for Swarm, just a YAML file for Kubernetes, so update the docs/README.md too

* UI dashboard
* GitHub push events

You'll need a second GitHub account with a MixedCase username (don't rename your existing one) and then add it to the official CUSTOMERS list or turn `validate_customers` off.

**Comment by martindekov** [comment]
I created mixed case username `MartinDekovWat` and deployed `goforfun` on the cloud the function name is `MartinDekovWat-goforfun` in the URL the name is mentioned with whatever case you wrote and its accepted e.i. `../overview?user=MartinDekovWat` == `../overview?user=mArTiNdEkOvWaT` == ... haven't tested the of-router yet but will start doing it now

**Comment by martindekov** [comment]
The router gives me 502 I don't yet know why. But for now I see in the code the function redirects me to the `../function/<name_of_function_in_ui>` my `<name_of_function_in_ui>` name is `MartinDekovWat-goforfun` which means that I wont be able to invoke in the URL like `MartinDekovWat.team-serverless.xyz/goforfun` I think you cant have case sensitive subdomains? Maybe we should rename functions to always be prefixed with lowercase github usernames e.g. `martindekovwat-goforfun` instead of the original name? I don't think people will be concerned with how their name is displayed. I hope I am following the logic here. Also the error reads 
```
$ curl -H "Host: MartinDekovWat.team-serverless.xyz" localhost:8081/goforfun
Proxying to: https://md-gw.team-serverless.xyz/function/MartinDekovWat-goforfun
Upstream https://md-gw.team-serverless.xyz/function/MartinDekovWat-goforfun status: 502
Get https://md-gw.team-serverless.xyz/function/MartinDekovWat-goforfun: context deadline exceeded
```

**Comment by alexellis** [comment]
Hi @martindekov this is all part of the task (please don't move off the task if you have questions, but see it through until completed.. Why? Because we'll end up with lots of half-finished work-in-progress) cc @burtonr 

We shouldn't mutate (change) the source of truth.

Please come up with 2-3 suggestions on how to proceed.

Alex

**Comment by alexellis** [comment]
If your function is deployed with the DNS entry of: `MartinDekovWat-goforfun` and we're mapping from a  `Host: ` entry then that host entry will always be lowercase i.e. `martindekovwat`. This means that the proxy will need to convert from  `martindekovwat` to `MartinDekovWat-goforfun`.

The simplest way I think you could do that is by querying the back-end API to match the function. This will add some latency, but not a lot especially if it's cached in-memory and periodically refreshed.

The other option is to mutate the name of the function when deployed so that the username prefix is lower-case. I'm not sure I like that option but it seems like a lot less work.

**Comment by martindekov** [comment]
Sorry I thought that I should only report my tests will proceed to work on the task

**Comment by alexellis** [comment]
I think this is actually on the wrong repo too.. (which is my fault)

**Comment by alexellis** [comment]
Derek close: wrong repo

**Comment by alexellis** [comment]
I wasn’t clear that (we as a team) need to fix up what is wrong or propose how to do so.
