### ISSUE TITLE
Add --sign flag for faas-cli invoke

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#512]
## Expected Behaviour

We should be able to enable HMAC on `faas-cli invoke` so that requests can be signed automatically with a symmetric key. This will help with testing GitHub integrations.

```
cat payload.json | faas-cli invoke --sign "X-GitHub-Event" --key "$KEY" --algorithm "sha1"
```

`sha1` should be a default option

This would add a header: `X-GitHub-Event: sha1=digest_of_body-bytes`

## Current Behaviour

Needs to be done manually, or replayed via GitHub UI

## Possible Solution

Make use of alexellis/hmac package for Signing.

**Comment by martindekov** [comment]
What if I want to append couple of headers? Currently I will just `... | ... invoke ... -H "..." -H "..." ...`. In the example I will need to `... --sign "<some header>" --key "<key for header>" --algorithm "<algorithm for  header>" to append single header. I was wondering isn't it a good idea to use existing header functionality and check if algorithm exists in the key e.g. `"header"="sha1=key_with_sha_algorithm_here"` `"header"="just_a_random_key_here"` and to determine by the first values of the key.It just seems that appending single header the way above is a lot of writing. Would there be any problems with that approach?

**Comment by warunsl** [comment]
@martindekov If I understand this correctly, this is what you mean, right? 
```
faas-cli invoke ... -H X-GitHub-Event="<algorithm>=<key-to-use>"
```
In that case, we would have to think of other valid cases for using a header of the form `faas-cli invoke ... -H Header="<key>=<value>"` where the user does not want to sign the content. Having a `--sign` expresses an intent that the user wants to sign the content?

**Comment by alexellis** [comment]
I'm not sure what is unclear in the issue/task.

What needs clarification for you guys?

**Comment by alexellis** [comment]
@warunsl please work on the implementation, how long do you think it will take?

Alex

**Comment by martindekov** [comment]
@warunsl We discussed and for the purposes we need the change go with Alex's approach.

**Comment by alexellis** [comment]
Hi @warunsl,

This has been inactive for 13 days so I'm going to suggest that @ivanayov or @martindekov pick this up. Feel free to pick up other issues as you have availability to work on them. 

Alex

**Comment by warunsl** [comment]
Should `sign` be a sub command of `invoke` and the usage be something like:
`faas-cli invoke echo --sign --signheader "X-GitHub-Event" --key "key" --algorithm "sha1"`

Having it they way suggested in PR: `faas-cli invoke echo --sign "X-GitHub-Event" --key "key" --algorithm "sha1"` would involve checking for all possibilities:
1. `--sign` present but `--key` not present --> Error and print usage.
2. `--key` present but no `--sign`  --> Error and print usage.
3. `--algorithm` present but not `--sign`  --> Error and print usage.

**Comment by rgee0** [comment]
I'm not entirely clear on the distinction here.  I do think that `--sign` with `--signheader` is potentially less intuitive and introduces some redundancy into the command.

I may be over-simplifying but in my mind all three possibilities would print the same usage output and since all three are required then its a single check against the two flags that don't have a default value.

```
if(len(sign)==0 || len(key)==0){
 return err
}
```

* Valid
```
$ faas-cli invoke echo --sign "X-GitHub-Event" --key "key" --algorithm "sha1"
```

* Valid
```
$ faas-cli invoke echo --sign "X-GitHub-Event" --key "key"
```

* Invalid
```
$ faas-cli invoke echo --sign "X-GitHub-Event" --algorithm "sha1"
Error: signing requires both --sign <header-value> and --key <key-value>
```

* Invalid
```
$ faas-cli invoke echo --key "key" --algorithm "sha1"
Error: signing requires both --sign <header-value> and --key <key-value>
```

* Invalid
```
$ faas-cli invoke echo --sign "X-GitHub-Event"
Error: signing requires both --sign <header-value> and --key <key-value>
```

* Invalid
```
$ faas-cli invoke echo --key "key"
Error: signing requires both --sign <header-value> and --key <key-value>
```

I wonder if we could pre-process these flags and pop them into the existing header handling facilities once the digest has been generated?

**Comment by alexellis** [comment]
`--sign` is fine for me like in the original issue.

@warunsl @rgee0 

How close are we to a PR with this? Are there any questions that need an answer or input from me?

**Comment by alexellis** [comment]
Yes that's fine for what we need it for and happy to omit `--algorithm` / `-a` for the initial pass or lock it down to only `sha1`
