### ISSUE TITLE
faas-cli up command issue (Please provide a valid --image name)

### ISSUE THREAD

**Issue by stayingcool** [openfaas/faas-cli#516]
Trying to use the new command `up` from [blog - tip 5](https://www.openfaas.com/blog/five-cli-tips/) throws this below message:
**`# faas-cli up`**
`Please provide a valid --image name for your Docker image`

## Expected Behaviour
I expected that the up command would just run fine without asking for anything more.

## Current Behaviour
Look at the above, it is asking for --image name.

## Steps to Reproduce (for bugs)
1. Just run the `up` command from the function folder where we have yaml file.

## Context
Trying to benefit from the new feature added in faas-cli v0.7.0

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:
 commit:  4fb0bbfb3546edf5f8b8e1874e88c0264c708f16
 version: 0.7.0
```
* Docker version ( Full output from: `docker version` ):
```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:26 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```
* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
Minikube

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

**Comment by rgee0** [comment]
Is your yaml file named `stack.yml`?  if it isn't then you'll need to pass in `-f <yaml-file>`.

**Comment by stayingcool** [comment]
No. It is as follows:

**```# ls```**
```
build			create-meeting		create-meeting.yml	template
```

**Comment by rgee0** [comment]
You've a choice:

```
mv create-meeting.yml stack.yml && faas-cli up
```
or
```
faas-cli up -f create-meeting.yml
```

**Comment by ivanayov** [comment]
Derek add label: support

**Comment by stayingcool** [comment]
Thanks @rgee0 

I'll ensure to use -f flag.
`faas-cli up -f create-meeting.yml`

I'm new to open-faas, anyhow getting a hang of certain things now. Thank you!
