### ISSUE TITLE
faas-cli invoke does not honour http_proxy

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#517]
## Expected Behaviour

HTTP Proxy should be set / honoured with faas-cli invoke

## Current Behaviour

It's not due to the Transport getting overwritten in proxy/invoke.go

```
	var timeout *time.Duration
	client := MakeHTTPClient(timeout, tlsInsecure)
	tr := &http.Transport{
		DisableKeepAlives: false,
		TLSClientConfig:   &tls.Config{InsecureSkipVerify: tlsInsecure},
		
	}
	client.Transport = tr
```

## Steps to Reproduce (for bugs)

1. Run `nc -l 3128`
2 `faas store deploy figlet`
2. `http_proxy=127.0.0.1:3128 faas-cli invoke figlet --gateway http://IP:port` - in this step the gateway must be accessed with the IP of your ethernet adapter, not with 127.0.0.1

When fixed you will see a HTTP request to the netcat window.

**Comment by alexellis** [comment]
@affix this regression may have been introduced from the changes made to add tlsinsecure

**Comment by affix** [comment]
I will fix this through the week :)
