### ISSUE TITLE
Proxy the version command's HTTP calls

### ISSUE THREAD

**Issue by burtonr** [openfaas/faas-cli#519]
Currently, all the commands are being proxied to call the gateway keeping all the http code in one place, while the commands are focused on processing the requests and displaying the information.

The `version` command is missing the proxy.

## Expected Behaviour

Expect `version` command to not include any http dependencies or calls. Those should be migrated to the proxy

## Current Behaviour

The `version` command includes all the HTTP calls as well as processing and displaying information

## Possible Solution

Create new `version.go` and `version_test.go` files in the `proxy` package. Move all the HTTP calls from the version command to the version proxy.

## Steps to Reproduce (for bugs)

N/A (not a bug... per se)

## Context

We are adding auth to all the `/system/` calls for additional security (specifically with Swarm) and will be needing to add `SetAuth()` to the version command. This command is part of the `proxy` package

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:
 commit:  b7ba9a60dc2cf19965a562fb653e6c1cab03e0ef
 version: 0.7.1
```
* Docker version ( Full output from: `docker version` ):
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:25:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:27 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
Swarm - FaaS-Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux - Ubuntu 18.04
* Link to your project or a code example to reproduce issue:
N/A

**Comment by viveksyngh** [comment]
Derek: Assign me
