### ISSUE TITLE
Task: Test templating during CI

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#527]
## Task:

Create a new function in a language such as python3 during CI and test that it works. Do not use the default handler, this must be overridden with some custom code to prove the templating engine is working end to end.

## Work:

Write a bash script to be called during CI to do the following:

- create a function using a template
- override the default message or handler code
- build using the cli
- run using Docker (not faas-cli deploy) with a set port
- access the port to make sure you get the correct value back

## Status

This is high priority because we had a regression last week in one of the CLI versions.

**Comment by ivanayov** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Derek close: resolved
