### ISSUE TITLE
describe verb should display annotations/labels

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#533]
## Expected Behaviour

describe verb should display annotations/labels

## Current Behaviour

It shows some data, but we have more available.

## Possible Solution

Suggest text output for how things will look and work with core contributor @rgee0 before raising PR.  

## Steps to Reproduce (for bugs)

1. `faas-cli store deploy nodeinfo --label label=value --annotation annotation=value`
2. `faas-cli describe nodeinfo`

**Comment by viveksyngh** [comment]
Derek assign: me
