### ISSUE TITLE
User prefix from environment in ci pipeline 

### ISSUE THREAD

**Issue by Rasarts** [openfaas/faas-cli#536]
For ci pipeline in gitlab I use environment variables and want to push image to two different docker registry.

## Expected Behaviour

I can push some commit to repository, after successful pipeline I can change $CI_REGISTRY_USER environment variable and restart last build stage for push image to other docker registry.

## Current Behaviour

I use this [.gitlab-ci.yml](https://gist.github.com/Rasarts/cfa48ebcaf63817d84ff6ff8f2c9b37d). In build section I try create new .yaml for build image with some user:
```yaml
  - faas-cli new $CI_PROJECT_NAME --lang go --prefix=$CI_REGISTRY_USER
```
Error: 
```bash
Folder: some-function-name already exists
```

Or, if I try add --image like that:

```bash
 - faas-cli build -f ./$CI_PROJECT_NAME.yml  --image=$CI_REGISTRY_USER/$CI_PROJECT_NAME
  - faas-cli build -f ./$CI_PROJECT_NAME.yml
  - docker push $CI_REGISTRY/$CI_REGISTRY_IMAGE
```

I get:
```bash
The push refers to repository [docker.io/some-name/some-project-name]
An image does not exist locally with the tag: some-name/some-project-name
```

## Possible Solution

1) override option:
``` bash
 faas-cli new $CI_PROJECT_NAME --lang go --prefix=$CI_REGISTRY_USER --override
```

2) image-tag option:
```bash
faas-cli build -f ./$CI_PROJECT_NAME.yml  --image-tag=$CI_REGISTRY_USER/$CI_PROJECT_NAME
```
## Steps to Reproduce (for bugs)

1. faas-cli new --lang go --prefix=some-user
2. add gitlab-ci.yml
3. add environment variables in ci pipeline settings
4. commit to repository

## Context

I want push images to open docker registry and some images to private registry.
I try use sed for change .yaml:
```yaml
- sed -i 's/\(.*image:.*\)/image: $CI_REGISTRY_IMAGE/g' $CI_PROJECT_NAME.yml
```
yaml-cli with nodejs:
```yaml
 apk add --no-cache nodejs npm
  - npm install -g yaml-cli
  - yaml set $CI_PROJECT_NAME.yml functions.$CI_PROJECT_NAME.image $CI_REGISTRY_IMAGE | >> $CI_PROJECT_NAME.yml

```

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:
 commit:  dcddef2ae92880f50444103963408451abe82cc4
 version: 0.7.5
```

* Docker version ( Full output from: `docker version` ):
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:20:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
Kubernetes (but it not important)

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

* Link to your project or a code example to reproduce issue:
https://gist.github.com/Rasarts/cfa48ebcaf63817d84ff6ff8f2c9b37d

**Comment by ivanayov** [comment]
The CLI does not support changing image name for the moment, but you can simplify by using 
`docker tag old-image-prefix/image-name:verision new-image-prefix/image-name:version`

If this is the use-case, you don’t need to build twice, nor to create the function twice.

**Comment by ivanayov** [comment]
@Rasarts did this work for you?

**Comment by Rasarts** [comment]
> @Rasarts did this work for you?

Yes. I understand, now. It's worked, thx.

**Comment by ivanayov** [comment]
Derek close
