### ISSUE TITLE
Issue with `faas-cli new --append` - overwrites environmental variables and secrets

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#543]
Issue with `faas-cli new --append` - overwrites environmental variables and secrets

## Expected Behaviour

```
faas-cli new --lang node test
mv test.yml stack.yml
```

Edit test and give it some env-vars or secrets

```
faas-cli new --node test1 --apend=stack.yml
```

Env-vars and all other configuration for `test` should remain.

## Current Behaviour

They're getting removed.

## Context

Confusing for users

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

```
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  dcddef2ae92880f50444103963408451abe82cc4
 version: 0.7.5
Error with YAML file
```

**Comment by alexellis** [comment]
I'd like an existing faas-cli contributor to look at this issue (not a Hacktoberfest issue)

Alex

**Comment by rgee0** [comment]
Still investigating, but I think the following could be implicated:

https://github.com/openfaas/faas-cli/blob/517db31170a099e96701987f96c247109f5c1e70/commands/new_function.go#L167-L180

**Comment by alexellis** [comment]
Good detective work. In an ideal world we now create a failing test in a branch to show the behaviour.

**Comment by rgee0** [comment]
Confirmed.  The template doesn't parse out the full set of attributes from the Function struct when iterating the existing set of services.
This will impact more than just `environment` & `secrets`

**Comment by rgee0** [comment]
Derek assign: me

**Comment by rgee0** [comment]
> Good detective work. In an ideal world we now create a failing test in a branch to show the behaviour.

See PR #544

**Comment by alexellis** [comment]
I originally pushed back on us re-writing the file in favour of appending to the file. Re-writing removes comments and any other custom meta-data that users may want.

Was there any discussion in the history / PRs as to why we went for re-writing the whole file?

**Comment by rgee0** [comment]
Took some tracking down as there were multiple PRs on this.  The story starts in #141, where it's agreed to append.

Then the feature is moved over to #213 which never saw the light of day as it was superseded by #301.

#301 took the existing file and appended to it.  Then #357 adds some deduplication to the functionality introduced in #301, so that files cannot contain multiple functions with the same name.

It looks like #485 may have introduced a change in nature to the append feature.

**Comment by alexellis** [comment]
Good detective work
