### ISSUE TITLE
Inconsistent application of secrets when multiple functions are deployed

### ISSUE THREAD

**Issue by rgee0** [openfaas/faas-cli#557]
## Expected Behaviour
Each deploy against a given `stack.yml` should be deterministic in terms of access to secrets.

## Current Behaviour
There are a couple of behaviours that manifest, which are discussed in detail in #402.  Both are related to the CLI collecting secrets cumulatively.

1) If a secret that is detailed in the `stack.yml` is missing from the orchestrator then the deploy will fail at different points on each run.  This will be difficult for a user to reproduce / understand / debug.

* Example

A stack file has 100 functions detailed. 50 of them have a unique secret specified. The remaining 50 have no secret. One of the secrets hasnt been added to the chosen orchestrator.

The first run of faas-cli deploy sees 10 functions deployed. All 10 are from the set with secrets so fn1 has one secret and fn10 has 10 secrets. The attempted 11th function is the one with the missing secret. The set of secrets now contains the missing secret which causes the remaining 90 functions to all fail, including those without a secret defined.

The second run of faas-cli deploy shows entirely different behaviour without anything being changed in my config. This time I see 50 secretless functions deployed and fn51 is the one with the missing secret. The remaining 50 fns will not deploy.

The third run of faas-cli deploy, again with no changes to my config shows 49 of my functions with secrets deployed. The 50th is the one with the erroneous secret. It fails and so do the 50 secretless functions.

Running a fourth time sees the missing secret function arrive last so I find myself with 99 functions deployed.

2) If a secret that is required by a function is incorrectly omitted from the `stack.yml` the function will successfully deploy and may perform correctly **if** a function deployed earlier in the deploy action had the omitted secret specified.  The same set of functions will perform correctly on some occasions and on others will not; this will be difficult for a user to reproduce / understand / debug.

* Example

Imagine two functions that both make use of `secret1`, `secret2` & `secret3` and the incorrectly specified pseudo-yaml:
```
fn1:
secrets:
 - secret1
 - secret2
fn2:
secrets:
 - secret1
 - secret2
 - secret3
```
It's incorrect as `fn1` should have the same secrets specified as `fn2`.

On the first deploy `fn2` is processed first which means the CLI secrets slice will consequently contain secrets 1-3, which are subsequently mounted into `fn1` when it is deployed.

On a different deploy the opposite is true and `fn1` comes first. The function will deploy because `secret1` and `secret2` exist within the orchestrator, but the function code will barf when it encounters the reference to `secret3` which hasn't been mounted.

Scaling this to a dozen or so functions and there stands a good chance that a failure wont be experienced immediately.

## Possible Solution
There are two causal factors are:

1. Deploy iterates a map which doesn't retain an order.
2. Secrets are cumulative so which secrets are applied depends on where they arrive in the order.

In order to fix we could:

1. Sort the functions so that deploying the same `stack.yml` results in the functions being deployed in the same order each time by parsing `services.Functions` into a sortable data structure prior to iterating/ranging the functions here:

https://github.com/openfaas/faas-cli/blob/772de4eafc1fe050582644e478ccdc75db8ade98/commands/deploy.go#L167

2. Only mount secrets into a function if they are specified in the `stack.yml` function definition.  The cumulative effect is generated here:

https://github.com/openfaas/faas-cli/blob/772de4eafc1fe050582644e478ccdc75db8ade98/commands/deploy.go#L179-L181

## Context
A deployment with a subtly misconfigured `stack.yml` would successfully deploy by virtue of a favourable ordering of functions being encountered.  It would then fail on a later deploy without any changes to any of the system config.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
$ faas version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  70ebebb71f015f4edb0c3e1f03ef3d262b1d84f6
 version: 0.7.7
```
* Docker version ( Full output from: `docker version` ):
```
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```
* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

**Comment by alexellis** [comment]
Great write-up and analysis here.

Perhaps on the line above here (the loop) we could create a new slice and use that to merge each time so that we don't get this cumulative effect?

https://github.com/openfaas/faas-cli/blob/772de4eafc1fe050582644e478ccdc75db8ade98/commands/deploy.go#L167

**Comment by rgee0** [comment]
That was along the lines of what I was thinking.  Initialise a new slice per function and append any deploy flag secrets specified.

I think both fixes could be relatively straight-forward.

**Comment by alexellis** [comment]
For the deterministic ordering for processing the functions - I think there are pros and cons to that, but for the slice per function I think we should do this right away. Do you want to work on it?

**Comment by rgee0** [comment]
Derek assign: me
