### ISSUE TITLE
faas-cli - separate out stdout and stderr stream

### ISSUE THREAD

**Issue by lucidprogrammer** [openfaas/faas-cli#572]
If there was a way to get the error stream separately while using faas-cli deploy, it could have been greatly helpful. Ideally separate out the stdout and stderr. Then its easy to check status of automatic deployments and do appropriate actions.

**Comment by alexellis** [comment]
Hi @lucidprogrammer thanks for your feedback.

I believe you should be able to look at the exit code ascertain whether there was an error a deployment time. Cc @ivanayov 

Alex

**Comment by ivanayov** [comment]
Hi @lucidprogrammer 

You can find instructions for that here: https://github.com/openfaas/workshop/blob/master/lab4.md#making-use-of-logging

**Comment by alexellis** [comment]
( @ivanayov this issue is about deployment, via the CLI not about invoking the function. )

**Comment by alexellis** [comment]
@lucidprogrammer did this help?

```
$ faas-cli deploy
To deploy a function give --yaml/-f or a --image and --name flag

$ echo $?
1

# Or

if [ ! $? = 0 ] ;
then
    echo "Deployment failed"
fi
```

**Comment by lucidprogrammer** [comment]
@alexellis thank you for the response and really like this project and using this heavily. can work with exit code, that's fine. Thank you
