### ISSUE TITLE
Allow pinning of templates to version via SHA/branch or tag (release)

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#573]
## Expected Behaviour

I should be able to pin a template to a specific version via SHA/branch or tag (release) so that I can control my build pipeline and keep it reproducible.

## Current Behaviour

I can clone and checkout a templates repo manually, but not via `faas-cli template pull`.

## Possible Solution

```
faas-cli template pull https://cdn.com/repo.git#0.1.0

faas-cli template pull https://cdn.com/repo.git#dev

faas-cli template pull https://cdn.com/repo.git#d22af7cf74b7e24b37f46f8c60cb912751e93eab
```

If no `#` is given then the behaviour should default to the current functionality.

**Comment by alexellis** [comment]
cc @LucasRoesler who wrote the original code

**Comment by LucasRoesler** [comment]
`dep` uses this format with an `@` instead of `#`  `dep ensure -add github.com/pkg/foo@^1.0.1` 

NPM also uses the same format.  Should we also use that?

**Comment by alexellis** [comment]
Sounds good to me
