### ISSUE TITLE
Refactor TLS warning into const

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#581]
## Expected Behaviour

The following string is repeated in several places, especially when we merge all the remaining secrets features such as #580 

```
"WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
```

## Possible Solution

We should extract these messages into a const within the package they live in. If they live in both, then maybe they should go in a common existing package?

**Comment by viveksyngh** [comment]
Like this there are few more error messages that we can refactor, they are mostly part of the proxy functions.

**Comment by mario-mazo** [comment]
I would like to take this one
