### ISSUE TITLE
Bump brew chart to 0.8.3

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#584]
We need someone to bump the brew chart to 0.8.3 to include the secrets work

Instructions are in or available via the README.md file.

@rgee0 normally does this, but anyone should be able to follow the instructions.

Alex

**Comment by alexellis** [comment]
Instructions: https://github.com/openfaas/faas-cli/blob/master/CONTRIBUTING.md#how-to-update-the-brew-formula

**Comment by recollir** [comment]
Can be closed. I just saw that the chart is already on 0.8.3.

**Comment by rgee0** [comment]
Derek close: [Already completed](https://github.com/Homebrew/homebrew-core/commit/5279454346c41740b5b48309c39bb02917a52f43)
