### ISSUE TITLE
Add instructions for updating get.sh

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#586]
## Expected Behaviour

There should be a note in the contributing guide saying that the `get.sh` file is served from https://github.com/openfaas/cli.openfaas.com and that PRs to that repo need to be made to keep get.sh in sync.

We could even add a note to the contributing guide in the top of the get.sh file stating its source and where it is served from.

I also noted get.sh didn't have `#!/bin/bash` at the top of the file?

**Comment by ZeoX06** [comment]
Hi,
as I wrote in slack, I can add some documentation. Nice to see that Alex already fixed the error message of the script.

**Comment by alexellis** [comment]
Please can you take this one?

**Comment by ZeoX06** [comment]
Yes, I'll have time tomorrow.

**Comment by ZeoX06** [comment]
Can someone check:
https://github.com/ZeoX06/docs/blob/add-get-script/docs/contributing/get-started.md
https://github.com/ZeoX06/cli.openfaas.com/blob/add-readme/README.md

Thanks :)

**Comment by alexellis** [comment]
Please can you raise the PR for me to check?

**Comment by rgee0** [comment]
@ZeoX06 The links aren't working for me.  Can you raise a PR with them, please?

**Comment by alexellis** [comment]
@rgee0 this is a trivial change. Please can you run with it?
