### ISSUE TITLE
Validate secret name before submission

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-cli#590]
The Secrets API currently returns all errors from the k8s cluster as 500 Server Error. This obfuscates validation errors and can be confusing.  This has been documented (as shown below) when the secret name is not valid. 

## Expected Behaviour

The CLI should validate the secret name before submitting to the API

```sh
$ echo 'burt' | faas secret create I_LOVE_UNDERSCORES
ERROR: invalid name: regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'
```

## Current Behaviour

No validation is done and the server will return a 500 error
```sh
$ echo 'burt' | faas secret create I_LOVE_UNDERSCORES
Creating secret: I_LOVE_UNDERSCORES
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
server returned unexpected status code: 500 - 
```

## Possible Solution

Add regex validation to the secret name field during creation.  Kubernetes uses 

```
[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
```

## Context

Relates to #577 and openfaas/faas-netes#362

**Comment by viveksyngh** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Thank you all
