### ISSUE TITLE
Proposal: Add `faas-cli log/describe fn`

### ISSUE THREAD

**Issue by ivanayov** [openfaas/faas-cli#591]
What do you think about abstracting function logs with the cli, as well as `docker inspect`/`kubectl describe`?

This would help with debugging functions. In Kubernetes it's taking longer to type `kubectl logs deploy/your-fn -n your namespace`, especially when you're debugging more complex environment (like OpenFaaS Cloud for example). Another good reason is abstracting over Swarm or K8s.

It can default the namespace function or service is deployed in.

For OpenFaaS Cloud this would allow us to provide with function logs, not only build logs.

Longer term would be great to provide options to investigate the whole cluster (not only pods and deployments, and secrets that are already available) with something like faas-cli debug mode.

**Comment by alexellis** [comment]
Sounds good @ivanayov @LucasRoesler is picking this up in #613
