### ISSUE TITLE
template pull invalid path

### ISSUE THREAD

**Issue by palade** [openfaas/faas-cli#601]
run **faas-cli new --lang python2 hello** in a terminal

## Expected Behaviour

A function should be created

I do have cygwin, and I added path faas-cli to the environment variables table.

## Current Behaviour

2019/02/05 17:27:21 No templates found in current directory.
2019/02/05 17:27:21 Attempting to expand templates from https://github.com/openfaas/templates.git
Cloning into 'C:\Users\Andrei\AppData\Local\Temp\openFaasTemplates654721331'...
fatal: Invalid path '/cygdrive/c/code/kubernets/openfaas/C:\Users\Andrei\AppData\Local\Temp\openFaasTemplates654721331': No such file or directory
2019/02/05 17:27:21 Unable to download templates from Github.
Python2 is unavailable or not **supported**

## Possible Solution

** '/cygdrive/c/code/kubernets/openfaas/C:\Users\Andrei\AppData\Local**

this path contains two paths. The first one is the linux-like one /cygdrive.... and so on. I don't know why this shows up. The second path is the windows 'C:\...'. This is where the template from the repository is cloned. I don't know why it appends the first path. 

## Steps to Reproduce (for bugs)

1. run **faas-cli new --lang python2 hello** in a terminal

## Context

Trying to setup a simple function (the hello world example) in OpenFaaS

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Hi there is no python2 template, where did you get that command from?

Alex

**Comment by palade** [comment]
Hi Alex, I tried with python3 as well. I found the command here:

https://medium.com/devopslinks/getting-started-with-openfaas-on-minikube-634502c7acdf

Thank you,
Andrei

**Comment by alexellis** [comment]
Please show the output with python3.

Cygwin is not supported, but cmd, powershell and Git Bash for Windows are.

**Comment by alexellis** [comment]
Derek close: cygwin not supported

**Comment by alexellis** [comment]
Please feel free to keep commenting or join Slack to talk more.
