### ISSUE TITLE
Support question: faas-cli invoke just hangs

### ISSUE THREAD

**Issue by palade** [openfaas/faas-cli#603]
After following the tutorial from this [website ](https://medium.com/devopslinks/getting-started-with-openfaas-on-minikube-634502c7acdf), the following command just hangs. No output is produced.

echo test | faas-cli invoke hello-python  --gateway $OPENFAAS_URL

## Expected Behaviour

my handler.py has the following content

def handle(req):
    print ( "HELLO " + req)

So I would expect for the faas-cli command to finish execution and return the message "Hello test"

When I do faas-cli list --gateway $OPENFAAS_URL

The number of invocations is incremented, but not immediately. If I run the previous command several times then it increments the number of invocations 

Function                        Invocations     Replicas
hello-java                      0               1
hello-python                    8               1

## Current Behaviour

The command just hangs for a few minutes, nothing happens.

The expected message should be returned.

## Steps to Reproduce (for bugs)

1. Follow the above tutorial 
2.
3.
4.

## Context

I'm just trying to run the hello-world example in OpenFaaS

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

v0.8.3

* Docker version ( Full output from: `docker version` ):

v18.09.1

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

Kubernetes (FaasS-neetes v0.7.0) on minikube version: v0.33.1

* Operating System and version (e.g. Linux, Windows, MacOS):

HOST OS="Ubuntu 16.04.5 LTS"

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
What is `$OPENFAAS_URL` and what is the exact code? Wrap it with a code-block quote

**Comment by palade** [comment]
192.168.99.100:31112

> def handle(req):
>       print ( "HELLO " + req)

**Comment by palade** [comment]
Gateway is set to OPENFAAS_URL. Also, when I deploy the function I get

> ubuntu@ubuntu1:~/openfaas$ faas-cli deploy -f ./hello-python.yml
> Deploying: hello-python.
> Deployed. 202 Accepted.
> URL: http://192.168.99.100:31112/function/hello-python

**Comment by richsanders** [comment]
@palade - Unless you pasted the code wrong you need to indent the second line of your python function.
`def handle(req):
    print ( "HELLO " + req)`
<img width="340" alt="screen shot 2019-02-12 at 1 19 46 pm" src="https://user-images.githubusercontent.com/47542929/52658402-ead9f400-2ec8-11e9-8eba-a719a1d709b3.png">

**Comment by alexellis** [comment]
Hi you also need to make sure you push the Docker image. Try faas-cli up instead.

**Comment by palade** [comment]
> 
> 
> @palade - Unless you pasted the code wrong you need to indent the second line of your python function.
> `def handle(req): print ( "HELLO " + req)`
> <img alt="screen shot 2019-02-12 at 1 19 46 pm" width="340" src="https://user-images.githubusercontent.com/47542929/52658402-ead9f400-2ec8-11e9-8eba-a719a1d709b3.png">

@[richsanders](/richsanders) thank you for you reply, but I don't think the indentation is the problem because I have the same issue in Java

**Comment by palade** [comment]
> you
Can you please provide an example or a template that shows how I configure my .yml file to push the image to push the Docker image?

**Comment by rgee0** [comment]
```
$ faas new --lang=python --prefix=rgee0 function-name
2019/02/12 18:38:01 No templates found in current directory.
2019/02/12 18:38:01 Attempting to expand templates from https://github.com/openfaas/templates.git
2019/02/12 18:38:07 Fetched 15 template(s) : [csharp csharp-armhf dockerfile go go-armhf java8 node node-arm64 node-armhf php7 python python-armhf python3 python3-armhf ruby] from https://github.com/openfaas/templates.git
Folder: function-name created.
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|


Function created in folder: function-name
Stack file written: function-name.yml
$ cat function-name.yml 
provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  function-name:
    lang: python
    handler: ./function-name
    image: rgee0/function-name:latest
```

**Comment by palade** [comment]
works now. Did docker login --username username --password password and pushed the image to Docker Hub. Afterwards it worked. I was jumping over the push phase since I though that build and deploy should be enough and I was working only with a local image. Apologies for this I'm quite new to this setup, and thank you for your help.

**Comment by rgee0** [comment]
Good news.  I'll close this.  You might find it useful to talk more with the community as you aim to get up to speed, details here: https://docs.openfaas.com/community/

**Comment by rgee0** [comment]
Derek close: resolved
