### ISSUE TITLE
Proposal: substitute environment variables in stack.yaml

### ISSUE THREAD

**Issue by brandonkal** [openfaas/faas-cli#606]
With docker-compose, I found it convenient to use environment variables in the shell (either as an .env file or directly). This is not possible with faas-cli as it is interpretted literally.

## Expected Behaviour

Both of these should work within a stack.yml file:
```
image: ${REGISTRY}/archive:latest
image: serverless:${TAG}
```

## Current Behaviour

```
ERROR - Could not execute command: [docker build -t ${REGISTRY}/archive:latest .]
```

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
faas-cli: 0.8.3
Provider
 name:          faas-swarm
 orchestration: swarm
 version:       0.6.1 
 sha:           3cac0ccc2e8bb7f567739a33f7d414cdb58440aa

* Docker version ( Full output from: `docker version` ):
18.06.1-ce

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS 10.12.6

**Comment by viveksyngh** [comment]
Derek add label: proposal

**Comment by Waterdrips** [comment]
This would be really useful for us.

We want to have different external APIs called based on the environment. For example calling a staging version of an external service rather than interacting with the prod service so we can do E2E testing with other systems.

**Comment by alexellis** [comment]
How this is done in the Docker CLI:

https://github.com/docker/cli/tree/master/cli/compose/template
https://github.com/docker/cli/tree/master/cli/compose/interpolation
https://github.com/docker/cli/blob/master/opts/env.go

**Comment by alexellis** [comment]
@brandonkal @Waterdrips a PR is available for testing, which I hope to release shortly.
