### ISSUE TITLE
Question: how to use constraints for CPU architecture?

### ISSUE THREAD

**Issue by gilkotton** [openfaas/faas-cli#616]
I have a small cluster with openfaas on K3S, the master node is an amd64 PC, with two arm rpi nodes as slaves. I want my openfaas function to deploy to its appropriate node by architecture. Tried specifying a function constraint with a node label. The pod didn't deploy to a specific architecture node.

## Expected Behaviour:
When deployed with openfaas, the image should have been deployed to its specified node type according to the node's label as specified in the constraints statement.

## Current Behaviour
I specified a constraint in the function yaml to specify a node label, deployed it (an amd64 built image). 
It deployed to any of the nodes and not  specificaly to the node by its label. 
Looking at the k8s deployment json I don't see a nodeSelector or similar statement.

Using a direct k8s/ kubectl deployment yaml with nodeSelector,  a pod was deployed on a specific node type as expected.

  

## Possible Solution
Ultimately, I would like the image being deployed only to an appropriate node.

## Steps to Reproduce (for bugs)

1. Add a constraints statement to the openfaas function yaml, something like:

  constraints:
       - "devtype == pc"

(where devtype is a label I labeled the nodes)

Or use a built-in node label, such as:

   constraints:
        - "beta.kubernetes.io/arch == amd64"

2. Deploy and check to which node the image was deployed. Was it subsequent pods deployed only to specified node types?

3. Check the deployment yaml to see if a nodeSelector or equivalent statement exists.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 
0.8.5

* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)? 
K3s + FaaS-netes according to @alexellisuk great blogs.

* Operating System and version (e.g. Linux, Windows, MacOS):
Lubuntu on the arm64 and raspbian on the arm.

* Link to your project or a code example to reproduce issue:
Tried it with the hello-python demo. With the contraints statement added to the hello-python.yaml file in the function section.

**Comment by alexellis** [comment]
Hi, I'll ping a couple of people.

In the meantime please can you go ahead and label your nodes and then try that?

Alex

**Comment by alexellis** [comment]
@gilkotton ?

**Comment by alexellis** [comment]
This may also be useful? https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/#add-a-label-to-a-node

**Comment by gilkotton** [comment]
Have tried it before I raised the question, I started trying to debug it,
looks like the contraint is not getting into the deployment yaml.

**Comment by alexellis** [comment]
Can you raise an issue on the faas-netes repo of that's the case?

**Comment by gilkotton** [comment]
Yes, thanks

**Comment by alexellis** [comment]
Derek close
