### ISSUE TITLE
Pick function store based-upon platform of client

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#618]
## Expected Behaviour

Running `faas-cli store list/deploy` on armhf / arm64 should use the relevant json file or platform from the openfaas/store repo.

## Current Behaviour

People may still deploy x86_64 images on an armhf device and get confused.

## Possible Solution

* Consolidate store*.json into one file with a platform field
* Detect the platform field

1) Either update build_redist.sh to inject the value into the final binary like we do with the git commit SHA
2) Or determine on the host at runtime

I prefer option 1.

We will also need to give a `--platform` override to the `faas-cli store list/deploy` functions for if someone deploys from an RPi to a public cloud (don't ask me why they would do that, but I'm sure some will try and then complain)

**Comment by alexellis** [comment]
@martindekov / @rgee0 did you start the first bullet or was that for the template store?

**Comment by rgee0** [comment]
This one?

https://github.com/openfaas/store/pull/63

**Comment by alexellis** [comment]
Thanks @rgee0 @martindekov that's now merged and I've raised: https://github.com/openfaas/faas-cli/issues/619 and https://github.com/openfaas/faas/issues/1145

**Comment by alexellis** [comment]
See functions.json https://github.com/openfaas/store/blob/master/functions.json for examples of platforms.

The default is obviously x86_64
