### ISSUE TITLE
Feature: switch to using functions.json for Function Store (help wanted)

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#619]
## Expected Behaviour

We now need to read the functions.json file here:

https://github.com/openfaas/store/blob/master/functions.json

Instead of store.json for the Function Store.

## Current Behaviour

Still using store.json

## Possible Solution

Fetch the new default URL and parse into the new struct format.

This affects `faas-cli store` commands.

In addition the platform is now required to know what device we are targeting. This could be embedded in the binary as an ldflag or read at runtime using a `GO*` env-var.

**Comment by alexellis** [comment]
@zeerorg @viveksyngh are either of you able to help with this?

**Comment by viveksyngh** [comment]
I can help with this one.

**Comment by viveksyngh** [comment]
Derek assign: me

**Comment by viveksyngh** [comment]
Derek close
