### ISSUE TITLE
Command 'faas-cli new --lang csharp xxxxxxx' returns csharp is unavailable or not supported.

### ISSUE THREAD

**Issue by EdsonF** [openfaas/faas-cli#628]
I'm following this tutorial 
https://secanablog.wordpress.com/2018/06/10/run-your-own-faas-with-openfaas-and-net-core/
and running 'faas-cli new --lang csharp csharp-function' command fails.

## Expected Behaviour
If successful, a new open-faas project should be created.

## Current Behaviour
But when I run the command 'faas-cli new --lang csharp csharp-function' the result is:
'csharp is unavailable or not supported.'.

## Steps to Reproduce (for bugs)

1. install faas-cli
2. run command 'faas-cli new --lang csharp csharp-function'
3. the result is 'csharp is unavailable or not supported.'

## Context
I've found this issue by installing the faas-cli and trying to start a new project

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
Commit: 91177ec27037eccaf6e827c265a0e452e772f1ab
Version: 0.5.0

* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 Kubernetes:
  Version:          v1.10.11
  StackAPI:         v1beta2

* Operating System and version (e.g. Linux, Windows, MacOS):
Windows 10.0.17134 Build 17134

* Link to your project or a code example to reproduce issue:

**Comment by rgee0** [comment]
Please update you CLI.

https://docs.openfaas.com/cli/install/

**Comment by EdsonF** [comment]
Many thanks, rgee0.

**Comment by rgee0** [comment]
Derek close: resolved
