### ISSUE TITLE
Problem on deploy function on ubuntu server openfaas 

### ISSUE THREAD

**Issue by Erickvami** [openfaas/faas-cli#643]
Hi, I am trying to deploy a node js function to openfaas using ubuntu server, I follow step by step but always on deploy returns 
Server returned unexpected status code: 404 - {
  "paths": [
    "/apis",
    "/apis/",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1beta1",
    "/healthz",
    "/healthz/etcd",
    "/healthz/log",
    "/healthz/ping",
    "/healthz/poststarthook/crd-informer-synced",
    "/healthz/poststarthook/generic-apiserver-start-informers",
    "/healthz/poststarthook/start-apiextensions-controllers",
    "/healthz/poststarthook/start-apiextensions-informers",
    "/metrics",
    "/openapi/v2",
    "/version"
  ]
}

## Expected Behaviour

 faas-cli deploy  -f ./js-fn.yml --annotation topic="ga" --tls-no-verify --network=func_functions

ok 200 success

## Current Behaviour

Server returned unexpected status code: 404 - {
  "paths": [
    "/apis",
    "/apis/",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1beta1",
    "/healthz",
    "/healthz/etcd",
    "/healthz/log",
    "/healthz/ping",
    "/healthz/poststarthook/crd-informer-synced",
    "/healthz/poststarthook/generic-apiserver-start-informers",
    "/healthz/poststarthook/start-apiextensions-controllers",
    "/healthz/poststarthook/start-apiextensions-informers",
    "/metrics",
    "/openapi/v2",
    "/version"
  ]
}

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version ( Docker version 18.09.6, build 481bc77
 ):

* Using Docker Swarm (FaaS-swarm )

* Operating System and version Linux LTS SERVER 18

**Comment by burtonr** [comment]
Please provide the output of `docker service ls` as well as `docker service logs --tail 100 func_gateway` and `docker service logs --tail 100 func_faas-swarm`

It's possible that the `faas-swarm` or `gateway` hasn't started or is having some issues on your cluster

**Comment by alexellis** [comment]
You appear to be running something else on port 8080 already (perhaps something related to Kubernetes?). Either stop that service or change the OpenFaaS gateway port. 

I'm going to close the issue as I am unaware of any issues with the OpenFaaS project on Swarm.

Please fell free to keep commenting. 

--
Join Slack to connect with the community
https://docs.openfaas.com

**Comment by alexellis** [comment]
To change the port on swarm. Edit docker-compose.yml for the gateway from 8080:8080 to something else like 8000:8080, then pass the --gateway parameter

**Comment by Erickvami** [comment]
@burtonr  right, there are no services about faas-swarm or gateway, I am not sure why are not creating them with "./deploy_stack.sh" or while installing, on mac os there are not problems while testing before deploy on server.

**Comment by Erickvami** [comment]
Ok @alexellis , I will try it

**Comment by Erickvami** [comment]
these are my current services

<img width="984" alt="Screen Shot 2019-05-31 at 3 09 25 PM" src="https://user-images.githubusercontent.com/18013526/58737375-21734600-83b6-11e9-8e31-f7bd31864931.png">

**Comment by Erickvami** [comment]
No success with 8000:8080

**Comment by rgee0** [comment]
Your port hasnt changed. As well as the earlier advice, please use an up to date version. Youre running 0.6.6d when the current version is 0.13.4.
