### ISSUE TITLE
help to solve this non zero code error: 8

### ISSUE THREAD

**Issue by rishavjaiswal** [openfaas/faas-cli#644]
Complete!
The command '/bin/sh -c yum install -y wget java-1.8.0-openjdk     && cd /tmp && wget -q $KAFKA_BIN     && export K_TAR=/tmp/$(ls kafka* | head -1)     && mkdir -p /opt/apache/kafka/ && tar -zxf $K_TAR -C /opt/apache/kafka/     && cd /opt/apache/kafka && ln -s $(ls) current     && rm -rf $K_TAR' returned a non-zero code: 8

**Comment by affix** [comment]
this is more a Dockerfile issue than an issue with OpenFaaS CLI. 

Error code 8 is Exec format erro

**Comment by alexellis** [comment]
Hi @rishavjaiswal I'd like to direct you to the Docker forums where you can get some help with your Dockerfile.

https://forums.docker.com

Once you've got your Dockerfile fixed-up, please let us know if you need any help with OpenFaaS projects/tooling over on Slack.

Cheers,

Alex

--
Join Slack to connect with the community
https://docs.openfaas.com

**Comment by affix** [comment]
Derek close
