### ISSUE TITLE
Get information for functions and templates without quotations

### ISSUE THREAD

**Issue by martindekov** [openfaas/faas-cli#657]
Currently if you would like to describe template or function with space in its name like `ASCII Cows` you should run `faas-cli ..... "ASCII Cows"` otherwise if written `faas-cli ..... ASCII Cows` ASCII would be considered function/template name

## Expected Behaviour

As a user I would like to just describe what I want without understanding how the naming is parsed.

## Current Behaviour

I would go with `faas-cli function store describe ASCII Cows` get error then go with `faas-cli store inspect 'ASCII Cows'`

## Possible Solution

For example in [here](https://github.com/openfaas/faas-cli/blob/9f5cadfc531b2337306c3cf28fdcb0b6048bd25e/commands/store_inspect.go#L41) instead of `args[0]` we can have logic which concatenates the name. Either way we can only inspect single function at a time, unless we would like to trade inspecting of multiple functions with one command, or single function.

Would we like to add functionality like
```
faas-cli store inspect `Awesomefi` `mememachine`
```
or have
```
faas-cli store inspect ASCII Cows
```

## Steps to Reproduce (for bugs)

```
$ faas-cli store inspect ASCII Cows
Function '' not found
```

## Context

We should chose between inspecting multiple functions or single function. If we can inspect single function/template at a time it is better UX to just write the name rather than stumble on the error and think about why this is.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
dev
* Docker version ( Full output from: `docker version` ):
18.06
* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
N/A
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux
* Link to your project or a code example to reproduce issue:
N/A run the command

**Comment by martindekov** [comment]
I can take this once it is approved/discussed

**Comment by alexellis** [comment]
I'm happy for you to come up with a solution and present it back. We've done that in at least one other place as far as I am aware

**Comment by alexellis** [comment]
Something like Args()

**Comment by martindekov** [comment]
I will go with inspecting single function. So:
```
faas-cli store describe ASCII Cows
```

**Comment by alexellis** [comment]
Yes. @johnmccabe and @LucasRoesler may have ideas, also see the Cobra docs.

**Comment by LucasRoesler** [comment]
I have mixed feelings on this,  is there another CLI that will automatically merge positional args like this? This is definitely easier for the user, but would be unexpected behavior for me because I can recall a CLI that doesn't require quoting or escaping arguments with spaces

**Comment by martindekov** [comment]
This is something that popped into my mind as we don't really use the command for anything else and I don't suppose we will. Thats why I opened the Issue, but you are right that this behaviour is present in all sorts of CLIs(the quotation aka current one).

I guess you are right @LucasRoesler I will close the Issue, can be reopen on further comments. :thumbsup:
