### ISSUE TITLE
Add support for openfaas.yaml in addition / instead of stack.yaml

### ISSUE THREAD

**Issue by ad-si** [openfaas/faas-cli#665]
Haskell's Stackage (https://www.stackage.org/) has been using the `stack.yaml` file name for ages. While there is certainly no exclusive right for Stackage to use this name, it would be nonetheless cool if OpenFaaS used something more descriptive. How about using `openfaas.yaml` instead of -- or at least in addition to -- `stack.yaml`?

**Comment by alexellis** [comment]
Thank you for your suggestion.

Are you aware that you can use any filename with the -f or --yaml override?

**Comment by alexellis** [comment]
Moving to CLI repo

**Comment by ad-si** [comment]
> Are you aware that you can use any filename with the -f or --yaml override?

Yes, but I'm a fan (maybe wrongfully) of convention over configuration. So I'd rather like to have good conventions and stick to them…

**Comment by alexellis** [comment]
That's our philosophy, however what you're asking for is starting to look a little bit like configuration. Our convention to date is stack.yml.

Hope this will keep you moving forward. I'm happy to monitor demand for this request

**Comment by tdbgamer** [comment]
+1

Even other tools like Travis or Gitlab CI use `.travis.yml` and `.gitlab.yml` to prevent conflicts. I realize it's not hard to work around, but in principle it's a little weird to trample on a config file Haskell has used for years now.

**Comment by alexellis** [comment]
@ad-si you're welcome to rename your YAML files to openfaas.yaml and to run `faas-cli up -f openfaas.yaml` etc
