### ISSUE TITLE
[Proposal] Allow formatting log output

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-cli#671]
## Expected Behaviour

We should be able to toggle off the timestamp, function name, and instance name in the log output. Additionally, it would be nice to control the timestamp formatting by specifying a time.Format layout.

## Current Behaviour

There are no CLI flags for controlling the output

## Possible Solution

Add new flags 

```
--name=bool
--instance=bool
--time-format=string
```
 When `time-format` is the empty string, the timestamp will not be printed. The boolean flags will show or hide the related field.

**Comment by alexellis** [comment]
I'm confused about this one? `--instance=bool`

How come it's bool?

**Comment by LucasRoesler** [comment]
It is just a toggle for show/hide the instance name
