### ISSUE TITLE
[Proposal] Change faas-cli login with --password-stdin to accept Enter as submitting password

### ISSUE THREAD

**Issue by Waterdrips** [openfaas/faas-cli#673]
## Expected Behaviour

Ideally an `enter` keypress should submit the password to be used to authenticate - currently its a `ctrl-d` - which I'm told is "long time terminal behaviour" but it caught me out.

This would allow more simple use of the login command that wont leave the password (or its location) in bash_history. 

## Current Behaviour

`ctrl-d` is needed to signal the end of input for the password otherwise the command just seems to hang. (I thought there was an issue somewhere else)
## Possible Solution

Change the login function to use enter as EOL and take the password from the single line.

## Context

A user on the openfaas slack posted with this happening - It seems like in a password input we expect `enter` to submit.

**Comment by Waterdrips** [comment]
So it looks like this is fairly standard - Docker login command behaves in the same way.

**Comment by alexellis** [comment]
Thank you for logging the suggestion.

This was designed to match the docker user experience (deliberately).

I think some consistency between related developer tooling is important, but let's track your suggestion here and see if it becomes an issue for users going forward.

**Comment by alexellis** [comment]
It's probably also worth noting that no keyboard interaction is required if somebody uses echo or cat and a pipe.

**Comment by alexellis** [comment]
Another thought. What does the help page say? @LucasRoesler since you showed an interest, could you find out and add a note about the flag if needed?

**Comment by Waterdrips** [comment]
This is true - and this behaviour should defiantly be maintained. 

Both of these options leave the credentials, or their location in bash_history, which might not be acceptible in some situations. 

The help command shows:
```go
Example: `  cat ~/faas_pass.txt | faas-cli login -u user --password-stdin
  echo $PASSWORD | faas-cli login -s  --gateway https://openfaas.mydomain.com
  faas-cli login -u user -p password`,
```

**Comment by LucasRoesler** [comment]
The help content doesn't say too much, but does provide 3 examples
```
faas-cli login -h
Log in to OpenFaaS gateway.
If no gateway is specified, the default value will be used.

Usage:
  faas-cli login [--username admin|USERNAME] [--password PASSWORD] [--gateway GATEWAY_URL] [--tls-no-verify] [flags]

Examples:
  cat ~/faas_pass.txt | faas-cli login -u user --password-stdin
  echo $PASSWORD | faas-cli login -s  --gateway https://openfaas.mydomain.com
  faas-cli login -u user -p password

Flags:
  -g, --gateway string    Gateway URL starting with http(s):// (default "http://127.0.0.1:8080")
  -h, --help              help for login
  -p, --password string   Gateway password
  -s, --password-stdin    Reads the gateway password from stdin
      --tls-no-verify     Disable TLS validation
  -u, --username string   Gateway username (default "admin")
```

We could probably make the current usage clearer by improving the description of the `--password-stdin` flag, perhaps something like 

```
  -s, --password-stdin    Reads the gateway password from stdin, input ends on ctrl-d
```
I am not sure that wording is quite right.

The `docker login` has a similar help string

```
docker login -h
Flag shorthand -h has been deprecated, please use --help

Usage:	docker login [OPTIONS] [SERVER]

Log in to a Docker registry.
If no server is specified, the default is defined by the daemon.

Options:
  -p, --password string   Password
      --password-stdin    Take the password from stdin
  -u, --username string   Username
```
