### ISSUE TITLE
Proposal build and push with git describe value as the tag

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-cli#677]
The options to the `--tag` flag should be expanded to include `'git-describe'`

For CI builds, it would be really helpful to use the output of `git describe --tags` as the docker image tag.  Per the man page

```
The command finds the most recent tag that is reachable from a commit. If the tag points to the commit, then only the tag is shown. Otherwise, it suffixes the tag name with the number of additional commits  on top of the tagged object and the abbreviated object name of the most recent commit.
```

Tags would look like `v1.2.2-1-g3443110`.

## Expected Behaviour

Accepts `git-describe` or `describe` as an option for `--tags` and use the output of `git-describe --tags` for the value.

## Current Behaviour

Currently, it supports tagging the function with the git SHA or the git BRANCH
```sh
--tag string                 Override latest tag on function Docker image, takes 'sha' or 'branch'
```

## Possible Solution

Accepts `git-describe` or `describe` as an option for `--tags` and use the output of `git-describe --tags` for the value.

## Context

I am currently working on an example workflow with Github Actions and it occurred to me that I could not create a workflow that meaningfully used git tags (not without a lot of bash to parse outputs and retagging things).  It would significantly reduce the amount of string parsing required in CI if  the `faas-cli` could be made tag aware.

**Comment by alexellis** [comment]
Sounds good. Would you like to prototype it so we can get some hands-on feedback?
