### ISSUE TITLE
Support: HTTP timeout when accessing template store

### ISSUE THREAD

**Issue by sriveros95** [openfaas/faas-cli#679]
## Expected Behaviour
faas-cli template store describe node10-express should describe 

## Current Behaviour
faas-cli template store describe node10-express
Error while fetching templates from store: error while requesting template list: Get https://raw.githubusercontent.com/openfaas/store/master/templates.json: context deadline exceeded

sudo -E faas-cli template store pull node10-express
Error while getting templates info: error while requesting template list: Get https://raw.githubusercontent.com/openfaas/store/master/templates.json: context deadline exceeded

## Steps to Reproduce (for bugs)
I'm new to openfaas, I'm following the workshop lab3 using Kubernetes on Digital Ocean
The laptop Im working runs Fedora 30

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
CLI:
 commit:  893972afffa5ea6672faa6e11743ae46322ec58c
 version: 0.9.2

Gateway
 uri:     http://157.230.197.201:8080
 version: 0.17.0
 sha:     c8e033f77afc8460c025d0161ca60d8f4b2d1c30
 commit:  Update stage name in Dockerfile

Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       0.8.5 
 sha:           b89240394f46b30bd83ba9f75dd1f93cf680113a

* Docker version ( Full output from: `docker version` ):
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:20:55 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:28 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
FaaS-netes
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux Fedora 30

**Comment by alexellis** [comment]
This is what I'm seeing:

```
$ faas-cli template store describe node10-express

Name:              node10-express
Platform:          x86_64
Language:          NodeJS
Source:            openfaas-incubator
Description:       Node.js 10 powered by express template
Repository:        https://github.com/openfaas-incubator/node10-express-template
Official Template: true
```

I wonder if you have some problems with your internet connection, or whether GitHub had an issue when you tried?

**Comment by sriveros95** [comment]
Thanks for your response Alex

I will debug my connection to check. Though trying with wget works.
```
[...lab3]$ faas-cli template store describe node10-express
Error while getting templates info: error while requesting template list: Get https://raw.githubusercontent.com/openfaas/store/master/templates.json: context deadline exceeded

[...lab3]$ sudo -E faas-cli template store describe node10-express
Error while getting templates info: error while requesting template list: Get https://raw.githubusercontent.com/openfaas/store/master/templates.json: context deadline exceeded

[...lab3]$ wget https://raw.githubusercontent.com/openfaas/store/master/templates.json
--2019-08-29 16:54:05--  https://raw.githubusercontent.com/openfaas/store/master/templates.json
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.48.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.48.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12964 (13K) [text/plain]
Saving to: ‘templates.json’

templates.json                                              100%[=========================================================================================================================================>]  12.66K  --.-KB/s    in 0s      

2019-08-29 16:54:20 (41.4 MB/s) - ‘templates.json’ saved [12964/12964]

[...lab3]$ cat templates.json
[
    {
        "template": "csharp",
        "platform": "x86_64",
        "language": "C#",
        "source": "openfaas",
        "description": "Official C# template",
        "repo": "https://github.com/openfaas/templates",
        "official": "true"
    },
    ...
    {
        "template": "node10-express-service",
        "platform": "x86_64",
        "language": "NodeJS",
        "source": "openfaas-incubator",
        "description": "Node.js 10 express.js microservice template",
        "repo": "https://github.com/openfaas-incubator/node10-express-service",
        "official": "true"
    }
]
```

**Comment by sriveros95** [comment]
I waited a little and tried again and it worked. 
Sorry for the inconvenience and thanks again!
