### ISSUE TITLE
Function/Template with symlinks file are failing to build 

### ISSUE THREAD

**Issue by viveksyngh** [openfaas/faas-cli#680]
Function or Templates having symlink files are not getting copied properly because of that it is failing to build the function. 

## Expected Behaviour

It should exit with an error if it is not able to copy files 
It should resolve the symlinks and copy the symlinked files.

## Current Behaviour

It is silently failing the copy and function are failing to build. 

## Steps to Reproduce (for bugs)

1. Download attached zip file
2. Unzip it 
3. Create a new function using the template  `node10-slackin` or use the existing function `invite-slack`
4.  Build the function using `faas-cli build ` 

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.8.21

* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

[template.zip](https://github.com/openfaas/faas-cli/files/3562169/template.zip)

**Comment by rgee0** [comment]
This is the silent fail in build.go:

https://github.com/openfaas/faas-cli/blob/893972afffa5ea6672faa6e11743ae46322ec58c/builder/build.go#L145-L147

It errors within the recursion in CopyFiles():

https://github.com/openfaas/faas-cli/blob/893972afffa5ea6672faa6e11743ae46322ec58c/builder/copy.go#L14-L17

The error propagates back out of the recursion and ends up here where it carries on into the function copy.

I changed it to:
```go
    if useFunction {
        copyErr := CopyFiles("./template/"+language, tempPath)
        if copyErr != nil {
            log.Fatal(copyErr)
        }
    }
```
And this happened:
```sh
$ ./faas-cli-darwin build -f test.yml 
[0] > Building test.
Clearing temporary build folder: ./build/test/
Preparing ./test/ ./build/test//function
Creating directory: node10-slackin at ./build/test/
cp - template/node10-slackin/.DS_Store build/test/.DS_Store
cp - template/node10-slackin/Dockerfile build/test/Dockerfile
Creating directory: function at build/test/function
Creating directory: .burt at build/test/function/.burt
cp - template/node10-slackin/function/.burt/burts_package build/test/function/.burt/burts_package
cp - template/node10-slackin/function/handler.js build/test/function/handler.js
cp - template/node10-slackin/function/package.json build/test/function/package.json
cp - template/node10-slackin/index.js build/test/index.js
Creating directory: node_modules at build/test/node_modules
Creating directory: .bin at build/test/node_modules/.bin
2019/08/30 22:56:58 stat template/node10-slackin/node_modules/.bin/atob: no such file or directory
```

**Comment by rgee0** [comment]
Probably worth noting that the symlinks are being resolved & copied - this is a red herring.  It's where an error occurs in the template copy that is causing the issue.
