### ISSUE TITLE
faas-cli new does not respect env var for template URL

### ISSUE THREAD

**Issue by burtonr** [openfaas/faas-cli#685]
## Expected Behaviour

Setting the environment variable `OPENFAAS_TEMPLATE_URL` and running `faas-cli new ...` should pull the template(s) from the URL set in the environment

## Current Behaviour

`faas-cli new ...` pulls from the default URL (`https://github.com/openfaas/templates.git
`) and not from the URL set in the `OPENFAAS_TEMPLATE_URL` environment variable

`faas-cli template pull` _does_ use the URL set in the environment variable as expected

## Possible Solution

Adjust the call to `PullTemplates()` here: https://github.com/openfaas/faas-cli/blob/master/commands/new_function.go#L118 *or* adjust the `PullTemplates` func here: https://github.com/openfaas/faas-cli/blob/master/commands/build.go#L223

## Steps to Reproduce (for bugs)

1. `export OPENFAAS_TEMPLATE_URL=https://github.com/openfaas-incubator/node10-express-service.git`
2. `faas new first --lang node10-express-service`
3. Observe the output indicating the templates pulled from `openfaas/templates.git`
4. `faas-cli template pull`
5. Observe the output indicating the template pulled from the `openfaas-incubator` URL

## Context

This has been reported to the team via Slack and I've verified

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:
 commit:  c9c4be99c808c352e9fdf73ffe1659cec1d2a7cf
 version: 0.8.9
```
* Docker version ( Full output from: `docker version` ):
```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false
```

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
N/A
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux
* Link to your project or a code example to reproduce issue:
N/A

**Comment by jonatasbaldin** [comment]
I can tackle this 💃

**Comment by burtonr** [comment]
Derek close: Courtesy of PR https://github.com/openfaas/faas-cli/pull/686
