### ISSUE TITLE
Proposal: `faas-cli exec` command

### ISSUE THREAD

**Issue by jonatasbaldin** [openfaas/faas-cli#689]
## Expected Behaviour
We could have a `faas-cli exec <function> <command>` to execute custom commands inside a function, even a shell, pretty much like `kubectl exec` works.

## Current Behaviour
We don't have anything like that in the current behaviour. We can, though, do:
`$ kubectl -n openfaas-fn exec <pod> <command>`

## Possible Solution
Basic idea is to implement a new command, it should:
- Identify the pod created by the function
- Execute the `kubectl exec` or implement the same behaviour

## Context
Just an idea I just had, worth discussing. It would be nice to have this command which kinda bridges FaaS and Containers worlds together ✨

**Comment by alexellis** [comment]
Thanks for the suggestion. I don't think this is something that is going to be worked on any time soon. I'm going to close and mark for revisit.
