### ISSUE TITLE
Don't Require `-f` If There's Only One .yml In Current Directory

### ISSUE THREAD

**Issue by Miserlou** [openfaas/faas-cli#699]
Simple usability thing: don't require `-f blah.yml` if the current working directory only contains a single yaml file, so that deploying is simple `faas up` for the majority of cases.

**Comment by rgee0** [comment]
Possible duplicate of https://github.com/openfaas/faas-cli/issues/635.  Please check and close/update accordingly.

**Comment by Miserlou** [comment]
Yeah, close enough.
