### ISSUE TITLE
Support request for private repositories on Docker Swarm

### ISSUE THREAD

**Issue by ziggekatten** [openfaas/faas-cli#705]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

So, deploying a function through either faas-cli returns success (202), and the function shows up in the UI with status not ready.

## Expected Behaviour

The function should be available to execute

## Current Behaviour

The function have status "not ready" in UI, and the images are never pulled to my faas-cluster.

There are no errors in any logs (nats, gateway, faas-swarn) and I do not know how to further investigate the issue. faas-cli login works toward registry. so does build and push. 

faas-cli version 0.9.3 (tried 0.9.2 as well) Docker Swarm 19.03.2

command used: "faas-cli deploy -a -f .\myfunc.yml"

Response "Deployed. 202 Accepted."

WHere should I start looking?

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 

0.9.3

* Docker version `docker version` (e.g. Docker 17.0.05 ): 

19.03.2

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? 

Swarm

* Operating System and version (e.g. Linux, Windows, MacOS): 

Ubuntu Linux

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
@ziggekatten once you can get the below working, with making the repo private, then OpenFaaS should also work for you.

The example runs `ping`:

```
docker tag alpine:3.10 harbor.myfaas.club/library/alpine:3.10
docker push harbor.myfaas.club/library/alpine:3.10

docker service create --with-registry-auth --name ping harbor.myfaas.club/library/alpine:3.10 ping google.com

overall progress: 1 out of 1 tasks 
1/1: running   [==================================================>] 
verify: Waiting 1 seconds to verify that tasks are stable... 
verify: Waiting 1 seconds to verify that tasks are stable... 
verify: Service converged 

docker service logs ping
ping.1.jztledkgyxty@docker-desktop    | PING google.com (216.58.204.78): 56 data bytes
ping.1.jztledkgyxty@docker-desktop    | 64 bytes from 216.58.204.78: seq=0 ttl=37 time=19.966 ms
ping.1.jztledkgyxty@docker-desktop    | 64 bytes from 216.58.204.78: seq=1 ttl=37 time=18.842 ms
ping.1.jztledkgyxty@docker-desktop    | 64 bytes from 216.58.204.78: seq=2 ttl=37 time=16.840 ms
ping.1.jztledkgyxty@docker-desktop    | 64 bytes from 216.58.204.78: seq=3 ttl=37 time=15.250 ms
ping.1.jztledkgyxty@docker-desktop    | 64 bytes from 216.58.204.78: seq=4 ttl=37 time=15.978 ms
```
