### ISSUE TITLE
Proposal: Default to a 'well-known' named stack file

### ISSUE THREAD

**Issue by 0xdevalias** [openfaas/faas-cli#71]
## Expected Behaviour

In a similar vein to `docker compose` it would be nice if `faas-cli` defaulted to a well-known, named yaml file (eg `openfaas.yml` or similar) If it did, it wouldn't be a requirement to specify `-f foo.yaml` on each CLI command.

**Comment by alexellis** [comment]
Good suggestion. We were talking about this recently. I think `stack.yml` or `functions.yml` could be a good name.

Are you interested in completing the work also?

@johnmccabe - can the `-f` flag be adapted to take a default easily?

**Comment by alias1** [comment]
At this stage i'm not sure if I have the capacity to contribute, though if I find I do down the line and it isn't implemented yet, happy to take a shot at it then.

**Comment by johnmccabe** [comment]
@alexellis that should be straight forward, the only bit that is worth calling out is the expected behaviour when passing explicit flags and no `-f|--yaml` as that logic will be impacted. The use of a default was mentioned in the examples in #17 but we'd decided against it at the time.

**Comment by alexellis** [comment]
> bit that is worth calling out is the expected behaviour when passing explicit flags and no -f|--yaml as that logic will be impacted. 

Can you give an example?

**Comment by johnmccabe** [comment]
Derek add label: skill/beginner

**Comment by johnmccabe** [comment]
Derek add label: enhancement

**Comment by alexellis** [comment]
I would see this as being "stack.yml". We have to make sure that the override works well with all the commands before merging a fix.

**Comment by nicholasjackson** [comment]
I can take a look at this in the morning

**Comment by alias1** [comment]
See https://github.com/openfaas/faas-cli/pull/126

**Comment by alexellis** [comment]
This has been merged.
