### ISSUE TITLE
[Feature request] flag override for image and name

### ISSUE THREAD

**Issue by GnaphronG** [openfaas/faas-cli#710]
While a lot of the values defined in the function.yml file can be overridden, the image name and the function name can't.

## Expected Behaviour

Passing image and/or function name should override the one in the yaml file passed using the `-f` flag. 

## Current Behaviour

The value of image or name are ignored if a yaml file is defined unlike the gateway or the secret for example.

## Possible Solution

Allow image parameter to override the values in the yaml file like in the example below: 
`/faas-cli  deploy -f function.yml --image=registry.local:5000/function:latest`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I use `docker buildx` to make multi-platform images and push them to my local registry to test before pushing them to docker.io. I try to keep the yaml file as environment agnostic as possible.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
CLI:
 commit:  3d0afd74bba7c8b9bc7b8b474e9d7cbc3ca08399
 version: 0.9.4

* Docker version ( Full output from: `docker version` ):
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 01:00:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:59:17 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
FaaS-netes

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

* Link to your project or a code example to reproduce issue:
https://github.com/Kynothon/faas-functions

**Comment by jgnagy** [comment]
@alexellis, I see the value in this as well. From a CI perspective, I'd like to be able to override the image (we use different docker registries per environment) and while envsubst is great, it adds a step to developers' workflows (I need them to open the stack yaml and edit the image key to include a shell-style variable). Otherwise I'll need to be a bit more creative and do that myself via `sed` or something, which is less than ideal.

**Comment by alexellis** [comment]
Try the substitution, it's why we added the feature. Let us know how it goes.

**Comment by rgee0** [comment]
For different docker registries per env, does injecting the envsubstr into the `stack.yml` at `faas new ...` help the workflow? Trying the following with the `--prefix` flag seems to address the described use case:

```
$ faas-cli new --lang python3 fn-prefix --prefix '${DOCKER_USER:-exampleco}'

$ cat fn-prefix.yml                                                         
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  fn-prefix:
    lang: python3
    handler: ./fn-prefix
    image: ${DOCKER_USER:-exampleco}/fn-prefix:latest
```

**Comment by alexellis** [comment]
Let's close then 👍
