### ISSUE TITLE
Print namespace in invoke URL after deployment

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#717]
## Expected Behaviour

The CLI should print the namespace of the deployment in the invoke URL after `faas-cli deploy`

## Current Behaviour

It's left out, so it could lead to confusion.

Regardless of the namespace, deploying nodeinfo will show:

```
URL: http://127.0.0.1:8081/function/nodeinfo
```

## Steps to Reproduce (for bugs)

Deploy two functions, both get the same invocation URL printed:

1. `faas-cli deploy --name nodeinfo --image functions/nodeinfo -g 127.0.0.1:8081 `
2. `faas-cli deploy --name nodeinfo --image functions/nodeinfo --namespace staging -g 127.0.0.1:8081`

The second should be: `URL: http://127.0.0.1:8081/function/nodeinfo.staging`

## Your Environment

faas-netes latest PR https://github.com/openfaas/faas-netes/pull/542

faas-cli 0.11.0 (latest)

**Comment by martindekov** [comment]
I can quickly fix this up fix this up 👍

**Comment by alexellis** [comment]
You may need https://github.com/openfaas/faas-netes/releases/tag/0.9.9

**Comment by martindekov** [comment]
Thank you Alex ^ will re-deploy and open PR shortly.

**Comment by rgee0** [comment]
My attempt.  May or may not be useful:

https://github.com/openfaas/faas-cli/compare/master...rgee0:addDeployURLNamespace?expand=1

**Comment by martindekov** [comment]
Aw, ok Richard, perfect thanks if you open PR I can review it :+1:
