### ISSUE TITLE
[Feature] Download kubeseal using Golang

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#722]
## Expected Behaviour

`kubeseal` is required for use with `faas-cli cloud seal`

We could add a command like this:

```
faas-cli download kubeseal
```

## Current Behaviour

There's manual instructions in the README on how to get `kubeseal`

## Possible Solution

Follow the approach taken by k3sup to determine architecture and download the binary to:

```
~/.openfaas/bin/
```

https://github.com/alexellis/k3sup/blob/master/pkg/cmd/openfaas_app.go#L65

We will also need to print a command like:

```
# Add $HOME/.openfaas/bin/ to your $PATH variable

export PATH=$PATH:$HOME/.openfaas/bin
```

**Comment by utsavanand2** [comment]
Derek assign: me
