### ISSUE TITLE
[Feature] List namespaces available to openfaas

### ISSUE THREAD

**Issue by martindekov** [openfaas/faas-cli#728]
Currently the OpenFaaS API provides a way to list namespaces which are available for OpenFaaS to deploy functions to, but it must be called with curl. We can add this behaviour to the cli.

## Expected Behaviour

List namespaces with `faas-cli list --namespaces`

## Current Behaviour

We must curl the endpoint in order to list the namespces

## Possible Solution

Add flag to `faas-cli list` which will get the namespaces available to openfaas.

## Steps to Reproduce (for bugs)

1. Try getting the namespaces with `faas-cli`
2. You can't

## Context

I want to quickly check the available namespaces in which I can dpeloy functions and to do so I need to write `curl -X GET ....`, instead we can just call elegantly `faas list --namespaces`.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
N/A
* Docker version ( Full output from: `docker version` ):
N/A
* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
N/A
* Operating System and version (e.g. Linux, Windows, MacOS):
N/A
* Link to your project or a code example to reproduce issue:
N/A

**Comment by alexellis** [comment]
Or `faas namespaces`?

**Comment by martindekov** [comment]
This is a good proposal ^ I like it 👍 I can add the option
