### ISSUE TITLE
--from-file not included in seal hint

### ISSUE THREAD

**Issue by brandonkal** [openfaas/faas-cli#729]
https://github.com/openfaas/faas-cli/blob/62c00fbf9eac1a14b1e3121bacb6d767ebc64fe0/commands/cloud.go#L52

**Comment by LucasRoesler** [comment]
This should be a very easy  change. It would also be nice to extend the examples as well, like we do for `faas-cli build`

https://github.com/openfaas/faas-cli/blob/62c00fbf9eac1a14b1e3121bacb6d767ebc64fe0/commands/build.go#L78-L87

@brandonkal is this something you would be willing to contribute?
