### ISSUE TITLE
dockerfile-armhf is not recognised by build as a 'non-language' template

### ISSUE THREAD

**Issue by georgenicoll** [openfaas/faas-cli#734]
## Expected Behaviour
When running build with a lang of 'Dockerfile-armhf', faas-cli should treat the build as a non-language template and not append /function to the function path (as it does when lang is set to 'Dockerfile').

## Current Behaviour
faas-cli treats 'Dockerfile-armhf' as a language template and appends /function so causes the build to fail with 'unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat .../build/sorter/Dockerfile: no such file or directory'

## Possible Solution
See https://github.com/openfaas/faas-cli/pull/733

## Steps to Reproduce (for bugs)
1.  Create a new function with:  faas-cli new --lang dockerfile-armhf <name>
2.  Try to build the function with:  faas-cli build -f <name>.yml
3.  Build fails with 'unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat .../build/sorter/Dockerfile: no such file or directory'

## Context
Prevented working through lab3 of the workshiop on armhf

## Your Environment
armhf
* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:
 commit:  0ab4012784510381e2b90c031ede3d77197b10b1
 version: 0.11.0

Gateway
 uri:     http://black:31112
 version: dev
 sha:     672b7c48b7fcefbc974c69abab06555ab21e9db5
 commit:  Add tiers


Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       dev 
 sha:           b4b112e1342979590eadd2d4471530f45734a46e
```

* Docker version ( Full output from: `docker version` ):
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:37:22 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:31:17 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
Raspbian

* Link to your project or a code example to reproduce issue:
Fix for this issue: https://github.com/openfaas/faas-cli/pull/733

**Comment by georgenicoll** [comment]
dockerfile-armhf template is now deprecated:  can just use dockerfile template.

**Comment by alexellis** [comment]
Go for it. The repo is openfaas/templates
