### ISSUE TITLE
Shouldn't I run openfass on Windows?

### ISSUE THREAD

**Issue by YeoHoonYun** [openfaas/faas-cli#735]
PS C:\Users\cjswo> .\faas-cli.exe build -f .\uptime.yml
[0] > Building uptime.
Clearing temporary build folder: ./build/uptime/
Preparing ./uptime/ ./build/uptime//function
Building: uptime:latest with python3 template. Please wait..
Sending build context to Docker daemon 9.216 kB
Step 1/29 : FROM openfaas/classic-watchdog:0.18.1 as watchdog
Error parsing reference: "openfaas/classic-watchdog:0.18.1 as watchdog" is not a valid repository/tag: invalid reference format

Hi, I am a programmer interested in serverless in Korea. Can I check the error "openfaas / classic-watchdog: 0.18.1 as watchdog" while installing with Docker on Windows 10 Pro?

Thank you.

**Comment by alexellis** [comment]
Moving to correct repository (faas-cli)

**Comment by YeoHoonYun** [comment]
> 올바른 저장소로 이동 (faas-cli)
Hi.
Thank you for your reply because I am translating with Google Translator with a little English.
This time, I'll run using git bash as the answer.
And the tutorial example I referenced was to use PowerShell on Windows. https://docs.openfaas.com/cli/install/
I'm interested in serverless, so I'll try hard.

**Comment by alexellis** [comment]
You should ensure that Docker is using Linux containers. Next update your Docker version to latest edge, thank you.

**Comment by YeoHoonYun** [comment]
Fixed issue with Docker Edge version (18.09.1) But the tutorial failed to run.
The error is as above.

Deploying: callme.
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Is OpenFaaS deployed? Do you need to specify the --gateway flag?
Put http://127.0.0.1:8080/system/functions: dial tcp 127.0.0.1:8080: connectex: No connection could be made because the target machine actively refused it.

Function 'callme' failed to deploy with status code: 500
------------------------------------------------------------------------------
Are you installing the gateway with docker swarm?

**Comment by alexellis** [comment]
Did you run the `kubectl port-forward` command given in the documentation and the workshop?

**Comment by YeoHoonYun** [comment]
![image](https://user-images.githubusercontent.com/45550361/70389338-8791f300-1a01-11ea-90a9-22ab6dd74304.png)

https://blog.alexellis.io/quickstart-openfaas-cli/

I think I should install Kubernetes or Docker Swarm to install the gateway. By the way, I can't access that path in the tutorial. Please confirm. Thank you.

**Comment by alexellis** [comment]
Use the workshop that I linked you to, not a blog post I wrote years ago.
