### ISSUE TITLE
describe function command does not produce the correct url for the supplied namespace

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-cli#739]
The `faas-cli describe` command is namespace aware, but does not print the correct urls that include the `.<namespace>`

## Expected Behaviour

The output should include the url with the namespace

```sh
$ faas-cli describe --namespace beta travel-predictions
Name:                travel-predictions
Status:              Ready
...
Function process:
URL:                 https://example.com/function/travel-predictions.beta
```

## Current Behaviour

```sh
$ faas-cli describe --namespace beta travel-predictions
Name:                travel-predictions
Status:              Ready
...
Function process:
URL:                 https://example.com/function/travel-predictions
```

## Possible Solution

Update the `getFunctionURLs` method

## Steps to Reproduce (for bugs)

1. Deploy to kuberenets with namespace support, as done in these docs https://docs.openfaas.com/reference/namespaces/
2. Add a namespace `beta` 
```sh
kubectl create ns beta
kubectl annotate ns beta openfaas="true"
```
3. Deploy a function to beta `faas-cli store deploy NodeInfo -n beta`
4. Describe that function `faas-cli describe -n beta nodeinfo`

## Context

Relates to openfaas/faas-netes#511

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
`0.11.2`

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
faas-netes in GKE

**Comment by codegold79** [comment]
Would it be all right if I took this one?

**Comment by codegold79** [comment]
Derek assign: me

**Comment by codegold79** [comment]
Derek assign: codegold79

**Comment by codegold79** [comment]
Should the async function url also have the dot namespace at the end of it?

**Comment by alexellis** [comment]
Try it, I think so, but not sure if it's implemented for certain.
