### ISSUE TITLE
Question: remove faas-cli + UI

### ISSUE THREAD

**Issue by loiane** [openfaas/faas-cli#746]
I have installed faas-cli and played with it for a while. Now I want to remove it from my computer and I was able to remove the command. However, http://localhost:8080/ui is still opening when docker is active. 
I have removed all images, services and containers and is still active.
Is there something else that needs to be removed in order to completely remove the portal UI?

## Expected Behaviour

http://localhost:8080/ui should not be available after removing the CLI.

## Current Behaviour

http://localhost:8080/ui is still active after removing the CLI.

## Steps to Reproduce (for bugs)

N/A

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version ( Full output from: `docker version` ):
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Please ask on Slack. You'll also need to say how you installed it.

**Comment by alexellis** [comment]
Actually the issue template asks you to state that you have searched the documentation before posting an issue.

The docs already cover CLI/Swarm and K8s removal:

https://docs.openfaas.com/deployment/troubleshooting/#uninstall-openfaas

**Comment by seguri** [comment]
@alexellis could you please provide the updated working link?

**Comment by alexellis** [comment]
@seguri This is an issue from 3 years ago. What do you need?

**Comment by seguri** [comment]
The last link you provided is broken, would you mind updating it with the working one? This thread is the first search result for "uninstall open faas".

**Comment by ventz** [comment]
For those that have installed `faasd` for the "single host" / local deployment, here are step by step uninstall instructions -- assuming Ubuntu:


1. **Stop services**:
    ```bash
    sudo systemctl stop faasd-provider
    sudo systemctl stop faasd
    sudo systemctl stop containerd
    sudo systemctl stop caddy
    ```

2. **Disable the services**:
    ```bash
    sudo systemctl disable faasd-provider
    sudo systemctl disable faasd
    sudo systemctl disable containerd
    sudo systemctl disable caddy
    ```

3. **Remove the binaries**:
    ```bash
    sudo rm /usr/local/bin/faasd
    sudo rm /usr/local/bin/faas-cli
    sudo rm /usr/local/bin/arkade
    sudo rm /usr/bin/caddy
    ```

4. **Delete associated directories**:
    ```bash
    sudo rm -rf /var/lib/faasd
    sudo rm -rf /etc/faasd
    sudo rm -rf /var/lib/caddy
    sudo rm -rf /etc/caddy
    sudo rm -rf /tmp/faasd-*-installation
    sudo rm -rf /opt/cni/bin
    ```

5. **Remove systemd service files**:
    ```bash
    sudo rm /etc/systemd/system/faasd-provider.service
    sudo rm /etc/systemd/system/faasd.service
    sudo rm /etc/systemd/system/caddy.service
    ```

    If you had a custom containerd service file:
    ```bash
    sudo rm /etc/systemd/system/containerd.service
    ```

6. **Uninstall related packages**:
    ```bash
    sudo apt-get purge -y curl runc bridge-utils iptables
    ```

    (Note: `apt-get purge` will remove the package and its configuration files. Ensure no other software requires these utilities before removing them.)

7. **Delete users**:
    ```bash
    sudo userdel -r caddy
    ```

8. **Revert sysctl changes**:
    ```bash
    sudo sed -i '/net.ipv4.conf.all.forwarding=1/d' /etc/sysctl.conf
    sudo sysctl -p
    ```

9. **Clean Up iptables rules**:
    (This step might be slightly tricky, as you might have other `iptables` rules. Ensure you remove only the rules associated with `faasd`.)
    ```bash
    sudo iptables -F
    ```

10. **Update and Upgrade**:
    After removing software, it's generally a good practice to update the package database and upgrade any existing packages.
    ```bash
    sudo apt update && sudo apt upgrade
    ```

11. **Reboot (Optional)**:
    You can reboot your system to ensure that all changes are fully applied and any residues of the software are gone.
    ```bash
    sudo reboot
    ```

**Comment by alexellis** [comment]
To remove the CLI, simply run `which faas-cli` and delete the corresponding binary.

Uninstallation of faasd involves the inverse of the hack/install.sh script. It's not recommended to install faasd alongside other software, so we are not going to maintain documentation on this.

You should always launch it on its own VM, or on a fresh SD card if you're using an IoT device.

**Comment by alexellis** [comment]
To remove the faas-cli, simply run `which faas-cli`, then remove that binary.

To uninstall openfaas, see the Helm chart instructions.

For faasd, you should always use a fresh VM or SD card, and never install it on a system that is running other workloads.
