### ISSUE TITLE
Convert sample github_hmac to use classic Go template

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#747]
Convert sample github_hmac to use classic Go template

https://github.com/openfaas/faas-cli/tree/master/sample/github_hmac

This will be less to maintain over time, a Dockerfile isn't required for the sample.

**Comment by aidun** [comment]
@alexellis I will take This issue

**Comment by Amalkh5** [comment]
@alexellis I will work on this issue as @aidun said in slack he can’t work on it.

**Comment by Amalkh5** [comment]
fixed in #783
