### ISSUE TITLE
Remove command should return non-zero exit code for HTTP error

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#748]
The `faas-cli remove` command should a return non-zero exit code for any HTTP errors detected, or errors returned from the proxy package. There are probably other commands that act this way too.

## Expected Behaviour

Remove command should return non-zero exit code for HTTP error

## Current Behaviour

It returns exit-code 0

## Possible Solution

Update the code to return a non-zero exit code, i.e. return any error in the remove command: 

https://github.com/openfaas/faas-cli/blob/master/commands/remove.go#L71

Note that there can be multiple errors, we should exit when we hit the first error with `return err` or similar.

## Steps to Reproduce (for bugs)

1. `faas-cli remove invalid-function && echo $?`
2. `faas-cli remove invalid-function --gateway bad-gateway:8080 && echo $?`

This gives 0, but shouldn't. The same happens for 500 errors

## Context

This gives a false-positive in integration testing, i.e. my Travis build passed when it should have failed - https://travis-ci.com/alexellis/faasd/builds/143038396

**Comment by LucasRoesler** [comment]
Returning the error after the call to `proxy.ListFunctionsToken`  should work exactly as expected, just like in the list command https://github.com/openfaas/faas-cli/blob/63f310208b4db547a7bb03842b04e8271a175635/commands/list.go#L59-L62

**Comment by LucasRoesler** [comment]
Looking at the proxy code, it seems like it will also need to be updated to return an error on non-200 status codes. Currently, it only prints to stdout for non-200 errors 

https://github.com/openfaas/faas-cli/blob/63f310208b4db547a7bb03842b04e8271a175635/proxy/delete.go#L60-L78

**Comment by alexellis** [comment]
:+1:

**Comment by itohan-uk** [comment]
How do i assign this issue to myself?

**Comment by burtonr** [comment]
@itohan-uk issues can only be (properly) assigned to members of the GitHub organization. That said, simply commenting on the issue that you will work on it as you have is more than enough. Thanks!

Let us know if you have any questions or troubles, and be sure to have a read through the [Contributing Guide](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md)

**Comment by itohan-uk** [comment]
Thanks @burtonr

**Comment by itohan-uk** [comment]
Currently have the code modified to return an error if one exists. However when i run the above command 
`faas-cli remove invalid-function && echo $?`
I don't see any exit code. But when i run 
`echo $?`  just after this, i see exit code 1. 
Any ideas why it works with the && when its an exit code of 0 and does not when its 1?

**Comment by alexellis** [comment]
@viveksyngh you mentioned you were available to help a little bit with new contributions.

**Comment by viveksyngh** [comment]
@itohan-uk. is it ok to raise a PR with your changes on so that we can have a look and help you with that ?

**Comment by itohan-uk** [comment]
@viveksyngh Sure. I'll raise one later today
