### ISSUE TITLE
kubeseal download on rpi3 fails

### ISSUE THREAD

**Issue by Waterdrips** [openfaas/faas-cli#749]
Kubeseal only package 
```
kubeseal-darwin-amd64
kubeseal-linux-amd64
kubeseal.exe
```
as shown here : https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.9.6

Running on a Pi tries to download the kubeseal binary - should we return with a warning if running on an unsupported arch?

when executed on rpi3
```
pi@raspberrypi:~ $ faas-cli cloud seal --download
Starting download of kubeseal v0.9.6, this could take a few moments.
Download completed, please run:

  chmod +x /tmp/kubeseal
  /tmp/kubeseal --version
  sudo install /tmp/kubeseal /usr/local/bin/

pi@raspberrypi:~ $   chmod +x /tmp/kubeseal
pi@raspberrypi:~ $   /tmp/kubeseal --version
/tmp/kubeseal: line 7: syntax error near unexpected token `newline'
/tmp/kubeseal: line 7: `<!DOCTYPE html>'
pi@raspberrypi:~ $ 

```
## Current Behaviour

we make a URL that points to a github 404 page.

## Possible Solution

only try with supported variables?
check the link isnt a 404 before downloading?

## Steps to Reproduce (for bugs)

shown in description

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
pi@raspberrypi:~ $ faas-cli version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  73004c23e5a4d3fdb7352f953247473477477a64
 version: 0.11.3
```
* Docker version ( Full output from: `docker version` ):
Not installed

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
N/A
* Operating System and version (e.g. Linux, Windows, MacOS):
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
```

**Comment by alexellis** [comment]
> check the link isnt a 404 before downloading?

SGTM, also let's raise an issue upstream and ask them to cross compile and point at our example?

**Comment by Waterdrips** [comment]
https://github.com/bitnami-labs/sealed-secrets/issues/173

**Comment by alexellis** [comment]
@Waterdrips can this be closed now?

**Comment by Waterdrips** [comment]
I was using it to remind me to look at raising the kubeseal pr to implement arm builds. But it can probably be closed yeh

**Comment by alexellis** [comment]
Go for it

**Comment by alexellis** [comment]
Raised PR: https://github.com/bitnami-labs/sealed-secrets/pull/344 to cover this. It should automatically work, when the return code is not 404, I believe?

The name will be arm for armhf, and arm64 for 64-bit ARM.
