### ISSUE TITLE
[Feature] Customise the template "function" folder

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#754]
## Description

Customise the template "function" folder #754

## Context and motivation

Templates consist of two parts - an entry point, and a handler. The folder name for the handler is hardcoded to "function", but there's some cases where this is obstructive.

For Elixir the name must be "lib" or "src", I forget which cc @dokie

Here's an imaginary programming language "ext":

```
./index.ext
./function/handler.ext
```

What if "ext" must, like Elixir have all sub-folders with a name "src", then we'd be stuck and have to resort to renaming things in the Dockerfile.

```
./index.ext
./src/handler.ext
```

Since "function" is hard-coded in the Go code, we can keep it as a default and offer to switch out for any value specified in template.yml, for instance `handler_folder: src`.

This is what we did to evolve the fprocess from being hard-coded in Go to being flexible for each template.

**Comment by dokie** [comment]
@alexellis For Elixir the root source folder is called `lib`

**Comment by alexellis** [comment]
Thanks for confirming. That's now supported if you're interested in trying it out with your template store submission?
