### ISSUE TITLE
Don't pull template defined in stack YAML file, if it is already in the filesystem

### ISSUE THREAD

**Issue by martindekov** [openfaas/faas-cli#759]
Currently templates are always pulled if config is provided in the yaml file:
```
configuration:
  templates:
    - name: golang-middleware
```
. We should skip pulling the same way we skip pulling if template folder exists like here:
https://github.com/openfaas/faas-cli/blob/30b7cec9634c708679cf5b4d2884cf597b431401/commands/build.go#L290

## Expected Behaviour

Don't fetch templates if template exists in building phase

## Current Behaviour

Fetches them and tries to override in building phase.

## Possible Solution

Wrap method:
https://github.com/openfaas/faas-cli/blob/30b7cec9634c708679cf5b4d2884cf597b431401/commands/build.go#L201
with logic similar in:
https://github.com/openfaas/faas-cli/blob/30b7cec9634c708679cf5b4d2884cf597b431401/commands/build.go#L290

`os.Stat("./template/%s",templateName)`

## Steps to Reproduce (for bugs)

1. Build function with configuration
2. Check templates pulled
3. Build function with configuration again
4. Check templates pulled and fail to override

## Context

Adds latency to the building phase

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
N/A
* Docker version ( Full output from: `docker version` ):
N/A
* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
N/A
* Operating System and version (e.g. Linux, Windows, MacOS):
N/A
* Link to your project or a code example to reproduce issue:
N/A

**Comment by alexellis** [comment]
@martindekov I have a vague recollection of a PR for this? @utsavanand2 was just asking whether he could take the issue.

**Comment by martindekov** [comment]
Yeah I had no PR for this, if we want this to work as described in the issue we should disable custom naming of the template in the feature, or change the CLI to pull the template in a folder pointed by the template custom's name. Though my approach in solving this might not be the best one. @utsavanand2 you can ping me for any ambiguity

**Comment by alexellis** [comment]
/add label: help wanted, good first issue

**Comment by kevin-lindsay-1** [comment]
Specifically, would the ideal behavior be to not pull if the files have not changed, or should updating via pull be its own separate behavior?

**Comment by nitishkumar71** [comment]
I will work on it.

**Comment by nitishkumar71** [comment]
> Specifically, would the ideal behavior be to not pull if the files have not changed, or should updating via pull be its own separate behavior?

an additional  ``--force`` should be helpful for this

**Comment by nitishkumar71** [comment]
> Specifically, would the ideal behavior be to not pull if the files have not changed, or should updating via pull be its own separate behavior?

I am planning to filter the templates for which directory exist in `./template` and pass the remaining to the `pullStackTemplates` for the pull. After this, we will only pull templates which are new in the file.

**Comment by kevin-lindsay-1** [comment]
It sounds to me like `faas-cli pull <template> --update` might be the cleanest for that behavior, then.
`--force` implies that it's potentially destructive in some way, and `--pullStackTemplates` implies that it updates all templates, which may not be what certain users want.

If the user would want to update all templates, then perhaps the command `faas-cli pull --update` could be used to update all.
