### ISSUE TITLE
Swarm - deploy prefers remote registry image over local one

### ISSUE THREAD

**Issue by johnmccabe** [openfaas/faas-cli#76]
## Expected Behaviour

If I edit the sample `url-ping` python handler in `sample/url-ping/handler.py`, run `faas-cli build -f ./samples.yml` I can see a new latest image is created `alexellis/faas-url-ping:latest`.

I would expect that running `faas-cli deploy -f ./samples.yml` would use the local `alexellis/faas-url-ping:latest` image.

## Current Behaviour

What appears to happen is that the local images are removed and `latest` is pulled from Docker hub.

## Steps to Reproduce (for bugs)

1. Edit `sample/url-ping/handler.py`, add a new print statement
2. Remove any existing function `faas-cli remove url-ping`
3. Build the samples `faas-cli build -f ./samples.yml`
3. Check the image contains your updates `docker run -ti --rm alexellis/faas-url-ping sh` 
4. Deploy the samples `faas-cli build -f ./samples.yml`
5. Hit the `url-ping` end point and see that your changes aren't applied, check the images and see that the newly build image has been replaced with the latest from the hub `docker images | grep ping`.

## Context

This behaviour is counter-intuitive when developing and complicates dev when updating functions that have been pushed to the hub.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
17.06.1-ce
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS
* Link to your project or a code example to reproduce issue:
Using the samples from faas-cli

**Comment by alexellis** [comment]
I believe this is because your image is published on the Docker Hub. When the swarm service creates your function replica it will check the Hub for a digest. What behavior do you see via the `docker CLI`?

**Comment by alexellis** [comment]
Ping @johnmccabe

**Comment by johnmccabe** [comment]
Its working the way its supposed to work, switching to my own local registry for images let me get the behaviour I wanted. Closing as invalid.

**Comment by alexellis** [comment]
Did you use TLS or insecure registry?
