### ISSUE TITLE
Support request for custom TLS certificate

### ISSUE THREAD

**Issue by den-vasyliev** [openfaas/faas-cli#761]
Different commands behavior with https gateway.
f list - works
f logs - not

www.ssllabs.com gives all green lights on tls cert

## Expected Behaviour

Expect f logs works with HTTPS gateway without --tls-no-verify

## Current Behaviour
```
1>f logs figlet
Server returned unexpected status code: 504 - upstream request timeout
```
## Steps to Reproduce (for bugs)

```
1>f logs figlet
Server returned unexpected status code: 504 - upstream request timeout

2>f logs figlet --tls-no-verify
2020-01-28T19:43:38Z 2020/01/28 19:43:38 Forking fprocess.

3>f list
Function                        Invocations     Replicas
astronaut-finder                0               1
base64                          0               1
echoit                          0               1
figlet                          0               1
```

## Context

security issue

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:
 commit:  73004c23e5a4d3fdb7352f953247473477477a64
 version: 0.11.3

Gateway
 uri:     https://faas.xxxxxx
 version: 0.18.7
 sha:     59b7839236098820e73ed25301258b722c3d33e4
 commit:  Change how and when we fetch and parse namespace info


Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       0.9.15 
 sha:           41c33f9f7c29e8276bd01387f78d6f0cff847890
Unable to find latest version online error: Head https://github.com/openfaas/faas-cli/releases/latest: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

k8s
gloo version
Client: {"version":"1.3.0"}
Server: {"type":"Knative","kubernetes":{"containers":[{"Tag":"1.3.1","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.3.1","Name":"gloo","Registry":"quay.io/solo-io"},{"Tag":"1.3.1","Name":"ingress","Registry":"quay.io/solo-io"},{"Tag":"1.3.1","Name":"gloo-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.3.1","Name":"gloo-envoy-wrapper","Registry":"quay.io/solo-io"}],"namespace":"gloo-system"}}

* Operating System and version (e.g. Linux, Windows, MacOS):

Linux, Windows, MacOS

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Hi, can you run a curl against your gateway and let us know what TLS version you're using? We've never had issues with genuine up to date TLS certs before.

Can you run `curl -v` perhaps?

Alex

**Comment by alexellis** [comment]
/set title: Support request for custom TLS certificate

**Comment by den-vasyliev** [comment]
> Hi, can you run a curl against your gateway and let us know what TLS version you're using? We've never had issues with genuine up to date TLS certs before.
> 
> Can you run `curl -v` perhaps?
> 
> I also wanted to ask if you could provide everything we request in the template, for instance under "Steps to Reproduce (for bugs)" you've given no context and nothing that I can run to reproduce the error.
> 
> We ideally need a list of everything you installed (with commands) and what's special/different about your TLS cert/set-up. For instance, I ran the same commands as you against nginx-ingress with cert-manager and it worked fine.
> 
> You may also find that Slack is a good place to get ad-hoc technical support from the community.
> 
> Alex

UPDATE:

Alex, first actually i appreciate your product and exactly code with documentation style - good job!

So i have review source code of gateway list and logs commands and no guess why first one works and second no - that is the main issue...

And.. found problem with ssl libs on macos and jump hosts affecting curl, faas-cli tls validation... 

New linux jump host and GKE cloud console works.

So openfaas under gloo and istio with custom wildcard cert works as a sharm!

Thanks for the fast reply and openfaas!
