### ISSUE TITLE
Push latest image to Docker Hub

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-cli#772]
## Expected Behaviour

`docker pull openfaas/faas-cli:latest` should work

## Current Behaviour

The image is not availabe

## Possible Solution

On each release, we should push both the versioned tag _and_ a new latest tag.

## Context

This could be helpful in CI situations, like Jenkins, Travis, or Github Actions.

**Comment by aidun** [comment]
@LucasRoesler I will take this issue

**Comment by aidun** [comment]
Should it be a flag, which defaults to true?

**Comment by aidun** [comment]
I have submited a pr for this. But I have a few questions, because I don't know much about github releases and travis:

1. What do you mean with release? A PR which is merged into the master?
2. Where is the release mechanism? So I can decide wether to push or not.

**Comment by alexellis** [comment]
We already push tags, look at the .travis.yml file to see where it all starts from. We just need to also push the latest tag along with the release version.

**Comment by aidun** [comment]
Okay, then I did it the right way in my PR. I was only concerned about the term release. But it seems that release means merged PR or direct commit. Thank you for the clarification!

________________________________
Von: Alex Ellis <notifications@github.com>
Gesendet: Monday, March 9, 2020 10:47:11 PM
An: openfaas/faas-cli <faas-cli@noreply.github.com>
Cc: Markus Hartmann <markush1986@gmail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [openfaas/faas-cli] Push latest image to Docker Hub (#772)


We already push tags, look at the .travis.yml file to see where it all starts from. We just need to also push the latest tag along with the release version.
