### ISSUE TITLE
Function is deployed, but never ready

### ISSUE THREAD

**Issue by estensen** [openfaas/faas-cli#774]
Deploying openfaas functions on KinD fails if you don't use a Docker registry

## Expected Behaviour
I expect the CLI to tell me when the deployment fails
I also expec to be able to deploy images without an image registry

## Current Behaviour
`faas-cli deploy` fails silently
Deployed functions are never ready

## Possible Solution
Push image to Docker Hub or other Docker registry

## Steps to Reproduce (for bugs)

1. Following this [tutorial](https://blog.alexellis.io/be-kind-to-yourself/) on how to use openfaas with KinD
2. There are two deviations from the tutorial:
- Instead of exporting KUBECONFIG run `kubectl cluster-info --context kind-<cluster-name>` as config-path is [deprecated](https://github.com/kubernetes-sigs/cluster-api/pull/1797) in KinD
- Also port-forward 8080 to 8080
3. Create function: `faas new --lang python3 --name nanoservice`
4. Deploy function: `faas-cli deploy -f ./nanoservice.yml`
5. Go to UI
6. Status for `nanoservice` is "not ready"
7. Test `certinfo`. It should work
8. If you switch back and forth fast `nanoservice` will have the status `ready` for some seconds, but that's more a UI glitch
9. Looking at the logs you can see that the image was never pulled `kubectl get events --sort-by=.metadata.creationTimestamp -n openfaas-fn`:

```
Failed to pull image "nanoservice:latest": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nanoservice:latest:latest": failed to resolve reference "docker.io/library/nanoservice:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

This is not clear from the UI. It seems to have been deployed and IMO the CLI should tell you that when you deploy and not fail silently.

It is the same problem as [this](https://github.com/openfaas/faas-netes/issues/135)

## Context
I'm trying to replace Minikube and Docker for mac with KinD

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:
 commit:  ea687659ecf14931a29be46c4d2866899d36c282
 version: 0.11.8

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.18.11
 sha:     326cc7a9b9235276ecf38430c49a5707a429c6c8
 commit:  Add featured videos section to community file


Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       0.10.1
 sha:           d39a153855c6fcdb17e5ecf4317964f2ccacb49d
```

* Docker version ( Full output from: `docker version` ):
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
KinD

* Operating System and version (e.g. Linux, Windows, MacOS):
macOS Catalina 10.15.3

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Sorry you'll need to use a registry. You can use the Docker Hub, or set one up in 5 minutes https://blog.alexellis.io/get-a-tls-enabled-docker-registry-in-5-minutes/

**Comment by shrout1** [comment]
It would be nice if that message were returned directly to the end user. I beat my head against this for longer than I care to admit.

**Comment by alexellis** [comment]
You should probably use the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
