### ISSUE TITLE
Proposal: Add template for golang functions

### ISSUE THREAD

**Issue by alias1** [openfaas/faas-cli#79]
## Expected Behaviour

Currently there are [templates](https://github.com/alexellis/faas-cli/tree/master/template) for:  csharp, node, python, ruby. It would be great to have a go template as well.

There is a [golang base function](https://github.com/alexellis/faas/tree/master/sample-functions/BaseFunctions/golang) in the main FaaS repository that can be used as a base. Though this could be improved even more using Docker multi-stage build syntax, and separating the golang compilation environment from the run environment (eg. static compilation)

The [faas-cli new command](https://github.com/alexellis/faas-cli/blob/master/commands/new_function.go#L45-L49) would also need to be updated to include this new template.

**Comment by alexellis** [comment]
Derek add label: skill/intermediate

**Comment by alexellis** [comment]
Want to have a go at this @alias1?

**Comment by rgee0** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
@rgee0 how practical is it to template with Golang? Should we generate a "Dockerfile" version with all the assets in the handler folder? I have the impression third party dependencies are often required beyond what you can pull with vndr or similar.

**Comment by alexellis** [comment]
I agree that we can make Hubstats multi-stage and the base Golang sample. Can someone do that initially?

**Comment by rgee0** [comment]
@alexellis initial thought was that Golang is potentially closer to the .exe use cases.  However, if we are going to include the build in the template then I think we head into the territory you're alluding to.  I'm not experienced enough with vndr to comment on that specifically.  What fuels you impression?

**Comment by alexellis** [comment]
Here's an idea - let Golang generate a Docker build. That way it's still a template but you are expected to hack on the Dockercon etc

**Comment by alias1** [comment]
This seems to have landed in https://github.com/openfaas/faas-cli/pull/145 with some additional work in https://github.com/openfaas/faas-cli/issues/146

**Comment by alexellis** [comment]
Yes - https://blog.alexellis.io/serverless-golang-with-openfaas/
