### ISSUE TITLE
faas-cli docker push denied

### ISSUE THREAD

**Issue by hermanslagman** [openfaas/faas-cli#795]
I'm following the tutorial: Deploy your first Serverless Function to Kubernetes

When I try to build the example function I get:
----------------------------
herman@Gandalf:~$ faas-cli up -f serverless.yml
[0] > Building serverless.
Clearing temporary build folder: ./build/serverless/
Preparing: ./serverless/ build/serverless/function
Building: hslagman/serverless:latest with python3 template. Please wait..
Sending build context to Docker daemon  10.75kB
Step 1/29 : FROM openfaas/classic-watchdog:0.18.1 as watchdog
...
Step 29/29 : CMD ["fwatchdog"]
 ---> Using cache
 ---> a3e9a645cf0e
Successfully built a3e9a645cf0e
Successfully tagged hslagman/serverless:latest
Image: hslagman/serverless:latest built.
[0] < Building serverless done in 0.29s.
[0] Worker done.

Total build time: 0.29s

[0] > Pushing serverless [hslagman/serverless:latest].
The push refers to repository [docker.io/hslagman/serverless]
bd45551b3487: Preparing
...
denied: requested access to the resource is denied
2020/04/12 12:43:45 ERROR - Could not execute command: [docker push hslagman/serverless:latest]
herman@Gandalf:~$
----------------------------------------
From the command line:
----------------------------------------------------------------
herman@Gandalf:~$ docker push hslagman/serverless:latest
The push refers to repository [docker.io/hslagman/serverless]
bd45551b3487: Layer already exists
...
latest: digest: sha256:cdffca10d0e0b20ef07d287bf11ede5fecd5cb2f62789e8248f4c6e9ce34a57f size: 4281
----------------------------------------------

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
CLI:
 commit:  2d183c713b32385831dc7f69c073e57c06e3b76c
 version: 0.12.2

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.18.13
 sha:     f6526929665cb05ceaca7c9c90a6bd7c5f32dca2
 commit:  Fix test on help description message

Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       0.10.1
 sha:           d39a153855c6fcdb17e5ecf4317964f2ccacb49d
* Docker version ( Full output from: `docker version` ):
herman@Gandalf:~$ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:22:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

* Operating System and version (e.g. Linux, Windows, MacOS):
Windows WSL with Pengwin

**Comment by alexellis** [comment]
Did you run docker login?

**Comment by alexellis** [comment]
Closing as we don't handle support requests via GitHub. Feel free to sign up to slack (link in docs)

**Comment by hermanslagman** [comment]
Well I don't see it as support, but as an issue with faas-cli. But that's ok.

**Comment by alexellis** [comment]
Our documentation and the workshop both instruct users to log in. When there's nothing wrong with the application and the documentation covers the request already, it's technical support. Not a problem, but we use Slack for that. 👍
