### ISSUE TITLE
Return types.Gatewayinfo instance from proxy.SystemInfo

### ISSUE THREAD

**Issue by viveksyngh** [openfaas/faas-cli#796]
Right now `proxy.SystemInfo` returns `map[string]interface{}`

## Expected Behaviour

It should return and instance for `types.Gatewayinfo `.

## Current Behaviour

It returns an  instance `map[string]interface{}`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
@viveksyngh are you working on this?

**Comment by alexellis** [comment]
@viveksyngh can you take this one please?

**Comment by viveksyngh** [comment]
derek assign: me

**Comment by alexellis** [comment]
Does GatewayInfo exist yet?

**Comment by viveksyngh** [comment]
We have `GatewayInfo` in `github.com/openfaas/faas/gateway/types`. There is challenge with this API is as it has two different version. There is legacy version and there is current version which we use today. They are very different in structure that might be the reason why we are still using interface as return value. If we need to support both version we will have return the result as `map[string]interface{}` so that consumer can parse consume these responses.

```
func getProviderDetails(m map[string]interface{}) (name, orchestration, sha, version string) {
	if k, ok := m["provider"]; ok {
		if kv, ok := k.(map[string]interface{}); ok {
			name, orchestration, sha, version = getProviderDetailsCurrent(kv)
		} else {
			name, orchestration, sha, version = getProviderDetailsLegacy(m)
		}
	}

	return
}

func getProviderDetailsLegacy(m map[string]interface{}) (name, orchestration, sha, version string) {
	name = m["provider"].(string)
	orchestration = m["orchestration"].(string)
	v := m["version"].(map[string]interface{})
	version = v["release"].(string)
	sha = v["sha"].(string)

	return
}

func getProviderDetailsCurrent(m map[string]interface{}) (name, orchestration, sha, version string) {
	v := m["version"].(map[string]interface{})
	version, ok := v["release"].(string)
	if !ok {
		version = ""
	}
	sha, ok = v["sha"].(string)
	if !ok {
		sha = ""
	}
	name, ok = m["provider"].(string)
	if !ok {
		name = ""
	}
	orchestration, ok = m["orchestration"].(string)
	if !ok {
		orchestration = ""
	}

	return
}
```

**Comment by alexellis** [comment]
There is no legacy version in use as far as I'm aware.

Just faas-netes and faasd, anything else will be out of scope. Can you check both and update accordingly?

**Comment by viveksyngh** [comment]
Sure
