### ISSUE TITLE
Move the CLI auth from the commands pkg 

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-cli#797]
## Expected Behaviour

We should be able to vendor the CLI auth without needing to vendor the entire commands package

## Current Behaviour

Currently you must import from both  commands and config to generate the CLI auth

```go
import (
    "github.com/openfaas/faas-cli/commands"
)

//....
//...

auth := commands.NewCLIAuth(token, gateway)
```

but this means the entire commands package is now vendored into the project.

## Possible Solution

Move the `NewCLIAuth` to the `config` package or the `proxy` package. 

## Context

I would like to enable auth in the certifier and it seems best to reuse the auth and config from the CLI to enable this.  Reusing the code from the CLI ensures that we test the CLI auth as well as the provider auth at the same time.

**Comment by viveksyngh** [comment]
Dereke assign: me
