### ISSUE TITLE
Support request

### ISSUE THREAD

**Issue by petvek** [openfaas/faas-cli#799]
It would be nice if the node_modules folder is skipped when preparing the build-folder

## Expected Behaviour
When doing a build, the node_modules folder is skipped.

## Current Behaviour
When doing a build, the node_modules folder is also being copied. 

## Possible Solution
Skip the node_modules folder

## Steps to Reproduce (for bugs)
1. Create a function from a template based on nodejs
2. Add/install some npm packages
3. Do a build with the faas-cli command
4. The node_modules folder will also be copied to the build folder

## Context
This significantly increases the build time

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:                                                     
 commit:  3b98878aa1b6300e1f9e1cb5ef2a28cdc6b6c1c1       
 version: dev                                            

Gateway                                                  
 uri:     http://127.0.0.1:8080                          
 version: 0.18.13                                        
 sha:     f6526929665cb05ceaca7c9c90a6bd7c5f32dca2       
 commit:  Fix test on help description message           
                                                         
                                                         
Provider                                                 
 name:          faas-swarm                               
 orchestration: swarm                                    
 version:       0.8.5                                    
 sha:           bb8b883758b07c23314bea83195642a38f4b6301 
```
* Docker version ( Full output from: `docker version` ):
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
   Docker Swarm 

* Operating System and version (e.g. Linux, Windows, MacOS):
   Windows

* Link to your project or a code example to reproduce issue:
  /

**Comment by alexellis** [comment]
Is there a reason you haven't given steps to reproduce this?

Which template are you using?
