### ISSUE TITLE
[Feature] Support for logs in namespaces

### ISSUE THREAD

**Issue by martindekov** [openfaas/faas-cli#801]
The `faas-netes` provider along with the SDK has a way in which you can specify namespaces for log requests. The namespaces support should be added for the logs.

## Expected Behaviour

Check logs of `figlet` in `dev` namespace:
```
faas-cli logs figlet --namespace dev
```
or
```
faas-cli logs figlet.dev
```
And one of the commands should succeed.

## Current Behaviour

Logs does not support this feature

## Possible Solution

Imaplement `--namespace` flag in [logs](https://github.com/openfaas/faas-cli/blob/master/commands/logs.go) see [list](https://github.com/openfaas/faas-cli/blob/master/commands/list.go) for example

## Steps to Reproduce (for bugs)

1. Try logs in dev namespace `faas-cli logs figlet --namespace dev`
2. Check:
```
Unknown flag: --namespace
```
3. Try by naming convention `faas-cli logs figlet.dev`
4. Check:
```
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
Handling connection for 8080
Server returned unexpected status code: 500 - unknown log request error (500)
```

## Context

Logs on the server side now support namespaces, the client should follow.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
Latest
* Docker version ( Full output from: `docker version` ):
18.04
* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
Kubernetes
* Operating System and version (e.g. Linux, Windows, MacOS):
N/A
* Link to your project or a code example to reproduce issue:
Check `Steps to Reproduce`

**Comment by alexellis** [comment]
Fixed in #802
