### ISSUE TITLE
faas-cli list Server returned unexpected status code: 404 - 404 page not found

### ISSUE THREAD

**Issue by mailahmeduk** [openfaas/faas-cli#806]
All faas-cli functions failing with 404 error, but the url is working perfectly fine
Server returned unexpected status code: 404 - 404 page not found

## Expected Behaviour

Should give a list of deployed functions

## Current Behaviour

$ faas-cli list
Server returned unexpected status code: 404 - 404 page not found

## Steps to Reproduce (for bugs)

1. Follow the workshop and Docker with Swarm
2. Lab 2 - Test things out
3. Tried port 8080 and 8000, nothing else is running on the port
4.

## Context

Doing the workshop

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
$ faas-cli version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  4c7ad39a5496a624420243e6eeb44af5c12809b9
 version: 0.12.3

* Docker version ( Full output from: `docker version` ):
$ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
 Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Windows

* Link to your project or a code example to reproduce issue:
Workshop

**Comment by mailahmeduk** [comment]
![image](https://user-images.githubusercontent.com/44420759/80773541-8f635700-8b9d-11ea-9205-922569593aa6.png)

**Comment by mailahmeduk** [comment]
![image](https://user-images.githubusercontent.com/44420759/80773587-ac982580-8b9d-11ea-9ff6-e1c8ea9b3fef.png)

**Comment by mailahmeduk** [comment]
![image](https://user-images.githubusercontent.com/44420759/80773646-da7d6a00-8b9d-11ea-9ece-19df2bbf7d75.png)

**Comment by mailahmeduk** [comment]
404 errors not found in below logs
$ docker service logs --tail 100 func_gateway
$ docker service logs --tail 100 func_faas-swarm

**Comment by alexellis** [comment]
The problem is that you've changed the port to 8000, in which case you know have to provide a `--gateway` flag or set the `OPENFAAS_URL` environment variable.

**Comment by alexellis** [comment]
Please use Slack for technical support, not GitHub.

**Comment by alexellis** [comment]
No issues found:

```
kosmos:faas alex$ docker swarm init
Swarm initialized: current node (rmdreg1rug3bzow779tics9gy) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join --token SWMTKN-1-4bqhmz2qqx64s7p5pstg8ebfvczum8123933wjhy5ptrgbm5xz-12e52gtchxvoxh1yjeodjdc9o 192.168.65.3:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.

kosmos:faas alex$ ./deploy_stack.sh 
Attempting to create credentials for gateway..
venyt7d9c1dcxs5x06a26ngzm
0dl1eri557g21zhy3h3r8lvi4
[Credentials]
 username: admin 
 password: 013ef60aeabdd643cee64f2bba8a8834023cb7f6631acf1a64f57fe33a862bd8
 echo -n 013ef60aeabdd643cee64f2bba8a8834023cb7f6631acf1a64f57fe33a862bd8 | faas-cli login --username=admin --password-stdin
Enabling basic authentication for gateway..

Deploying OpenFaaS core services
Creating network func_functions
Creating config func_alertmanager_config
Creating config func_prometheus_config
Creating config func_prometheus_rules
Creating service func_prometheus
Creating service func_alertmanager
Creating service func_gateway
Creating service func_basic-auth-plugin
Creating service func_faas-swarm
Creating service func_nats
Creating service func_queue-worker
kosmos:faas alex$ 
kosmos:faas alex$ 
kosmos:faas alex$  echo -n 013ef60aeabdd643cee64f2bba8a8834023cb7f6631acf1a64f57fe33a862bd8 | faas-cli login --username=admin --password-stdin
Calling the OpenFaaS server to validate the credentials...
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
credentials saved for admin http://127.0.0.1:8080
kosmos:faas alex$ faas-cli list
Function                      	Invocations    	Replicas
kosmos:faas alex$ 
```
