### ISSUE TITLE
Proposal: Alter templates to run as non-privileged user

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#81]
## Expected Behaviour

Instead of "root" let's run as a non-privileged user

## Current Behaviour

They use the default root user.

## Possible Solution

https://github.com/alexellis/faas-cli/blob/master/template/node/Dockerfile

**Comment by johnmccabe** [comment]
Derek add label: enhancement

**Comment by alexellis** [comment]
Work in progress above.

**Comment by alexellis** [comment]
WIP. Closing issue.
