### ISSUE TITLE
TLS certificate is generated but it's still showing not secure in the browser .

### ISSUE THREAD

**Issue by priyankak1212** [openfaas/faas-cli#810]
@alexellis I am facing the same issue. TLS certificate is generated but it's still showing not secure in the browser .

Expected Behaviour
Whenever we search for api.devnm.es/api, it should redirect from HTTP to HTTPS and must be secure as TLS certificate is applied. OpenFaas UI must there on this API.

Current Behaviour
Whenever I am searching for api.devnm.es/api, it's getting redirected from HTTP to HTTPS but showing not secure even though TLS certificate is applied.

Your Environment
FaaS-CLI version ( Full output from: faas-cli version ): 0.12.1

Docker version ( Full output from: docker version ): 19.0.3

Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)? : OpenFaas Kubernetes on Digital Ocean

Operating System and version (e.g. Linux, Windows, MacOS): Centos 7

When I am ddoing loging from fass-cli, it's giving me the following error.
Cannot connect to OpenFaaS on URL: https://api.devnm.es. Get https://api.devnm.es/system/functions: x509: certificate signed by unknown authority

Please help me on this issue.
@alexellis Thanks

**Comment by alexellis** [comment]
Hi, I took a look at your certificate the other day - I think you mentioned this somewhere else? Do you have another issue like this?

The core issue is that you're using a staging certificate and not a production one. Switch your issuer to the production one and issue it again.

<img width="548" alt="Screenshot 2020-06-02 at 09 38 32" src="https://user-images.githubusercontent.com/6358735/83499189-db632d80-a4b4-11ea-9350-bb601f589fcc.png">

If you need further help with cert-manager, there is a channel on the Kubernetes Slack - https://slack.k8s.io/
Alex

**Comment by priyankak1212** [comment]
> Hi, I took a look at your certificate the other day - I think you mentioned this somewhere else? Do you have another issue like this?
> 
> The core issue is that you're using a staging certificate and not a production one. Switch your issuer to the production one and issue it again.
> 
> <img alt="Screenshot 2020-06-02 at 09 38 32" width="548" src="https://user-images.githubusercontent.com/6358735/83499189-db632d80-a4b4-11ea-9350-bb601f589fcc.png">
> 
> If you need further help with cert-manager, there is a channel on the Kubernetes Slack - https://slack.k8s.io/
> Alex

@alexellis Yes, I issued staging certificate only. Not issued production one. I will check with that.

**Comment by alexellis** [comment]
That is the reason you are running into errors.

**Comment by alexellis** [comment]
As I mentioned before - for K8s, nginx-ingress and cert-manager support please see https://slack.k8s.io - for openfaas you can also approach https://slack.openfaas.io/
