### ISSUE TITLE
Allow configuring "build" folder.

### ISSUE THREAD

**Issue by doowb** [openfaas/faas-cli#814]
## Expected Behaviour

I would like to be able to configure the root folder that is used for "building" the functions.

## Current Behaviour

Currently, `./build` is [hard coded](https://github.com/openfaas/faas-cli/blob/080cde3a486e2cb7d72e411874f6e57b11073959/builder/build.go#L168) as the root folder used during the build as the Docker build context.

## Possible Solution

Allow configuring this folder, leaving the default as `build` for backward compatibility.
I suggest this follows the same rules as `copyExtraPaths` to allow specifying in the `stack.yml` or as a command line flag.

## Context

I use the `./build` folder differently than the `faas-cli` and I would like to be able to configure `faas-cli` so I don't impact conventions I already use.

**Comment by alexellis** [comment]
@doowb what problem does this solve? I am probably not reading this carefully enough, but can't see any technical or functional reason why this would be needed?

Feel free to add detail in your request.

**Comment by doowb** [comment]
I have a convention of putting build related code in a `./build` folder. If I want to introduce OpenFaaS in the same project, the `faas-cli` is doing 2 things that conflict with my convention:

- Adds `template` and `build` to `.gitignore` when creating a new function
  This conflicts with my conventions if I'm expecting to use some of my build related code in my CI/CD pipeline.
- Copies to and deletes folders within the `./build` folder during the build process.
  This might not be an issue if there aren't any conflicting folders or files in the `./build` folder, but allowing this option to be configurable would reduce the risk of accidentally losing something.

I have seen other tools make use of the `./build` folder for generating distributable assets, but I have been able to configure that destination to match my own conventions.

**Comment by alexellis** [comment]
Ok, thanks for the context. I'm going to close the issue so that we can gauge interest from other users. Happy to revisit at a future date.
