### ISSUE TITLE
Context Deadline Exceeded

### ISSUE THREAD

**Issue by oze4** [openfaas/faas-cli#819]
Run: `faas-cli template store pull node10-express`

Error: `Error while fetching templates from store: error while requesting template list: Get https://raw.githubusercontent.com/openfaas/store/master/templates.json: context deadline exceeded`

This happens when running `faas-cli template store list` as well.

On Catalina 10.15.6

K8 cluster is v1.18.8

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Hi, thanks for your interest. Why don't you try running your command again?

FYI: I'm not getting that error on my computer, can I direct you to Slack? Perhaps you can find other Catalina users there and ask them if they get the same issue.

I'll close this out now, and re-open if we find a problem with Catalina (I suspect this is specific to your environment, or network conditions)

**Comment by oze4** [comment]
Sorry about that. The issue was I had to use the --gateway switch.

**Comment by alexellis** [comment]
That would be unrelated to the store..
