### ISSUE TITLE
Add better support for CI/CD environments

### ISSUE THREAD

**Issue by utsavanand2** [openfaas/faas-cli#830]
faas-cli can be improved to better handle running in CI/CD environments

## Expected Behaviour

Running faas-cli in CI/CD environments should allow for more permissive permissions for the artifacts created by `faas-cli login` and `faas-cli build`, so these files can be shared across multiple users in a CI/CD environment.
The location of the `.openfaas/config.yml` dir should be the current dir rather than the $HOME dir in a CI environment.
These change in behaviour should be able to be toggled with a simple env var or a flag.

## Current Behaviour

faas-cli does not have the aforementioned behaviour making it really difficult to run the container image of faas-cli in a CI environment without making the workflow configuration too complex for the average user.

## Possible Solution

PR #831 

## Context

Running the containerised version of faas-cli in Github Actions is difficult without making the workflow action YAML too complicated.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.12.13

**Comment by alexellis** [comment]
Linked PR was merged. @utsavanand2 in future please use closing keywords in your commit or PR text, i.e. `Closes: #` or `Fixes: #` - otherwise it leaves dangling issues like this one.

**Comment by utsavanand2** [comment]
Sure @alexellis ! I left it without the keyword initally, so I don't spam a lot of `forced-pushed` messages here. Thought I would do that in the end when the changes are finalised after review. But forgot about it. Will keep this in mind.
