### ISSUE TITLE
faas-cli login gives "Cannot connect to OpenFaaS on URL..." + "net/http: request canceled (Client.Timeout exceeded while awaiting headers)"

### ISSUE THREAD

**Issue by r3mattia** [openfaas/faas-cli#833]
I am trying to use `faas up -f function.yml` which tells me:

```
unauthorized access, run "faas-cli login" to setup authentication for this server
```

after building my image with no errors.

When I try to to use `faas-cli login` with the following login command:

```
echo -n $OPENFAAS_PASS | faas login -g $OPENFAAS_URL -u admin --password-stdin
```
I am unable to login.

$OPENFAAS_PASS and $OPENFAAS_URL works in my browser, as does the admin user.

## Expected Behaviour
I expect to successfully login. 

## Current Behaviour
I get this error:

```
Cannot connect to OpenFaaS on URL: http://$OPENFAAS_URL. Get http://$OPENFAAS_URL/system/functions: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

Where $OPENFAAS_URL is defined with IP:PORT and PORT is 8080. 

## Steps to Reproduce (for bugs)
In this case I've deployed OpenFaaS using the Helm chart to a private AKS cluster.
The AKS cluster is managed from a boot-node, which is the machine I've used to deploy OpenFaaS, and the machine I have installed the `faas-cli` on. Therefore, I am running the `faas-cli login` command from the boot-node.

## Context
I am trying to establish a cheaper, more secure function runtime environment, and would really like to use OpenFaaS.

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:
 commit:  c12d57c39ac4cc6eef3c9bba2fb45113d882432f
 version: 0.12.14

Gateway
 uri:     http://51.11.0.50:8080
 version: 0.18.18
 sha:     11ff356ccea32b89b9da556c18305cd7c5ea9ba5
 commit:  Remove service namespace from scale request


Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       0.12.3 
 sha:           811e55497a0431b438e0d628265a262f2267dbb0
```

* Docker version ( Full output from: `docker version` ):
```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:03:03 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:33 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
Kubernetes
* Operating System and version (e.g. Linux, Windows, MacOS):
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
* Link to your project or a code example to reproduce issue:
NA

**Comment by alexellis** [comment]
I'm going to close this issue since there is no bug with OpenFaaS, this is a technical support request which we handle through Slack.
