### ISSUE TITLE
https://cli.openfaas.com script not working

### ISSUE THREAD

**Issue by Skikepok** [openfaas/faas-cli#844]
The installation command `curl -sSL https://cli.openfaas.com | sh ` does not work anymore (it worked an hour ago).

## Expected Behaviour
This script is supposed to install the faas-cli script on the machine

## Current Behaviour
Running the command currently fails with the following error:

```bash
$ curl -sSL https://cli.openfaas.com | sh
Finding latest version from GitHub
0.12.16
Downloading package https://github.com/openfaas/faas-cli/releases/download/0.12.16/faas-cli as /tmp/faas-cli
sha256sum: can't open 'bin/faas-cli': No such file or directory
sha256sum: WARNING: 1 of 1 computed checksums did NOT match
Binary checksum didn't match. Exiting
```

## Steps to Reproduce (for bugs)
1. Run the command `curl -sSL https://cli.openfaas.com | sh`

## Context
I'm using that command to install faas-cli on my gitlab CI/CD and suddenly it stopped working

## Your Environment
* Operating System and version: Ubuntu 20;04

**Comment by alexellis** [comment]
Thanks for reporting this. I'm taking a look.

My initial feeling is that our shasum file now uses the "bin/faas-cli" format where before it used "faas-cli", which is causing the 404 error.

**Comment by alexellis** [comment]
Thanks for reporting the issue.

This is fixed by:

9e3c15ef3ad7bd7cceb0cd577144aebb50c6681c Move back out of ci folder after hashgen by @alexellis
a1b891909977657e616656be6dce651d1ae1c361 Update hashgen not to inject bin in the path by @alexellis

I would recommend not using a bash script to download faas-cli in production, but instead pinning to a specific version and upgrading that periodically.

**Comment by alexellis** [comment]
```bash
space-mini:faas-cli alex$ curl -sSL https://cli.openfaas.com | sudo sh
Password:
Finding latest version from GitHub
0.12.18
Downloading package https://github.com/openfaas/faas-cli/releases/download/0.12.18/faas-cli-darwin as /tmp/faas-cli-darwin
Download complete.

Running with sufficient permissions to attempt to move faas-cli to /usr/local/bin
New version of faas-cli installed to /usr/local/bin
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  9e3c15ef3ad7bd7cceb0cd577144aebb50c6681c
 version: 0.12.18
space-mini:faas-cli alex$ 
```

I would encourage you and team to look into: [Get the most out of OpenFaaS as an end-user](https://github.com/openfaas/faas/issues/1591)
