### ISSUE TITLE
Cannot install faas-cli using get.sh script

### ISSUE THREAD

**Issue by zhangcicely** [openfaas/faas-cli#856]
## Expected Behaviour
I am trying to install faas-cli by following the curl command provided in README
curl -sSL https://cli.openfaas.com | sudo sh
I expect it to install properly, and it works before

## Current Behaviour
Right now, by running this command, it failed with this error

$ curl -sSL https://cli.openfaas.com | sudo sh

Finding latest version from GitHub
0.12.21socket-worker-5029ae85.js
Downloading package https://github.com/openfaas/faas-cli/releases/download/0.12.21socket-worker-5029ae85.js/faas-cli as /tmp/faas-cli
sha256sum: 'standard input': no properly formatted SHA256 checksum lines found
Binary checksum didn't match. Exiting

## Steps to Reproduce (for bugs)

1. Run in ubuntu the following command "curl -sSL https://cli.openfaas.com | sudo sh"
2.
3.
4.

## Context

A show stopper, cannot install faas-cli

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version ( Full output from: `docker version` ):
  19.03.13
* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
       kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
      ubuntu

* Link to your project or a code example to reproduce issue:

**Comment by michalke-it** [comment]
Having the same issue, https://github.com/openfaas/faas-cli/releases/download/0.12.21socket-worker-5029ae85.js/faas-cli returns 404 at the moment.
However, the binary is still accessible in the releases section, so you can work around this like this (change link to target file if not on amd64 platform):
sudo wget https://github.com/openfaas/faas-cli/releases/download/0.12.21/faas-cli && sudo mv faas-cli /usr/local/bin/ && sudo chmod +x /usr/local/bin/faas-cli

Hope this helps until it is fixed.

**Comment by tshakhmu-dev** [comment]
So problem right now is located on identifying latest version from github. Right now we have `curl -sI https://github.com/openfaas/faas-cli/releases/latest|grep -i location
`
I guess we are expecting to see redirect header like
`Location: https://github.com/openfaas/faas-cli/releases/tag/0.12.21`
instead we are facing 
`Location: https://github.com/openfaas/faas-cli/releases/tag/0.12.21
Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events wss://alive.github.com online.visualstudio.com/api/v1/locations; font-src github.githubassets.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com; img-src 'self' data: github.githubassets.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; manifest-src 'self'; media-src 'none'; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; worker-src github.com/socket-worker-5029ae85.js gist.github.com/socket-worker-5029ae85.js`
As a result we have latest version like `0.12.21socket-worker-5029ae85.js`
Easiest way would be doing 
`curl -sI https://github.com/openfaas/faas-cli/releases/latest|grep -i location:`

**Comment by alexellis** [comment]
Hi all, we have put a PR up for this. 

Please see: https://github.com/openfaas/cli.openfaas.com/pull/6

Please pay specific attention to the section "Anything else we should know?"

You can continue to download faas-cli via the releases page, brew and "arkade get"

Best,

Alex

**Comment by zhangcicely** [comment]
Thanks @alexellis @michalke-it , and the workaround from @michalke-it  works well, thanks a lot for sharing
