### ISSUE TITLE
Add registry-login command from ofc-bootstrap

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#858]
In faasd, when you need to get a private registry configuration, it requires a Docker registry secret that's unencrypted, but Docker Desktop puts passwords in the keychain.

## Expected Behaviour

```
faas-cli registry-login \
  --username <your-registry-username> \
  --password-stdin
# (the enter your password and hit return)
```

## Current Behaviour

Available in ofc-bootstrap:

```
ofc-bootstrap registry-login \
  --username <your-registry-username> \
  --password-stdin
# (the enter your password and hit return)
```

## Possible Solution

Given that this is now useful for faasd as well as OFC - we can promote it into the main CLI.

I'm open to suggestions on whether `registry-login` is the correct name / wording.

## Steps to Reproduce (for bugs)

1. Get a private registry
2. Try `docker login` on Mac or Windows and see that your ~/.docker/config.json doesn't have a secret in it, but a reference to a keychain
3. Copy over to the faasd instance, and see that it fails

## Context

It seems odd to install ofc-bootstrap for this task, and OpenFaaS Cloud is likely going to be deprecated, if not put on hold for the time being.

**Comment by alexellis** [comment]
@Waterdrips want to take a look at this?

**Comment by alexellis** [comment]
This issue needs a past contributor or openfaas member to pick it up and deliver it.

**Comment by nitishkumar71** [comment]
I will pick this up.
