### ISSUE TITLE
faas-cli secret create corrupts the secret when there is a whitespace at the end

### ISSUE THREAD

**Issue by kissgyorgy** [openfaas/faas-cli#859]
In my specific case, I wanted to create OpenSSH private keys, but this is a general issue.
SSH private keys MUST have a new line at the end, but the `faas-cli secret create` command trims the secret value.

This is the problematic line, it should be simply removed: https://github.com/openfaas/faas-cli/blob/356b9130018debcce7ef291843e5c3247c07c7f9/commands/secret_create.go#L102

**Comment by alexellis** [comment]
@kissgyorgy we appreciate your interest in the project. We can take a look at this, but first please edit your issue and use the template.

I assume that you were in a rush, but this is very easy for you to edit and fix - https://raw.githubusercontent.com/openfaas/faas-cli/master/.github/ISSUE_TEMPLATE.md

**Comment by alexellis** [comment]
I assume that being asked to fill in the template is why you closed your issue, however you can also create openfaas secrets via kubectl which will not trim any trailing lines.

**Comment by alexellis** [comment]
https://docs.openfaas.com/reference/secrets/#define-a-secret-in-kubernetes-advanced

**Comment by alexellis** [comment]
/set title: [Feature request] Make trimming newlines optional for secret creation

**Comment by kissgyorgy** [comment]
> /set title: [Feature request]

When something **corrupts** the data, it's clearly a bug. This is not a feature request.

> you can also create openfaas secrets via kubectl

Yes, I do that.
