### ISSUE TITLE
Core supported languages

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#86]
This issue tracks the core supported languages by the FaaS-CLI. This is a finite set of languages the project maintainers are happy to support.

## Existing

* CSharp / .NET standard 2.0
* Node.js
* Python
* Ruby

## Candidates

* Golang
* Java

These may be covered by community support #85 

* #55 PHP
* #84 Perl
* Swift via @nicholasjackson

Anything else can be submitted as a "sample-function" to:

http://github.com/alexellis/faas/blob/master/sample-functions/

Alex

**Comment by alex-dixon** [comment]
Hi. I see a sample function was added for Clojure (#89). Is there a process for adding support for `--lang clojure` to the cli along with the other magic you provide for the currently supported languages? Thanks! :)

**Comment by austinfrey** [comment]
@alex-dixon i think the idea is that there will be a few core supported languages, with the ability to add you own templates from GitHub using a flag. check this pull request for details #87

**Comment by alexellis** [comment]
Custom templates are now possible and documented too. @alex-dixon if you'd like to set one up for Clojure that would be great.
