### ISSUE TITLE
Feature request: execute faas-cli not only from directory with functions

### ISSUE THREAD

**Issue by egorsmth** [openfaas/faas-cli#861]
## Expected Behaviour
I need to execute faas-cli from any directory not only where functions are.

## Current Behaviour
Right know it seems I only can execute it in directory with function, I get that error if I execute it in another directory:
`faas-cli build -f path/to/stack.yaml`
```
Errors received during build:
- building somename/funcname:latest-fa1bf8e494, ./funcname is an invalid path
```

## Possible Solution
 May be add flag --dir with directory of functions

## Context
I try to run faas-cli from java runtime, where you can't execute `cd` to change execution directory. Also repository with my functions can't be pulled to root of runtime.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):CLI:
 commit:  598336a0cad38a79d5466e6a3a9aebab4fc61ba9
 version: 0.12.21

* Docker version ( Full output from: `docker version` ):
```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)? Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS): ubuntu 20.04

**Comment by egorsmth** [comment]
@alexellis edited by template, is it ok?

**Comment by alexellis** [comment]
Yes that's appreciated.

> I try to run faas-cli from java runtime, where you can't execute cd to change execution directory. Also repository with my functions can't be pulled to root of runtime.

Can you explain that in a little more detail?

What are you trying to achieve there, because we may have other ways for you.

**Comment by egorsmth** [comment]
Sorry my mistake, I can execute commands from specific folders with java.
