### ISSUE TITLE
Support request for timeout during login command

### ISSUE THREAD

**Issue by yogsoft** [openfaas/faas-cli#862]
https://github.com/openfaas/faas-cli/blob/f65bf00e2fc6ce7e1dcca25823c9bf577c18077f/commands/login.go#L109

## Expected Behaviour

login command time-out should be made configurable either via environment variable or CLI argument.

## Current Behaviour

5 Seconds login timeout hard-coded in code which makes login command fail if gateway command does not respond in 5 seconds and makes it impossible to get around this timeout. 

## Possible Solution

login timeout can be made less aggressive and/or should allowed to be override it using CLI argument or configuration or environment variable.

## Steps to Reproduce (for bugs)

Make the gateway respond more than 5 seconds for login call

## Context

Applies to containerized as well non-containarized platform

## Your Environment

* FaaS-CLI version: 0.12.21

* Docker version ( Full output from: `docker version` ):
N/A

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
N/A

* Operating System and version (e.g. Linux, Windows, MacOS): 
Linux

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
/set title: Support request for timeout during login command

**Comment by yogsoft** [comment]
@alexellis details are in issue now. Can you please remove invalid tag on this?

**Comment by alexellis** [comment]
The issue should say whether this is something that affected you. Did it? And in what scenario? The CLI has had this timeout for a considerable amount of time, so we need to understand the scenario where a simple basic auth validation in openfaas takes > 5s.

**Comment by yogsoft** [comment]
@alexellis I faced timeout while running command from `WSL` connecting to OpenFaaS deployed on Kubernetes behind ingress. I don't really think this timeout is because of server side execution in Gateway but it could be due to network latency.

In the network latency scenario, I am hoping, I should be able to specify longer timeout for login command. If there is way to specify in timeout, please let me know.

**Comment by alexellis** [comment]
I can't remember if there is a configuration item for this, I suspect that there isn't. My take is that the community will not want to add this feature if it's not a problem that many people run into.

Are you still hitting this, or was it a one-off?

WSL shouldn't add 5 seconds to this call and I wonder if it was ever going to complete if it took 5 seconds?

**Comment by yogsoft** [comment]
Yes, timeout frequency is higher, probably due to network latency. Sometimes it is working when its taking 4 seconds. 

Is there any chance to increase timeout to 10 or 20 seconds for login?

`deploy` command seems to be having 60 seconds timeout.

https://github.com/openfaas/faas-cli/blob/88a6baff343cc4ccaa9402c533e88e6462c3df5d/proxy/deploy.go#L21

**Comment by alexellis** [comment]
PR #864 raised for this.

**Comment by yogsoft** [comment]
Thanks @alexellis  for quick turnaround!
