### ISSUE TITLE
Openfaas faas-cli deployment 401 error

### ISSUE THREAD

**Issue by krotofil** [openfaas/faas-cli#867]
Hello together, 

we deployed an openfaas locally version on our VM ubuntu Image.

**Our Version:** 
```
__                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  ec002af3c1ef848c507080a83a4e5c6ec6dab308
 version: 0.13.5

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.20.8
 sha:     d5b98a70783019f171553a99e604250ed72aa89a


Provider
 name:          faasd
 orchestration: containerd
 version:       0.11.0 
 sha:           0bf221b286ea07291a5e62e109e6c62103fb1669
Your faas-cli version (0.13.5) may be out of date. Version: 0.13.6 is now available on GitHub.
´
```

First of all we build an easy testing go function -> named classic-go

if we running the comand faas-cli up -f classic-go.yml, they starting to build the Docker Image:

```
/mnt/hgfs/SCAP/services/faas$ faas-cli up -f classic-go.yml
[0] > Building classic-go.
Clearing temporary build folder: ./build/classic-go/
Preparing: ./classic-go/ build/classic-go/function
Building: ecedevweubscapacr.azurecr.io/classic-go:latest with go template. Please wait..
Sending build context to Docker daemon  8.704kB
Step 1/35 : FROM --platform=${TARGETPLATFORM:-linux/amd64} ghcr.io/openfaas/classic-watchdog:0.1.5 as watchdog
 ---> c164772f02dd
Step 2/35 : FROM --platform=${BUILDPLATFORM:-linux/amd64} golang:1.15-alpine3.13 as builder
 ---> 85ad54a21c4a
Successfully built 40fb055a632e
Successfully tagged XXXXXXXXXXX.azurecr.io/classic-go:latest
Image: XXXXXXXXXXX.azurecr.io/classic-go:latest built.
[0] < Building classic-go done in 0.30s.
[0] Worker done.

Total build time: 0.30s

```
After that, tehy Pushing it into our Azure Container Registry:

```
[0] > Pushing classic-go [XXXXXXXXXXX.azurecr.io/classic-go:latest].
The push refers to repository [XXXXXXXXXXX.azurecr.io/classic-go]
8c784e795e15: Layer already exists 
2374a52a21f7: Layer already exists 
ce82abc7147e: Layer already exists 
058a47023f77: Layer already exists 
be6f72eb5279: Layer already exists 
777b2c648970: Layer already exists 
latest: digest: sha256:9bd8b2023f821c2f8ed83bfe40d1cef4097a8eb8d7ec0887072679eef6b6ed26 size: 1577
[0] < Pushing classic-go [XXXXXXXXXXX.azurecr.io/classic-go:latest] done.
[0] Worker done.
```

Now your deployment goes fail with these Code:

Deploying: classic-go.

`Unexpected status: 400, message: unable to pull image XXXXXXXXXXX.azurecr.io/classic-go:latest: cannot pull: failed to resolve reference "XXXXXXXXXXX.azurecr.io/classic-go:latest": failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized`

We checked following steps:

1. pull & pushing manually with docker comand works fine
2. if we use another Regstry to pull images (DockerHub) works fine

We configure our classic-go.yaml as well:

```
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  classic-go:
    lang: go
    handler: ./classic-go
    image: XXXXXXXXXXX.azurecr.io/classic-go:latest
    imagePullPolicy: Always
```

But we getting the same error:

`Unexpected status: 400, message: unable to pull image XXXXXXXX.azurecr.io/classic-go:latest: cannot pull: failed to resolve reference "XXXXXXX.azurecr.io/classic-go:latest": failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized`

before wie running the deplyoment, we executing the docker login successfully.

**Comment by alexellis** [comment]
Hi there,

It sounds like you haven't configured your private registry correctly.

This is explained in the [faasd handbook](https://gumroad.com/l/serverless-for-everyone-else)

Regards,

Alex

**Comment by alexellis** [comment]
/set title: Question - how do I use a private registry with faasd?
