### ISSUE TITLE
faas-cli build overwrites tag in wrong place when column present in image name

### ISSUE THREAD

**Issue by wapiflapi** [openfaas/faas-cli#875]
## Expected Behaviour

When running `faas-cli build --tag=sha --image foo/bar` the SHA is inserted in the wrong place when the private registry (`foo`) contains a column.

## Current Behaviour

Working fine when no `:` in the registry:
```
$ faas-cli build --tag=sha --lang python3 --image foo/bar --handler . --name my-function 
[...]
Successfully tagged foo/bar:latest-52f0c55
Image: foo/bar:latest-52f0c55 built.
```

That's expected. Now:

```
$ faas-cli build --tag=sha --lang python3 --image foo:4567/bar --handler . --name my-function
[...]
Successfully tagged foo:4567/bar-52f0c55:latest
Image: foo:4567/bar-52f0c55 built.
```

Notice `bar:latest-52f0c55` (expected) vs `bar-52f0c55:latest` which is wrong.

## Possible Solution

I suspect faas-cli is inserting the tag after the first `:` it finds instead of the last one.

## Steps to Reproduce (for bugs)

```
$ faas-cli new foo --lang python
$ git init && git add foo/* && git commit -m "initial commit"
$ faas-cli build --tag sha --image foo:1234/bar --handler ./foo --name foo --lang python
[...]
Successfully tagged foo:1234/bar-de32b50:latest
Image: foo:1234/bar-de32b50 built.
```

`foo:1234/bar-de32b50:latest` should be `foo:1234/bar:latest-de32b50`

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
$ faas-cli version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  2cec97955a254358de5443987bedf8ceee272cf8
 version: 0.13.9
```

* Docker version ( Full output from: `docker version` ):
```
$ docker version
Client:
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        4484c46
 Built:             Fri Dec 18 12:00:51 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:57 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
No.

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
@cpanato want to take a look and see if you can add a failing unit test?

**Comment by cpanato** [comment]
@alexellis PR here: https://github.com/openfaas/faas-cli/pull/877

**Comment by alexellis** [comment]
IMHO `foo:4567` is an invalid username for a registry.

@wapiflapi we need you to provide the stack.yaml file to look into this. Sorry for the confusion.

**Comment by wapiflapi** [comment]
> IMHO `foo:4567` is an invalid username for a registry.
> 
> @wapiflapi we need you to provide the stack.yaml file to look into this. Sorry for the confusion.

Isn't the steps to reproduce from a fresh template enough? I don't have any specific stack.yaml files.

**Comment by cpanato** [comment]
@alexellis I think that is invalid as well, but that builds and might be used just internally. 

What do we want to do here? block this kind of format? or alloy like THis PR fix the behavior?

**Comment by wapiflapi** [comment]
I'm not sure what's being discussed, but from docker's documentation at https://docs.docker.com/engine/reference/commandline/tag/#:~:text=An%20image%20name%20is%20made,prefixed%20by%20a%20registry%20hostname.&text=If%20a%20hostname%20is%20present,.docker.io%20by%20default.

> An image name is made up of slash-separated name components, optionally prefixed by a registry hostname. The hostname must comply with standard DNS rules, but may not contain underscores. **If a hostname is present, it may optionally be followed by a port number in the format :8080**. If not present, the command uses Docker’s public registry located at registry-1.docker.io by default. Name components may contain lowercase letters, digits and separators. A separator is defined as a period, one or two underscores, or one or more dashes. A name component may not start or end with a separator.

So I think the port name definitely is valid in a docker image name.

**Comment by alexellis** [comment]
Thanks for elaborating, this is the context we were missing all along. You're trying to use a registry with a port number. Just make sure you are not running an insecure registry without HTTPS 😄 

This seems like an edge-case, but should help @cpanato to add new unit tests to prove whether using a port is supported or not. @cpanato please don't change existing unit tests but add new ones which use the specific verbiage about WithCustomServerPort etc.

**Comment by cpanato** [comment]
@alexellis @wapiflapi added the test cases, let me know what y'all think about that

**Comment by wapiflapi** [comment]
> @alexellis @wapiflapi added the test cases, let me know what y'all think about that

Test cases look good to me :+1:
