### ISSUE TITLE
Dockerfile is unavailable or not supported

### ISSUE THREAD

**Issue by asencis** [openfaas/faas-cli#878]
I'm following the guide for publishing an existing flask application through OpenFAAS.

However, when running the command:

```sh
faas-cli new --lang dockerfile $FN
```

I receive the following error:

```
Dockerfile is unavailable or not supported
```

I'm following the guide here: https://www.openfaas.com/blog/openfaas-flask/

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.12.21

* Docker version ( Full output from: `docker version` ): 20.10.5

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)? Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS): MacOS

**Comment by asencis** [comment]
Closing issue.

It seems I need to pull down all the available templates 🤦‍♂️

**Comment by alexellis** [comment]
This happens if you first pull a custom template, then you must explicitly pull the "default" templates. Otherwise this works out of the box.

**Comment by asencis** [comment]
@alexellis Yeh. We discovered the need to pull after a while of digging. It might be worth highlighting this in the https://www.openfaas.com/blog/openfaas-flask/ blog, but other than this OpenFaaS is working really well! Thank you 🥇 

One thing we have found tho - is that what we can do with `req` within the handler() function for the python3-flask-template is a little bit mysterious. Might it be worth us adding something to the documentation for Flask?

**Comment by alexellis** [comment]
There is documentation in the repo, have you checked out its docs yet?

https://github.com/openfaas/python-flask-template/

**Comment by alexellis** [comment]
I can't see any issues with the blog post because it has an explicit command `faas-cli template store pull python3-flask
`? What am I missing?

**Comment by asencis** [comment]
Hi @alexellis ,

So - the issue is with the section "**Running an existing Flask app**" -> and the command `faas-cli new --lang dockerfile $FN`. We didn't know we had to pull down this image - we assumed that it was some sort of default - but adding the line `faas-cli template store pull dockerfile`, would be so beneficial to this blog? Maybe? (Not sure that this is the exact line) I think yes, we're new to all this, so this is all very unfamilar. The notion of the faas store isn't quite in our language as yet. But worth stating explicitly for dev teams in our situation.

So with the req object, do we treat this exactly like a flask request object...we're looking an we assume not - it's a bytes str. So we're very confused as to what we can do with it in the "traditional" flask sense.

**Comment by alexellis** [comment]
It is because you already had alternative templates in place. Try it in a new directory and you'll see it work immediately.

```
alex@alex-nuc8:/tmp$ export FN=test
alex@alex-nuc8:/tmp$ faas-cli new --lang dockerfile $FN
Folder: test created.
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|


Function created in folder: test
Stack file written: test.yml
alex@alex-nuc8:/tmp$ 
```

Feel free to ask questions on Slack. We don't use the issue tracker for technical support, but for tracking what work we're doing and for issues with a repro.
