### ISSUE TITLE
Question: Any intention to support multiple platforms/proxies

### ISSUE THREAD

**Issue by tatemz** [openfaas/faas-cli#887]
As noted in the documentation, solutions like Google Cloud Run happen to use the same port (8080) and `faas-cli` could work well to rapidly use templates and build Docker images. Using something like Google Cloud Run would mean that useful commands like `faas-cli invoke` or `faas-cli deploy` are made obsolete.

Since most of the logic for communicating with the gateway is stored in the `proxy` folder, would it be a feasible feature to build out multiple API implementations for varying solutions (e.g. Google Cloud Run, Docker Desktop, etc)?

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## List All Possible Solutions and Workarounds

Wrap the `proxy` implementation in an interface and use dependency injection to use it when making gateway API calls. Once an interface exists, other implementations could be made to support multiple gateway types.

## Context

Thinking through using Google Cloud Run with OpenFaaS templates and images.

**Comment by alexellis** [comment]
> Using something like Google Cloud Run would mean that useful commands like faas-cli invoke or faas-cli deploy are made obsolete.

I am sorry, but I don't understand this. What is your ask?

I'm going to close this issue since it's a question and we take those by Slack, but feel free to keep commenting since you've started.

**Comment by tatemz** [comment]
Thanks for the comment. I'll try to make the question clearer. Correct  me if I am wrong, but the OpenFaaS Gateway supports the following features:

- Building Docker images using shrinkwrapped templates
- Pushing built Docker images
- Publishing/removing containers
- Managing secrets
- Invoking running containers
- etc

A lot of these features are offered by products like Google Cloud. I'm interested in making the `faas-cli` work in with Google Cloud. 

Today, I can make use of very helpful `faas-cli` commands to quickly manage functions, shrinkwrap customized templates, and build Docker images. I can then use Google Cloud Run to deploy those images as function containers that scale to 0.

If I choose to deploy my images to Google Cloud Run (or something like it), then I miss out on great `faas-cli` features like `faas-cli invoke` or `faas-cli up`.

What if the `faas-cli` was able to be configured to either use an OpenFaaS gateway OR another product like Google Cloud.

This would be a fairly simple undertaking because you have done a great job at isolating all of the OpenFaaS gateway API calls in the `proxy` folder. If a Go interface called `GatewayProxy` was extracted to account for the various methods that are needed, then we could implement that `GatewayProxy` with any implementation:

- `OpenFaasGatewayProxy`
- `GoogleCloudProxy`
- `KubernetesProxy`
- etc

**Comment by alexellis** [comment]
You can use faas-cli in Google Cloud Build and then deploy to Cloud Run, not a problem.

You should be doing that through a production pipeline, not by running `faas-cli up` on your laptop anyway 🙂 

See also: Run your OpenFaaS Functions on Google Cloud Run for free - https://www.openfaas.com/blog/openfaas-cloudrun/

And https://github.com/utsavanand2/gcb-openfaas-go

In short, openfaas has a provider model that could be used to create a provider for Google Cloud Run, providing they have the correct APIs: https://blog.alexellis.io/the-power-of-interfaces-openfaas/

Is there anything stopping you from doing that? No.

Are we going to do that? No.

**Comment by alexellis** [comment]
/set title: [Feature request] Create a Google Cloud Run provider for OpenFaaS
