### ISSUE TITLE
Display help message with no args on `faas-cli generate`

### ISSUE THREAD

**Issue by yankeexe** [openfaas/faas-cli#894]
## Expected Behaviour

Show help message when no arguments is passed like all the other sub commands.

## Current Behaviour

Shows nothing when `faas-cli generate` is invoked without arguments.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## List All Possible Solutions and Workarounds

Check for arguments length; if none; show help.

```go
if len(args) == 0 {
	cmd.Help()
	os.Exit(0)
}

```

## Steps to Reproduce (for bugs)

```bash 
faas-cli generate
```

## Context

Intuitive/expected behavior of CLI to show help message, if it requires certain args to run.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.13.11

* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS): Linux 

* Link to your project or a code example to reproduce issue:

**Comment by yankeexe** [comment]
@alexellis  Do you want me to address this?

**Comment by alexellis** [comment]
Yes, perhaps: `--yaml or --from-store are required`
