### ISSUE TITLE
feature request: provide `faas-cli down` to be opposite of up

### ISSUE THREAD

**Issue by sayjeyhi** [openfaas/faas-cli#897]
This is a feature request and not an issue.
I was wishing to see `faas-cli down` like how `tilt` or other tools has, to work in the opposite way of `faas-cli up`.
maybe it should be just an alias to `faas-cli remove`.

**Comment by yankeexe** [comment]
Hey @sayjeyhi can you please edit the description and use our [Issue Template](https://raw.githubusercontent.com/openfaas/faas-cli/master/.github/ISSUE_TEMPLATE.md). 

Also, can you prefix the title of this issue with `feature request: <text>`, so we will have better visibility. thanks

**Comment by alexellis** [comment]
We do have this, it's called `faas-cli remove`

Thanks for the suggestion and next time please fill out the entire issue template instead of deleting it.

Cheers,

Alex
