### ISSUE TITLE
faas-cli describe command has wrong formatting

### ISSUE THREAD

**Issue by xrazis** [openfaas/faas-cli#900]
When using `describe`, the *Labels* and the *Annotations* are printed on the same line.  They should both be printed in separate lines.

## Expected Behaviour
```
$ faas-cli describe go-long

Name:                 go-long
Status:               Ready
Replicas:             1
Available replicas:   1
Invocations:          6
Image:                alexellis2/go-long:0.1.3
Function process:     ./handler
URL:                  http://127.0.0.1:8080/function/go-long
Async URL:            http://127.0.0.1:8080/async-function/go-long
Labels:
Annotations:   topic : faas-request
```

## Current Behaviour
```
$ faas-cli describe go-long

Name:                 go-long
Status:               Ready
Replicas:             1
Available replicas:   1
Invocations:          6
Image:                alexellis2/go-long:0.1.3
Function process:     ./handler
URL:                  http://127.0.0.1:8080/function/go-long
Async URL:            http://127.0.0.1:8080/async-function/go-long
Labels:Annotations:   topic : faas-request
```

## Are you a GitHub Sponsor (Yes/No?)
- [ ] Yes
- [x] No

## List All Possible Solutions and Workarounds
1. We change the  funcDesc.Labels if statement to not enter if the Labels map is empty. This way we don't print an empty Labels tag. That should also be applied to Annotations.
- Current: `if funcDesc.Labels != nil {...}`
- Proposed: `if len(*funcDesc.Labels) != 0 {...}`

2. We check if the map is empty in the if statement and print a new line.
- Current: 
none
- Proposed: 
    ```
    if len(*funcDesc.Labels) != 0 {
        fmt.Fprintln(w, "")
    }
    ```
3. We check the map at the beginning of a new function, print *<none>*, and return.
- Current: 
none
- Proposed: 
    ```
	if len(labels) == 0 {
		w.WriteLine("<none>")
		return
	}
    ```

## Which Solution Do You Recommend?
I'd favor the last one.  

## Steps to Reproduce (for bugs)
Use no labels and then run:

1. faas-cli describe \<function>

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ):  0.13.0

* Docker version ( Full output from: `docker version` ):  20.10.10

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)? No

* Operating System and version (e.g. Linux, Windows, MacOS): Linux - Pop!_OS 21.04

**Comment by alexellis** [comment]
In the future, write this text in your commit message:

`Fixes: #...`

See mine for example by typing in `git log` and scrolling through this repo or faas-netes.
