### ISSUE TITLE
faas-cli build --handler  not rewrite the handler

### ISSUE THREAD

**Issue by daiwenlong** [openfaas/faas-cli#903]
## Expected Behaviour

 faas-cli build --image=daiwenlong/find-one:3.0 --lang=java11 --handler=./test --name=find-one

replace the default handler with my handler in ./test

## Current Behaviour
not rewrite the handler , the handler is the default handler

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.13.13

* Docker version ( Full output from: `docker version` ):  20.10.8

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?: Kubernetes 

* Operating System and version (e.g. Linux, Windows, MacOS): Windows

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
This is working as designed, and not supported by the faas-cli.

This doesn't seem to be usual behaviour. What exactly are you trying to do?

**Comment by daiwenlong** [comment]
> This is working as designed, and not supported by the faas-cli.
> 
> This doesn't seem to be usual behaviour. What exactly are you trying to do?

I don't want to replace the Handler.java file manually, so I try to do it with faas-cli  build --handler command,  it doesn't work， Is there any way to do it ?

**Comment by alexellis** [comment]
@daiwenlong you haven't told us what you're trying to achieve yet. I've already asked for more information, but all I can do is guess at this point.

What are you trying to do, and why does the normal workflow not work for you?

https://www.openfaas.com/blog/get-started-with-java-openjdk11/

**Comment by daiwenlong** [comment]
> @daiwenlong you haven't told us what you're trying to achieve yet. I've already asked for more information, but all I can do is guess at this point.
> 
> What are you trying to do, and why does the normal workflow not work for you?
> 
> https://www.openfaas.com/blog/get-started-with-java-openjdk11/

 I'm trying to build  CI / CD with shell, developers only need to write functions, not a complete project.

**Comment by alexellis** [comment]
If you wanted to book a session with me to discuss this further, I have some drop-in sessions left this week and next: https://calendly.com/alexellis/

For a complete solution, you'd probably find our [Pro builder option](https://docs.openfaas.com/openfaas-pro/builder/) useful. [Waylay](https://www.waylay.io/) provide a source to function capability in their platform and I'm sure they won't mind me saying that they have just moved over to it.

Alex
