### ISSUE TITLE
[Question] How to publish multiple functions in one Github Action?

### ISSUE THREAD

**Issue by ctwkongmu** [openfaas/faas-cli#909]
Hi community,

I'm quite new to openfaas and github action, and I have a seemly realistic CD scenario where one github project manages multiple openfaas functions, and in the CD process performed by github action, there might be multiple functions being added/updated after the PR is merged.
How to build all those updated/created functions and publish them to openfaas in one github action?

Now I'm following https://www.openfaas.com/blog/openfaas-functions-with-github-actions/, which is a great post to show how to setup CD process for openfaas functions, if you only have 1 function to publish in the PR, since buildx builds one image at a time.

I wonder if there is a working solution to build and deploy multiple functions to openfaas in 1 github action?
Because github action doesn't have much control flow, I can't easily loop functions "dynamically".
One solution would be make openfaas allow users to define different functions in one image, which is also stated here in this issue: https://github.com/openfaas/faas/issues/638.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [X] No

## List All Possible Solutions and Workarounds
- Make openfaas allow build multiple functions in one image?
- Integrate buildx inside faas-cli so that one can loop functions inside faas-cli?

## Which Solution Do You Recommend?
I think either of above approaches feels natural to me.
Probably the second one makes more sense, since we have `faas-cli up`, it would be great if it can build/push/deploy multiple functions in one go in github action.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
`0.13.15`

* Docker version ( Full output from: `docker version` ):
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:31 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Hi, that's a very old blog post

You should follow the sample in Serverless For Everyone Else. I reworked it and use it myself. It is much more concise and supports multiple functions and tags.

[Serverless for Everyone Else
](http://store.openfaas.com/l/serverless-for-everyone-else)

Alex

**Comment by ctwkongmu** [comment]
Thanks @alexellis .
I will check it out!

**Comment by alexellis** [comment]
We have a promotion running tomorrow, for 50 USD discount on the complete package. Don't leave it too long.

Cheers
