### ISSUE TITLE
Could I operate openfaas with http rather than faas-cli

### ISSUE THREAD

**Issue by zryu000** [openfaas/faas-cli#917]
## Expected Behaviour

Operate openfaas through restful api
## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [-] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by welteki** [comment]
Hi @zryu000,

Thanks for your interest in OpenFaaS.

We have a great chapter on this in Serverless For Everyone Else called "Can I get an API with that?"

[Serverless for Everyone Else](http://store.openfaas.com/l/serverless-for-everyone-else)

Han
