### ISSUE TITLE
faas-cli not respecting --tls-no-verify flag, not respecting containerd registry configuration.

### ISSUE THREAD

**Issue by NeoTech** [openfaas/faas-cli#918]
Faas CLI does not respect the --tls-no-verify flag

## Expected Behaviour
When issuing `faas deploy --tls-no-verify -f hello-python.yml` i would expect it to pull image from my local development repository without arguing.

I'm running faasd locally with a Local registry that is setup with x509 self signed certificate.

## Current Behaviour
 faas deploy --tls-no-verify -f hello-python.yml
Deploying: hello-python.

Unexpected status: 400, message: unable to pull image registry.local.com:5000/hello-python:latest: cannot pull: failed to resolve reference "registry.local.com:5000/hello-python:latest": failed to do request: Head "https://registry.local.com:5000/v2/hello-python/manifests/latest": x509: certificate signed by unknown authority

## Are you a GitHub Sponsor (Yes/No?)
No

Check at: https://github.com/sponsors/openfaas
- [ x ] Yes
- [ ] No

## List All Possible Solutions and Workarounds
- Respect deploy flag --tls-no-verify
- Respect containerd registry configuration
- Respect docker certificate workaround.

## Which Solution Do You Recommend?
- Respect --tls-no-verify

## Steps to Reproduce (for bugs)
1. Setup FaasD
2. Configure Containerd
3. Install a local registry with x509 self signed cert and basic auth
4. run faas deploy command

## Context
I'm trying to demoing the viability of openfaas in a commercial setting, showing that local development is possible without relying on heavy and costly kubernetes clusters hosted online. Instead using faasd locally directly.

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ):
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  b1c09c0243f69990b6c81a17d7337f0fd23e7542
 version: 0.14.2

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.21.3
 sha:     cdb6badddaede0f69ef8ce9cb4b7e25e876b75fa

Provider
 name:          faasd
 orchestration: containerd
 version:       0.16.0
 sha:           e668beef139ee094ad7364a5534b15d84b1b1f6d

* Docker version ( Full output from: `docker version` ):
Client:
 Version:           20.10.15
 API version:       1.41
 Go version:        go1.18.1
 Git commit:        fd82621d35
 Built:             Thu May  5 23:16:45 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.15
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.1
  Git commit:       4433bf67ba
  Built:            Thu May  5 23:16:31 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.3
  GitCommit:        f830866066ed06e71bad64871bccfd34daf6309c.m
 runc:
  Version:          1.1.1
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
No

* Operating System and version (e.g. Linux, Windows, MacOS):
Arch Linux

* Link to your project or a code example to reproduce issue:
https://github.com/NeoTech/local-registry
Here is how i spin up a local registry with a self signed certificate..

**Comment by LucasRoesler** [comment]
@alexellis this error must come from fast right? The CLI does not actually pull images, the `--tls-no-verify` only applies to the openfaas gateway tls, not the image. The faasd service itself needs to be configured to ignore tls for local registries, right?

**Comment by alexellis** [comment]
Hi, thanks for the interest in faasd.

I'm going to close this issue since this is just a misconfiguration of your faasd instance, rather than an issue with faas-cli.

The `--tls-no-verify` flag for faas-cli (like @LucasRoesler mentions) is just about the gateway.

See the [eBook Serverless For Everyone Else](https://openfaas.gumroad.com/l/serverless-for-everyone-else) on how to configure faasd with a private registry.

Regards,

Alex
