### ISSUE TITLE
Managing functions progrmatically away from cmd

### ISSUE THREAD

**Issue by seekeramento** [openfaas/faas-cli#924]
faas-cli provides the required commands that help mange functions such as build, deploy, and push. In my case, I need to have an app that can deploy functions dynamically. A way to do that is to run faas-cli commands from this app. However, I am not sure if this sound like the best way to do it. 

## Expected Behaviour
Is there a way to manage functions programmatically away from faas-cli?

## Current Behaviour
The only solution I have is to use faas-cli.

## Are you a GitHub Sponsor (Yes/No?)
No

Check at: https://github.com/sponsors/openfaas
- [* ] Yes
- [ ] No

## List All Possible Solutions and Workarounds
Piggyback on faas-cli.

## Which Solution Do You Recommend?
There could be a way to call faas API programmatically when required.

## Steps to Reproduce (for bugs)
N/A

## Context
N/A

## Your Environment
Windows

**Comment by LucasRoesler** [comment]
Hi @seekeramento the deploy command is an API call, you can find the entire API for OpenFaaS in Swagger 2.0 here https://github.com/openfaas/faas/tree/master/api-docs

Unfortunately, build and push are locally run commands, they just delegate to your local Docker. However, if you have [OpenFaaS Pro](https://docs.openfaas.com/openfaas-pro/introduction/), then it does include [a builder](https://docs.openfaas.com/openfaas-pro/builder/), thus an API for the build and push.

**Comment by seekeramento** [comment]
Many thanks. I have been considering OpenFaaS Pro.
