### ISSUE TITLE
Show memory and CPU requests/limits in faas-cli describe

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#926]
## Expected Behaviour

Show memory and CPU requests/limits in faas-cli describe

## Current Behaviour

OpenFaaS Pro shows utilization, but neither Pro or CE show the limit as set on the function spec.

## List All Possible Solutions and Workarounds

See if it's present in the API, and display it if it is.

## Steps to Reproduce (for bugs)

See example stack.yml here:

https://docs.openfaas.com/reference/yaml/#function-memorycpu-limits

Then run faas-cli describe

## Context

Confusing for users - it's not easy to tell if a limit or request has been set for CPU/RAM.

**Comment by rgee0** [comment]
What am I misunderstanding in the issue if I suggest the `-v` flag provides this?

**Comment by alexellis** [comment]
Thanks for the reminder :facepalm: 

I guess that it was so non-obvious that I even forgot how it was implemented.

**Comment by LucasRoesler** [comment]
I am pretty sure it is hidden behind the `-v` for "backwards compatibility". But i don't know any use cases that would break by showing the values by default.
