### ISSUE TITLE
Print environment variables in a deterministic order in faas-cli describe

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#932]
## Expected Behaviour

I'd expect `faas-cli describe` to print environment variables in a deterministic order, perhaps sorted by the default string sorter.

## Current Behaviour

I was just running this on a Raspberry Pi with faasd as the back end and noticed the fields appeared to be "jumping about".

## Why do you need this?

It's a bit jarring when running `watch faas-cli describe FN`

## List All Possible Solutions and Workarounds

1) Do nothing
2) Create a slice of strings based upon the keys of the environment variable map, then sort it and use it to print out the keys for the describe command

@rgee0 may have done something to help ordering in `faas-cli generate`, which could be re-used.

## Which Solution Do You Recommend?

I think 2 would be a good fit

## Steps to Reproduce (for bugs)

1. This may not be the same on Kubernetes, but with faasd, I did `faas-cli store deploy env` followed by `watch faas-cli describe env`

Not sure if a failing test can be written here to show the problem before moving onto a fix? https://github.com/openfaas/faas-cli/blob/master/commands/describe_test.go

https://github.com/openfaas/faas-cli/blob/master/commands/describe.go
https://github.com/openfaas/faas-cli/blob/master/commands/generate.go

**Comment by rgee0** [comment]
Derek assign rgee0

**Comment by rgee0** [comment]
Derek assign: rgee0
