### ISSUE TITLE
findRelease() assumes usage is only for kubeseal

### ISSUE THREAD

**Issue by rgee0** [openfaas/faas-cli#935]
This is loosely related to #874 and is extant in the current CLI version.

## Expected Behaviour
If a faas-cli version check fails the error message that bubbles up to the user should be specific to faas-cli

## Current Behaviour
Due to https://github.com/openfaas/faas-cli/blob/master/commands/cloud.go#L194 if a faas-cli version check fails due to a zero length location header the error message returned to the user will refer to kubeseal.

## Why do you need this?
Clarity for the user

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## List All Possible Solutions and Workarounds
Swap out the string literal that refers to the tool name and use the incoming url value instead

## Which Solution Do You Recommend?
Swap out the string literal that refers to the tool name and use the incoming url value instead

## Steps to Reproduce (for bugs)
Difficult as it requires the specific error condition to be forced.  Its easier understood through code inspection.

This call:
https://github.com/openfaas/faas-cli/blob/d08553ed3f60fd33ee7b7d3ee35e9738d6e0e3c8/commands/version.go#L69
Reaches:
https://github.com/openfaas/faas-cli/blob/d08553ed3f60fd33ee7b7d3ee35e9738d6e0e3c8/commands/cloud.go#L194
which returns:
https://github.com/openfaas/faas-cli/blob/d08553ed3f60fd33ee7b7d3ee35e9738d6e0e3c8/commands/cloud.go#L219

## Context
This is something I spotted while working on #874 and is more of a consideration if #874 doesn't get merged.  In any event id suggest `findReleases()` should be made more generic.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
Is there a package in arkade that we can vendor for this?

**Comment by rgee0** [comment]
Maybe:

https://github.com/alexellis/arkade/blob/7b7ade38cff998b68886fe7f1260d080e881383a/pkg/get/get.go#L181

**Comment by alexellis** [comment]
I've made the suggested change, thank you for looking into it
