### ISSUE TITLE
Add --quiet option to faas-cli push

### ISSUE THREAD

**Issue by vnourdin** [openfaas/faas-cli#937]
## Expected Behaviour
A `--quiet` option on the `faas-cli push` would suppress every docker logs about the push to registry.
Especially for CI that doesn't have interactive consoles and thus log a lot of lines for each state change (Preparing, Waiting, Mounted, Pushed)

## Current Behaviour
We currently have all logs from docker push.

## Why do you need this?
To make my CI logs readable.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## Possible Solution
Add the `--quiet` option to be passed to `docker push`.

## Workaround
I could use directly `docker push --quiet` for each function, but I like the `--parallel` option of `faas-cli push`.

## Steps to Reproduce (for bugs)
1. `faas-cli push`
2. see all the logs

## Context
Using `faas-cli push` in my CI, with `--parallel` option, and this creates a lot of logs, and logs of all functions are mixed together.

## Your Environment
* FaaS-CLI version: 0.14.8
* Docker version: 20.10.18

**Comment by alexellis** [comment]
Hey thanks for your interest in OpenFaaS again.  

Just to be transparent, we are prioritising the needs of customers and sponsors at the moment.

So some ideas for you:

Maybe Docker has an environment variable that you could use?

You might want to try DOCKER_BUILDKIT=1 as a comparison to see if the output is more palatable to you

faas-cli is open source so you may want to fork it and make it work how you need it.

**Comment by vnourdin** [comment]
Hi, I understand your prioritization, no problem !

I haven't found any env variable to reduce docker push outputs, and BuildKit isn't helping on the push side.
I'll consider opening a PR !

**Comment by alexellis** [comment]
Hi @vnourdin 

I can get this done for you, if you sign up as a sponsor on GitHub either for OpenFaaS or for me, I don't mind which. If you don't see a tier that matches the current value you get from our work, then create a custom one.

The PR is pending on my computer, let me know when you want it to be released for you.

Alex

**Comment by alexellis** [comment]
Hi @vnourdin it's been a couple of weeks, should we get this closed, or did you want to sponsor OpenFaaS and get this feature?

Your personal account or your company, we don't mind.

https://github.com/sponsors/openfaas

Alex

**Comment by alexellis** [comment]
You can sponsor us from *any amount* per month, if you're already using it and both requesting features and technical support, then we would expect you to contribute.

`faas-cli publish` does the same as the above, why don't you look into it?
