### ISSUE TITLE
Have the ability to override not only the gateway URL but also the image name (repository, tag) in faas CLI commands

### ISSUE THREAD

**Issue by CleverCoder** [openfaas/faas-cli#938]
## Expected Behaviour
Be able to build, push, and deploy locally using a function configuration file, while being able to easily override the gateway and image repository:tag.

## Current Behaviour
The only workaround I've found is to change the name of the image in the function <functionname>.yml file. I am able to build the image locally to Docker (where the image name remains the name in the config file - which is what's used in production, requiring a round-trip over the internet), and even add a tag to my local repository, but I'm unable to tell the `faas` CLI to deploy the function to my local OpenFaas instance using the new image tag.

It's worth noting that I'm able to override the OpenFaas gateway easily, but not the image name.

This has caused situations where I've accidentally pushed an image to production, or simply been unable to test changes to workflows and CI/CD steps locally.

To cover a common use case where I'm developing and testing all locally through CLI commands, and not wanting any image or deployments to go into the shared cloud provider.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## List All Possible Solutions and Workarounds
Suggestion: add the `-i` or `--image` CLI argument to all the `faas` CLI comments that allows overriding the image used from the config file.

## Which Solution Do You Recommend?
The one I mention.

## Steps to Reproduce (for bugs)
1. Create a function with a config that points to an image in docker hub or ECR
2. Try to develop the function locally, while keeping the image builds and OpenFaas deployments local to your machine, only using the `faas` CLI.
3. Notice that this is hard.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:
 commit:  10815dfbdb2b8a30f60282d4265df62ba365847e
 version: 0.14.10

Gateway
 uri:     http://192.168.64.2:8080
 version: 0.25.2
 sha:     bc2eeff4678407583faec982c1c7d1da915dd60c


Provider
 name:          faasd
 orchestration: containerd
 version:       0.16.7 
 sha:           282b05802cccd311678a73efaee78af0086cc7fd
```

* Docker version ( Full output from: `docker version` ):
```
Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```
* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
no
* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS
* Link to your project or a code example to reproduce issue:
Not specific to a project

**Comment by alexellis** [comment]
Thanks for your interest 

This is already implemented and available 

See my note where I answered you on an existing issue at:

https://github.com/openfaas/faas-cli/pull/614#issuecomment-1288024170

**Comment by CleverCoder** [comment]
Not to be pedantic, but if this is implemented, what's the command (when running `faas` or `faas-cli` command line) to be able to override the image used when building, pushing, and deploying to an OpenFaas instance? 🤔

**Comment by rgee0** [comment]
I'm pretty sure this achieves what you are asking about.  For transparency, this took me 20 mins to pull together; I'd love to know which company I've been solving problems for.  

Create a new function:
```
$ faas-cli new --lang go clever
```

Inspect the new `stack.yml`:

```
$ cat clever.yml 
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  clever:
    lang: go
    handler: ./clever
    image: clever:latest
```

Add env vars into `stack.yml`

```
$ cat clever.yml
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  clever:
    lang: go
    handler: ./clever
    image: ${DOCKER_USER:-rgee0}/${IMAGE_NAME:-fred}:${TAG:-latest}
```

Run a build without env vars set:

<pre>
$ faas build -f clever.yml
[0] > Building clever.
Clearing temporary build folder: ./build/clever/
Preparing: ./clever/ build/clever/function
Building: <b>rgee0/fred:latest</b> with go template. Please wait..
</pre>

Run a build with those vars set:

<pre>
$ DOCKER_USER="clevercoder" IMAGE_NAME="burt" TAG="0.2" faas build -f clever.yml         
[0] > Building clever.
Clearing temporary build folder: ./build/clever/
Preparing: ./clever/ build/clever/function
Building: <b>clevercoder/burt:0.2</b> with go template. Please wait..
</pre>

**Comment by CleverCoder** [comment]
Thanks for the suggestion, but it doesn't actually provide a pure override through the CLI without the use of environment vars.

I'm aware I could use env vars like this.

Using environment vars require modifying the CICD pipeline as well as editing the function configuration files. If I was able to override the image on the CLI (similar to the gateway with '-g'), then nothing would need to be changed in the checked in repos.

**Comment by alexellis** [comment]
> but it doesn't actually provide a pure override through the CLI without the use of environment vars.

Well it does though?

```
DOCKER_USER="clevercoder" IMAGE_NAME="burt" TAG="0.2" faas build -f clever.yml
```

Environment variables can also be saved into files and inputted, if that suits you better.
