### ISSUE TITLE
Add ARM64 build for MacOS

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#941]
Add ARM64 build for MacOS

## Expected Behaviour

We can provide an ARM64 build for Darwin, Go supports this and it would be quicker for MacOS users on M1.

https://github.com/openfaas/faas-cli/releases

## Current Behaviour

Rosetta emulation is used on ARM Macs

## Why do you need this?

I think it is expected now, and we have it for arkade/inlets, so it should be straightforward to add here following the same patterns.

## Who is this for?

No immediate demand, I do own an M1 but use the x86 binary.

## Context

This should also update the installer script in https://github.com/openfaas/cli.openfaas.com

**Comment by nitishkumar71** [comment]
I will work on it.
