### ISSUE TITLE
Capability to select container driver

### ISSUE THREAD

**Issue by corinz** [openfaas/faas-cli#944]
I am using Podman, and unable to issue faas-cli commands to build using the podman driver. Does faas-cli have the capability to select an alternative driver?

## Expected Behaviour
faas-cli would work with podman by selecting the driver

## Current Behaviour
faas-cli is hardcoded to work with docker

## Why do you need this?
Some background to show the strategic selection here... There are several reasons Podman may be selected over Docker
- totally open source/license friendly
- flexibility when it comes to defining VMs
- near 1:1 interface with docker cli
- supported by popular distros like minikube, kind

## Who is this for?
Asking this as a personal inquiry, feature request for the community. I am not on the adopters list.

## Are you a GitHub Sponsor (Yes/No?)
I am not a github sponsor

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## List All Possible Solutions and Workarounds
A command line flag to select the alternaive driver and/or the ability to point to the socket

## Which Solution Do You Recommend?
A command line flag to specify the driver

## Steps to Reproduce (for bugs)
n/a

## Context
Some moving away from Docker as they find other tools more appropriate for the use case. Tools that are hard-coded to use Docker will find that they lose OSS consumer base.

AFAIK I was unable to find this feature in the docs...

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.14.11
* Docker version ( Full output from: `docker version` ):
v20
* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
faas-netes, yes
* Operating System and version (e.g. Linux, Windows, MacOS):
macOS
* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
We might consider this for a customer or a sponsor, but for now we're not going to consider having Podman as an option.
