### ISSUE TITLE
feature: add watch mode to faas-cli up workflow

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-cli#952]
## Expected Behaviour

We want to add a flag to the `faas-cli up` command so that it can run continuously and re-build and deploy when files are changed.

For example `faas-cli up --watch` will build and deploy the functions in the `stack.yaml` and then continue watching for file change notifications and rebuild and deploy the stack when an event is seen.

## Current Behaviour

`faas-cli up` is a one-off workflow right now.

## Why do you need this?

Make the dev-loop shorter. 

## Context

This was discussed in the community call as a feature that we would like to have and it would be a test ground for also adding the watch behavior to the `faas-cli local-run`

**Comment by LucasRoesler** [comment]
For the file notifications, [skaffold is using](https://github.com/GoogleContainerTools/skaffold/blob/main/go.mod#LL179) the [fsnotify package](https://pkg.go.dev/github.com/fsnotify/fsnotify) and it looks like a solid package.

**Comment by alexellis** [comment]
Here's the equivalent command with Google Skaffold which is well known for giving an "auto-build" workflow:

https://github.com/GoogleContainerTools/skaffold/issues/8396

Example function / config for Skaffold with faas-cli: https://github.com/alexellis/openfaas-skaffold-faas-cli

After we have a working prototype for faas-cli up, local-run would probably be a good place to go next.

**Comment by alexellis** [comment]
An example with a library that doesn't need CGO and it's used by Skaffold:

https://github.com/alexellis/fstail/

**Comment by NikhilSharmaWe** [comment]
I would like to work on this.
