### ISSUE TITLE
Issue with new feature faas-cli up --watch

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#968]
I'm getting an issue with the new feature `faas-cli up --watch` feature by @NikhilSharmaWe and @LucasRoesler
 
## Expected Behaviour

Editing a file, whilst having run:

```
faas-cli up --watch
```

Should rebuild

## Current Behaviour

It didn't when editing handler.go with nano / vim.

## List All Possible Solutions and Workarounds

Do additional testing?

## Steps to Reproduce (for bugs)

See:

https://asciinema.org/a/cHAZUrr3WPc95g7tjKrMN7xO6

## Your Environment

Ubuntu Linux 
faas-cli 0.16.9

**Comment by nitishkumar71** [comment]
I tried to reproduce this in my local with `faasd` on `multipass` using `ubuntu`. This scenario can only be produced if we are running `asciinema rec` to record  terminal output. If not, `watch` flag works correctly. I tried multiple times and each time without `asciinema rec` `watch` flag works correctly.

**Comment by alexellis** [comment]
That's a really interesting finding. I'll take a quick look again now.

**Comment by alexellis** [comment]
That's not working right now, or outside of tmux with vim. I did see it work once or twice then stopped.

**Comment by alexellis** [comment]
It also seems like adding a new file isn't picked up because we are watching specific files instead of directories:

![image](https://github.com/openfaas/faas-cli/assets/6358735/3cddc39b-84d3-4fc6-82b2-91ddf6533403)

**Comment by alexellis** [comment]
The code only looks for a Write:

But a Create should trigger this, as should a Delete/Remove.

Perhaps vim was doing a "trunctate" - i.e. Remove/Create and not the expected: "write"

```go

			select {
			case event, ok := <-watcher.Events:
				if !ok {
					return fmt.Errorf("watcher's Events channel is closed")
				}

				if event.Op == fsnotify.Write {
```

**Comment by nitishkumar71** [comment]
> That's not working right now, or outside of tmux with vim. I did see it work once or twice then stopped.

Ahh, I was able to reproduce it now. There are 3 cases

1. with tmux using and edit in vim
2. open 2 terminal and run `watch` command in one and use  `vim` in another
3. use `asciinema rec` with tmux and edit in `vim`

In first case it works, but does not works for second and third. 

> But a Create should trigger this, as should a Delete/Remove.
Agree, these should be handled too.

**Comment by alexellis** [comment]
This is what a save looks like from vim:

![image](https://github.com/openfaas/faas-cli/assets/6358735/85a143bb-9f70-4695-b6c3-098aff94a938)

**Comment by NikhilSharmaWe** [comment]
Hey @nitishkumar71
Currently, I am acquired with some other work.
Feel free to take it up.

Thankyou

**Comment by alexellis** [comment]
I'm working on #969. I'd like someone to volunteer to try it out and test a few different edge cases and scenarios.

I'd like some suggestions on how to make it more generic to also be used in "local run"
