### ISSUE TITLE
Make it possible for image version to have fixed length

### ISSUE THREAD

**Issue by BParnikel** [openfaas/faas-cli#974]
## Summary
Hello, we use latest `faas-cli` in our project and we have 2 different pipelines referencing images: one in GitHub Action (generates images) and one in Jenkins (references image). Both of them have access to git.
The problem we faced is that version length in faas-cli build/publish is not deterministic because `git rev-parse --short HEAD` can return different number of characters (7 to 12) based on collisions. 
As a result, in Jenkins we cannot reference images generated in GitHub action. At the same time there is no option to use fixed length by using `faas-cli` to make it predictable.

## Suggested solution
Provide an extra option to specify fixed length version
```sh
faas-cli build .... --tag sha-fixed --length 12
```

**Comment by alexellis** [comment]
Hi @BParnikel, we're glad to hear you are using OpenFaaS in your team. Can you send a note to our ADOPTERS file with the use-case? https://github.com/openfaas/faas/blob/master/ADOPTERS.md

We'll need full steps for reproducing the issue and for you to fill out the whole issue template. https://raw.githubusercontent.com/openfaas/faas-cli/master/.github/ISSUE_TEMPLATE.md

Once you've done the above we'll take a look at this, perhaps on the next community call on Wednesday. You're welcome to come along and walk us through it - https://docs.openfaas.com/community/

And whilst we appreciate your ideas for a solution, it may be that you've overlooked another more appropriate solution that others are using.

Alex

**Comment by BParnikel** [comment]
Hi @alexellis, thank you!
Actually we've already found a workaround how to make image tag predictable. We achieved it by utilising `core.abbrev` config of git (see https://github.com/git/git/commit/dce96489162b05ae3463741f7f0365ff56f0de36 for more details). By using it one can specify length of image tag provided by `faas-cli`

**Comment by alexellis** [comment]
So, what's the command to set that up within a git repository? We should add this to the docs.

Having spoken to @welteki, I think it may also make sense to use a full-length SHA instead of a short SHA.

One more thing - if you're using OpenFaaS commercially, which it sounds like you are, you may benefit from checking out [OpenFaaS Standard](https://openfaas.com/pricing) / or [sponsoring OpenFaaS on GitHub](https://github.com/sponsors/openfaas)

You get paid a salary to work on your product, we need to be able to pay people too. Hope that makes sense.

**Comment by BParnikel** [comment]
@alexellis thank you for your response. Length is controlled by `core.abbrev` property, see screenshot below.
As for community edition, we have plans to migrate to Standard edition as we may need better scaling.
Thank you.

<img width="361" alt="image" src="https://github.com/openfaas/faas-cli/assets/8242619/9e232d63-2953-4be0-840a-43fcd096ea2c">
