### ISSUE TITLE
I hope to have a more flexible configuration.

### ISSUE THREAD

**Issue by simon12138-code** [openfaas/faas-cli#975]
## Expected Behaviour

![image](https://github.com/openfaas/faas-cli/assets/54308158/65d7196f-a9ec-42e1-b8d2-2398b9cdf031)
I want a template param to set the image pullpolicy,The template allows the addition of corresponding image pull policy configuration options. However, I found that in the corresponding source code, only the strategy of always pulling from the remote repository exists.
## Current Behaviour

![image](https://github.com/openfaas/faas-cli/assets/54308158/bad343a2-a6e0-4890-8db6-12e0018dd78c)

## Why do you need this?
In cases of poor network latency, there may be difficulties in pulling the corresponding image. However, the function image created by `faas-cli` is immediately available locally. Therefore, I believe this is a parameter that can be adjusted.

## Are you a GitHub Sponsor (Yes/No?)
No

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [ ] No

## Which Solution Do You Recommend?

If possible, let me submit a PR.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by alexellis** [comment]
This is configurable already in faas-netes. Thanks for the interest.
